### ISSUE TITLE
Return ThinkResult.NoJob;  on map start with modlist

### ISSUE THREAD

**Issue by Artembelov** [cseelhoff/RimThreaded#103]
// Token: 0x060028B1 RID: 10417 RVA: 0x000EFFE4 File Offset: 0x000EE1E4
		private ThinkResult DetermineNextJob(out ThinkTreeDef thinkTree)
		{
			ThinkResult result = this.DetermineNextConstantThinkTreeJob();
			if (result.Job != null)
			{
				thinkTree = this.pawn.thinker.ConstantThinkTree;
				return result;
			}
			ThinkResult result2 = ThinkResult.NoJob;
			try
			{
				result2 = this.pawn.thinker.MainThinkNodeRoot.TryIssueJobPackage(this.pawn, default(JobIssueParams));
			}
			catch (Exception exception)
			{
				JobUtility.TryStartErrorRecoverJob(this.pawn, this.pawn.ToStringSafe<Pawn>() + " threw exception while determining job (main)", exception, null);
				thinkTree = null;
				return ThinkResult.NoJob;
			}
			finally
			{
			}
			thinkTree = this.pawn.thinker.MainThinkTree;
			return result2;
		}

Links to photos 
https://ibb.co/p0wNQt9
https://ibb.co/hW6VD9Q

**Comment by Artembelov** [comment]
https://ibb.co/4SgS3J4

**Comment by cseelhoff** [comment]
Closing bug. Many bugs have been fixed since this was reported. Please reopen in new bug report using the new templates if this issue persists.
