### ISSUE TITLE
Thread did not Finish 

### ISSUE THREAD

**Issue by TiresomeCube34** [cseelhoff/RimThreaded#105]
**Specs:**
AMD Ryzen 5 3600X 6-core
Radeon RX 570

**Modlist:**
Loading game from file Pact of Farreoum with mods:
  - Harmony
  - RimWorld
  - HugsLib
  - Humanoid Alien Races
  - Hospitality
  - PawnNameVariety
  - SRTSexpanded
  - BetterPawnControl
  - Animals Logic
  - Blueprints
  - AllowTool
  - Android Tiers
  - Snapout
  - GlassLights
  - Mend And Recycle
  - Miscellaneous.Core
  - MoreTradeShips
  - Infused
  - Bulletcasings
  - Pack Mules Extended-Dinosauria
  - Pack Mules Extended
  - MineItAll
  - Glowinghealroot
  - Misc. Robots
  - Misc Robots ++
  - Simple Search Bar
  - Color Coded MoodBar [1.1+]
  - Damage Indicators [1.2]
  - Project RimFactory Revived
  - Reinforced Walls
  - Wall Light
  - Achtung
  - Alpha Animals
  - Dub's Paint Shop
  - Level Up!
  - Various Space Ship Chunk (Continued)
  - Expanded Roofing
  - Simple Sidearms
  - Dinosauria
  - Research Tree (Out of Date mod, for 1.0 & 1.1 currently)
  - EdB Prepare Carefully
  - Doors Expanded (Out of Date mod, for 1.0 & 1.1 currently)
  - [FSF] Filth Vanishes With Rain And Time
  - Harvest Organs Post Mortem
  - More Sculpture
  - RimNauts
  - NetGun
  - Absolute Legends Hair
  - Project Itzal - Main Pack
  - Project Itzal - Even More Guns 
  - Project Itzal - Bonus Pack
  - Extended Human Body Simulation
  - Holsters And Scabbards
  - Bandage Wraps
  - Electric Fences And Floors (Continued)
  - Modders Deserve Credit, too
  - Sandy's RPG Style Inventory [1.2]
  - Vanilla Cooking Expanded - Sushi
  - Vanilla Cooking Expanded - Stews
  - Fav Locker
  - Vanilla Hair Expanded
  - Vanilla Hair Expanded - Beards
  - Ranged DPS
  - Dragon's Descent
  - Vanilla Expanded Framework
  - Vanilla Plants Expanded
  - Vanilla fishing Expanded
  - Vanilla Cooking Expanded
  - Vanilla Plants Expanded - Succulents
  - Vanilla Brewing Expanded
  - Vanilla Weapons Expanded - Grenades
  - Smarter Construction
  - Vanilla Weapons Expanded - Lasers
  - The  Human Hive
  - TMC Armory - Shotguns # 1
  - TMC Armory - AssaultRifle # 1
  - TMC Armory - Sidearms # 1
  - No Death Cooties On Armor
  - T45b Power Armor (Out of Date mod, for 1.0 & 1.1 currently)
  - RimThreaded [1.2]
  - Android Resurrection Kit (rebuild)
  - Jewelry
  - Gunplay
  - Grazing Lands
  - RimHeli
  - Save Our Ship 2
  - LED Lights
  - Room Sense
  - Pick Up And Haul (Out of Date mod, for 1.0 & 1.1 currently)

**Issue:** 
Game comes to a Crawling Frozen Slideshow, Debug menu shows multiple "Thread: XX did not finish within 1000ms. Restarting thread... " errors.

As far as I can discern, this is caused by a herd of Muffalo Revenge Chasing a Tier[2] Android settler of mine who had been hunting them began as two Muffalo got close enough to attack the Colonist. However I tried to wait it our and the error continues to happen actively whilst the Muffalo were not actively attacking, though they were on melee cooldown still (see Screenshots). I have replicated this in a new game by getting a herd of elephants to revenge at my colonist. the moment they went into the manhunter state, the game began to freeze and i started getting the "Thread: XX did not finish..." messages.

I had this issue happen with a raid previously, but it only seemed to happen for a short period of the approach when two of the attackers were moving on the same tile. They were in no way engaging in combat as they  were out of range at the time. I unfortunately do not have screenshots of this and have not been able to replicate it. 
I have not had problems with pawns walking on the same spot otherwise, even with caravans, so perhaps it has to do with the pawns being drafted or manhunting?

I hope this data is helpful!

Good Luck!

**Muffalo Incident Debug Menu output**
<script src="https://gist.github.com/TiresomeCube34/0daf8e5d5e4ba6f6e3ecefedbb2a16fb.js"></script>

**Recreation Debug Menu Output**
<script src="https://gist.github.com/TiresomeCube34/08e7fecfa65745912ee646bb27d41f98.js"></script>

 **and screenshots for all**
[screenshots and original logs.zip](https://github.com/cseelhoff/RimThreaded/files/5222549/screenshots.and.original.logs.zip)

**Comment by Natrukei** [comment]
@cseelhoff Here aswell
