### ISSUE TITLE
Exception in Verse.AI.ThinkNode_Priority TryIssueJobPackage 

### ISSUE THREAD

**Issue by Artembelov** [cseelhoff/RimThreaded#106]
Occours on loading in the map on game start slows down until it freezes does not recover

// Token: 0x0600601E RID: 24606 RVA: 0x0013C66C File Offset: 0x0013A86C
		private int FindEntry(TKey key)
		{
			if (key == null)
			{
				throw new ArgumentNullException("key");
			}
			if (this.buckets != null)
			{
				int num = this.comparer.GetHashCode(key) & int.MaxValue;
				for (int i = this.buckets[num % this.buckets.Length]; i >= 0; i = this.entries[i].next)
				{
					if (this.entries[i].hashCode == num && this.comparer.Equals(this.entries[i].key, key))
					{
						return i;
					}
				}
			}
			return -1;
		}

Pictures
https://ibb.co/vVY6kHJ
https://ibb.co/BKwQMgr

Mods UsedVersion: 1
Name: Playtesting
Mods:
- Id: brrainz.harmony_copy
  Name: Harmony
- Id: ludeon.rimworld
  Name: Core
- Id: ludeon.rimworld.royalty
  Name: Royalty
- Id: unlimitedhugs.hugslib_copy
  Name: HugsLib
- Id: fluffy.modmanager_copy
  Name: Mod Manager
- Id: majorhoff.rimthreaded_copy
  Name: RimThreaded [1.2]
- Id: crashm.colorcodedmoodbar.11_copy
  Name: CM Color Coded Mood Bar [1.1+]
- Id: troopersmith1.deathrattle_copy
  Name: Death Rattle Continued [1.2]
- Id: fluffy.desirepaths_copy
  Name: Desire Paths
- Id: dracoix.doormat.r12a_copy
  Name: Door Mat
- Id: edb.preparecarefully_copy
  Name: EdB Prepare Carefully
- Id: murmur.enemyselfpreservation_copy
  Name: Enemy Self Preservation
- Id: murmur.factionresources_copy
  Name: Faction Resources
- Id: mlie.factiontoempires_copy
  Name: Faction to Empires (Continued)
- Id: fluffy.fluffybreakdowns_copy
  Name: Fluffy Breakdowns
- Id: gt.sam.glittertech_copy
  Name: Glitter Tech
- Id: hc.animalreskins.1_copy
  Name: H.C_AnimalReskins_1
- Id: hc.animalreskins.10_copy
  Name: H.C_AnimalReskins_10
- Id: hc.animalreskins.2_copy
  Name: H.C_AnimalReskins_2
- Id: hc.animalreskins.3_copy
  Name: H.C_AnimalReskins_3
- Id: hc.animalreskins.4.1_copy
  Name: H.C_AnimalReskins_4.1
- Id: hc.animalreskins.5_copy
  Name: H.C_AnimalReskins_5
- Id: hc.animalreskins.6_copy
  Name: H.C_AnimalReskins_6
- Id: hc.animalreskins.9_copy
  Name: H.C_AnimalReskins_9
- Id: hc.thrumboreskin_copy
  Name: H.C_ThrumboReskin
- Id: hc.animal.1_copy
  Name: HC_Animal_1
- Id: hc.animal.2_copy
  Name: HC_Animal_2
- Id: hc.animal.3_copy
  Name: HC_Animal_3
- Id: hc.animal.4_copy
  Name: HC_Animal_4
- Id: leion247612.higherhpower_copy
  Name: Higher Power
- Id: orion.hospitality_copy
  Name: Hospitality
- Id: taveron.increasedstack_copy
  Name: Increased Stack
- Id: zzz.invisibleconduit_copy
  Name: Invisible Conduit
- Id: hanabishi.inwallcoolersandvents_copy
  Name: In-wall coolers and vents
- Id: mlie.jecstobaccoandcigarettes_copy
  Name: Jecs Tobacco and Cigarettes (Continued)
- Id: troopersmith1.lifesupport_copy
  Name: Life Support Continued [1.1][1.2]
- Id: pyrce.mass.graves_copy
  Name: Mass Graves
- Id: haplo.miscellaneous.robots_copy
  Name: Misc. Robots
- Id: leion247658.miscvhcraftablehrobots_copy
  Name: Misc. Craftable Robots
- Id: gloriousyuri.mcrretexture_copy
  Name: Misc. Craftable Robots Retexture
- Id: shadow.mcraddon_copy
  Name: Misc. Craftable Robots Addon
- Id: fluffy.pharmacist_copy
  Name: Pharmacist
- Id: arandomkiwi.powerpp_copy
  Name: Power++
- Id: extracting.organs_copy
  Name: Prisoner Harvesting
- Id: rimfridge.kv.rw_copy
  Name: '[KV] RimFridge'
- Id: sierra.rtgt_copy
  Name: RimTraits - General Traits
- Id: petetimessix.simplesidearms_copy
  Name: Simple sidearms
- Id: dhultgren.smarterconstruction_copy
  Name: Smarter Construction
- Id: gt.sam.tilledsoil_copy
  Name: Tilled Soil
- Id: neceros.tradershavemoney_copy
  Name: Traders Have Money
- Id: neceros.undergroundsoil_copy
  Name: Underground Soil
- Id: dhultgren.useminifiedbuildings_copy
  Name: Use Minified Buildings
- Id: murmur.walllight_copy
  Name: Wall Light
- Id: pinochemicali.moretradeships_copy
  Name: More Trade Ships
- Id: crlsniper.realisticrooms_copy
  Name: Realistic Rooms
- Id: shinzy.apparello_copy
  Name: Apparello 2
- Id: itzal.pi.bg_copy
  Name: Project Itzal - Bonus Guns
- Id: itzal.pi.cp_copy
  Name: Project Itzal - Charge Pack
- Id: itzal.vw.cp_copy
  Name: Project Itzal - Community Pack
- Id: itzal.vw.emg_copy
  Name: Project Itzal - Even More Guns
- Id: itzal.vw.eg_copy
  Name: Project Itzal - Extra Guns
- Id: itzal.pi.laser_copy
  Name: Project Itzal - Lasers
- Id: itzal.pi.mp_copy
  Name: Project Itzal - Main Pack
- Id: itzal.pi.sd_copy
  Name: Project Itzal - Special Delivery
- Id: itzal.pi.tmg_copy
  Name: Project Itzal - Too Many Guns
- Id: itzal.pi.ubw_copy
  Name: Project Itzal - Underbarreled weapons
- Id: nephlite.orbitaltradecolumn_copy
  Name: Utility Columns
- Id: syrchalis.universalfermenter
  Name: '[SYR] Universal Fermenter'
- Id: dismarzero.vgp.vgpvegetablegarden_copy
  Name: VGP Vegetable Garden
- Id: dismarzero.vgp.vgpsoylentproduction_copy
  Name: VGP Soylent Production
- Id: dismarzero.vgp.vgpmoreveggies_copy
  Name: VGP More Veggies
- Id: dismarzero.vgp.vgpgardentools_copy
  Name: VGP Garden Tools
- Id: dismarzero.vgp.vgpgardenresources_copy
  Name: VGP Garden Resources
- Id: dismarzero.vgp.vgpgardenmedicine_copy
  Name: VGP Garden Medicine
- Id: dismarzero.vgp.vgpgardengourmet_copy
  Name: VGP Garden Gourmet
- Id: dismarzero.vgp.vgpgardenfabrics_copy
  Name: VGP Garden Fabrics
- Id: dismarzero.vgp.vgpgardendyes_copy
  Name: VGP Garden Dyes
- Id: dismarzero.vgp.vgpgardencanning_copy
  Name: VGP Garden Canning
- Id: vanillaexpanded.vplantse_copy
  Name: Vanilla Plants Expanded
- Id: vanillaexpanded.vplantsesucculents_copy
  Name: Vanilla Plants Expanded - Succulents
- Id: vanillaexpanded.vtexe_copy
  Name: Vanilla Textures Expanded
- Id: vanillaexpanded.vwe_copy
  Name: Vanilla Weapons Expanded
- Id: harkon.gunnut_copy
  Name: Gun Nut
- Id: vanillaexpanded.vweg_copy
  Name: Vanilla Weapons Expanded - Grenades
- Id: vanillaexpanded.vwel_copy
  Name: Vanilla Weapons Expanded - Laser
- Id: vanillaexpanded.vweq_copy
  Name: Vanilla Weapons Expanded - Quickdraw
- Id: vanillaexpanded.vappe_copy
  Name: Vanilla Apparel Expanded
- Id: dninemfive.earlyindustrialsocieties_copy
  Name: Early Industrial Societies
- Id: vanillaexpanded.varme_copy
  Name: Vanilla Armour Expanded
- Id: saakra.empire_copy
  Name: Empire
- Id: oskarpotocki.vanillafactionsexpanded.core_copy
  Name: Vanilla Expanded Framework
- Id: vanillaexpanded.vcookestews_copy
  Name: Vanilla Cooking Expanded - Stews
- Id: vanillaexpanded.vcooke_copy
  Name: Vanilla Cooking Expanded
- Id: vanillaexpanded.vaeas_copy
  Name: Vanilla Animals Expanded — Arid Shrubland
- Id: vanillaexpanded.vaeau_copy
  Name: Vanilla Animals Expanded — Australia
- Id: vanillaexpanded.vaebf_copy
  Name: Vanilla Animals Expanded — Boreal Forest
- Id: vanillaexpanded.vaecd_copy
  Name: Vanilla Animals Expanded — Cats and Dogs
- Id: vanillaexpanded.vaed_copy
  Name: Vanilla Animals Expanded — Desert
- Id: vanillaexpanded.vaeed_copy
  Name: Vanilla Animals Expanded — Extreme Desert
- Id: vanillaexpanded.vaeis_copy
  Name: Vanilla Animals Expanded — Ice Sheet
- Id: vanillaexpanded.vaetr_copy
  Name: Vanilla Animals Expanded — Tropical Rainforest
- Id: vanillaexpanded.vaets_copy
  Name: Vanilla Animals Expanded — Tropical Swamp
- Id: vanillaexpanded.vaet_copy
  Name: Vanilla Animals Expanded — Tundra
- Id: vanillaexpanded.vbookse_copy
  Name: Vanilla Books Expanded
- Id: vanillaexpanded.vbrewe_copy
  Name: Vanilla Brewing Expanded
- Id: oskarpotocki.vanillafactionsexpanded.medievalmodule_copy
  Name: Vanilla Factions Expanded - Medieval
- Id: oskarpotocki.vanillafactionsexpanded.settlersmodule_copy
  Name: Vanilla Factions Expanded - Settlers
- Id: vanillaexpanded.vcef_copy
  Name: Vanilla Fishing Expanded
- Id: vanillaexpanded.vfecore_copy
  Name: Vanilla Furniture Expanded
- Id: vanillaexpanded.vfeart_copy
  Name: Vanilla Furniture Expanded - Art
- Id: vanillaexpanded.vfefarming_copy
  Name: Vanilla Furniture Expanded - Farming
- Id: vanillaexpanded.vfemedical_copy
  Name: Vanilla Furniture Expanded - Medical Module
- Id: vanillaexpanded.vfepower_copy
  Name: Vanilla Furniture Expanded - Power
- Id: vanillaexpanded.vfeproduction_copy
  Name: Vanilla Furniture Expanded - Production
- Id: vanillaexpanded.vfepropsanddecor_copy
  Name: Vanilla Furniture Expanded - Props and Decor
- Id: vanillaexpanded.vfesecurity_copy
  Name: Vanilla Furniture Expanded - Security
- Id: vanillaexpanded.vfespacer_copy
  Name: Vanilla Furniture Expanded - Spacer Module
- Id: ryder.turnitonoff_copy
  Name: Turn It On and Off
- Id: mlie.brrandphew_copy
  Name: Brrr and Phew (Continued)
- Id: canicvs.turtlefriendlyraids_copy
  Name: Turtle Friendly Raids
- Id: bob.tickspersecond
  Name: '[1.2] TicksPerSecond'
- Id: fluffy.thebirdsandthebees_copy
  Name: The Birds and the Bees
- Id: cb84.theyreinthetrees_copy
  Name: Theyre in the Trees
- Id: sun.reducer_copy
  Name: Sun Lamp Power
- Id: earthyturtle.stackablechunks_copy
  Name: Stackable Chunks
- Id: neceros.reinforcedwalls_copy
  Name: Reinforced Walls
- Id: cb84.longerrange_copy
  Name: Long Range Firefights
- Id: mlie.insulation_copy
  Name: Insulation (Continued)
- Id: arandomkiwi.guardsforme_copy
  Name: Guards For Me
- Id: dubwise.dubsmintminimap_copy
  Name: Dubs Mint Minimap
- Id: frozensnowfox.efficientutilities_copy
  Name: '[FSF] Efficient Utilities'
- Id: mlie.deeprim_copy
  Name: DeepRim (Continued)
- Id: dninemfive.d9framework_copy
  Name: D9 Framework
- Id: dninemfive.ajo.misc_copy
  Name: Additional Joy Objects - Misc
- Id: user19990313.runtimegc
  Name: RuntimeGC
- Id: sulusdacor.james76543.meltup.advancedpowerplus
  Name: Advanced Power Plus
- Id: oblitus.animalslogic
  Name: Animals Logic
- Id: madarauchiha.custommapsizes
  Name: Custom Map Sizes
- Id: sarg.geneticrimalphaanimals
  Name: GeneticRim Alpha Animals Patch
- Id: dylan.animalgear
  Name: Animal Gear
- Id: sarg.geneticrim
  Name: Genetic Rim
- Id: mantrasong.survadd.1
  Name: Survivalist's Additions
- Id: vanillaexpanded.vtexgr
  Name: Vanilla Textures Expanded - Genetic Rim
- Id: vanillaexpanded.vcookesushi
  Name: Vanilla Cooking Expanded - Sushi
- Id: uuugggg.safelyhiddenaway
  Name: Safely Hidden Away
- Id: zylle.morevanillabiomes
  Name: More Vanilla Biomes
- Id: smashphil.boats
  Name: Boats
- Id: sarg.alphaanimals
  Name: Alpha Animals
- Id: meltup.mylittleboat
  Name: My Little Boat Expansion
- Id: fluffy.researchtree
  Name: Research Tree
- Id: biomesteam.biomescore
  Name: Biomes! Core
- Id: biomesteam.biomesislands
  Name: Biomes! Islands
- Id: sarg.alphabiomes
  Name: Alpha Biomes
- Id: jaxe.coastlines
  Name: Coastlines
- Id: arandomkiwi.mercenariesforme
  Name: Mercenaries For Me

**Comment by Tschuangtse** [comment]
Can confirm; mod exists universally.
Appended log file.

Bug is not picked up by dnSpy for me.

[Player.log](https://github.com/cseelhoff/RimThreaded/files/5226863/Player.log)
![2020-09-15 19_33_27-Window](https://user-images.githubusercontent.com/62553097/93247877-464c2200-f78f-11ea-97fe-7a3ce901cf6f.png)

**Comment by cseelhoff** [comment]
Closing bug. Many bugs have been fixed since this was reported. Please reopen in new bug report using the new templates if this issue persists.
