### ISSUE TITLE
That combat melee death thing

### ISSUE THREAD

**Issue by Artembelov** [cseelhoff/RimThreaded#107]
Inside of HediffComp_Effecter

namespace Verse
{
	// Token: 0x02000280 RID: 640
	public static class HediffUtility
	{
		// Token: 0x06001133 RID: 4403 RVA: 0x000613AC File Offset: 0x0005F5AC
		public static T TryGetComp<T>(this Hediff hd) where T : HediffComp
		{
			HediffWithComps hediffWithComps = hd as HediffWithComps;
			if (hediffWithComps == null)
			{
				return default(T);
			}
			if (hediffWithComps.comps != null)
			{
				for (int i = 0; i < hediffWithComps.comps.Count; i++)
				{
					T t = hediffWithComps.comps[i] as T;
					if (t != null)
					{
						return t;
					}
				}
			}
			return default(T);
		}
https://ibb.co/JQqPN6F
https://ibb.co/kM7dSKz
https://ibb.co/P58w5xz
https://ibb.co/4SQBGpc

Caused by the ususal 10000 point raid and tribal archers mixed in them after skipping many other errors

**Comment by Natrukei** [comment]
@cseelhoff this could be one aswell
