### ISSUE TITLE
Trying on the benchmarkers map (10000 colonists)

### ISSUE THREAD

**Issue by TheVillageGuy** [cseelhoff/RimThreaded#118]
It works for roughly 170 ticks, then starts throwing exceptions. From that moment forward nothing is displayed on the screen except for the colonists` names and nothing seems to happen, unless when the game menu is opened. Running only your mod.

https://www.reddit.com/r/RimWorldPorn/comments/hc0q24/herwitstonbenchmarkers10000temperate_forest3060/?sort=confidence

[Player.log](https://github.com/cseelhoff/RimThreaded/files/5238514/Player.log)

**Comment by cseelhoff** [comment]
fixed RimThreaded.SituationalThoughtHandler_Patch.RemoveExpiredThoughtsFromCache
