### ISSUE TITLE
Sidescrolling as if key is stuck

### ISSUE THREAD

**Issue by Tschuangtse** [cseelhoff/RimThreaded#122]
Version 1.0.25
Mod-List: 
-Harmony
-HugsLib
-RimThreaded

No error thrown to log or unity engine via dnSpy.

Appears in vanilla: false
Reproducable: true
Open xbox game bar with Win+g (default: win10)
Start a new recording
Close the window with the same shortcut again while holding down w, a, s, d
The pressed key is now stuck and moves your camera accordingly

Behavior persists on world map.

Work around: 
Saving the game stops this. No reloading of the save game required.

Video links to illustrate:
https://1drv.ms/v/s!ArmQvHd08mRLoDEOWwggsgcc7lJQ?e=GAfGtu
https://1drv.ms/u/s!ArmQvHd08mRLoDRd1nVkyF7p_H7g?e=wCces1

Personal note: I believe this to be a weird interaction with gamebar, as no error is thrown, and we might just have to disregard it as "Third party issue".

**Comment by cseelhoff** [comment]
Closing bug. Many bugs have been fixed since this was reported. Please reopen in new bug report using the new templates if this issue persists.
