### ISSUE TITLE
Exception in JobDriver tick for pawn

### ISSUE THREAD

**Issue by Tschuangtse** [cseelhoff/RimThreaded#123]
Version: 1.0.25
Modlist:
-Harmony
-HugsLib
-RimThreaded

Appears in vanilla: false
Reproducable: true

When executing multiple raids with 10000 points (three in my last test) the game crashes with a System.Threading.ThreadAbortException at Verse.AI.JobDriver.DriverTick

Added player.log as well as screenshot of dnSpy
[Player.log](https://github.com/cseelhoff/RimThreaded/files/5241665/Player.log)
![dnSpy](https://user-images.githubusercontent.com/62553097/93524351-acbe7500-f934-11ea-868f-42a75a04a0e4.png)

**Comment by cseelhoff** [comment]
Closing bug. Many bugs have been fixed since this was reported. Please reopen in new bug report using the new templates if this issue persists.
