### ISSUE TITLE
Temperature of tiles in world map not generating correctly.

### ISSUE THREAD

**Issue by magistrate04** [cseelhoff/RimThreaded#131]
Specs:
Processor: Intel i7-8700 @ 3.20GHz no OC
Hard drive: Western Digital NAND WDS100T2B0A 1TB SSD
GPU: RTX 2070

Modlist:
Harmony (1.0.4.0)
Core (1.2.2753)
Royalty
RimThreaded (1.0.31.0)

Expected Behavior:
Standard Rimworld world generation for usual game with standard temperature variations.

Behavior:
Temperature ranges are completely static on world tiles when the world map generates, so every tile on the map spawns with a set temperature that does not fluctuate at all. (For example, a selected world tile might show "Average temperature: 45.0F (45F to 45F) ALL tiles generate this way.) Growing period shows either "Never" or "Year-Round" with no exceptions anywhere.

Note:
I submitted the only line that appeared in the debug log, no other yellow or red lines were present. The "Already executed" line appears when I click to generate the world, regardless of any settings I change. This is my first time submitting a bug report for anything, ever, so I hope I got everything you need. This mod was working previously for me yesterday, but broke with the new update. Thanks again for all your guys work!

Link to Error(s):
https://gist.github.com/magistrate04/e2be8e6b7402141d06668f018bb49394

**Comment by cseelhoff** [comment]
I guess my change in 1.0.31 broke this. I'll roll back that change once I get to a PC.
