### ISSUE TITLE
Could not load UnityEngine.Texture2D

### ISSUE THREAD

**Issue by AGingersaurusRex** [cseelhoff/RimThreaded#134]
Any time I craft apparel I get this red error. I don't know if anyone else has reported this.

https://gist.github.com/AGingersaurusRex/200aebef563f3db8fb36f9b7f2c48b89

**Comment by cseelhoff** [comment]
Nice job finding this, if it is indeed reproducible. I've been trying to hunt this one for a while.

**Comment by cseelhoff** [comment]
Closing bug. Many bugs have been fixed since this was reported. Please reopen in new bug report using the new templates if this issue persists.
