### ISSUE TITLE
Crash Landing(mod) dosn't crash land

### ISSUE THREAD

**Issue by jal21** [cseelhoff/RimThreaded#140]
i started a new moded play throw and i did crash lading (easy) and my colonist where ok but when ever a peas of the ship landed it would disappear on contact. i know it has not been updated to 1.12 but it dose work on 1.12. there was nothing in the logs for what happened just some 2d objects could not be loaded by unity and i saw someone else put a ticket in for that.

**Comment by cseelhoff** [comment]
Closing bug. Many bugs have been fixed since this was reported. Please reopen in new bug report using the new templates if this issue persists.
