### ISSUE TITLE
Could not Load UnityEngine.Texture2D (A different problem?)

### ISSUE THREAD

**Issue by AGingersaurusRex** [cseelhoff/RimThreaded#141]
So I'm getting the "Could not load UnityEngine.Texture2D" again. However this just randomly happens (verse at the crafting bench every time a new item was crafted). Could be related to my other UnityEngine.Texture2D errors.

**Edit1: can confirm that this happens on vanilla (no mods). It just seems totally random!**

https://gist.github.com/2647db466b791b29cf64bafa2154b564

Could not load UnityEngine.Texture2D at Things/Pawn/Humanlike/Hairs/Ponytails_northm in any active mod or in base resources.
Verse.Log:Error(String, Boolean)
RimThreaded.ContentFinder_Texture2D_Patch:GetTexture2D(String, Boolean)
RimThreaded.Ticklist_Patch:RespondToTexture2DRequests()
RimThreaded.Ticklist_Patch:MainThreadWaitLoop()
RimThreaded.Ticklist_Patch:Tick(TickList)
Verse.TickList:Verse.TickList.Tick_Patch1(TickList)
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()

**Comment by cseelhoff** [comment]
Closing bug. Many bugs have been fixed since this was reported. Please reopen in new bug report using the new templates if this issue persists.
