### ISSUE TITLE
Shooting X amount of guns at a target results in thread restarts

### ISSUE THREAD

**Issue by ProvoGo** [cseelhoff/RimThreaded#144]
Modlist:
Harmony
Core
RimThreaded (1.0.39)

Expected behavior:
Shooting lots of guns still works

Behavior:
Shooting lots of guns sometimes results in thread restarts.
Making it happen again just takes 3 guys with miniguns shooting at random animals for a bit

https://gist.github.com/ProvoGo/ae3a3bae94ff278c6c195694a99fc7db

**Comment by cseelhoff** [comment]
Closing bug. Many bugs have been fixed since this was reported. Please reopen in new bug report using the new templates if this issue persists.
