### ISSUE TITLE
Exception with hospitality 

### ISSUE THREAD

**Issue by Artembelov** [cseelhoff/RimThreaded#145]
Located during loading the world while playtesting a modpack 

		// Token: 0x06006020 RID: 24608 RVA: 0x0013C758 File Offset: 0x0013A958
		private bool TryInsert(TKey key, TValue value, InsertionBehavior behavior)
		{
			if (key == null)
			{
				throw new ArgumentNullException("key");
			}
			if (this.buckets == null)
			{
				this.Initialize(0);
			}
			int num = this.comparer.GetHashCode(key) & int.MaxValue;
			int num2 = num % this.buckets.Length;
			int num3 = 0;
			int i = this.buckets[num2];
			while (i >= 0)
			{
				if (this.entries[i].hashCode == num && this.comparer.Equals(this.entries[i].key, key))
				{
					if (behavior == InsertionBehavior.OverwriteExisting)
					{
						this.entries[i].value = value;
						this.version++;
						return true;
					}
					if (behavior == InsertionBehavior.ThrowOnExisting)
					{
						throw new ArgumentException(SR.Format("An item with the same key has already been added. Key: {0}", key));
					}
					return false;
				}
				else
				{
					num3++;
					i = this.entries[i].next;
				}
			}
			int num4;
			if (this.freeCount > 0)
			{
				num4 = this.freeList;
				this.freeList = this.entries[num4].next;
				this.freeCount--;
			}
			else
			{
				if (this.count == this.entries.Length)
				{
					this.Resize();
					num2 = num % this.buckets.Length;
				}
				num4 = this.count;
				this.count++;
			}
			this.entries[num4].hashCode = num;
			this.entries[num4].next = this.buckets[num2];
			this.entries[num4].key = key;
			this.entries[num4].value = value;
			this.buckets[num2] = num4;
			this.version++;
			if (num3 > 100 && this.comparer is NonRandomizedStringEqualityComparer)
			{
				this.comparer = (IEqualityComparer<TKey>)EqualityComparer<string>.Default;
				this.Resize(this.entries.Length, true);
			}
			return true;
		}

https://ibb.co/kS1xQ49
https://ibb.co/NKdgw8g
https://ibb.co/gRDY9Ks

**Comment by cseelhoff** [comment]
Closing bug. Many bugs have been fixed since this was reported. Please reopen in new bug report using the new templates if this issue persists.
