### ISSUE TITLE
Room is unroffed - no gameplay effect

### ISSUE THREAD

**Issue by Tschuangtse** [cseelhoff/RimThreaded#148]
Running RimThreaded 1.41
Other Mods
-Harmony
-HugsLib
-TicksPerSecond

After constructing a room I noticed it to be labeled as unroofed. This remained so after saving and reloading.
The temperature of the room does not seem to be affected.
There is no entry in the error log at all from this.

Picture added for clarification.
![bug: unroffed](https://user-images.githubusercontent.com/62553097/94337499-14d32200-ffeb-11ea-8967-7c035dffe615.png)

My guess is that the check if the roof as been constructed successfully and the actual building of the roof are two separate methods in the original game, and the check is not called correctly. Also, this would not explain why I get "indoor temperatures".

Kind regards
Tschua

**Comment by cseelhoff** [comment]
Closing bug. Many bugs have been fixed since this was reported. Please reopen in new bug report using the new templates if this issue persists.
