### ISSUE TITLE
Exception ticking world pawn

### ISSUE THREAD

**Issue by Tschuangtse** [cseelhoff/RimThreaded#150]
OS: Linux (Manjaro)
Game version: 1.2.2753
Current content BuildID: 5527989

Can be recreated: yes
Cause of issue: Unknown

Relevant log attached: yes
Modlist attached: yes

Description: when running a modded game exceptions are thrown for world pawns who cannot be ticked. This throws an error to the in game log. It does not appear to affect gameplay in the shortterm. The same error/exception is thrown for all known world pawns.

[Log.txt](https://github.com/cseelhoff/RimThreaded/files/5288364/Log.txt)

[Main.txt](https://github.com/cseelhoff/RimThreaded/files/5288368/Main.txt)

**Comment by cseelhoff** [comment]
Td enhance is currently not compatible. It will require their code to be modified

**Comment by cseelhoff** [comment]
Closing bug. Many bugs have been fixed since this was reported. Please reopen in new bug report using the new templates if this issue persists.
