### ISSUE TITLE
Exception in JobDriver tick for pawn

### ISSUE THREAD

**Issue by Tschuangtse** [cseelhoff/RimThreaded#151]
OS: Linux (Manjaro)
Game version: 1.2.2753
Current content BuildID: 5527989

Can be recreated: yes
Cause of issue: Unknown

Relevant log attached: yes
Modlist attached: yes

Description: when playing regularly an exception is thrown to the in game error log for each pawn  on the map.

[Log2.txt](https://github.com/cseelhoff/RimThreaded/files/5288374/Log2.txt)
[Main.txt](https://github.com/cseelhoff/RimThreaded/files/5288375/Main.txt)

**Comment by cseelhoff** [comment]
Another td enhance conflict

**Comment by cseelhoff** [comment]
Closing bug. Many bugs have been fixed since this was reported. Please reopen in new bug report using the new templates if this issue persists.
