### ISSUE TITLE
exception with quality builder and buildable terrain

### ISSUE THREAD

**Issue by tehchanman** [cseelhoff/RimThreaded#171]
Specs:
Intel Xeon x5690 oc 4.5ghz
sandisk ultra 500gb
24gb
rtx 2070 super FE

Mods:
brrainz.harmony
ludeon.rimworld
smashphil.neceros.srtsexpanded
ludeon.rimworld.royalty
unlimitedhugs.hugslib
dracoix.mdk.terrain
nyan.sortie
fluffy.modmanager
edb.preparecarefully
lokivklokenaandoke.autopriorities
nestofmoon.jobslimittweak
vanya.tools.bulkcarrier
krafs.levelup
rimfridge.kv.rw
lwm.deepstorage
user19990313.runtimegc
zylle.mapdesigner
leafzxg.masterofcrafting
leafzxg.masterofcooking
avilmask.microdesignations
aardvark.morevisiblepause
dingo.persistentfloatmenus
automatic.recipeicons
notfood.researchpal
jaxe.rimhud
savestoragesettings.kv.rw
roolo.searchanddestroy
erdelf.showmoddesignators
jelly.craftsmanship
dubwise.dubsbreakmod
dubwise.dubsmintminimap
dubwise.dubsmintmenus
dubwise.dubsperformanceanalyzer
mlie.foodalert
notfood.frameratecontrol
denethor0.gainskillpassions
ling.thelowcooler
dame.activecircuits
unlimitedhugs.allowtool
com.bymarcin.architecticons
razor2.3.anotherrimworldmod.autocutblight
mireia.bodies
voult.betterpawncontrol
owlchemist.bettervanillamasking
falconne.bwm
insertkey.buildertweaks
brrainz.cameraplus
kapitanoczywisty.changemapedge
void.charactereditor
navyseal5.cleaningstation
petetimessix.compacthediffs
vincenty.craftableglitterworldmedicine
jaxe.disableautojoin
jaxe.disableruins
tikubonn.dontblockdoor
zylle.extraalerts
forcedojob.kv.rw
alex.friendlyfiretweaks
telefonmast.graphicssettings
automatic.gunplay
falconne.heatmap
netrve.usemelee
ratys.madskills
supes.mapwideorbitaltradebeacon
fluffy.medicaltab
erdelf.minifyeverything
kapitanoczywisty.minimallightcontrol
sirrandoo.mpe
lingluo.coolheater
malkav73.neurotrainer
mitz.nobarrackpenalty
doug.nojobauthors
smuffle.nomurderousrage
kasumitakeshi.noprisonbreaks
ryflamer.norockets
smuffle.noslaughterer
mlie.npdtiers
proxyer.optionalicons4ai
pathavoid.kv.rw
fed1splay.pawntargetfix
fluffy.pharmacist
arandomkiwi.downforme
arandomkiwi.powerpp
dninemfive.qualitycooldown
hatti.qualitybuilder
hatti.qualitysurgeon
mastertea.randomplus
brrainz.rangefinder
crlsniper.realisticrooms
jaxe.reorderer
uuugggg.replacestuff
brrainz.reversecommands
arandomkiwi.rimthemes
uuugggg.roomfood
ratys.rtfuse
brrainz.samespot
mlie.runandhide
okradonkey.singleplanttexturepatch
pinochemicali.skilledstonecutting
uuugggg.smartmedicine
weilbyte.snapout
azelion.sortcolonistbar
linkolas.stabilize
automatic.startupimpact
earthyturtle.stackablechunks
uuugggg.tdpack
ghxx.techadvancing
pyrce.terrain.zone.select
uuugggg.thickarmor
jaxe.toggleharvest
tradingcontrol.common.core
canicvs.turtlefriendlyraids
grimm.unlimited
knight.useyourgun
murmur.walllight
mlie.wehadatrader
crlsniper.metaldoesntburn
neceros.ninetyninepercent
brrainz.achtung
fozzy421.butcherhfirst
proxyer.desurgeries.desurgeriescolor
fozzy107.deconstructhfirst
alias.degeneralizework
wemd.expandedfloors
frozensnowfox.filthvanisheswithrainandtime
velc.hatsdisplayselection
wexman.mines
sneaks.recycle
neceros.plantgrowthsync
ratys.rtsolarflareshield
gt.sam.tilledsoil
paradies.resurrectorserumonrotten
tammybee.whereismyweapon
dracoix.zars.core
dracoix.zars.spots
dracoix.zars.thermo
lbmaian.begonemessage
vat.epoeforked
vat.epoeforkedroyalty
tarojun.epoeforked.directcraftingonly
malteschulze.rimmsqol
targhetti.showdrafteesweapon
vanillaexpanded.vtexe
jelly.pleasehaulperishables
sulusdacor.james76543.meltup.advancedpowerplus
frozensnowfox.betterspiketraps
mantrasong.farmableneutroamine.1
mlie.hightechlaboratoryfacilities
okradonkey.infiniterefuelables
proxyer.makeableartifacts
rjah.rw.nohumanbutcher
mlie.rimbank
itchyflea.medicaltraining
automatic.bionicicons
ogliss.ykara.harvesteverything
svcbot.lhm_copy
mlie.sdluciferiumproduction_copy
roolo.runandgun
etrt.medicineproduction
battlemage64.geneticallymodifiedplants
falconne.labelsonfloor
dismarzero.vgp.smokedmeat
cp.military.furniture_copy
mehni.pickupandhaul
tammybee.cutplantsbeforebuilding
phomor.craftingqualityrebalanced
ogre.ogrestack
mlie.centralizedclimatecontrol
jaxxa.ed.enhancedoptions
anomalous.dynamicpopulation
roolo.dualwield
com.yayo.combat3
sarg.smartspeed
merthsoft.designatorshapes
jaxe.boommod
ryflamer.misc.drawabead_copy
not.food
mlie.incidentcountmultiplier
automatic.incidenttweaker
mlie.mercerbackpacksnanosuit
nomaxbills.kv.rw
avilmask.nonunopinata
bdew.cremateautostrip
netrve.dsgui
xedos.personabond
lingluo.planthuman
jamaicancastle.shoo
wemd.smallsolarpanels
automatic.prisonerbedsetowner
phoenix.vanillasolarsheild
mlie.dehotkeys
spdskatr.ssbiggerbatteries
spdskatr.ssbatteryfuse
bob.tickspersecond
ruyan.stuffcount
dhultgren.smarterconstruction
mlie.raidersneverdie
tallidown.numbers
mlie.10xcarryingcapacity
uuugggg.sharetheload
coca.simplyhyperweave
thegoofyone.exoticjoy
etrt.cannibaltweaks
mehni.misc.modifications
sumghaidubwise.replimat
mlie.prisonerarena
notooshabby.bettercolonistbar
proxyer.removablemtrockroofpatche
sixdd.littlestorage2
mlie.thewitchertrials
auxiliusm.supersoil
mlie.morehydroponicscrops
okradonkey.noedgefade
otheruolly118.diyhneutroamine
likeafox.rimworld.safepause
captainhaywood179.smeltheverything
mlie.grubfarm
frozensnowfox.growablemushrooms
8z.callforintel
automatic.autolinks
adda.droponwaterrevived
wemd.reinforceddoors
arandomkiwi.raidsforme
arandomkiwi.rimsaves
spookiewookie.additionalvanillacrafting
jaxe.bubbles
daylight.wbsmorelinkf
daylight.wbsmorelinkfsuper
torann.rimwar
codeoptimist.assortedalterations
syrchalis.setupcamp
saucypigeon.addtransportpod
dubwise.dubsrimkit
fumble.betterspeed
unlimitedhugs.mapreroll
antaioz.bettervents
kentington.saveourship2
jovianpug.caravanlageliminator
buildable.terrain
majorhoff.rimthreaded
ludeon.rimworld.royalty

Behavior:
Using buildable terrain sand 'terraform.' On new colony start, desert map. While trying to change soft sand to sand with sand terraform. Following errors occur. Pawns start to lag and sand terraform job fails to finish leaving soft stand still.

Expected Behavior: 
Terraform soft sand to sand.

Log:
https://gist.github.com/tehchanman/e58061c36c50332a3672b0c1d21f805d

**Comment by cseelhoff** [comment]
Closing bug. Many bugs have been fixed since this was reported. Please reopen in new bug report using the new templates if this issue persists.
