### ISSUE TITLE
Root level expectation and more 

### ISSUE THREAD

**Issue by EasedMango** [cseelhoff/RimThreaded#173]
![image](https://user-images.githubusercontent.com/52468946/95616114-4ca08780-0a37-11eb-8b4b-4ca79ae27e1c.png)

I only have mod  manager and allowtool with hugslib and harmony. not counting RimThreaded. the game runs for a few seconds and then freezes

**Comment by cseelhoff** [comment]
Closing bug. Many bugs have been fixed since this was reported. Please reopen in new bug report using the new templates if this issue persists.
