### ISSUE TITLE
Fluffy breakdown issue.

### ISSUE THREAD

**Issue by PixelRave** [cseelhoff/RimThreaded#179]
Everything seems to work without fluffy breakdown. Much needed mod.

https://gist.github.com/9ded2e96549ae10f34ac6682c5d5c151

Mods:
- Id: brrainz.harmony
  Name: Harmony
- Id: majorhoff.rimthreaded
  Name: RimThreaded [1.2]
- Id: ludeon.rimworld
  Name: Core
- Id: smashphil.neceros.srtsexpanded
  Name: SRTS Expanded
- Id: unlimitedhugs.hugslib
  Name: HugsLib
- Id: com.yayo.combat3
  Name: Yayo's Combat 3
- Id: vanillaexpanded.vwe
  Name: Vanilla Weapons Expanded
- Id: lwm.deepstorage
  Name: LWM's Deep Storage
- Id: fluffy.researchtree
  Name: Research Tree
- Id: fluffy.commandpalette
  Name: Command Palette
- Id: dubwise.dubsmintminimap
  Name: Dubs Mint Minimap
- Id: fluffy.colonymanager
  Name: Colony Manager
- Id: dhultgren.smarterconstruction
  Name: Smarter Construction
- Id: fluffy.stuffedfloors
  Name: Stuffed Floors
- Id: buildable.terrain
  Name: Buildable Terrain v1
- Id: falconne.labelsonfloor
  Name: Labels on Floor
- Id: nanoce.glasslights
  Name: Glass+Lights
- Id: neceros.reinforcedwalls
  Name: Reinforced Walls
- Id: fluffy.worktab
  Name: Work Tab
- Id: fluffy.modmanager
  Name: Mod Manager
- Id: ykara.epoe
  Name: Expanded Prosthetics and Organ Engineering
- Id: haplo.miscellaneous.training
  Name: Misc. Training
- Id: vanillaexpanded.vplantse
  Name: Vanilla Plants Expanded
- Id: dubwise.rimatomics
  Name: Rimatomics
- Id: vanillaexpanded.vcef
  Name: Vanilla Fishing Expanded
- Id: unlimitedhugs.allowtool
  Name: Allow Tool
- Id: fluffy.fluffybreakdowns
  Name: Fluffy Breakdowns
- Id: 4loris4.morelinkables
  Name: More Linkables
- Id: invisible.conduits
  Name: Invisible Conduits 1.2
- Id: ratys.rtfuse
  Name: RT Fuse
- Id: soulfulpumpkin.tabletoptrove
  Name: Tabletop Trove - Additional Joy Objects and Decor
- Id: ogliss.thewhitecrayon.quarry
  Name: Quarry 1.1
- Id: dubwise.dubsbadhygiene
  Name: Dubs Bad Hygiene
- Id: dubwise.dubsperformanceanalyzer
  Name: Dubs Performance Analyzer
- Id: bishop.music
  Name: Music on the Rim
- Id: unlimitedhugs.mapreroll
  Name: Map Reroll
- Id: edb.preparecarefully
  Name: EdB Prepare Carefully

**Comment by cseelhoff** [comment]
Closing bug. Many bugs have been fixed since this was reported. Please reopen in new bug report using the new templates if this issue persists.
