### ISSUE TITLE
Threads keep restarting at Verse.AI.JobDriver.DriverTick

### ISSUE THREAD

**Issue by FervidFiend** [cseelhoff/RimThreaded#183]
Specs:
Ryzen 9 3900x oc 4.4GHz
gtx 1080 oc 

RimThreaded Version: 1.0.60

Modlist:
-Harmony
-Core
-HugsLib
-Mod Manager
-Smart Speed
-TicksPerSecond
-RimThreaded
-Camera+

Appears in vanilla: false
Reproducible: true

Similar to error 123 (https://github.com/cseelhoff/RimThreaded/issues/123), when running 2 or more raids on a new map when they attack each other the threads keep restarting at Verse.AI.JobDriver.DriverTick

Whole error is as follows:
https://gist.github.com/FervidFiend/05691bc064b6e1ae90670317ecc791c5

**Comment by cseelhoff** [comment]
Closing bug. Many bugs have been fixed since this was reported. Please reopen in new bug report using the new templates if this issue persists.
