### ISSUE TITLE
errors with no path

### ISSUE THREAD

**Issue by FervidFiend** [cseelhoff/RimThreaded#187]
Specs:
Ryzen 9 3900x oc 4.4GHz
gtx 1080 oc

RimThreaded Version: 1.0.63

Modlist:
-Harmony
-Core
-HugsLib
-Mod Manager
-Smart Speed
-TicksPerSecond
-RimThreaded
-Camera+

Appears in vanilla: false
Reproducible: somewhat

error when colonists try to build roofs, ran into it a few different times now and it seems to be when they cant reach the build roof zone but im not sure.

errors:
https://gist.github.com/FervidFiend/7ec5801842b5ece818bec38c1684e7dd
https://gist.github.com/FervidFiend/0d2c77cc0066221dcf0970b546870721

discovered another error probably to do with pawns having no path, console goes crazy with it when i have alot of colonists

error:
https://gist.github.com/FervidFiend/56bcf57d57d3a6ff2f76136f96057c1e

**Comment by cseelhoff** [comment]
Closing bug. Many bugs have been fixed since this was reported. Please reopen in new bug report using the new templates if this issue persists.
