### ISSUE TITLE
JobDriver_AttackMelee error

### ISSUE THREAD

**Issue by FervidFiend** [cseelhoff/RimThreaded#188]
Specs:
Ryzen 9 3900x oc 4.4GHz
gtx 1080 oc

RimThreaded Version: 1.0.63

Modlist:
-Harmony
-Core
-HugsLib
-Mod Manager
-Smart Speed
-TicksPerSecond
-RimThreaded
-Camera+

Appears in vanilla: false
Reproducible: true (pretty much always happens when i run the battleroyale humanlike in dev tools)

occasional error when multiple pawns try to melee the same pawn:
https://gist.github.com/FervidFiend/c998031065cc175260a3d029f698ca2b (human on mech)
https://gist.github.com/FervidFiend/cb422104d66f0bb1bb807c0aa02ff356 (human on human)

**Comment by cseelhoff** [comment]
Closing bug. Please reopen in new bug report using the new templates if this issue persists.
