### ISSUE TITLE
error when multiple explosions affect the same thing (tested on wooden walls)

### ISSUE THREAD

**Issue by FervidFiend** [cseelhoff/RimThreaded#189]
Specs:
Ryzen 9 3900x oc 4.4GHz
gtx 1080 oc

RimThreaded Version: 1.0.63

Modlist:
-Harmony
-Core
-HugsLib
-Mod Manager
-Smart Speed
-TicksPerSecond
-RimThreaded
-Camera+

Appears in vanilla: false
Reproducible: true (use devmodes explosions)

error when multiple explosions go off in close proximity affecting the same thing, tested multiple explosives, they pretty much all do the same thing.

got 3 main frequent errors:
https://gist.github.com/FervidFiend/36b1fc49d6d2cd0378fe7c95afd433cb
https://gist.github.com/FervidFiend/53076e115957b3f887c62e394bb49d99
https://gist.github.com/FervidFiend/2443c83ede6f80c78d84e655e8ecd157

**Comment by cseelhoff** [comment]
Closing bug. Please reopen in new bug report using the new templates if this issue persists.
