### ISSUE TITLE
CanGiveJob and JobOnX methods may not be synchronized

### ISSUE THREAD

**Issue by Tschuangtse** [cseelhoff/RimThreaded#191]
Running a heavily modded game I came across this beauty of an error.
Using 6 Cores/Threads.
Standard map size.
Current build: 1.0.64

RimWorld.WorkGiver_GrowerSow provided target (166, 0, 112), Map_0 but yielded no actual job for pawn Aghvidhson. The CanGiveJob and JobOnX methods may not be synchronized.
Verse.Log:Error(String, Boolean)
Verse.Log:ErrorOnce(String, Int32, Boolean)
RimWorld.JobGiver_Work:RimWorld.JobGiver_Work.TryIssueJobPackage_Patch0(JobGiver_Work, Pawn, JobIssueParams)
RimThreaded.ThinkNode_PrioritySorter_Patch:TryIssueJobPackage(ThinkNode_PrioritySorter, ThinkResult&, Pawn, JobIssueParams)
Verse.AI.ThinkNode_PrioritySorter:Verse.AI.ThinkNode_PrioritySorter.TryIssueJobPackage_Patch1(ThinkNode_PrioritySorter, Pawn, JobIssueParams)
RimThreaded.ThinkNode_Priority_Patch:TryIssueJobPackage(ThinkNode_Priority, ThinkResult&, Pawn, JobIssueParams)
Verse.AI.ThinkNode_Priority:Verse.AI.ThinkNode_Priority.TryIssueJobPackage_Patch1(ThinkNode_Priority, Pawn, JobIssueParams)
Verse.AI.ThinkNode_Tagger:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Subtree:TryIssueJobPackage(Pawn, JobIssueParams)
RimThreaded.ThinkNode_Priority_Patch:TryIssueJobPackage(ThinkNode_Priority, ThinkResult&, Pawn, JobIssueParams)
Verse.AI.ThinkNode_Priority:Verse.AI.ThinkNode_Priority.TryIssueJobPackage_Patch1(ThinkNode_Priority, Pawn, JobIssueParams)
Verse.AI.ThinkNode_Conditional:TryIssueJobPackage(Pawn, JobIssueParams)
RimThreaded.ThinkNode_Priority_Patch:TryIssueJobPackage(ThinkNode_Priority, ThinkResult&, Pawn, JobIssueParams)
Verse.AI.ThinkNode_Priority:Verse.AI.ThinkNode_Priority.TryIssueJobPackage_Patch1(ThinkNode_Priority, Pawn, JobIssueParams)
Verse.AI.Pawn_JobTracker:DetermineNextJob(ThinkTreeDef&)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob()
Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.EndCurrentJob_Patch1(Pawn_JobTracker, JobCondition, Boolean, Boolean)
Verse.AI.Pawn_JobTracker:JobTrackerTick()
Verse.Pawn:Verse.Pawn.Tick_Patch1(Pawn)
RimThreaded.RimThreaded:ExecuteTicks()
RimThreaded.RimThreaded:ProcessTicks()
RimThreaded.<>c:<CreateWorkerThread>b__97_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

[Player - verified.log](https://github.com/cseelhoff/RimThreaded/files/5383105/Player.-.verified.log)
[Player-prev.log](https://github.com/cseelhoff/RimThreaded/files/5383110/Player-prev.log)

github rejects my player.log file. Relevant part above for that reason.

**Comment by cseelhoff** [comment]
Closing bug. Please reopen in new bug report using the new templates if this issue persists.
