### ISSUE TITLE
Exception ticking world pawn [Zombieland Mod]

### ISSUE THREAD

**Issue by Jeffrey2457** [cseelhoff/RimThreaded#193]
Specs:
Threadripper 1950x
64GB DDR4-3200Mhz
GTX 1080ti

Modlist:
Harmony
Core
Rimthreaded
Zombieland
(Have tried loading Rimthreaded before and after Zombieland, same results regardless of order)

Threads spam not finishing after the initial error, causing 0.00TPS/FPS, putting the game in an unplayable state

https://gist.github.com/Jeffrey2457/259d0d0ab17e87b2152ef7757d8032f8    <---Initial error(Occurs with every zombie that is on the map)
https://gist.github.com/Jeffrey2457/91b7374a12ede898fa2a05c3f09ec96a      <---Spams infinitely, causing 0.00TPS/unresponsive game

**Comment by cseelhoff** [comment]
Closing bug. Please reopen in new bug report using the new templates if this issue persists.
