### ISSUE TITLE
Occasional errors regarding textures not loading

### ISSUE THREAD

**Issue by cseelhoff** [cseelhoff/RimThreaded#2]

**Comment by Stanui** [comment]
Found this while playing with CE 

Could not load UnityEngine.Texture2D at Things/Pawn/Humanlike/Apparel/PrestigeCataphractHelmet/PrestigeCataphractHelmet_west in any active mod or in base resources.
Verse.Log:Error(String, Boolean)
Verse.ContentFinder`1:Verse.ContentFinder`1[[UnityEngine.Texture2D, UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]].Get_Patch1(String, Boolean)
RimThreaded.Ticklist_Patch:MainThreadWaitLoop()
RimThreaded.Ticklist_Patch:Tick(TickList)
Verse.TickList:Verse.TickList.Tick_Patch1(TickList)
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()

Could not load UnityEngine.Texture2D at Things/Pawn/Humanlike/Apparel/PrestigeCataphractHelmet/PrestigeCataphractHelmet_westm in any active mod or in base resources.
Verse.Log:Error(String, Boolean)
Verse.ContentFinder`1:Verse.ContentFinder`1[[UnityEngine.Texture2D, UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]].Get_Patch1(String, Boolean)
RimThreaded.Ticklist_Patch:MainThreadWaitLoop()
RimThreaded.Ticklist_Patch:Tick(TickList)
Verse.TickList:Verse.TickList.Tick_Patch1(TickList)
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()
