### ISSUE TITLE
Incident Debug is broken/ Error log with Dynamic diplomacy mod/ Could not load unity engine for Andriod tier mod

### ISSUE THREAD

**Issue by HenMeeNooMai** [cseelhoff/RimThreaded#205]
[Player.log](https://github.com/cseelhoff/RimThreaded/files/5427486/Player.log)

A hot mess coming right at ya.

**Comment by HenMeeNooMai** [comment]
Incident Debugging won't open and will pop from Debug menu along side with some error. After reading the log,I assume the infestation cause event is broken? only mod I have for infestation event is VFE-Insectoid.

Dynamic diplomacy event just not happening and spit some error.

And Andriod tier don't have their head load properly? despite it look okay, maybe Vanilla hairs expanded/Beards expanded cause this?

**Comment by cseelhoff** [comment]
Closing bug. Many bugs have been fixed since this was reported. Please reopen in new bug report using the new templates if this issue persists.
