### ISSUE TITLE
duplicate events and minor pathing

### ISSUE THREAD

**Issue by LonerStars** [cseelhoff/RimThreaded#209]
So I have a i9 with 8 cores, and using all 8 cores to run the game (cause i mean, i made the error of going to Intel, and missed out on a 16 core amd). Also other then harmony, base rimworld, and rimthreaded, I also was running royalty dlc too (cause I am totally rich and need to flaunt my wealth around (Im a broke college kid, send help))

But some events seem to improperly reserve I believe, because say when I got raided, it triggered 2 raids, or say guests triggered twice, though mad animal event and wander joining did not seem to trigger it. (screen shot of events
![Proof of duplicate events](https://user-images.githubusercontent.com/39807763/97793528-7d915980-1baa-11eb-8918-3975a6e67983.png)
along with event log
![Event log](https://user-images.githubusercontent.com/39807763/97793570-f1336680-1baa-11eb-8dd1-5505983280b6.png)
)

Also minor pathing bug (photo of what happened), so i was building in mountain area, and I tell them to build a wall, with a corner of wood, which was blocked off from the inside, well no issue, I do recall they would still be able to build it (and if not, they could come from the outside, where it is wide open). Regardless, my pawns would go back and fourth inside, with wood, about to build it, but stopping when they got close, and then turning around to grab wood to go build it on loop, until I just had them build a corner inside, and then they went around to build it externally.

![Wooden Wall broken](https://user-images.githubusercontent.com/39807763/97793604-656e0a00-1bab-11eb-94ee-498761f03bbd.png)

Minor stuff, sure, but hay, everything helps (plus the ideal of a late game duplicate raid scares me o.o)

**Comment by LonerStars** [comment]
So I triggered a raid in dev mode, and it did not seem to trigger it, neither in 1x or 3x speed. I do not fully understand how this happened....

**Comment by cseelhoff** [comment]
Thanks for the bug report. If there is a way to reproduce this, I will definitely look into it. I suspect it is caused by some sort of race condition. If that is the case, it should be pretty easy to fix, once I locate the part of the code that spawns these kinds of events.

**Comment by lourencomcviana** [comment]
> 
> 
> Thanks for the bug report. If there is a way to reproduce this, I will definitely look into it. I suspect it is caused by some sort of race condition. If that is the case, it should be pretty easy to fix, once I locate the part of the code that spawns these kinds of events.

I started a new game with royalty and the bug was there from the start. All games that i start has the same issue.

**Comment by cseelhoff** [comment]
I fixed the pathing bug and the double events might have something to do with colony item wealth which was fixed as well. Please reopen if either are still an issue, especially if there is a way to produce double events consistently.
