### ISSUE TITLE
Getting 1000ms and occasional errors, but now running stable boomalope farm.

### ISSUE THREAD

**Issue by TheVillageGuy** [cseelhoff/RimThreaded#211]
[Player.log](https://github.com/cseelhoff/RimThreaded/files/5484766/Player.log)
[modlist.txt](https://github.com/cseelhoff/RimThreaded/files/5484767/modlist.txt)

**Comment by TheVillageGuy** [comment]
Some of  these errors could be mod related of course.

**Comment by cseelhoff** [comment]
Closing bug. Many bugs have been fixed since this was reported. Please reopen in new bug report using the new templates if this issue persists.
