### ISSUE TITLE
Sparta @693 colonists, worse performance than without rimthreaded, but stable.

### ISSUE THREAD

**Issue by TheVillageGuy** [cseelhoff/RimThreaded#212]
[Player.log](https://github.com/cseelhoff/RimThreaded/files/5484797/Player.log)
[modlist.txt](https://github.com/cseelhoff/RimThreaded/files/5484798/modlist.txt)

**Comment by TheVillageGuy** [comment]
Directly after posting this it crashed :)

**Comment by cseelhoff** [comment]
Closing bug. Many bugs have been fixed since this was reported. Please reopen in new bug report using the new templates if this issue persists.
