### ISSUE TITLE
Rimworld crashes when pawns Mine

### ISSUE THREAD

**Issue by AzrealMarkieve** [cseelhoff/RimThreaded#236]
[Broken Rimthreaded Mining.txt](https://github.com/cseelhoff/RimThreaded/files/5562630/Broken.Rimthreaded.Mining.txt)

With this load order, going through adding each mod one at a time, then putting RimThreaded at the bottom, the game freezes, then crashes as soon as a pawn finishes mining out any type of resource.

**Comment by Niilo007** [comment]
Please try the newest version of Rimthreaded

**Comment by pastorismylord** [comment]
RuntimeGC seems to be causing issues as well. please visit https://github.com/cseelhoff/RimThreaded/wiki/Mod-Compatibility
