### ISSUE TITLE
Stone types keep changing during world tile selection

### ISSUE THREAD

**Issue by GervyMaglina** [cseelhoff/RimThreaded#239]
![Screenshot (1)](https://user-images.githubusercontent.com/72695469/99629486-0812fd80-2a73-11eb-8dce-23060d26ff91.png)
![Screenshot (2)](https://user-images.githubusercontent.com/72695469/99629497-0b0dee00-2a73-11eb-9580-7132a24cb81e.png)
![Screenshot (3)](https://user-images.githubusercontent.com/72695469/99629500-0c3f1b00-2a73-11eb-8d86-b85afa0d2994.png)

I can't find the error log since it doesn't produce any kind of errors when I checked the log. Just wanted to let you know.

**Comment by GervyMaglina** [comment]
It can happen when you hover your cursor to any clickable menu (even the lines on the error log).
Loaded mod :
-Harmony
-Rimthreaded
-Core
-Mod Manager

**Comment by cseelhoff** [comment]
thanks for bug report. fixed in 1.1.5
