### ISSUE TITLE
Possible pathfinding issues when giddyupcore enabled after about 1 mins or so

### ISSUE THREAD

**Issue by Hellcommander** [cseelhoff/RimThreaded#242]
seems issues with AwesomeInventory and terrain movement issues with giddyupcore active https://pastebin.ubuntu.com/p/2PmW8bWVnZ/ are most of the errors
[5:23 PM]
https://pastebin.ubuntu.com/p/hCt9VBDD6J/ is full log

**Comment by cseelhoff** [comment]
I just did a patch to giddyup and awesome. Can you retest for me?

**Comment by Hellcommander** [comment]
I'll test it when I get the chance

**Comment by Hellcommander** [comment]
was able to get the game to crash after running the game speed at >>> for a few minutes still see some giddyupcore references (and issues with other mods in the player.log https://pastebin.ubuntu.com/p/jW48PMq25B/)

**Comment by pastorismylord** [comment]
Please try the latest version of rimthreaded
