### ISSUE TITLE
"Dubs Bad Hygiene" Massive error logs and game crashed when quit game (dubs bad hygiene)

### ISSUE THREAD

**Issue by 136068448** [cseelhoff/RimThreaded#243]
**Describe the bug**
start a new game and wait a few days, it will occur a error when game autosave about grass and will lag a while, then i choose to start another new game with same mod and choose the ice sheet, then the second type of error occured, the generate hare frozed and in dev mode the game creat massive error log but use dev mode to kill the hare can solve this question.
Another question is when i try to quit game, the game will crashed, then i found that only use both rimthreaded and dubsbadhygiene will cause thischange mod loadorder seems useless), i test with HAR and it doesnt cause crash when quit game
**To Reproduce**
1.start a new game
2.build the colony
3.wait someday in game
4.those error may occur
5.quit game, and the game may crashed

**ModList**
Initializing new game with mods:
  - brrainz.harmony
  - Ludeon.RimWorld
  - Ludeon.RimWorld.Royalty
  - UnlimitedHugs.HugsLib
  - Dubwise.DubsBadHygiene
  - majorhoff.rimthreaded

**PlayerLog**
THE ERROR WHEN GAME AUTOSAVE:https://gist.github.com/136068448/edbe2090d9efe2c71f0a01d3eacfe47f

THE ERROR ABOUT THE ANIMAL LAG ON ICE SHEET:https://gist.github.com/136068448/5e78fadeaa9d7d68007e0d80890025ac

**Comment by cseelhoff** [comment]
Removing vanilla tag. Dubwise.DubsBadHygiene is known to have issues. I enjoy using that mod myself, so it will probably get worked on soon.

**Comment by Niilo007** [comment]
Do you still get the errors in the most recent RimThreaded version? if yes, re open this issue. (there is already another issue report about the unity crash)
