### ISSUE TITLE
Tried to queue null region.

### ISSUE THREAD

**Issue by thefriendlycacti** [cseelhoff/RimThreaded#245]
Tried to queue null region.

**To Reproduce**
I have not found a way to reproduce this specifically but I will run into it ~once or twice per 2 hours of playing rimworld

**Error Log**
https://gist.github.com/thefriendlycacti/ca41942ee598cd65e8fa10af0f2e6abe

**Mod List**
Loaded mods:
Harmony(brrainz.harmony)[mv:1.0.4.0]: 0Harmony(2.0.2), HarmonyMod(1.0.4)
Core(Ludeon.RimWorld): (no assemblies)
Royalty(Ludeon.RimWorld.Royalty): (no assemblies)
RimThreaded [1.2](majorhoff.rimthreaded): 0Harmony(2.0.2), RimThreaded(1.1.7), UnityEngine.AssetBundleModule(0.0.0), UnityEngine.TextRenderingModule(0.0.0)
HugsLib(UnlimitedHugs.HugsLib)[ov:8.0.1]: 0Harmony(av:2.0.2,fv:1.2.0.1), HugsLib(av:1.0.0,fv:8.0.1)
Allow Tool(UnlimitedHugs.AllowTool): AllowTool(av:3.6.0,fv:3.9.0)

**Comment by Niilo007** [comment]
We think we found a way to reproduce this issue: mine a large area of the side of a mountain in a way that causes roof collapses.
sometimes the regions don't update correctly and become "null regions"

Hoff is looking into this issue now that he knows what is happening

**Comment by Niilo007** [comment]
fixed in 1.2.6. re open this issue if it happens again.
