### ISSUE TITLE
Error message when use Rimthreaded and Combat Extend(seems just error massage)

### ISSUE THREAD

**Issue by 136068448** [cseelhoff/RimThreaded#247]
**Describe the bug**
When active Rimthreaded and CE and use any weapon(or turret), will occur a lot of red error massage and inactive Rimthreaded will make error massage disappear,but seems have no effect with game,just error massage,and the function of CE seems normal
**To Reproduce**
1. active Rimthreaded and CE
2. go to game and shot something

**Error Log**
https://gist.github.com/136068448/ceb1b8281cf0a681af5896f514aa9636

**Mod List**
  - brrainz.harmony
  - Ludeon.RimWorld
  - Ludeon.RimWorld.Royalty
  - UnlimitedHugs.HugsLib
  - majorhoff.rimthreaded
  - CETeam.CombatExtended
  - CETeam.CombatExtendedGuns
  - n7huntsman.CombatExtendedWeapons
  - mi.chinesePack.combatExtended
  - fluffy.modmanager

**Screenshots**
![Only active CE](https://user-images.githubusercontent.com/74740183/99841775-ab662e80-2ba9-11eb-8064-02c7311ace18.gif)
![Active CE and Rimthreaded](https://user-images.githubusercontent.com/74740183/99842099-321b0b80-2baa-11eb-8822-9b41551a1dd7.gif)

**Comment by cseelhoff** [comment]
great bug report. I think I know how to fix this. It will probably be fixed in 1.1.9

**Comment by 136068448** [comment]
> great bug report. I think I know how to fix this. It will probably be fixed in 1.1.9

The normal ammo seems normal,but the mortar HE shell stil have such question

**Comment by cseelhoff** [comment]
sorry, this is taking me longer to isolate than I thought it would. I am still prioritizing it, since CE compatibility is important to me.

**Comment by cseelhoff** [comment]
Fixed in 1.1.23
