### ISSUE TITLE
no vegetation spawns on world gen

### ISSUE THREAD

**Issue by thefriendlycacti** [cseelhoff/RimThreaded#249]
**Describe the bug**
When loading in any new map

**To Reproduce**
load mods in order as shown below and load

**Error Log**
spams "Trying to get valid region at (246, 0, 83) but RegionAndRoomUpdater is disabled. The result may be incorrect."

**Mod List**
  - brrainz.harmony
  - Ludeon.RimWorld
  - Ludeon.RimWorld.Royalty
  - UnlimitedHugs.HugsLib
  - majorhoff.rimthreaded
  - fluffy.modmanager
  - Haplo.Miscellaneous.Robots
  - Alaestor.MiscRobots.PlusPlus

Log: https://gist.github.com/6eb2135570946373f6413c132db788f1

**Screenshots**
https://imgur.com/a/SqEcYNj

**Comment by cseelhoff** [comment]
bug fixed. Thanks for the heads up though!

**Comment by fishnuggs** [comment]
im getting a whole different problem where it doesnt load at all and it says the same thing
