### ISSUE TITLE
MapComponentTick Compatibility Exception

### ISSUE THREAD

**Issue by xywf221** [cseelhoff/RimThreaded#250]
**Describe the bug**
Exception after several versions

**To Reproduce**
Wait for the game to run

**Error Log**

[log link](https://gist.github.com/xywf221/94c7ee1824731ed73d33fec67e1bc886)

**Mod List**
Loading game from file test with mods:
  - brrainz.harmony
  - Ludeon.RimWorld
  - Ludeon.RimWorld.Royalty
  - UnlimitedHugs.HugsLib
  - fluffy.modmanager
  - bob.ticksPerSecond
  - Torann.RimWar
  - RWZH.ChinesePack.RimWar
  - moretraitslots.kv.rw
  - moretraitslotsZH.kv.rw
  - tradingspot.kv.rw
  - rimfridge.kv.rw
  - impassablemapmaker.kv.rw
  - ChinesePackage.ConfigurableMaps
  - configurablemaps.kv.rw
  - FrozenSnowFox.MoreQuests
  - FrozenSnowFox.FilthVanishesWithRainAndTime
  - 8Z.CallForIntel.zhcn
  - archer.modding.zhcn
  - archer.modding
  - bob.draggableCornerss
  - Vanya.Agent.HouseMaidNukos
  - Dango.HardworkingNukos_copy
  - brrainz.achtung
  - RWZH.ChinesePack.achtung
  - SaucyPigeon.AddTransportPod
  - sulusdacor.james76543.Meltup.AdvancedPowerPlus
  - RWZH.ChinesePack.AdvancedPowerPlus
  - UnlimitedHugs.AllowTool
  - cucumpear.azrael.varietycoats
  - com.bymarcin.ArchitectIcons
  - automatic.autolinks
  - razor2.3.AnotherRimworldMod.AutoCutBlight
  - netrve.bettertime
  - BetterStuffs.BS
  - fluffy.blueprints
  - shakeyourbunny.BetterReportProbablyMissingAttributes
  - Vanya.Tools.BulkCarrier
  - Buildable.Terrain
  - Devdisigdu.Bulk.Components
  - xrushha.BuyablePsylinkNeuroformers
  - 8Z.CallForIntel
  - void.charactereditor
  - gon.ChinesePawnName
  - CrashM.ColorCodedMoodBar.11
  - Dragon.CraftablePsylinkNeuroformers
  - Zephyr.CraftableRoyaltyWeaponsZh
  - Dalrae.CustomMoteMaker
  - CaesarV6.DamageIndicators
  - UnlimitedHugs.DefensivePositions
  - WiseClock.AC.DaysMatter
  - latta.fsharp.core
  - latta.devl10n
  - lingluo.latta.devl10n.zh
  - RWZH.ChinesePack.dressPatients
  - eagle0600.dressPatients
  - Dubwise.DubsMintMenus
  - dubwise.dubsmintminimap
  - Dubwise.DubsPerformanceAnalyzer
  - LingLuo.PrepareCarefully
  - Jaxxa.EnhancedDevelopment.Core
  - RWZH.ChinesePack.epoeforked
  - vat.epoeforked
  - RWZH.ChinesePack.epoeforkedroyalty
  - vat.epoeforkedroyalty
  - fluffy.fluffybreakdowns
  - ChinesePackage.PickUpAndHaul
  - LWM.DeepStorage
  - RWZH.ChinesePack.DeepStorage
  - LWOP.Terrible.Chest
  - Mehni.PickUpAndHaul
  - BOXrsxx.MorePracticalTraits
  - Jaxxa.ED.Embrasures
  - CaptainSnafu.EmbrasuresChinese
  - HC.ThrumboReskin
  - keep.hayresearch
  - latta.infusion
  - Zephyr.infusion
  - InsertKey.ItemListSelector
  - Mlie.LessStupidRomanceAttempt
  - Uuugggg.ListEverything
  - smashphil.loadinginprogress
  - krkr.locks2
  - LWOP.Package
  - LWOP.Package.R.P
  - ratys.madskills
  - MakeButcherTablesFromStone.velcroboy333
  - UnlimitedHugs.MapReroll
  - leafzxg.MasterOfCooking
  - leafzxg.MasterOfCrafting
  - sumghai.medpod
  - notfood.MendAndRecycle
  - GHSGKD.MendAndRecycleZH
  - Haplo.Miscellaneous.MapGenFactionbase
  - name.krypt.rimworld.moddiff
  - Mlie.MoEvents
  - RWZH.ChinesePack.MoEvents
  - Bichang.MoreSculpture
  - net.daavko.moreshelves
  - Mlie.NPDTiers
  - zyxabacab.NoSympathyForPrisoners
  - Palmzia.noawat
  - RWZH.ChinesePack.OgreStack
  - Ogre.OgreStack
  - telardo.NumbersTraitAddOn
  - Primus.OverWallNutrient
  - fed1sPlay.PawnTargetFix
  - battlemage64.PeopleCanChange
  - RWZH.ChinesePack.PeopleCanChange
  - Vanya.Polarisbloc.CoreLab
  - Vanya.Polarisbloc.SecurityForce
  - hatti.qualitybuilder
  - RWZH.ChinesePack.qualitybuilder
  - Ogliss.TheWhiteCrayon.Quarry
  - aRandomKiwi.RaidsForMe
  - brrainz.rangefinder
  - automatic.recipeicons
  - tfaivre.RichTraders
  - tfaivre.RichTradersRoyalty
  - Mlie.RimBank
  - Jaxe.RimHUD
  - shouer.chinesepack.RimHUD
  - aRandomKiwi.RimSaves
  - RWZH.ChinesePack.RimSaves
  - aRandomKiwi.RimThemes
  - user19990313.RuntimeGC
  - automatic.prisonerbedsetowner
  - nmeijer.settlementinventory
  - Uuugggg.ShareTheLoad
  - erdelf.ShowModDesignators
  - PeteTimesSix.SimpleSidearms
  - dhultgren.smarterconstruction
  - zh.Smokedmeat
  - dismarzero.VGP.Smokedmeat
  - sirrandoo.msf
  - Linkolas.Stabilize
  - Uuugggg.ThePriceIsRight
  - UuuggggZH1.ThePriceIsRight
  - cn.Sam.TilledSoil
  - GT.Sam.TilledSoil
  - smashphil.dropspot
  - RWZH.ChinesePack.dropspot
  - automatic.traderships
  - RWZH.ChinesePack.traderships
  - RWZH.ChinesePack.UnlimitedHugs
  - smashphil.neceros.srtsexpanded
  - nephlite.orbitaltradecolumn
  - RWZH.ChinesePack.orbitaltradecolumn
  - VanillaExpanded.VAEAS
  - VanillaExpanded.VAEAU
  - VanillaExpanded.VAEBF
  - VanillaExpanded.VAECD
  - VanillaExpanded.VAED
  - VanillaExpanded.VAEED
  - VanillaExpanded.VAEIS
  - VanillaExpanded.VAETF
  - VanillaExpanded.VAETR
  - VanillaExpanded.VAETS
  - VanillaExpanded.VAET
  - OskarPotocki.VanillaFactionsExpanded.Core
  - Hlx.RimworldAlteredCarbon
  - RWZH.ChinesePack.RimworldAlteredCarbon
  - jelly.transportcargopod
  - VanillaExpanded.VARME
  - shavius.vce.zh
  - VanillaExpanded.VCookE
  - VanillaExpanded.VCookEStews
  - VanillaExpanded.VEE
  - OskarPotocki.VanillaExpanded.RoyaltyPatches
  - OskarPotocki.VFE.Vikings
  - VanillaExpanded.VFECore
  - VanillaExpanded.VFEMedical
  - VanillaExpanded.VFEPower
  - VanillaExpanded.VFEProduction
  - VanillaExpanded.VFESecurity
  - shavius.vpe.zh
  - VanillaExpanded.VPlantsE
  - VanillaExpanded.VWE
  - VanillaExpanded.VWEL
  - VanillaExpanded.VWEQ
  - RWZH.ChinesePack.VAE
  - RWZH.ChinesePack.VanillaExpandedVEE
  - RWZH.ChinesePack.VanillaFactionsExpandedCore
  - RWZH.ChinesePack.Vikings
  - RWZH.ChinesePack.VFE
  - RWZH.ChinesePack.VWAAE
  - Vanya.VanillaEX.Abilities
  - dismarzero.VGP.VGPGardenMedicine
  - Murmur.WallLight
  - XeoNovaDan.VisiblePants
  - tammybee.whereismyweapon
  - daylight.WBSMoreLinkF
  - dolphin.WBSMoreLinkF
  - daylight.WBSMoreLinkFSuper
  - xydk.rimworld.mods
  - Banneronisan.GeneralStone
  - Banneronisan.GeneralStone.Royalty
  - Xun.OverWallNutrientPasteDispenserNPDTiers
  - RWZH.ChinesePack.coffeeandtea
  - syrchalis.coffeeandtea
  - Misha.CraftableRoyaltyWeapons
  - Chowdurr.CryogenicGenerator
  - andery233xj.CNPack.CryogenicGenerator
  - Daniledman.HardworkingAnimals
  - daavko191.MoreHShelvesUzh
  - com.github.alandariva.moreplanning
  - TalliDown.Numbers
  - NotooShabby.RestartRimWorld
  - Storage.Search.RSA
  - StrongBackByIndeed.ReuploadByMastice
  - RWZH.ChinesePack.VFEPower
  - Xun.SRTSExpanded
  - majorhoff.rimthreaded

**Comment by cseelhoff** [comment]
I think I fixed this yesterday. Does this still seem to be an issue for you?

**Comment by xywf221** [comment]
I saw it come back

```c#
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
  at System.Collections.Generic.Dictionary`2+Enumerator[TKey,TValue].MoveNext () [0x00016] in <567df3e0919241ba98db88bec4c6696f>:0 
  at Fluffy_Breakdowns.MapComponent_Durability.MapComponentTick () [0x00148] in <70ea35f011ff48a4bca4ea5a451c569c>:0 
  at Verse.MapComponentUtility.MapComponentTick (Verse.Map map) [0x00013] in <6326ac03f61f45efb3178f3bfd084139>:0 
```

**Comment by MrHrulgin** [comment]
Googling the "MapComponent_Durability.MapComponentTick" bit brought me here; I'm having the same issue: https://gist.github.com/1756172079b5b59201248fa27bab2c0c

System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
  at System.Collections.Generic.Dictionary`2+Enumerator[TKey,TValue].MoveNext () [0x00016] in <567df3e0919241ba98db88bec4c6696f>:0 
  at Fluffy_Breakdowns.MapComponent_Durability.MapComponentTick () [0x00148] in <17af4cc81fe94cb38103e0961fac977e>:0 
  at Verse.MapComponentUtility.MapComponentTick (Verse.Map map) [0x00013] in <d72310b4d8f64d25aee502792b58549f>:0

**Comment by cseelhoff** [comment]
> Googling the "MapComponent_Durability.MapComponentTick" bit brought me here; I'm having the same issue: https://gist.github.com/1756172079b5b59201248fa27bab2c0c
> 
> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
> at System.Collections.Generic.Dictionary`2+Enumerator[TKey,TValue].MoveNext () [0x00016] in <567df3e0919241ba98db88bec4c6696f>:0
> at Fluffy_Breakdowns.MapComponent_Durability.MapComponentTick () [0x00148] in <17af4cc81fe94cb38103e0961fac977e>:0
> at Verse.MapComponentUtility.MapComponentTick (Verse.Map map) [0x00013] in :0

@MrHruglin. I would start by visiting the RimThreaded Discord channel. There are many helpful people there. Looking at your load order for your modlist would be my first concern. Make sure to read the mod's readme for some tips :-)
