### ISSUE TITLE
Dead pawns instantly despawn

### ISSUE THREAD

**Issue by Andrew1997** [cseelhoff/RimThreaded#251]
**When a pawn or animal gets killed its body instantly disappears making looting/butchering impossible**

**To Reproduce**
1. Kill any animal or pawn on the map
2. Observe its body disappear

**Error Log**
https://gist.github.com/1b9f0cf0cb055eb7ad944a319e76f705

**Mod List**
Modlist in link above

**Screenshots**
Here's a video: https://youtu.be/hT5ypAf8Gtg?t=25

**Comment by cseelhoff** [comment]
I think this is fixed now. At least with vanilla it is no longer happening. Please reopen the bug if it is still persisting.
