### ISSUE TITLE
"Rim War" Major conflict with rimwar

### ISSUE THREAD

**Issue by GruppyOrange** [cseelhoff/RimThreaded#252]
**Describe the bug**
Once I opened world map, massive red log start appear, at some point the map will stop working and turn into blank, with no base, no caravan, nothing, but you can switch back to local map with ",", "." key. Once the world map turn into blank, creatures can't die even if the critical parts are destoryed, including colonists. If a pawn's the critical parts be destoryed before it falls down 
due to pain or something else, the pawn will be considered constantly die though you can still control it, I have one of my colonist who has a bonded pet killed though console command "T: 5000 damage", which destroyed her torso, yet she still standing, shooting a manhunter megasloth, while her pet continuously mental break, another colonist was "killed" by revolver, her torso suffered 15 shot which is about 180 damage, but human torso only has 40 HP, she was down before her torso destroyed. and stayed down when her torso was gone. Then game just start lagging. I save the game,  reopen it, the save is no longer working, "Error while loading a map" screen shows up.

I have recovered the save file before game break, I can send you a copy if you need.

**To Reproduce**
1. Start the game.
2. Play until world map turn into blank.
3. "Kill" something
4. Then the game is broken.

**Error Log**
https://gist.github.com/HugsLibRecordKeeper/c600d32fbe92288ddb7eb5d034621759

https://gist.github.com/HugsLibRecordKeeper/388e1b8b817a1083b7fc61fa34e17cd1

https://gist.github.com/HugsLibRecordKeeper/ad407f3bb382368d2d5e9dd7756a7721

**Mod List**
  <activeMods>
    <li>brrainz.harmony</li>
    <li>ludeon.rimworld</li>
    <li>majorhoff.rimthreaded</li>
    <li>smashphil.neceros.srtsexpanded</li>
    <li>topkek.razorcrest</li>
    <li>neceros.srtsexpandedoldgenesis</li>
    <li>ludeon.rimworld.royalty</li>
    <li>unlimitedhugs.hugslib</li>
    <li>unlimitedhugs.allowtool</li>
    <li>sulusdacor.james76543.meltup.advancedpowerplus</li>
    <li>erdelf.humanoidalienraces</li>
    <li>torann.rimwar</li>
    <li>sumghaidubwise.replimat</li>
    <li>avilmask.commonsense</li>
    <li>mlie.weaponssorter</li>
    <li>edb.preparecarefully</li>
    <li>fluffy.modmanager</li>
    <li>brrainz.achtung</li>
    <li>uuugggg.thickarmor</li>
    <li>fluffy.animaltab</li>
    <li>mlie.pickupandhaul</li>
    <li>brrainz.cameraplus</li>
    <li>oblitus.animalslogic</li>
    <li>walkingproblem.wildanimalsex</li>
    <li>eagle0600.dresspatients</li>
    <li>uuugggg.buildfrominventory</li>
    <li>insertkey.buildertweaks</li>
    <li>vanya.tools.bulkcarrier</li>
    <li>fluffy.backuppower</li>
    <li>fluffy.blueprints</li>
    <li>arandomkiwi.rimsaves</li>
    <li>fluffy.commandpalette</li>
    <li>ratys.bricksdontvanish</li>
    <li>jaxe.boommod</li>
    <li>shakeyourbunny.betterreportprobablymissingattributes</li>
    <li>fluffy.medicaltab</li>
    <li>factioncontrol.kv.rw</li>
    <li>fluffy.colonymanager</li>
    <li>fluffy.pharmacist</li>
    <li>fluffy.worktab</li>
    <li>fluffy.fluffybreakdowns</li>
    <li>fluffy.areaunlocker</li>
    <li>indeed.stackxxl</li>
    <li>fluffy.stuffedfloors</li>
    <li>jovianpug.caravanlageliminator</li>
    <li>dhultgren.changecaravanloadout</li>
    <li>zylle.carpetleatherfloor</li>
    <li>mlie.wehadatrader</li>
    <li>bar0th.war</li>
    <li>co.uk.epicguru.whatsthatmod</li>
    <li>syrchalis.universalfermenter</li>
    <li>mlie.apparelorganizer</li>
    <li>tradingspot.kv.rw</li>
    <li>bodlosh.floratab</li>
    <li>linkolas.stabilize</li>
    <li>automatic.autolinks</li>
    <li>neceros.badcanbegood</li>
    <li>falconne.aff</li>
    <li>madeline.modmismatchformatter</li>
    <li>voult.betterpawncontrol</li>
    <li>thewirelord354.conduitdeconstruct</li>
    <li>thegoofyone.betterspots</li>
    <li>ari.forcedmarch</li>
    <li>jaxe.coastlines</li>
    <li>mlie.cleaningpriority</li>
    <li>mattthewaz.weaponstab</li>
    <li>adjustabletradeships.kv.rw</li>
    <li>khamenman.armorracks</li>
    <li>mlie.clothingsorter</li>
    <li>orion.therapy</li>
    <li>weilbyte.snapout</li>
    <li>petetimessix.simplesidearms</li>
    <li>falconne.bwm</li>
    <li>jecrell.jecstools</li>
    <li>torann.customdeathrandomness</li>
    <li>sarg.smartspeed</li>
    <li>dhultgren.smarterconstruction</li>
    <li>dubwise.dubsskylights</li>
    <li>dubwise.dubsmintminimap</li>
    <li>uuugggg.sharetheload</li>
    <li>dninemfive.settlementdescription</li>
    <li>falconne.roomsense</li>
    <li>dubwise.dubsmintmenus</li>
    <li>syrchalis.setupcamp</li>
    <li>petetimessix.compacthediffs</li>
    <li>user19990313.runtimegc</li>
    <li>krkr.locks2</li>
    <li>mlie.roadsoftherim</li>
    <li>spoonshortage.spoonshairmod</li>
    <li>uuugggg.smartmedicine</li>
    <li>mse2.core</li>
    <li>dismarzero.vgp.vgpvegetablegarden</li>
    <li>dismarzero.vgp.vgpgardenfabricssimplified</li>
    <li>oskarpotocki.vanillafactionsexpanded.core</li>
    <li>oskarpotocki.vanillaexpanded.royaltypatches</li>
    <li>vanillaexpanded.vappe</li>
    <li>vanillaexpanded.vbookse</li>
    <li>vanillaexpanded.vbrewe</li>
    <li>vanillaexpanded.vcooke</li>
    <li>vanillaexpanded.vcooke.healthpatch</li>
    <li>vanillaexpanded.vcookestews</li>
    <li>oskarpotocki.vfe.insectoid</li>
    <li>vanillaexpanded.vwe</li>
    <li>oskarpotocki.vanillafactionsexpanded.medievalmodule</li>
    <li>oskarpotocki.vanillafactionsexpanded.settlersmodule</li>
    <li>oskarpotocki.vfe.vikings</li>
    <li>vanillaexpanded.vfecore</li>
    <li>vanillaexpanded.vfeart</li>
    <li>vanillaexpanded.vfefarming</li>
    <li>vanillaexpanded.vfemedical</li>
    <li>vanillaexpanded.vfepower</li>
    <li>vanillaexpanded.vfeproduction</li>
    <li>vanillaexpanded.vfesecurity</li>
    <li>vanillaexpanded.vfespacer</li>
    <li>vanillaexpanded.vhe</li>
    <li>vanillaexpanded.vplantse</li>
    <li>phoenix.vanillasolarsheild</li>
    <li>vanillaexpanded.vtexe</li>
    <li>vanillaexpanded.vwel</li>
    <li>vanillaexpanded.varme</li>
    <li>mlie.variousspaceshipchunk</li>
    <li>argon.saltedmeat</li>
    <li>dubwise.rimatomics</li>
    <li>dubwise.rimefeller</li>
    <li>gregorycurrie.animalgenetics</li>
    <li>hlx.rimworldunscarmoury</li>
    <li>murmur.isid</li>
    <li>com.yayo.racequestpawn</li>
    <li>spdskatr.projectrimfactory</li>
    <li>rimfridge.kv.rw</li>
    <li>yrtwof.rimpedia</li>
    <li>rimsenal.core</li>
    <li>rimsenal.evp</li>
    <li>rimsenal.federation</li>
    <li>rimsenal.feral</li>
    <li>rimsenal.hair</li>
    <li>rimsenal.security</li>
    <li>frozensnowfox.complexjobs</li>
    <li>frozensnowfox.meditationfreedom</li>
    <li>anomalous.dynamicpopulation</li>
    <li>vat.epoeforked</li>
    <li>vat.epoeforkedroyalty</li>
    <li>kongmd.qee</li>
    <li>zylle.mapdesigner</li>
    <li>unlimitedhugs.mapreroll</li>
    <li>ratys.rtfuse</li>
    <li>ratys.rtsolarflareshield</li>
    <li>lwm.deepstorage</li>
    <li>primitivestorage.velcroboy333</li>
    <li>jangodsoul.simplestorage</li>
    <li>netrve.dsgui</li>
    <li>oken.rebalanceddeepstorage</li>
    <li>ubergarm.kanbanstockpile</li>
    <li>bob.middleflakpants</li>
    <li>torann.caravanoptions</li>
    <li>sumghai.medpod</li>
    <li>reiquard.researchinfo</li>
    <li>mobius.royaltytweaks</li>
    <li>wemd.partiallypassablewindturbines</li>
    <li>saucypigeon.addtransportpod</li>
    <li>chippedchap.blueprinttotalstooltip</li>
    <li>tarojun.epoeforked.allowdirectcrafting</li>
    <li>forcedojob.kv.rw</li>
    <li>falconne.heatmap</li>
    <li>jaxe.toggleharvest</li>
  </activeMods>
  <knownExpansions>
    <li>ludeon.rimworld.royalty</li>
  </knownExpansions>

**Screenshots**
undead squirrel
<a href="https://imgur.com/QNO32bq"><img src="https://i.imgur.com/QNO32bq.jpg" title="source: imgur.com" /></a>
undead colonist
<a href="https://imgur.com/Ek8ZTtk"><img src="https://i.imgur.com/Ek8ZTtk.jpg" title="source: imgur.com" /></a>
constant pet mental break
<a href="https://imgur.com/yQayZDm"><img src="https://i.imgur.com/yQayZDm.jpg" title="source: imgur.com" /></a>
undead downed colonist
<a href="https://imgur.com/wDEvrSB"><img src="https://i.imgur.com/wDEvrSB.jpg" title="source: imgur.com" /></a>
unable to reopen the save
<a href="https://imgur.com/HVtnJKd"><img src="https://i.imgur.com/HVtnJKd.jpg" title="source: imgur.com" /></a>

**Comment by giganticats** [comment]
hey, rimwar is not ment to be played with this mod yet im pretty sure, its not conpatable yet

**Comment by cseelhoff** [comment]
Error logs are definitely pointing to Rim War as the conflicting mod. I have added it to our incompatible mod list for now.

**Comment by AmericanWeeb** [comment]
spent the last 4 hours trying to reproduce this, and I couldn't until I added the mods in the order reported, seems this issue occurred because Rimthreaded wasn't loaded last but instead 3rd

**Comment by pastorismylord** [comment]
Tested Rim War with RimTheaded 2.2.19 preview. The game is stable but I've got some object out of range errors: 

RIMWAR: [OFFTHREAD] error in Object reference not set to an instance of an object at   at (wrapper dynamic-method) Verse.WorldFloodFiller.Verse.WorldFloodFiller.FloodFill_Patch0(Verse.WorldFloodFiller,int,System.Predicate`1<int>,System.Func`3<int, int, bool>,int,System.Collections.Generic.IEnumerable`1<int>)
  at RimWorld.Planet.TileFinder.TryFindPassableTileWithTraversalDistance (System.Int32 rootTile, System.Int32 minDist, System.Int32 maxDist, System.Int32& result, System.Predicate`1[T] validator, System.Boolean ignoreFirstTilePassability, System.Boolean preferCloserTiles, System.Boolean canTraverseImpassable) [0x00042] in <7927e938de4c4089b4add4215e58d5b1>:0 
  at RimWar.Planet.WorldComponent_PowerTracker.AttemptSettlerOffMainThread (RimWar.RimWarData rwd, RimWorld.Planet.Settlement parentSettlement, RimWar.Planet.RimWarSettlementComp rwsComp, System.Boolean ignoreRestrictions, System.Boolean ignoreNearbyTown, RimWar.Planet.WorldComponent_PowerTracker+ContextStorage context) [0x00082] in <43975f45c15f4ad3aa1766bb54a65473>:0 
  at RimWar.Planet.WorldComponent_PowerTracker+<>c__DisplayClass75_0.<AttemptSettlerMission>b__0 () [0x00012] in <43975f45c15f4ad3aa1766bb54a65473>:0 
  at RimWar.RocketTools.RocketTasker`1+RocketTask`1[T,T].RunOffMainThread () [0x00000] in <43975f45c15f4ad3aa1766bb54a65473>:0 
Verse.Log:Error(String, Boolean)
RimWar.RocketTools.RocketTask`1:RunOnMainThread()
RimWar.RocketTools.RocketTask`1:TryFinalize()
RimWar.RocketTools.RocketTasker`1:Tick()
RimWar.Planet.WorldComponent_PowerTracker:WorldComponentTick()
RimThreaded.WorldComponentUtility_Patch:WorldComponentListTick()
RimThreaded.RimThreaded:ExecuteTicks()
RimThreaded.RimThreaded:ProcessTicks(ThreadInfo)
RimThreaded.RimThreaded:InitializeThread(Object)
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart(Object)
