### ISSUE TITLE
there may have a bug or mod conflication cause animal and pawn can't move and make massive lag

### ISSUE THREAD

**Issue by 136068448** [cseelhoff/RimThreaded#253]
**Describe the bug**
When game spawn some new animal and pawn or try to make them do somthing, the animal or pawn will do nothing and stay at the place they spawn or stand before do some thing, then will occur lots of red error message, then game will gave a massive lag, if i use the mod named Character Edit to move them to another place, it can handle this question and i try to restart game and load save it also be ,and i try to re product this bug again after restart game but failled(Edit: this question happended again when  in a Herd migration event and error log same as this one and if use DEV menu to kill the animal which stunk, it will be solved).

**Error Log**
https://gist.github.com/136068448/517a055dee7dac8d6c82d2a6470793f9

**Mod List**
  - brrainz.harmony
  - Ludeon.RimWorld
  - Ludeon.RimWorld.Royalty
  - UnlimitedHugs.HugsLib
  - majorhoff.rimthreaded
  - CETeam.CombatExtended
  - CETeam.CombatExtendedGuns
  - n7huntsman.CombatExtendedWeapons
  - mi.chinesePack.combatExtended
  - Nals.FacialAnimation
  - erdelf.HumanoidAlienRaces
  - RWZH.ChinesePack.HumanoidAlienRaces
  - velc.HatsDisplaySelection
  - OskarPotocki.VanillaFactionsExpanded.Core
  - vanillaexpanded.achievements
  - vanillaexpanded.zh
  - brrainz.achtung
  - RWZH.ChinesePack.achtung
  - brrainz.cameraplus
  - RWZH.ChinesePack.cameraplus
  - void.charactereditor
  - UnlimitedHugs.MapReroll
  - UnlimitedHugs.AllowTool
  - fluffy.colonymanager
  - Vanya.Tools.BlightedAlert
  - Oblitus.AnimalsLogic
  - GHSGKD.AnimalsLogicZH
  - falconne.BWM
  - sarg.smartspeed
  - fluffy.animaltab
  - fluffy.blueprints
  - fluffy.pharmacist
  - fluffy.relationstab
  - fluffy.worktab
  - fluffy.stuffedfloors
  - fluffy.medicaltab
  - leafzxg.MasterOfCooking
  - leafzxg.MasterOfCrafting
  - automatic.gunplay
  - velc.MineItAll
  - tikubonn.DontBlockDoor
  - Ogliss.Mythos.DiseasesOverhauled
  - DiseasesOverhauled.Chinese
  - Troopersmith1.DeathRattle
  - Dubwise.DubsMintMenus
  - dubwise.dubsmintminimap
  - GHSGKD.DeathRattleZH
  - WiseClock.AC.DaysMatter
  - fluffy.areaunlocker
  - Mlie.LessArbitrarySurgery
  - Mlie.LessStupidRomanceAttempt
  - smashphil.loadinginprogress
  - brrainz.justignoremepassing
  - ChippedChap.BlueprintTotalsTooltip
  - Zephyr.BlueprintTotalsTooltipZh
  - smashphil.carrycapacityfixed
  - Mlie.PickUpAndHaul
  - Jaxe.Bubbles
  - JaxeZH.Bubbles
  - ChinesePackage.ConfigurableMaps
  - configurablemaps.kv.rw
  - Orion.Gastronomy
  - Zephyr.Gastronomyzh
  - jelly.harvestsync
  - 400.ImpassableHChestUdeepHWater
  - tammybee.predatorhuntalert
  - RWZH.ChinesePack.OgreStack
  - Ogre.OgreStack
  - samo.RareTraits
  - Unon.NoBurnMetal
  - tammybee.whereismyweapon
  - fed1sPlay.PawnTargetFix
  - com.yayo.raceQuestPawn
  - Ogliss.RescueeJoinsPlus
  - GG.RescueeJoinsPlus
  - Ogliss.WanderJoinsPlus
  - GG.WanderJoinsPlus
  - Vanya.Tools.IncidentPersonStat
  - crlsniper.realisticrooms
  - GHSGKD.realisticroomsZH
  - Mlie.RealDining
  - ONegative.ReworkedTemperatureExtremeEvents
  - dhultgren.smarterconstruction
  - zlj.staticQualityPlus.124
  - tradingspot.kv.rw
  - RWZH.ChinesePack.tradingspot
  - RWZH.ChinesePack.UnlimitedHugs
  - Linkolas.Stabilize
  - weilbyte.snapout
  - RWZH.ChinesePack.snapout
  - PeteTimesSix.SimpleSidearms
  - RWZH.ChinesePack.RBSEHC
  - Rah.RBSEHC
  - Jaxe.RimHUD
  - shouer.chinesepack.RimHUD
  - PeteTimesSix.CompactHediffs
  - Zephyr.CompactHediffsZh
  - Mlie.ExpandedIncidents
  - RWZH.ChinesePack.ExpandedIncidents
  - Mlie.MoEvents
  - RWZH.ChinesePack.MoEvents
  - Ameiro.Animehairs
  - Gloomy.GloomyHairMk2
  - GWhair.noface
  - rimsenal.hair
  - sakama.RoppoiHair
  - RWZH.ChinesePack.VHE
  - Orion.XevaRimhair
  - ChJees.Androids
  - RWZH.ChinesePack.Androids
  - RunneLatki.RabbieRaceMod
  - RWZH.ChinesePack.RabbieRaceMod
  - RunneLatki.RabbieVanillafacepatch
  - Solaris.RatkinRaceMod
  - RWZH.ChinesePack.RatkinRaceMod
  - Solaris.RatkinVanillaFace
  - Daemon976.FacialAnimationplus
  - shavius.alienrbse
  - sulusdacor.james76543.Meltup.AdvancedPowerPlus
  - RWZH.ChinesePack.AdvancedPowerPlus
  - Mlie.SDBridges
  - dracoix.doormat.r12a
  - factioncontrol.kv.rw
  - Solaris.FurnitureBase
  - RWZH.ChinesePack.FurnitureBase
  - Haplo.Miscellaneous.Endgame
  - rimfridge.kv.rw
  - Albion.SparklingWorlds.Full
  - RWZH.ChinesePack.SparklingWorldsFull
  - GT.Sam.TilledSoil
  - automatic.traderships
  - RWZH.ChinesePack.traderships
  - nephlite.orbitaltradecolumn
  - RWZH.ChinesePack.orbitaltradecolumn
  - sarg.alphaanimals
  - QAQ.QAAAQ
  - sarg.alphabiomes
  - QA.QQIJQ
  - VanillaExpanded.VAEAS
  - VanillaExpanded.VAEAU
  - VanillaExpanded.VAEBF
  - VanillaExpanded.VAECD
  - VanillaExpanded.VAED
  - VanillaExpanded.VAEED
  - VanillaExpanded.VAEIS
  - VanillaExpanded.VAETF
  - VanillaExpanded.VAETR
  - VanillaExpanded.VAETS
  - VanillaExpanded.VAET
  - RWZH.ChinesePack.VAE
  - VanillaExpanded.VAPPE
  - VanillaExpanded.VARME
  - VanillaExpanded.VWE
  - VanillaExpanded.VWEQ
  - RWZH.ChinesePack.VWAAE
  - VanillaExpanded.VCEF
  - RWZH.ChinesePack.VCEF
  - VanillaExpanded.VFECore
  - VanillaExpanded.VFEArt
  - VanillaExpanded.VFEFarming
  - VanillaExpanded.VFEMedical
  - VanillaExpanded.VFEProduction
  - VanillaExpanded.VFESecurity
  - VanillaExpanded.VFESpacer
  - RWZH.ChinesePack.VFE
  - dismarzero.VGP.VGPVegetableGarden
  - argon.vanillavgarden
  - dismarzero.VGP.VGPGardenFabrics
  - argon.vanillavgardenfab
  - dismarzero.VGP.VGPThreeSistersPlants
  - dismarzero.VGP.VGPMoreVeggies
  - dismarzero.VGP.VGPGardenResources
  - argon.vanillavgardenresources
  - dismarzero.VGP.VGPGardenMedicine
  - dismarzero.VGP.VGPGardenTools
  - shavius.vpe.zh
  - VanillaExpanded.VPlantsE
  - shavius.vbe.zh
  - VanillaExpanded.VBrewE
  - shavius.vce.zh
  - VanillaExpanded.VCookE
  - VanillaExpanded.VCookEStews
  - shavius.vbookse.zh
  - VanillaExpanded.VBooksE
  - OskarPotocki.VanillaFactionsExpanded.MedievalModule
  - RWZH.ChinesePack.MedievalModule
  - OskarPotocki.VanillaFactionsExpanded.SettlersModule
  - RWZH.ChinesePack.SettlersModule
  - shavius.vfeinsectoids.zh
  - OskarPotocki.VFE.Insectoid
  - OskarPotocki.VFE.Vikings
  - RWZH.ChinesePack.Vikings
  - VSE.PerryPersistent
  - RWZH.ChinesePack.PerryPersistent
  - VanillaExpanded.VTEXE
  - RWZH.ChinesePack.VTEXE
  - Mlie.RoadsOfTheRim
  - RWZH.ChinesePack.RoadsOfTheRim
  - Vanya.Polarisbloc.CoreLab
  - Vanya.Polarisbloc.SecurityForce
  - rimsenal.core
  - rimsenal.EVP
  - rimsenal.federation
  - rimsenal.feral
  - rimsenal.storyteller
  - rimsenal.security
  - RWZH.ChinesePack.rimsenal
  - JPT.SoftWarmBeds
  - RWZH.ChinesePack.JPT
  - notfood.SeedsPlease
  - shadow.spaiomegapatch
  - tikubonn.RimSeasoning
  - RWZH.ChinesePack.RimSeasoning
  - LingLuo.PrepareCarefully
  - co.uk.epicguru.whatsthatmod
  - fluffy.modmanager
  - RWZH.ChinesePack.Fluffy

**Screenshots**
![RimWorld by Ludeon Studios 2020-11-22 01-25-3020201122224206](https://user-images.githubusercontent.com/74740183/99884551-0f502c00-2c6a-11eb-975d-1ea396826682.gif)
![RimWorld by Ludeon Studios 2020-11-22 01-25-302020112222597](https://user-images.githubusercontent.com/74740183/99884572-3f97ca80-2c6a-11eb-904d-f92b94f78f4d.gif)

**Comment by cseelhoff** [comment]
This is hard to troubleshoot with the extensive mod list. I looked at the error log, and nothing stands out to me at this time. If you can isolate this down to one mod, that would help.

**Comment by 136068448** [comment]
> This is hard to troubleshoot with the extensive mod list. I looked at the error log, and nothing stands out to me at this time. If you can isolate this down to one mod, that would help.


I found this issue will occur when there have too many animal in a map,seems too many animal will make the path calculate of some animal stop,because i kill the animal in map the game not slow agian and the error disappear,i will try to find which mod conflict cause this issue

**Comment by Niilo007** [comment]
this is just a stab in the dark but try to disable "fluffy.areaunlocker" and see if the problem stops happening.
