### ISSUE TITLE
Job giver errors& modded library issues.

### ISSUE THREAD

**Issue by shawarmacat** [cseelhoff/RimThreaded#254]
Job giver continues to spam error log folder leading to game stuttering and slowdown, might be caused from adding a pawn. Maybe from modded pawns and or resurrected ones.

Constant requests for modded items from an empty library, not sure what the cause of this.

Job giver:  comes out from normal gameplay, starts to spam the log

Mod library empty requests: unsure how to replicate; Maybe from certain moded items?

[modlist.txt](https://github.com/cseelhoff/RimThreaded/files/5578367/modlist.txt)
[job.giver.error.txt](https://github.com/cseelhoff/RimThreaded/files/5578369/gob.giver.error.txt)

![screenshot4](https://user-images.githubusercontent.com/74803651/99887578-deb6c500-2c5e-11eb-806e-9f448c6f5975.png)

**Comment by cseelhoff** [comment]
It looks like it might be caused by the mod: "Moyo-From the depth". Want to see if removing that mod fixes the issue?

**Comment by pastorismylord** [comment]
please visit https://github.com/cseelhoff/RimThreaded/wiki/Mod-Compatibility and clean up your modlist
