### ISSUE TITLE
Red all red.

### ISSUE THREAD

**Issue by shawarmacat** [cseelhoff/RimThreaded#258]
**Describe the bug**

Unsure of the cause but it seems the new update broke a lot of things. All of these errors are from the start of the game and continue to spam. Most notable thing is that camera+ plus mod removes all UI unlike the previous update

[more red than a soviet wedding.txt](https://github.com/cseelhoff/RimThreaded/files/5579061/more.red.than.a.soviet.wedding.txt)

[modlist.txt](https://github.com/cseelhoff/RimThreaded/files/5579062/modlist.txt)

1. spawn error.

![screenshot4](https://user-images.githubusercontent.com/74803651/99897075-e05ca900-2caf-11eb-8c4e-793e95ff5699.png)

2. Removed UI.
![screenshot5](https://user-images.githubusercontent.com/74803651/99897090-f9655a00-2caf-11eb-8e63-a78e86871fd5.png)

**Comment by cseelhoff** [comment]
Do you have the player.log to go with this?

**Comment by pastorismylord** [comment]
please verify your modlist as several incompatible mods have been identified. Check the wiki and our discord community for aditional details
