### ISSUE TITLE
incompatible with CE

### ISSUE THREAD

**Issue by 136068448** [cseelhoff/RimThreaded#259]
**Describe the bug**
use both RIMTHREADED and CE, cause the hunter animal can't attack,when the hunter animal hunger they try to hunt something but they only stanhding, then a lot of red error message about CE and RIMTHREADED appear and cause game massive lag, if kill the animal or remove CE, it will be solved

**To Reproduce**
1. active CE and RIMTHREADED
2. use dev mode to make a hunter huger
3. wait the hunter try to hunt other animal

**Error Log**
https://gist.github.com/136068448/c6c9b0e5daa1418725e564dcfef2a7bc

**Mod List**
  - brrainz.harmony
  - Ludeon.RimWorld
  - Ludeon.RimWorld.Royalty
  - majorhoff.rimthreaded
  - CETeam.CombatExtended

**Screenshots**

![RimWorld by Ludeon Studios 2020-11-22 14-50-39202011221453232](https://user-images.githubusercontent.com/74740183/99897201-80c3c500-2cd2-11eb-9dd2-5234b25f9a1c.gif)

**Comment by cseelhoff** [comment]
I think I just fixed this in 1.1.12. Please reopen bug if this is not the case.
