### ISSUE TITLE
"Save Our Ship 2" Root level exception (Ship combat is broken)

### ISSUE THREAD

**Issue by Lerupt** [cseelhoff/RimThreaded#261]
**Describe the bug**
Game spams the error when ship to ship combat ensues with SoS 2, first the game stops instantly when i try to fast forward, when the enemy ship comes into boarding range it spams the error log with the same message very fast,

**To Reproduce**
1. Initiate ship to ship combat
2. Wait until the game pauses and continue again and again until enemy starts to board your ship
3. Watch the error log
4. Everything goes black when running and even when you put speed to 1x game doesn't run.

**Error Log**
https://gist.github.com/Lerupt/808594c7e0ecaf6dd4106459c62a7f81

**Mod List**
  - brrainz.harmony
  - Ludeon.RimWorld
  - Ludeon.RimWorld.Royalty
  - UnlimitedHugs.HugsLib
  - Dubwise.DubsBadHygiene
  - pyrce.dire.raids
  - VanillaExpanded.VFEMedical
  - VanillaExpanded.VFESecurity
  - KurtusMob.Vertibird
  - VanillaExpanded.VFEProduction
  - VanillaExpanded.VFEFarming
  - VanillaExpanded.VFEArt
  - OskarPotocki.VanillaFactionsExpanded.Core
  - VanillaExpanded.VFESpacer
  - K.GlitterNet
  - VanillaExpanded.VCookE
  - kongmd.qee
  - Agracore141.Asphalt
  - Jaxxa.ED.Embrasures
  - stormknight.outdoorlighting
  - DoctorVanGogh.MiningShaft
  - Alaestor.QuantumCooling
  - kentington.saveourship2
  - sarg.alphaships
  - Storm.SoS2Ex
  - majorhoff.rimthreaded
  - KurtusMob.BosCompendium
  - Indeed.StackXXL

**Comment by cseelhoff** [comment]
Marking as enhancement. It may be a little time before I focus on SoS compatibility.

**Comment by Niilo007** [comment]
[message (1).txt](https://github.com/cseelhoff/RimThreaded/files/6370295/message.1.txt)

Tested in the experimental 2.0.7
i got errors and the screen was flickering
the enemy ship also seemed to generate incorrectly and the battle didnt progress

![image](https://user-images.githubusercontent.com/75486261/115968465-d3830080-a540-11eb-9d1e-2528d4d29ff3.png)

**Comment by Niilo007** [comment]
issue persists after qutting to menu and starting a new colony

**Comment by Niilo007** [comment]
![image](https://user-images.githubusercontent.com/75486261/115968749-0083e300-a542-11eb-9f3e-419b99a2131f.png)

**Comment by pastorismylord** [comment]
issue solved on 2.3.5, additional granular bug reports will be needed for further tracking.
