### ISSUE TITLE
endless siege and indigestion battle

### ISSUE THREAD

**Issue by 136068448** [cseelhoff/RimThreaded#262]
**Describe the bug**
after start a siege event, the event become endless, it send 1-2 enemy pawns per wave and never stop, then i send my pawns to against them, first thing happended is my pawn shot the enemy without any obstacle and very close, they(enemy and my pawn)can't actually shot with each other, then the most indigestion thing happended, they shot very fast(shown as screenshot) but still useless, i try to draft and disdraft them, still shot fast even my pawns are eating food, then i try to use devmenu to kill enemy, failed. but everything turn to normal after reload the save

**Error Log**
https://gist.github.com/136068448/fcf35b20d17811db8247df2fc8820b1b

**Mod List**
  - brrainz.harmony
  - Ludeon.RimWorld
  - Ludeon.RimWorld.Royalty
  - majorhoff.rimthreaded
  - UnlimitedHugs.HugsLib
  - Nals.FacialAnimation
  - erdelf.HumanoidAlienRaces
  - RWZH.ChinesePack.HumanoidAlienRaces
  - velc.HatsDisplaySelection
  - OskarPotocki.VanillaFactionsExpanded.Core
  - vanillaexpanded.achievements
  - vanillaexpanded.zh
  - brrainz.achtung
  - RWZH.ChinesePack.achtung
  - brrainz.cameraplus
  - RWZH.ChinesePack.cameraplus
  - void.charactereditor
  - UnlimitedHugs.MapReroll
  - UnlimitedHugs.AllowTool
  - fluffy.colonymanager
  - Vanya.Tools.BlightedAlert
  - Oblitus.AnimalsLogic
  - GHSGKD.AnimalsLogicZH
  - falconne.BWM
  - sarg.smartspeed
  - fluffy.animaltab
  - fluffy.blueprints
  - fluffy.pharmacist
  - fluffy.relationstab
  - fluffy.worktab
  - fluffy.stuffedfloors
  - fluffy.medicaltab
  - leafzxg.MasterOfCooking
  - leafzxg.MasterOfCrafting
  - automatic.gunplay
  - velc.MineItAll
  - tikubonn.DontBlockDoor
  - Ogliss.Mythos.DiseasesOverhauled
  - DiseasesOverhauled.Chinese
  - Troopersmith1.DeathRattle
  - Dubwise.DubsMintMenus
  - dubwise.dubsmintminimap
  - GHSGKD.DeathRattleZH
  - WiseClock.AC.DaysMatter
  - fluffy.areaunlocker
  - Mlie.LessArbitrarySurgery
  - Mlie.LessStupidRomanceAttempt
  - smashphil.loadinginprogress
  - brrainz.justignoremepassing
  - ChippedChap.BlueprintTotalsTooltip
  - Zephyr.BlueprintTotalsTooltipZh
  - smashphil.carrycapacityfixed
  - Mlie.PickUpAndHaul
  - Jaxe.Bubbles
  - JaxeZH.Bubbles
  - ChinesePackage.ConfigurableMaps
  - configurablemaps.kv.rw
  - Orion.Gastronomy
  - Zephyr.Gastronomyzh
  - jelly.harvestsync
  - 400.ImpassableHChestUdeepHWater
  - reiquard.researchinfo
  - tammybee.predatorhuntalert
  - RWZH.ChinesePack.OgreStack
  - Ogre.OgreStack
  - samo.RareTraits
  - tammybee.whereismyweapon
  - neceros.metaldontburn
  - fed1sPlay.PawnTargetFix
  - com.yayo.raceQuestPawn
  - Ogliss.RescueeJoinsPlus
  - GG.RescueeJoinsPlus
  - Ogliss.WanderJoinsPlus
  - GG.WanderJoinsPlus
  - Vanya.Tools.IncidentPersonStat
  - crlsniper.realisticrooms
  - GHSGKD.realisticroomsZH
  - Mlie.RealDining
  - ONegative.ReworkedTemperatureExtremeEvents
  - dhultgren.smarterconstruction
  - zlj.staticQualityPlus.124
  - tradingspot.kv.rw
  - RWZH.ChinesePack.tradingspot
  - RWZH.ChinesePack.UnlimitedHugs
  - Linkolas.Stabilize
  - weilbyte.snapout
  - RWZH.ChinesePack.snapout
  - PeteTimesSix.SimpleSidearms
  - RWZH.ChinesePack.RBSEHC
  - Rah.RBSEHC
  - sarg.alphaanimals
  - QAQ.QAAAQ
  - weilbyte.nopowerwires
  - Jaxe.RimHUD
  - shouer.chinesepack.RimHUD
  - PeteTimesSix.CompactHediffs
  - Zephyr.CompactHediffsZh
  - Mlie.ExpandedIncidents
  - RWZH.ChinesePack.ExpandedIncidents
  - Mlie.MoEvents
  - RWZH.ChinesePack.MoEvents
  - Ameiro.Animehairs
  - Gloomy.GloomyHairMk2
  - GWhair.noface
  - rimsenal.hair
  - sakama.RoppoiHair
  - RWZH.ChinesePack.VHE
  - Orion.XevaRimhair
  - ChJees.Androids
  - RWZH.ChinesePack.Androids
  - RunneLatki.RabbieRaceMod
  - RWZH.ChinesePack.RabbieRaceMod
  - RunneLatki.RabbieVanillafacepatch
  - Solaris.RatkinRaceMod
  - RWZH.ChinesePack.RatkinRaceMod
  - Solaris.RatkinVanillaFace
  - Daemon976.FacialAnimationplus
  - shavius.alienrbse
  - sulusdacor.james76543.Meltup.AdvancedPowerPlus
  - RWZH.ChinesePack.AdvancedPowerPlus
  - Mlie.SDBridges
  - dracoix.doormat.r12a
  - factioncontrol.kv.rw
  - Solaris.FurnitureBase
  - RWZH.ChinesePack.FurnitureBase
  - Haplo.Miscellaneous.Endgame
  - rimfridge.kv.rw
  - Albion.SparklingWorlds.Full
  - RWZH.ChinesePack.SparklingWorldsFull
  - GT.Sam.TilledSoil
  - automatic.traderships
  - RWZH.ChinesePack.traderships
  - nephlite.orbitaltradecolumn
  - RWZH.ChinesePack.orbitaltradecolumn
  - VanillaExpanded.VAEAS
  - VanillaExpanded.VAEAU
  - VanillaExpanded.VAEBF
  - VanillaExpanded.VAECD
  - VanillaExpanded.VAED
  - VanillaExpanded.VAEED
  - VanillaExpanded.VAEIS
  - VanillaExpanded.VAETF
  - VanillaExpanded.VAETR
  - VanillaExpanded.VAETS
  - VanillaExpanded.VAET
  - RWZH.ChinesePack.VAE
  - VanillaExpanded.VAPPE
  - VanillaExpanded.VARME
  - VanillaExpanded.VWE
  - VanillaExpanded.VWEQ
  - RWZH.ChinesePack.VWAAE
  - VanillaExpanded.VCEF
  - RWZH.ChinesePack.VCEF
  - VanillaExpanded.VFECore
  - VanillaExpanded.VFEArt
  - VanillaExpanded.VFEFarming
  - VanillaExpanded.VFEMedical
  - VanillaExpanded.VFEProduction
  - VanillaExpanded.VFESecurity
  - VanillaExpanded.VFESpacer
  - RWZH.ChinesePack.VFE
  - dismarzero.VGP.VGPVegetableGarden
  - argon.vanillavgarden
  - dismarzero.VGP.VGPGardenFabrics
  - argon.vanillavgardenfab
  - dismarzero.VGP.VGPThreeSistersPlants
  - dismarzero.VGP.VGPMoreVeggies
  - dismarzero.VGP.VGPGardenResources
  - argon.vanillavgardenresources
  - dismarzero.VGP.VGPGardenMedicine
  - dismarzero.VGP.VGPGardenTools
  - shavius.vpe.zh
  - VanillaExpanded.VPlantsE
  - shavius.vbe.zh
  - VanillaExpanded.VBrewE
  - shavius.vce.zh
  - VanillaExpanded.VCookE
  - VanillaExpanded.VCookEStews
  - VanillaExpanded.VCookESushi
  - shavius.vbookse.zh
  - VanillaExpanded.VBooksE
  - OskarPotocki.VanillaFactionsExpanded.MedievalModule
  - RWZH.ChinesePack.MedievalModule
  - OskarPotocki.VanillaFactionsExpanded.SettlersModule
  - RWZH.ChinesePack.SettlersModule
  - shavius.vfeinsectoids.zh
  - OskarPotocki.VFE.Insectoid
  - OskarPotocki.VFE.Vikings
  - RWZH.ChinesePack.Vikings
  - VSE.PerryPersistent
  - RWZH.ChinesePack.PerryPersistent
  - VanillaExpanded.VTEXE
  - RWZH.ChinesePack.VTEXE
  - Mlie.RoadsOfTheRim
  - RWZH.ChinesePack.RoadsOfTheRim
  - Vanya.Polarisbloc.CoreLab
  - Vanya.Polarisbloc.SecurityForce
  - rimsenal.core
  - rimsenal.EVP
  - rimsenal.federation
  - rimsenal.feral
  - rimsenal.storyteller
  - rimsenal.security
  - RWZH.ChinesePack.rimsenal
  - JPT.SoftWarmBeds
  - RWZH.ChinesePack.JPT
  - notfood.SeedsPlease
  - shadow.spaiomegapatch
  - LingLuo.PrepareCarefully
  - co.uk.epicguru.whatsthatmod
  - fluffy.modmanager
  - RWZH.ChinesePack.Fluffy

**Screenshots**
https://imgur.com/S8q5FdY
https://imgur.com/FPyvQFp
https://imgur.com/OwLYaDj

**Comment by pastorismylord** [comment]
please check the wiki for mod compatibility.
