### ISSUE TITLE
Staggering when androids attack

### ISSUE THREAD

**Issue by Meskitaa** [cseelhoff/RimThreaded#265]
**Describe the bug**
As soon as some androids decide to attack me (with humans it was fine) the game start to stagger
on the log it says 

**To Reproduce**
Have some androids spawn to attack you, or it might even be just the androids by itself (it said on the trelo page it was compatible so it might be something else)

Once I deleted the androids/killed them the game went back to normal

**Error Log**
https://gist.github.com/d516fb7a142f0a37b2d6f53ed10b7e12

thread 66 did not finish within 1000ms. restarting thread
https://gist.github.com/a833be63ae8bdbaa3d37c7094a3c6b2c

**Mod List**
[Mod list length: 149]
Harmony [https://steamcommunity.com/sharedfiles/filedetails/?id=2009463077]
Core [https:// no link (local mod)]
Royalty [Official DLC] [https:// no link (local mod)]
Startup impact [https://steamcommunity.com/sharedfiles/filedetails/?id=1684944322]
HugsLib [https://steamcommunity.com/sharedfiles/filedetails/?id=818773962]
4M Mehni's Misc Modifications [1.2] [https://steamcommunity.com/sharedfiles/filedetails/?id=2228765246]
Allow Tool [https://steamcommunity.com/sharedfiles/filedetails/?id=761421485]
Vanilla Animals Expanded — Arid Shrubland [https://steamcommunity.com/sharedfiles/filedetails/?id=1836900626]
Vanilla Animals Expanded — Australia [https://steamcommunity.com/sharedfiles/filedetails/?id=1963681588]
Vanilla Animals Expanded — Tundra [https://steamcommunity.com/sharedfiles/filedetails/?id=1895364585]
Vanilla Animals Expanded — Tropical Rainforest [https://steamcommunity.com/sharedfiles/filedetails/?id=1907283872]
Vanilla Animals Expanded — Ice Sheet [https://steamcommunity.com/sharedfiles/filedetails/?id=1895364782]
Vanilla Animals Expanded — Cats and Dogs [https://steamcommunity.com/sharedfiles/filedetails/?id=1823540489]
Vanilla Animals Expanded — Desert [https://steamcommunity.com/sharedfiles/filedetails/?id=1849183875]
Vanilla Animals Expanded — Boreal Forest [https://steamcommunity.com/sharedfiles/filedetails/?id=1895364938]
Vanilla Animals Expanded — Tropical Swamp [https://steamcommunity.com/sharedfiles/filedetails/?id=1907283935]
Vanilla Animals Expanded — Extreme Desert [https://steamcommunity.com/sharedfiles/filedetails/?id=1849184079]
Vanilla Expanded Framework [https://steamcommunity.com/sharedfiles/filedetails/?id=2023507013]
Vanilla Expanded - Royalty Patches [https://steamcommunity.com/sharedfiles/filedetails/?id=2260012940]
Vanilla Furniture Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1718190143]
Vanilla Furniture Expanded - Medical Module [https://steamcommunity.com/sharedfiles/filedetails/?id=1718191613]
Humanoid Alien Races 2.0 [https://steamcommunity.com/sharedfiles/filedetails/?id=839005762]
Android tiers [https://steamcommunity.com/sharedfiles/filedetails/?id=1386412863]
Android Tiers + Vanilla Expanded Medical [https://steamcommunity.com/sharedfiles/filedetails/?id=1956510084]
Animal Tab [https://steamcommunity.com/sharedfiles/filedetails/?id=712141500]
Architect Icons [https://steamcommunity.com/sharedfiles/filedetails/?id=1195427067]
Auto-Cut Blight [https://steamcommunity.com/sharedfiles/filedetails/?id=1885186534]
Avoid Friendly Fire [https://steamcommunity.com/sharedfiles/filedetails/?id=1134165362]
Vanilla Armour Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1814988282]
Vanilla Hair Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1888705256]
Vanilla Apparel Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1814987817]
Vanilla Weapons Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1814383360]
Awesome Inventory [https://steamcommunity.com/sharedfiles/filedetails/?id=2050289408]
Beautiful Outdoors [https://steamcommunity.com/sharedfiles/filedetails/?id=2011794898]
Better ModMismatch Window [https://steamcommunity.com/sharedfiles/filedetails/?id=1872244972]
Better Pawn Control [https://steamcommunity.com/sharedfiles/filedetails/?id=1541460369]
Better Time Format [https://steamcommunity.com/sharedfiles/filedetails/?id=2072773208]
Better Vanilla Masking [https://steamcommunity.com/sharedfiles/filedetails/?id=1736114368]
Better Workbench Management [https://steamcommunity.com/sharedfiles/filedetails/?id=935982361]
Bionic icons [https://steamcommunity.com/sharedfiles/filedetails/?id=1677616980]
Brrr and Phew (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2195938471]
Build From Inventory [https://steamcommunity.com/sharedfiles/filedetails/?id=1691419062]
Bulk Stonecutting [https://steamcommunity.com/sharedfiles/filedetails/?id=2021425587]
CM Color Coded Mood Bar [1.1+] [https://steamcommunity.com/sharedfiles/filedetails/?id=2006605356]
Camera+ [https://steamcommunity.com/sharedfiles/filedetails/?id=867467808]
Centralized Climate Control (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2007268173]
Change map edge limit [https://steamcommunity.com/sharedfiles/filedetails/?id=1546494565]
CleaningArea [https://steamcommunity.com/sharedfiles/filedetails/?id=870089952]
Dubs Mint Menus [https://steamcommunity.com/sharedfiles/filedetails/?id=1446523594]
Compact Hediffs [https://steamcommunity.com/sharedfiles/filedetails/?id=2031734067]
De-generalize Work [https://steamcommunity.com/sharedfiles/filedetails/?id=2011655761]
D9 Framework [https://steamcommunity.com/sharedfiles/filedetails/?id=2037445541]
Vanilla Events Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1938420742]
Vanilla Textures Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2016436324]
Vanilla Textures Expanded - Mod Expansion [https://steamcommunity.com/sharedfiles/filedetails/?id=2032079102]
[SYR] Universal Fermenter [https://steamcommunity.com/sharedfiles/filedetails/?id=2073225100]
Vanilla Factions Expanded - Settlers [https://steamcommunity.com/sharedfiles/filedetails/?id=2052918119]
Vanilla Weapons Expanded - Quickdraw [https://steamcommunity.com/sharedfiles/filedetails/?id=1906780517]
Vanilla Weapons Expanded - Laser [https://steamcommunity.com/sharedfiles/filedetails/?id=1989352844]
Vanilla Furniture Expanded - Farming [https://steamcommunity.com/sharedfiles/filedetails/?id=1957158779]
Vanilla Furniture Expanded - Spacer Module [https://steamcommunity.com/sharedfiles/filedetails/?id=2028381079]
Vanilla Furniture Expanded - Security [https://steamcommunity.com/sharedfiles/filedetails/?id=1845154007]
Vanilla Fishing Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1914064942]
Vanilla Plants Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2134308522]
Vanilla Cooking Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2134308519]
Vanilla Furniture Expanded - Art [https://steamcommunity.com/sharedfiles/filedetails/?id=1968134023]
Vanilla Furniture Expanded - Power [https://steamcommunity.com/sharedfiles/filedetails/?id=2062943477]
Vanilla Furniture Expanded - Production [https://steamcommunity.com/sharedfiles/filedetails/?id=1880253632]
Vanilla Factions Expanded - Medieval [https://steamcommunity.com/sharedfiles/filedetails/?id=2023513450]
Vanilla Brewing Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2186560858]
[SYR] Metallic Batteries [https://steamcommunity.com/sharedfiles/filedetails/?id=1489425285]
DocWorld [https://steamcommunity.com/sharedfiles/filedetails/?id=1568744597]
DontBlockDoor[1.0-1.2] [https://steamcommunity.com/sharedfiles/filedetails/?id=1691076769]
Dubs Break Mod [https://steamcommunity.com/sharedfiles/filedetails/?id=1722398508]
ED-Embrasures [https://steamcommunity.com/sharedfiles/filedetails/?id=722085442]
Expanded Roofing [https://steamcommunity.com/sharedfiles/filedetails/?id=2026595894]
FSharp.Core [https://steamcommunity.com/sharedfiles/filedetails/?id=2059725183]
Fallout Traits (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2016437642]
Fixable Mood Debuffs Alert [https://steamcommunity.com/sharedfiles/filedetails/?id=1307316672]
Giddy-up! Core [https://steamcommunity.com/sharedfiles/filedetails/?id=1216999901]
Giddy-up! Battle Mounts [https://steamcommunity.com/sharedfiles/filedetails/?id=1217001091]
Giddy-up! Caravan [https://steamcommunity.com/sharedfiles/filedetails/?id=1253251478]
Giddy-up! Ride and Roll [https://steamcommunity.com/sharedfiles/filedetails/?id=1331961995]
Haul to Stack [https://steamcommunity.com/sharedfiles/filedetails/?id=949498803]
Heat Map [https://steamcommunity.com/sharedfiles/filedetails/?id=947972722]
High quality textures [https://steamcommunity.com/sharedfiles/filedetails/?id=1676969930]
I Clearly Have Enough! (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2023661266]
Interaction Bubbles [https://steamcommunity.com/sharedfiles/filedetails/?id=1516158345]
Jobs of Opportunity (While You're Up) [https://steamcommunity.com/sharedfiles/filedetails/?id=2034960453]
Just Ignore Me Passing [https://steamcommunity.com/sharedfiles/filedetails/?id=1231617602]
Less Arbitrary Surgery (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2018250654]
Level Up! [https://steamcommunity.com/sharedfiles/filedetails/?id=1701592470]
Locks [https://steamcommunity.com/sharedfiles/filedetails/?id=1157085076]
Mad Skills [https://steamcommunity.com/sharedfiles/filedetails/?id=731111514]
Metal Don't Burn [https://steamcommunity.com/sharedfiles/filedetails/?id=2022726345]
Mod Manager [https://steamcommunity.com/sharedfiles/filedetails/?id=1507748539]
ModDiff [https://steamcommunity.com/sharedfiles/filedetails/?id=2200054867]
More Harvest Designators! [https://steamcommunity.com/sharedfiles/filedetails/?id=1541250497]
More Planning [https://steamcommunity.com/sharedfiles/filedetails/?id=881100382]
[KV] RimFridge [https://steamcommunity.com/sharedfiles/filedetails/?id=1180721235]
LWM's Deep Storage [https://steamcommunity.com/sharedfiles/filedetails/?id=1617282896]
Netrve's DeepStorage GUI [https://steamcommunity.com/sharedfiles/filedetails/?id=2169841018]
No Job Authors [https://steamcommunity.com/sharedfiles/filedetails/?id=2009825774]
Numbers (patched) 1.2 [https://steamcommunity.com/sharedfiles/filedetails/?id=2255104042]
Pawn Rules [https://steamcommunity.com/sharedfiles/filedetails/?id=1499843448]
PawnTargetFix [https://steamcommunity.com/sharedfiles/filedetails/?id=2014789938]
Pick Up And Haul (Continued) [https:// no link (local mod)]
QualityBuilder [https://steamcommunity.com/sharedfiles/filedetails/?id=754637870]
QualitySurgeon [https://steamcommunity.com/sharedfiles/filedetails/?id=857350593]
Quick Stockpile Creation [https://steamcommunity.com/sharedfiles/filedetails/?id=1742151109]
RT Fuse [https://steamcommunity.com/sharedfiles/filedetails/?id=728314182]
RT Solar Flare Shield [https://steamcommunity.com/sharedfiles/filedetails/?id=728315620]
Range Finder [https://steamcommunity.com/sharedfiles/filedetails/?id=1332119637]
RimHUD [https://steamcommunity.com/sharedfiles/filedetails/?id=1508850027]
Recipe icons [https://steamcommunity.com/sharedfiles/filedetails/?id=1616643195]
ResearchPal [https://steamcommunity.com/sharedfiles/filedetails/?id=946390822]
RimThreaded [1.2] [https://steamcommunity.com/sharedfiles/filedetails/?id=2222907981]
Rimpedia [https://steamcommunity.com/sharedfiles/filedetails/?id=2145524536]
Roads of the Rim (Continued) [https:// no link (local mod)]
Show Draftees Weapon [https://steamcommunity.com/sharedfiles/filedetails/?id=1690978457]
Simple Search Bar [https://steamcommunity.com/sharedfiles/filedetails/?id=1827546987]
Simple sidearms [https://steamcommunity.com/sharedfiles/filedetails/?id=927155256]
Skilled Stonecutting [https://steamcommunity.com/sharedfiles/filedetails/?id=1207390617]
Smarter Construction [https://steamcommunity.com/sharedfiles/filedetails/?id=2202185773]
Snap Out! [https://steamcommunity.com/sharedfiles/filedetails/?id=1319782555]
Sparkling Worlds - Full Mod [https://steamcommunity.com/sharedfiles/filedetails/?id=1123043922]
Therapy [https://steamcommunity.com/sharedfiles/filedetails/?id=1076950211]
Tilled Soil [https://steamcommunity.com/sharedfiles/filedetails/?id=725747149]
TradeHelper [https://steamcommunity.com/sharedfiles/filedetails/?id=2113372560]
Ugh You Got Me [https://steamcommunity.com/sharedfiles/filedetails/?id=1542424705]
Vanilla Cooking Expanded - Stews [https://steamcommunity.com/sharedfiles/filedetails/?id=2134312965]
Vanilla Cooking Expanded - Sushi [https://steamcommunity.com/sharedfiles/filedetails/?id=2158539170]
Vanilla Factions Expanded - Insectoids [https://steamcommunity.com/sharedfiles/filedetails/?id=2149755445]
Vanilla Factions Expanded - Vikings [https://steamcommunity.com/sharedfiles/filedetails/?id=2231295285]
Vanilla Furniture Expanded - Props and Decor [https://steamcommunity.com/sharedfiles/filedetails/?id=2102143149]
Vanilla Storytellers Expanded - Igor Invader [https://steamcommunity.com/sharedfiles/filedetails/?id=2249879548]
Vanilla Storytellers Expanded - Perry Persistent [https://steamcommunity.com/sharedfiles/filedetails/?id=2149702069]
Wall Light [https://steamcommunity.com/sharedfiles/filedetails/?id=1423699208]
WeaponStats [https://steamcommunity.com/sharedfiles/filedetails/?id=974066449]
[1.1] TicksPerSecond [https://steamcommunity.com/sharedfiles/filedetails/?id=2014026734]
Vanilla Books Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2193152410]
[FSF] Complex Jobs [https://steamcommunity.com/sharedfiles/filedetails/?id=2069684319]
[FSF] Filth Vanishes With Rain And Time [https://steamcommunity.com/sharedfiles/filedetails/?id=1508341791]
[KV] Consolidated Traits [https://steamcommunity.com/sharedfiles/filedetails/?id=1507384362]
[KV] More Trait Slots [https://steamcommunity.com/sharedfiles/filedetails/?id=1508292711]
[KV] Trading Spot [https://steamcommunity.com/sharedfiles/filedetails/?id=1180719658]
[SYR] Doormats [https://steamcommunity.com/sharedfiles/filedetails/?id=1508778962]
[SYR] Harvest Yield [https://steamcommunity.com/sharedfiles/filedetails/?id=1461790308]
[SYR] Set Up Camp [https://steamcommunity.com/sharedfiles/filedetails/?id=1470065926]

**Screenshots**
Not sure it would help happened when only 1 attacked and now with a couple more

**Comment by cseelhoff** [comment]
Thanks for bug reports. I noticed 2 errors, one with vanilla and one with PawnRules. Both will be fixed in next release. Please reopen if issue reoccurs.
