### ISSUE TITLE
"Where is my weapon?" Freezes and crash with 1.1.13

### ISSUE THREAD

**Issue by Magichp** [cseelhoff/RimThreaded#273]
**Describe the bug**
Freeze game indefinitely on start or load game

**To Reproduce**
1. Start a game with the mods mentionned in the log below
2. Click on speed modifier
3. Game freezes or rather gets to a very low framerate (1 frame per 15 seconds or so)

**Error Log**
Link to contents of Player.log or Error.log (Please use something like gist or pastebin. DO NOT PASTE HERE)
https://gist.github.com/0889b02028c1bad7a3913fc7c5d0c6af
**Mod List**
Paste contents of ModList used when bug occurred.
https://pastebin.com/BYM2AchK
**Screenshots**

**Comment by cseelhoff** [comment]
WhereIsMyWeapon is not compatible. Can you try removing and seeing if that helps?

**Comment by Magichp** [comment]
Yes, it does seem to have fixed that issue. At least, the issue changed radically from a frozen game to a Unity crash, but that one is most likely linked to issue 275.
You can add WhereIsMyWeapon to the incompatible mods list (sadly, that was a nice QoL mod ^^ ) .

**Comment by cseelhoff** [comment]
I added it to the incompat mod list on Trello. I marked this bug as an enhancement and I will come back to making this mod compatible at some point likely.

**Comment by Niilo007** [comment]
Please try with the most recent version of RimThreaded, also your load order has some problems.
If you get this issue again, re open this issue, if you get something else make a new issue report

**Comment by pastorismylord** [comment]
tested with 2.2.17, unable to reproduce the issue. Mod works fine now
