### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by shawarmacat** [cseelhoff/RimThreaded#274]
the game runs fine but it keeps sending red text at me and suddenly my screen went black

i simply put the game on 3x speed to test the new update

[modlist.txt](https://github.com/cseelhoff/RimThreaded/files/5586469/modlist.txt)
[blacked.com.txt](https://github.com/cseelhoff/RimThreaded/files/5586470/blacked.com.txt)

![20201124035505_1](https://user-images.githubusercontent.com/74803651/100028864-4b6dc300-2e09-11eb-8bc0-7a9ee3aa36e0.jpg)

**Comment by cseelhoff** [comment]
Can you check the mod settings for RimThreaded? There should be a section for incompatible mods. Can you post that here?

**Comment by pastorismylord** [comment]
please verify your modlist as several incompatible mods have been identified. Check the wiki and our discord community for aditional details
