### ISSUE TITLE
"RJW" Unity crash with 1.1.14

### ISSUE THREAD

**Issue by Magichp** [cseelhoff/RimThreaded#275]
**Describe the bug**
After a few seconds up to a minute of being ingame, a Unity crash window appears and closes the game.

**To Reproduce**
1. Install the mods from the following Modlist (a 7zip containing local mods can be found at http://www.mediafire.com/file/ztp5hpe7oypys5v/Mods.7z for ease of use)
2. Start a new save or load an existing one (Current savefile used : http://www.mediafire.com/file/an47kkciw0kshzl/United_Flesh_Cult_Fixed.rws/file ) 
3. Play normally (usually for a few seconds to 1 or 2 minutes)
4. See Unity crash window close the game.

**Error Log**
Link to contents of Player.log or Error.log (Please use something like gist or pastebin. DO NOT PASTE HERE)
Error.log : https://pastebin.com/h4dePwP7
Player.log : https://gist.github.com/Magichp/06e0d008155ca4c6970cdbcdea759062
**Mod List**
Paste contents of ModList used when bug occurred.
https://pastebin.com/efzGQvy2
Rimpy Exported ModOrder for ease of use : http://www.mediafire.com/file/p882g3bltiln90h/RimpyModlist.xml/file
**Screenshots**

**Comment by cseelhoff** [comment]
Looks like problem with Rimworld-Animations. This will likely get fixed in a future release. Thanks for the bug report!

**Comment by pastorismylord** [comment]
issue was fixed on 2.2.19 preview.
