### ISSUE TITLE
Planet Temperature thread restarting 

### ISSUE THREAD

**Issue by thefriendlycacti** [cseelhoff/RimThreaded#279]
**Describe the bug**
TPS drops to basically 1 as the game slowly moves forward

**To Reproduce**
no idea

**how to fix**
reload game

harmony log:
https://gist.github.com/7351ac64ef11e9390713d412d684105d

Specific error"
https://gist.github.com/thefriendlycacti/1e9551b05e85f5dc8a716c34cda8a5ad

**Comment by Lerupt** [comment]
I Have the same problem.

**Comment by Niilo007** [comment]
Re open this issue if it happens in the new versions
