### ISSUE TITLE
UI disappear,error about animal's pathfinder and other bugs

### ISSUE THREAD

**Issue by 136068448** [cseelhoff/RimThreaded#281]
**Describe the bug**
1.it's seems the game is calculating a loop and wrong social state and cause game lag, the log said that calculate about such as eat humanlike; defeat faction leader; butch humanlike; kill colony animal. and all of those thing i never did, but it still try to calculate it

2.the Gallatross from Alpha Animal mod seems have some incompatible issue when use both CE and RT, i spawn a gallatross and make it into the Man-Hunter mental, and the gallatross use range power to attack pawn, then the attack donesnt  have effect but can hear the sound of boom, in the same time the red error spawn crazy and make game lag

3.when use the CE's loadout system and in this time if your pawn doesn't have enough space to carry ammo, it will product many error about it but have no affect about performence, and give pawn a bag or other thing can make more space the pawn can carry will resolve this question

4.it is similar with #253, the animal spawn from Herd migration; join; caravan or in the cold snap, will make animal stunk and make game can't run, only have 1 or less than it per second,it seems have the pathfind error when they stunk, also like #253, kill those animals can resolve this question

5.there have a error i dont understand about it, it have a error about talemanager, have a little affect with performence(can encounte this error with vanilla enviroment)

6.i order my pawns to load something into transport pod, then UI disappear but game can run, pawns still can do things as normal,but i try to click everything and no UI appear, at last, i click the world tab,the planet have nothing and also useless when click anything so i can't return to my colony,only shut down the game.

there have a question that when bug 4 and 5 in this report appear and run a while,then when trade with caravan will make the trade UI can't click but can use ESC to exit it and the things trade can correctly appear on ground, and the bug 6 may appear after the trade UI question appear

### EDIT: I found the UI problem will happended randomly if there need a UI to appear,usually after finish some thing, such as the research finished, finish load the things into trasnsport pod, the caravan trade UI, those will randomly cause the UI dissappear and it is fatal because if occur this issue, the game will can't control only can restart game, but restart game can't resolve this problem, it just make this fatal issue happend later, and i test it with vanilla enviroment(include modmanager mod)and seems dont have such a error.

[SAVE.zip](https://github.com/cseelhoff/RimThreaded/files/5591725/SAVE.zip)

**To Reproduce**
1. load my save
2. run it for a while
3. all of the bugs will appear except bug6

**Error Log**
https://gist.github.com/136068448/d28df938c5e0401739b3d671be4a518a

WHOLE LOG:
https://gist.github.com/136068448/23cebe6746e9a6f5e6ce663d44e1f007

**Mod List**
  - brrainz.harmony
  - Ludeon.RimWorld
  - Ludeon.RimWorld.Royalty
  - UnlimitedHugs.HugsLib
  - CETeam.CombatExtended
  - CETeam.CombatExtendedGuns
  - n7huntsman.CombatExtendedWeapons
  - mi.chinesePack.combatExtended
  - Nals.FacialAnimation
  - erdelf.HumanoidAlienRaces
  - RWZH.ChinesePack.HumanoidAlienRaces
  - velc.HatsDisplaySelection
  - OskarPotocki.VanillaFactionsExpanded.Core
  - vanillaexpanded.achievements
  - vanillaexpanded.zh
  - brrainz.achtung
  - RWZH.ChinesePack.achtung
  - brrainz.cameraplus
  - RWZH.ChinesePack.cameraplus
  - void.charactereditor
  - UnlimitedHugs.MapReroll
  - UnlimitedHugs.AllowTool
  - fluffy.colonymanager
  - Vanya.Tools.BlightedAlert
  - razor2.3.AnotherRimworldMod.AutoCutBlight
  - Oblitus.AnimalsLogic
  - GHSGKD.AnimalsLogicZH
  - falconne.BWM
  - sarg.smartspeed
  - fluffy.animaltab
  - fluffy.blueprints
  - fluffy.pharmacist
  - fluffy.relationstab
  - fluffy.worktab
  - fluffy.stuffedfloors
  - fluffy.medicaltab
  - leafzxg.MasterOfCooking
  - leafzxg.MasterOfCrafting
  - automatic.gunplay
  - velc.MineItAll
  - tikubonn.DontBlockDoor
  - Ogliss.Mythos.DiseasesOverhauled
  - DiseasesOverhauled.Chinese
  - Troopersmith1.DeathRattle
  - Dubwise.DubsMintMenus
  - dubwise.dubsmintminimap
  - GHSGKD.DeathRattleZH
  - WiseClock.AC.DaysMatter
  - fluffy.areaunlocker
  - Mlie.LessArbitrarySurgery
  - Mlie.LessStupidRomanceAttempt
  - smashphil.loadinginprogress
  - brrainz.justignoremepassing
  - ChippedChap.BlueprintTotalsTooltip
  - Zephyr.BlueprintTotalsTooltipZh
  - smashphil.carrycapacityfixed
  - Mlie.PickUpAndHaul
  - Jaxe.Bubbles
  - JaxeZH.Bubbles
  - ChinesePackage.ConfigurableMaps
  - configurablemaps.kv.rw
  - Orion.Gastronomy
  - Zephyr.Gastronomyzh
  - jelly.harvestsync
  - 400.ImpassableHChestUdeepHWater
  - reiquard.researchinfo
  - tammybee.predatorhuntalert
  - RWZH.ChinesePack.OgreStack
  - Ogre.OgreStack
  - samo.RareTraits
  - neceros.metaldontburn
  - fed1sPlay.PawnTargetFix
  - com.yayo.raceQuestPawn
  - Ogliss.RescueeJoinsPlus
  - GG.RescueeJoinsPlus
  - Ogliss.WanderJoinsPlus
  - GG.WanderJoinsPlus
  - Vanya.Tools.IncidentPersonStat
  - crlsniper.realisticrooms
  - GHSGKD.realisticroomsZH
  - Mlie.RealDining
  - ONegative.ReworkedTemperatureExtremeEvents
  - dhultgren.smarterconstruction
  - zlj.staticQualityPlus.124
  - tradingspot.kv.rw
  - RWZH.ChinesePack.tradingspot
  - RWZH.ChinesePack.UnlimitedHugs
  - Linkolas.Stabilize
  - weilbyte.snapout
  - RWZH.ChinesePack.snapout
  - PeteTimesSix.SimpleSidearms
  - RWZH.ChinesePack.RBSEHC
  - Rah.RBSEHC
  - sarg.alphaanimals
  - QAQ.QAAAQ
  - weilbyte.nopowerwires
  - Jaxe.RimHUD
  - shouer.chinesepack.RimHUD
  - PeteTimesSix.CompactHediffs
  - Zephyr.CompactHediffsZh
  - Mlie.ExpandedIncidents
  - RWZH.ChinesePack.ExpandedIncidents
  - Mlie.MoEvents
  - RWZH.ChinesePack.MoEvents
  - Ameiro.Animehairs
  - Gloomy.GloomyHairMk2
  - GWhair.noface
  - rimsenal.hair
  - sakama.RoppoiHair
  - RWZH.ChinesePack.VHE
  - Orion.XevaRimhair
  - ChJees.Androids
  - RWZH.ChinesePack.Androids
  - RunneLatki.RabbieRaceMod
  - RWZH.ChinesePack.RabbieRaceMod
  - RunneLatki.RabbieVanillafacepatch
  - Solaris.RatkinRaceMod
  - RWZH.ChinesePack.RatkinRaceMod
  - Solaris.RatkinVanillaFace
  - Daemon976.FacialAnimationplus
  - shavius.alienrbse
  - sulusdacor.james76543.Meltup.AdvancedPowerPlus
  - RWZH.ChinesePack.AdvancedPowerPlus
  - Mlie.SDBridges
  - dracoix.doormat.r12a
  - factioncontrol.kv.rw
  - Solaris.FurnitureBase
  - RWZH.ChinesePack.FurnitureBase
  - Haplo.Miscellaneous.Endgame
  - rimfridge.kv.rw
  - Albion.SparklingWorlds.Full
  - RWZH.ChinesePack.SparklingWorldsFull
  - GT.Sam.TilledSoil
  - automatic.traderships
  - RWZH.ChinesePack.traderships
  - nephlite.orbitaltradecolumn
  - RWZH.ChinesePack.orbitaltradecolumn
  - VanillaExpanded.VAEAS
  - VanillaExpanded.VAEAU
  - VanillaExpanded.VAEBF
  - VanillaExpanded.VAECD
  - VanillaExpanded.VAED
  - VanillaExpanded.VAEED
  - VanillaExpanded.VAEIS
  - VanillaExpanded.VAETF
  - VanillaExpanded.VAETR
  - VanillaExpanded.VAETS
  - VanillaExpanded.VAET
  - RWZH.ChinesePack.VAE
  - VanillaExpanded.VAPPE
  - VanillaExpanded.VARME
  - VanillaExpanded.VWE
  - VanillaExpanded.VWEQ
  - RWZH.ChinesePack.VWAAE
  - VanillaExpanded.VCEF
  - RWZH.ChinesePack.VCEF
  - VanillaExpanded.VFECore
  - VanillaExpanded.VFEArt
  - VanillaExpanded.VFEFarming
  - VanillaExpanded.VFEMedical
  - VanillaExpanded.VFEProduction
  - VanillaExpanded.VFESecurity
  - VanillaExpanded.VFESpacer
  - RWZH.ChinesePack.VFE
  - dismarzero.VGP.VGPVegetableGarden
  - argon.vanillavgarden
  - dismarzero.VGP.VGPGardenFabrics
  - argon.vanillavgardenfab
  - dismarzero.VGP.VGPThreeSistersPlants
  - dismarzero.VGP.VGPMoreVeggies
  - dismarzero.VGP.VGPGardenResources
  - argon.vanillavgardenresources
  - dismarzero.VGP.VGPGardenMedicine
  - dismarzero.VGP.VGPGardenTools
  - shavius.vpe.zh
  - VanillaExpanded.VPlantsE
  - shavius.vbe.zh
  - VanillaExpanded.VBrewE
  - shavius.vce.zh
  - VanillaExpanded.VCookE
  - VanillaExpanded.VCookEStews
  - VanillaExpanded.VCookESushi
  - shavius.vbookse.zh
  - VanillaExpanded.VBooksE
  - OskarPotocki.VanillaFactionsExpanded.MedievalModule
  - RWZH.ChinesePack.MedievalModule
  - OskarPotocki.VanillaFactionsExpanded.SettlersModule
  - RWZH.ChinesePack.SettlersModule
  - shavius.vfeinsectoids.zh
  - OskarPotocki.VFE.Insectoid
  - OskarPotocki.VFE.Vikings
  - RWZH.ChinesePack.Vikings
  - VSE.PerryPersistent
  - RWZH.ChinesePack.PerryPersistent
  - VanillaExpanded.VTEXE
  - RWZH.ChinesePack.VTEXE
  - Mlie.RoadsOfTheRim
  - RWZH.ChinesePack.RoadsOfTheRim
  - Vanya.Polarisbloc.CoreLab
  - Vanya.Polarisbloc.SecurityForce
  - rimsenal.core
  - rimsenal.EVP
  - rimsenal.federation
  - rimsenal.feral
  - rimsenal.storyteller
  - rimsenal.security
  - RWZH.ChinesePack.rimsenal
  - JPT.SoftWarmBeds
  - RWZH.ChinesePack.JPT
  - NotooShabby.AwesomeInventory
  - AwesomeZH.Inventory
  - notfood.SeedsPlease
  - shadow.spaiomegapatch
  - LingLuo.PrepareCarefully
  - co.uk.epicguru.whatsthatmod
  - fluffy.modmanager
  - RWZH.ChinesePack.Fluffy
  - majorhoff.rimthreaded

**Screenshots**
The UI and the faction on planet disappear:
![20201124214013_1](https://user-images.githubusercontent.com/74740183/100132209-0ce70f80-2ec0-11eb-92d9-b3d986b9b9a4.jpg)

**Comment by cseelhoff** [comment]
Thanks for bug report. I fixed the Verse.Verb_LaunchProjectile.TryCastShot issue in 1.1.22. Can you test again and attach a new error log. That would be very helpful. Thanks!

**Comment by 136068448** [comment]
Thanks for fix, but i test in same save, and i call a 10000point raid of tribes,and it seems have such enemy stop at a place in my kill box(seems have some pathing problem and it cause massive lag and product error message very very quick), and the stick bomb in CE can't cause damage for my pawn but it can destory the building and kill themself correctly so i think may because of the Android race have some problem with RT,and still have some error message about ammo(in other save i don't have such a problem,i will test this in a new game)

HERE is the new error log:https://gist.github.com/136068448/23e15c7751ae9b16a6edf1aec808b799

Hope it will give some help for it

**Comment by Niilo007** [comment]
Please re open the issue if you can get this to happen again. (fixed in 1.2.6)
