### ISSUE TITLE
Geothermal Generators logging repeated errors

### ISSUE THREAD

**Issue by Teldrik** [cseelhoff/RimThreaded#287]
**Describe the bug**
Having a room, any room, as well as geothermal generators causes a red error to spam. Seems to not actually cause gameplay issues aside from generating the error itself though. But it's annoying at best if you keep the option to pause on severe error on since it does it around 2-3 times a second.

**To Reproduce**
1. Make room of any size or shape. Doesn't need to be near the generators. Just needs to be a separate room.
2. Make a geothermal generator on a vent. 
3. ???
4. Error occurs.

**Error Log**
https://gist.github.com/Teldrik/295307178ce927b1f2a8bdf2cd739668

**Mod List**
Harmony
Core
Royalty
SRTS Expanded
SRTS Expanded Realism Patch
HugsLib
Mod Manager
JecsTools (Unofficial)
Character Editor
Humanoid Alien Races 2.0
What the hack?!
[FSF] Encounter Map Resources
Mountainous Cave System
Map Designer
Map Reroll
Fertile Planet
Vanilla Expanded Framework
[KV] More Trait Slots
[KV] Consolidated Traits
Cybernetic Organism and Neural Network
Expanded Prosthetics and Organ Engineering
[1.2] DE Surgeries
A Dog Said... Animal Prosthetics
Death Rattle Continued [1.2]
Harvest Organs Post Mortem
Pawnmorpher
Android tiers
Android tiers - Fixes + Tweaks
Android Tiers - Gynoids [1.2]
Autocleaner
RuntimeGC
Space Western (Music Pack)
Enhanced Combat Sounds
[SF] Priority treatment 1.1
I3's Combat Sounds (I3CS)
Desynchronized: Tales and News (Continued)
[RF] Rumor Has It.... (Continued)
Rational Romance 2
Beautiful Outdoors
[XND] Turret Extensions
Balanced Eclipse and Solar Flare
CustomDeathRandomness
4M Mehni's Misc Modifications [1.2]
Hospitality
Carry Capacity Fixed
PawnTargetFix
Field Medic [1.0+]
Realistic Rooms
Caravan Lag Eliminator
Alternative Sapper AI
Avoid Friendly Fire
Metabolism Feels Cared About Now
NightVision
[XND] Proper Shotguns
Grenade Fix: Rearmed
DocPawnOverhaul
Gain Skill Passions
Gunplay
Yayo's Combat 3
Brrr and Phew (Continued)
Dire Raids
Chatting on Comms
Undraft After Tucking
Non uno Pinata
De-generalize Work
Do Something for Idle
Smarter Construction
Animals Logic
Share The Load
Pep In Your Step
Just Ignore Me Passing
Loading In Progress
NPC Bonus (Continued)
Haul to Stack
Common Sense
Jobs of Opportunity (While You're Up)
Inspiration Tweaks
Quality Cooldown
Thick Armor
[SYR] Set Up Camp
Snap Out!
Camera+
Auto-Cut Blight
Run and Hide (Continued)
Real Faction Guest
Mad Skills
Fluffy Breakdowns
Let's Trade!
More Trade Ships
Set Owner for Prisoner Beds
[SYR] Harvest Yield
Faster Aging
Grazing Lands
Replace Stuff
Hydroponics Growth Sync (Continued)
Where is my weapon?
Overcapped Accuracy
Cut plants before building
Better Infestations 1.2
Simple Slavery [1.1]
Desire Paths
I Clearly Have Enough! (Continued)
Simple sidearms
Meals On Wheels
Long Distance
Lasting Flowers
Colony Leadership
Nurse Job
Outfitted
Squad UI Tweaks
[RF] Tribal Pawn Names (Continued)
Better Message Placement (Continued)
Wild Cultivation - Fan Update
[FSF] Better Spike Traps
GlitterNet
[KV] Path Avoid
[NL] Dynamic Portraits
H.C_ThrumboReskin
Various Space Ship Chunk (Continued)
Prisoners Need Recruiting
Better Vanilla Masking
Graphics Settings+
Greenworld Lite
RimFlix
Apparel BodyType Resolver
Plant Growth Sync
[KV] Show Hair With Hats or Hide All Hats
Simply Bulk Crafting
TicksPerSecond
FrameRateControl
[FSF] Filth Vanishes With Rain And Time
Sometimes Raids Go Wrong (patched) [1.2]
Interaction Bubbles
Nandonalt's Visual Addons (Continued)
Shit Rimworld Says
RenameColony
More Planning
Level Up!
Architect Icons
Dismiss Trader (Continued)
Damage Indicators [1.2]
Dub's Paint Shop
We Had a Trader? (Continued)
Hats Display Selection
RimHUD
Awesome Inventory
Gear Up And Go
Achtung!
Rimpedia
1.2 - Imprisonment On The Go! (Make Pawns Prisoners Without Beds)
Pawn Name Variety
Dubs Mint Menus
Dubs Mint Minimap
Settlement Descriptions
Allow Tool
Dress Patients
Blueprints
Simple Search Bar
Numbers (patched) 1.2
Relations Tab
Pawn Badge Fan Fork
Better ModMismatch Window
QualityBuilder
Power Alerts
ResearchPal
More Harvest Designators!
Better Pawn Control
Simple Stockpile Presets (Continued)
Mo'Events (Continued)
Vanilla Achievements Expanded
Vanilla Textures Expanded
Vanilla Events Expanded
Vanilla Hair Expanded
Vanilla Hair Expanded - Beards
Vanilla Storytellers Expanded - Empress Evil
Vanilla Storytellers Expanded - Perry Persistent
Vanilla Storytellers Expanded - Igor Invader
Vanilla Factions Expanded - Vikings
Vanilla Factions Expanded - Settlers
Vanilla Factions Expanded - Insectoids
Pawnmorpher: Insectoids
Vanilla Weapons Expanded
Vanilla Factions Expanded - Medieval
Vanilla Weapons Expanded - Grenades
Vanilla Weapons Expanded - Laser
Vanilla Weapons Expanded - Quickdraw
Vanilla Armour Expanded
Vanilla Apparel Expanded
Vanilla Fishing Expanded
Vanilla Books Expanded
Vanilla Brewing Expanded
Vanilla Cooking Expanded
Vanilla Cooking Expanded - Stews
Vanilla Cooking Expanded - Sushi
Vanilla Expanded - Royalty Patches
Vanilla Furniture Expanded
Vanilla Furniture Expanded - Art
Vanilla Furniture Expanded - Medical Module
Android Tiers + Vanilla Expanded Medical
Vanilla Furniture Expanded - Farming
Vanilla Furniture Expanded - Power
Vanilla Furniture Expanded - Props and Decor
Vanilla Furniture Expanded - Security
Vanilla Furniture Expanded - Production
Vanilla Furniture Expanded - Spacer Module
[FSF] Always Rearm Turrets
Vanilla Plants Expanded
Vanilla Plants Expanded - Succulents
Vanilla Animals Expanded — Arid Shrubland
Vanilla Animals Expanded — Australia
Vanilla Animals Expanded — Boreal Forest
Vanilla Animals Expanded — Cats and Dogs
Vanilla Animals Expanded — Desert
Vanilla Animals Expanded — Extreme Desert
Vanilla Animals Expanded — Ice Sheet
Vanilla Animals Expanded — Tropical Rainforest
Vanilla Animals Expanded — Tropical Swamp
Vanilla Animals Expanded — Tundra
Vanilla Animals Expanded — Temperate Forest
Vanilla Animals Expanded - Patch Pack[CE]
VFME - Caravan Packs!
Recon And Discovery (Continued)
Roads of the Rim (Continued)
[KV] RimFridge
LWM's Deep Storage
Rebalanced Deep Storage
Pick Up And Haul
Doors Expanded (Dev)
Locks 2: Lock Them Out!
Spotted (Continued)
[FSF] Growable Grass
Rimefeller
RimNauts
Expanded Roofing
Wall Mounted Turrets (Continued)
Advanced Moisture Pump
Wall Light
Utility Columns
ED-Embrasures
Trade Ships Drop Spot
More Linkables
Temperature Gauge (Continued)
Taming Artifact
Subsurface Conduit
Simply More Bridges (Continued)
[T] MoreFloors
[SYR] Metallic Batteries
Mass Graves
Fences And Floors (Continued)
Antigrain
Fertile Fields [1.1]
[SYR] Doormats
Quarry 1.1
Life Support Continued [1.1][1.2]
Alpha Animals
Megafauna
Leeani Playable Race
[SYR] Naga
Ferrex Race (Continued)
Astoriel
Equiums
Orassans
Nyaron race
RimThreaded [1.2]
Children and Pregnancy
[Ry]HD Pawn Textures(HAR Edition)
[XPatch] HD Icon Organs NPBA
Legacy Terrain Overhaul

**Comment by cseelhoff** [comment]
Patch to fix this should be working now in version 1.1.18
