### ISSUE TITLE
Lots of Errors Ticking Animal Pather

### ISSUE THREAD

**Issue by maarxx** [cseelhoff/RimThreaded#288]
Lots of Errors Ticking Animal Pather

https://gist.github.com/maarxx/731afd71f4ae92861ea30a54436f0ad2

![hoffchat](https://user-images.githubusercontent.com/7416299/100185788-ac9da100-2eb2-11eb-9c6f-0f09a58e4773.png)

**Comment by Niilo007** [comment]
Please re open the issue if the issue still occurs in the new versions.
