### ISSUE TITLE
Error Generating Rewards for Quest

### ISSUE THREAD

**Issue by maarxx** [cseelhoff/RimThreaded#289]
Error Generating Rewards for Quest

Quest offered without any selectable rewards.

https://gist.github.com/maarxx/fb87818ae480308256ace13990e45018

![damagedQuest](https://user-images.githubusercontent.com/7416299/100191771-b75e3300-2ebe-11eb-8da5-bb1f1eeb5881.png)

**Comment by Niilo007** [comment]
Test with new version of RT and re open if needed
