### ISSUE TITLE
Pure Vanilla - Hard Lockup Moving Caravan on Worldmap

### ISSUE THREAD

**Issue by maarxx** [cseelhoff/RimThreaded#292]
Original Title: Pure Vanilla - Hard Lockup Splitting Caravan

New Title: Pure Vanilla - Hard Lockup Moving Caravan on Worldmap

I thought it had to do with splitting the caravan but it actually might not, just move the caravan and advance time and it seems to freeze anyway.

### SAVEGAME

https://drive.google.com/file/d/1RE678M4PdMpsiBBg7OlhOqU2kBPYYEk6/view?usp=sharing

### SCREENSHOTS

![20201125125925_1](https://user-images.githubusercontent.com/7416299/100265530-6716bd80-2f1e-11eb-9234-7d87c626e399.jpg)

![20201125125648_1](https://user-images.githubusercontent.com/7416299/100265547-6d0c9e80-2f1e-11eb-80da-d8782e657989.jpg)

![20201125125703_1](https://user-images.githubusercontent.com/7416299/100265558-7138bc00-2f1e-11eb-9e82-82376558428d.jpg)

![20201125125711_1](https://user-images.githubusercontent.com/7416299/100265576-7564d980-2f1e-11eb-9921-8f6f5708f620.jpg)

![20201125125721_1](https://user-images.githubusercontent.com/7416299/100265679-9cbba680-2f1e-11eb-8673-1bcc6cdded63.jpg)

![boom](https://user-images.githubusercontent.com/7416299/100265687-a04f2d80-2f1e-11eb-8330-4505f1fc5638.png)

**Comment by cseelhoff** [comment]
I don't know if I'm doing something wrong or if it is just something I fixed in 1.1.20, but I can no longer reproduce this error. Please reopen bug report if it is still occurring on latest version of the mod.
