### ISSUE TITLE
Random crash with mods (UnityPlayer.dll caused an Access Violation (0xc0000005))

### ISSUE THREAD

**Issue by Wad67** [cseelhoff/RimThreaded#297]
**Describe the bug**
Was watching some robots dig in a quarry and then the game went kaput

**To Reproduce**
Not known

**Error Log**
https://gist.github.com/Wad67/2d09c317d557d3293c9e12aa9d63d88d

**Mod List**

>   <activeMods>
>     <li>brrainz.harmony</li>
>     <li>ludeon.rimworld</li>
>     <li>ludeon.rimworld.royalty</li>
>     <li>majorhoff.rimthreaded</li>
>     <li>erdelf.humanoidalienraces</li>
>     <li>atlas.androidtiers</li>
>     <li>ogliss.thewhitecrayon.quarry</li>
>   </activeMods>

**Screenshots**
![image](https://user-images.githubusercontent.com/991507/100290299-bdd7d200-2fc6-11eb-9eca-2b8ce59ead81.png)
 :)

**Comment by cseelhoff** [comment]
Definitely an error with AndroidTiers. I will try to work on its compatibility
