### ISSUE TITLE
Exception ticking World Component brings game to 1 TPS

### ISSUE THREAD

**Issue by lourencomcviana** [cseelhoff/RimThreaded#298]
**Describe the bug**
In case we find this again or find a way to reproduce. Im having an error where i get constantly the following exception (reducing TPS to 1/s)

It happened right after i left one base i destroyed via pods. I might test it later because people rarelly leave destroyed bases by pods. I didnt had much surviving muffallos 😢 

Loading the game completely fixed the issue

I know this report is almost useless. Puting it here case i find more details 

**To Reproduce**
Dunno

**Error Log**
```
Exception ticking World Component: RimWorld.Planet.TileTemperaturesCompSystem.Threading.ThreadAbortException
  at (wrapper dynamic-method) RimWorld.Planet.TileTemperaturesComp.RimWorld.Planet.TileTemperaturesComp.WorldComponentTick_Patch0(RimWorld.Planet.TileTemperaturesComp)
  at RimThreaded.RimThreaded.ExecuteTicks () [0x00ca0] in <60167be910e14ffd90c81ad404a744e2>:0 
Verse.Log:Error(String, Boolean)
RimThreaded.RimThreaded:ExecuteTicks()
RimThreaded.RimThreaded:ProcessTicks()
RimThreaded.<>c:<CreateWorkerThread>b__128_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()
```

**Mod List**
- A lot of Vannilla extended content
- Alien races
  - Naga
  - harpy
  - androids
  - dragonian 
  - moyo
  - astoriel
  - hisa
- zoom plus
- dubs mint menu
- open the windows
- roads to rin
- git-up mods
- Ticks per second

**Screenshots**

![image](https://user-images.githubusercontent.com/5264383/100290341-dd84e100-2f59-11eb-9dea-76ada5cc04a1.png)

**Comment by thefriendlycacti** [comment]
I ran into this issue as well but with a very different mod list. Here is a link to the issue I submitted with the same error https://github.com/cseelhoff/RimThreaded/issues/279 (idk if I can link these issues any other way)

**Comment by Niilo007** [comment]
please test with the newest version of RT and re open the issue if needed
