### ISSUE TITLE
exception in WorkGiver Train

### ISSUE THREAD

**Issue by thefriendlycacti** [cseelhoff/RimThreaded#300]
**Describe the bug**
This bug is being spammed in log till it gets limited 

**To Reproduce**
not reproducible

**Error Log**
https://gist.github.com/thefriendlycacti/1cf6015636740cf6e7f612b881be4dfc

**Mod List**
https://gist.github.com/thefriendlycacti/100a1eff20f09a80a4a5988b407fabf9

**Comment by Niilo007** [comment]
Test with newest version of RT and re open this issue if needed
