### ISSUE TITLE
seems have compatible issue with Vanilla Achievement Expand

### ISSUE THREAD

**Issue by 136068448** [cseelhoff/RimThreaded#302]
**Describe the bug**
when use both RT and VAE, there will occur a red error and it may cause some affect with performance 

**To Reproduce**
1. active two mods
2. run for a while
3. See error

**Error Log**
https://gist.github.com/136068448/d8872a5c3dfcb05f35849bf1864ef500

**Mod List**
brrainz.harmony
Ludeon.RimWorld
Ludeon.RimWorld.Royalty
vanillaexpanded.achievements
fluffy.modmanager
majorhoff.rimthreaded

**Comment by Niilo007** [comment]
Re open this issue if you still get these errors with the new versions of rimthreaded
