### ISSUE TITLE
a bugs cause bullet in CE no effect and make the pawn can't attack and crash UI

### ISSUE THREAD

**Issue by 136068448** [cseelhoff/RimThreaded#303]
**Describe the bug**
i order ma pawn to attack a animal with a shotgun and animal which has been down stand again and attack may pawn, then may pawn use gun shot it, then RIMHUD crashed and the bullet become useless even it actually hti the animal and my another pawn use a knife to attack but only have an attack until i order she attack again and the knife seems no effect too, also the animal's attack have no affect too, i don't know if it will appear agian in my game but restart game seems fix it, if it occur again i will report it agian in this report
**EDIT**it occur again and i try to remove RT,it resolved, so i think it may caused by some incompatible issue with CE and RT

**Error Log**
https://gist.github.com/136068448/26ce861238b16fb1896f2c7e4a7bc489

**Mod List**
  - brrainz.harmony
  - Ludeon.RimWorld
  - Ludeon.RimWorld.Royalty
  - UnlimitedHugs.HugsLib
  - CETeam.CombatExtended
  - CETeam.CombatExtendedGuns
  - n7huntsman.CombatExtendedWeapons
  - mi.chinesePack.combatExtended
  - Nals.FacialAnimation
  - erdelf.HumanoidAlienRaces
  - RWZH.ChinesePack.HumanoidAlienRaces
  - velc.HatsDisplaySelection
  - OskarPotocki.VanillaFactionsExpanded.Core
  - vanillaexpanded.achievements
  - vanillaexpanded.zh
  - brrainz.achtung
  - RWZH.ChinesePack.achtung
  - brrainz.cameraplus
  - RWZH.ChinesePack.cameraplus
  - void.charactereditor
  - UnlimitedHugs.MapReroll
  - UnlimitedHugs.AllowTool
  - fluffy.colonymanager
  - Vanya.Tools.BlightedAlert
  - razor2.3.AnotherRimworldMod.AutoCutBlight
  - Oblitus.AnimalsLogic
  - GHSGKD.AnimalsLogicZH
  - falconne.BWM
  - sarg.smartspeed
  - fluffy.animaltab
  - fluffy.blueprints
  - fluffy.pharmacist
  - fluffy.relationstab
  - fluffy.worktab
  - fluffy.stuffedfloors
  - fluffy.medicaltab
  - leafzxg.MasterOfCooking
  - leafzxg.MasterOfCrafting
  - automatic.gunplay
  - velc.MineItAll
  - tikubonn.DontBlockDoor
  - Ogliss.Mythos.DiseasesOverhauled
  - DiseasesOverhauled.Chinese
  - Troopersmith1.DeathRattle
  - Dubwise.DubsMintMenus
  - dubwise.dubsmintminimap
  - Katavrik.CrashLanding
  - GHSGKD.DeathRattleZH
  - WiseClock.AC.DaysMatter
  - fluffy.areaunlocker
  - Mlie.LessArbitrarySurgery
  - Mlie.LessStupidRomanceAttempt
  - smashphil.loadinginprogress
  - brrainz.justignoremepassing
  - ChippedChap.BlueprintTotalsTooltip
  - Zephyr.BlueprintTotalsTooltipZh
  - smashphil.carrycapacityfixed
  - Mlie.PickUpAndHaul
  - Jaxe.Bubbles
  - JaxeZH.Bubbles
  - ChinesePackage.ConfigurableMaps
  - configurablemaps.kv.rw
  - Orion.Gastronomy
  - Zephyr.Gastronomyzh
  - jelly.harvestsync
  - 400.ImpassableHChestUdeepHWater
  - reiquard.researchinfo
  - tammybee.predatorhuntalert
  - RWZH.ChinesePack.OgreStack
  - Ogre.OgreStack
  - samo.RareTraits
  - neceros.metaldontburn
  - fed1sPlay.PawnTargetFix
  - com.yayo.raceQuestPawn
  - Ogliss.RescueeJoinsPlus
  - GG.RescueeJoinsPlus
  - Ogliss.WanderJoinsPlus
  - GG.WanderJoinsPlus
  - Vanya.Tools.IncidentPersonStat
  - crlsniper.realisticrooms
  - GHSGKD.realisticroomsZH
  - Mlie.RealDining
  - ONegative.ReworkedTemperatureExtremeEvents
  - dhultgren.smarterconstruction
  - zlj.staticQualityPlus.124
  - tradingspot.kv.rw
  - RWZH.ChinesePack.tradingspot
  - RWZH.ChinesePack.UnlimitedHugs
  - shavius.yayocombat3.zh
  - com.yayo.combat3
  - Linkolas.Stabilize
  - weilbyte.snapout
  - RWZH.ChinesePack.snapout
  - JM.betterTraders
  - com.yayo.BetterJumpPack
  - PeteTimesSix.SimpleSidearms
  - RWZH.ChinesePack.RBSEHC
  - Rah.RBSEHC
  - spoonshortage.ADogSaidAnimalProsthetics
  - sarg.alphaanimals
  - QAQ.QAAAQ
  - weilbyte.nopowerwires
  - Jaxe.RimHUD
  - shouer.chinesepack.RimHUD
  - PeteTimesSix.CompactHediffs
  - Zephyr.CompactHediffsZh
  - Mlie.ExpandedIncidents
  - RWZH.ChinesePack.ExpandedIncidents
  - Mlie.MoEvents
  - RWZH.ChinesePack.MoEvents
  - Ameiro.Animehairs
  - Gloomy.GloomyHairMk2
  - GWhair.noface
  - rimsenal.hair
  - sakama.RoppoiHair
  - RWZH.ChinesePack.VHE
  - Orion.XevaRimhair
  - ChJees.Androids
  - RWZH.ChinesePack.Androids
  - RunneLatki.RabbieRaceMod
  - RWZH.ChinesePack.RabbieRaceMod
  - RunneLatki.RabbieVanillafacepatch
  - Solaris.RatkinRaceMod
  - RWZH.ChinesePack.RatkinRaceMod
  - Solaris.RatkinVanillaFace
  - Daemon976.FacialAnimationplus
  - Nals.DynamicPortraits
  - shavius.alienrbse
  - sulusdacor.james76543.Meltup.AdvancedPowerPlus
  - RWZH.ChinesePack.AdvancedPowerPlus
  - Mlie.RunAndHide
  - zh.WallLight
  - Murmur.WallLight
  - hatena.VoiceroidAsAnimal
  - hatti.qualitybuilder
  - RWZH.ChinesePack.qualitybuilder
  - Mlie.SDBridges
  - NanoCE.GlassLights
  - neceros.plantgrowthsync
  - wit.expandedroofing
  - sarg.alphabiomes
  - QA.QQIJQ
  - dracoix.doormat.r12a
  - factioncontrol.kv.rw
  - Solaris.FurnitureBase
  - RWZH.ChinesePack.FurnitureBase
  - Haplo.Miscellaneous.Endgame
  - rimfridge.kv.rw
  - Albion.SparklingWorlds.Full
  - RWZH.ChinesePack.SparklingWorldsFull
  - GT.Sam.TilledSoil
  - automatic.traderships
  - RWZH.ChinesePack.traderships
  - nephlite.orbitaltradecolumn
  - RWZH.ChinesePack.orbitaltradecolumn
  - VanillaExpanded.VAEAS
  - VanillaExpanded.VAEAU
  - VanillaExpanded.VAEBF
  - VanillaExpanded.VAECD
  - VanillaExpanded.VAED
  - VanillaExpanded.VAEED
  - VanillaExpanded.VAEIS
  - VanillaExpanded.VAETF
  - VanillaExpanded.VAETR
  - VanillaExpanded.VAETS
  - VanillaExpanded.VAET
  - RWZH.ChinesePack.VAE
  - VanillaExpanded.VAPPE
  - VanillaExpanded.VARME
  - VanillaExpanded.VWE
  - VanillaExpanded.VWEQ
  - RWZH.ChinesePack.VWAAE
  - VanillaExpanded.VCEF
  - RWZH.ChinesePack.VCEF
  - VanillaExpanded.VFECore
  - VanillaExpanded.VFEArt
  - VanillaExpanded.VFEFarming
  - VanillaExpanded.VFEMedical
  - VanillaExpanded.VFEProduction
  - VanillaExpanded.VFESecurity
  - VanillaExpanded.VFESpacer
  - RWZH.ChinesePack.VFE
  - akairo.ShibaWanko
  - dismarzero.VGP.VGPVegetableGarden
  - argon.vanillavgarden
  - dismarzero.VGP.VGPGardenFabrics
  - argon.vanillavgardenfab
  - dismarzero.VGP.VGPThreeSistersPlants
  - dismarzero.VGP.VGPMoreVeggies
  - dismarzero.VGP.VGPGardenResources
  - argon.vanillavgardenresources
  - dismarzero.VGP.VGPGardenMedicine
  - dismarzero.VGP.VGPGardenTools
  - shavius.vpe.zh
  - VanillaExpanded.VPlantsE
  - shavius.vbe.zh
  - VanillaExpanded.VBrewE
  - shavius.vce.zh
  - VanillaExpanded.VCookE
  - VanillaExpanded.VCookEStews
  - VanillaExpanded.VCookESushi
  - shavius.vbookse.zh
  - VanillaExpanded.VBooksE
  - OskarPotocki.VanillaFactionsExpanded.MedievalModule
  - RWZH.ChinesePack.MedievalModule
  - OskarPotocki.VanillaFactionsExpanded.SettlersModule
  - RWZH.ChinesePack.SettlersModule
  - shavius.vfeinsectoids.zh
  - OskarPotocki.VFE.Insectoid
  - OskarPotocki.VFE.Vikings
  - RWZH.ChinesePack.Vikings
  - VSE.PerryPersistent
  - RWZH.ChinesePack.PerryPersistent
  - VanillaExpanded.VTEXE
  - RWZH.ChinesePack.VTEXE
  - Mlie.RoadsOfTheRim
  - RWZH.ChinesePack.RoadsOfTheRim
  - Vanya.Polarisbloc.CoreLab
  - Vanya.Polarisbloc.SecurityForce
  - Mlie.MealRadius
  - Harkon.GunNut.Chapter1
  - Harkon.GunNut.Chapter2
  - Harkon.GunNut.Community
  - RWZH.ChinesePack.GunNut
  - TMC.Armory.AssaultRifle.1
  - TMC.Armory.CommunityPack
  - TMC.Armory.Shotguns.1
  - TMC.Armory.Sidearms.1
  - TMC.Armory.SMGs.1
  - TMC.Armory.RF.1
  - TMC.Armory.SW.1
  - TMC.AAM
  - TMC.Armory.SMGs.1.zhcn
  - TMC.Armory.Sidearms.1.zhcn
  - TMC.Armory.AssaultRifle.1.zhcn
  - TMC.Armory.Shotguns.1.chcn
  - TMC.AAM.zhcn
  - TMC.Armory.CE.Patch
  - rimsenal.core
  - rimsenal.EVP
  - rimsenal.federation
  - rimsenal.feral
  - rimsenal.storyteller
  - rimsenal.security
  - RWZH.ChinesePack.rimsenal
  - JPT.SoftWarmBeds
  - RWZH.ChinesePack.JPT
  - NotooShabby.AwesomeInventory
  - AwesomeZH.Inventory
  - notfood.SeedsPlease
  - shadow.spaiomegapatch
  - LingLuo.PrepareCarefully
  - avilmask.CommonSense
  - co.uk.epicguru.whatsthatmod
  - fluffy.modmanager
  - RWZH.ChinesePack.Fluffy
  - majorhoff.rimthreaded

**Comment by cseelhoff** [comment]
I did a lot of CE fixes in 1.1.23. Can you confirm that this is still an issue and reopen if it is? Thanks!

**Comment by 136068448** [comment]
> I did a lot of CE fixes in 1.1.23. Can you confirm that this is still an issue and reopen if it is? Thanks!
in 1.1.27,seems still have a problem with CE when the ammo which have fragment and when the ammo fire the ammo fly to everywhere,will cause a error message and it seems just message,because the fragment and the flying ammo still can kill my pawn
this is the log:https://gist.github.com/136068448/c23ceb3b7acffc3d1d22029278cd7a2a
