### ISSUE TITLE
seems still have some incompatible issue with CE

### ISSUE THREAD

**Issue by 136068448** [cseelhoff/RimThreaded#304]
**Describe the bug**
when the pawn aim or shoot, it will appear a error seems like #247,and it may cause the bugs in#303 

**To Reproduct**
1.active CE AND RT
2.shot something

**Error Log**
https://gist.github.com/136068448/f77da12aeb28fe79acc0f2b800b895fc

**Mod List**
  - brrainz.harmony
  - Ludeon.RimWorld
  - Ludeon.RimWorld.Royalty
  - majorhoff.rimthreaded

**Comment by cseelhoff** [comment]
Fixed in 1.1.23
