### ISSUE TITLE
"RJW" Game is crashing. Unknown caused an Access Violation (0xc0000005) (RJW incompatibility)

### ISSUE THREAD

**Issue by InsideBSI** [cseelhoff/RimThreaded#307]
**Describe the bug**
The game crash after one or two days into a new save. Had this issue on multiple saves. I'm linking the last one below.
The issue does not happens without rimthreaded loaded

**To Reproduce**
1. Import the modlist with rimpy
2. Start the game and load the provided save
3. Wait for a bit
4. The game crash before everybody wakes up (1-3mins depending on simspeed)

**Error Log**
[player.log & error.log](https://gist.github.com/InsideBSI/b24cd98a5fcc88dd78df45efb404f384)

**Mod List**
[RimPy modlist](https://gist.github.com/InsideBSI/2ff6692b1371c75afc2158d267386184)
[Text modlist](https://gist.github.com/InsideBSI/a55aadf253a8f5171237c30f3e35d396)

**Screenshots**
UnityCrashWindow.png

**Save**
[Savefile](https://gist.github.com/InsideBSI/5425ab59237137014037dc3820be861b)

**Comment by cseelhoff** [comment]
It looks like RJW may be causing some issues. Someone else posted similar problems with it earlier I think. Unfortunately the hard unity crash that you experienced did not show much in the error.log. Thank you for including it though. Thank you for including reproducible steps as well. I am looking at some vanilla bugs ATM. Are you able to see if removing RJW fixes the issue, if only to help me narrow it down?

**Comment by InsideBSI** [comment]
Looks like beside making my pawns fuck each others rjw fucked my game as well. Removing it seems to have fixed the issue I had. Thanks for helping me. Have a nice day !
