### ISSUE TITLE
Game Crash (v1.0.6) - Large Mod list - All log files and feedback attached

### ISSUE THREAD

**Issue by ferdinandwinters** [cseelhoff/RimThreaded#31]
This is less of a bug/issue and more feedback. I know it won't be working with all the mods and without crashes for some time, but I wanted to provide feedback and logs in case it helps you find an issue.

#### Modded Game
---------------------

For the modded game TPS was around 300-340 when running at the fastest non-dev speed, this was on a fresh 500x500 map, temperate forest. FPS was 30~. Load order was; Harmony > RimThreaded > Core > Royalty > Everything Else

The game did crash for me after a short while, not sure what the exact cause is but I thought I would send you all the logs and the mod list.

[error.log](https://github.com/cseelhoff/RimThreaded/files/5200415/error.log) 
[Player.log](https://github.com/cseelhoff/RimThreaded/files/5200416/Player.log) 
[crash.dmp.zip](https://github.com/cseelhoff/RimThreaded/files/5200418/crash.zip) 
[modlist.xml.txt](https://github.com/cseelhoff/RimThreaded/files/5200624/modlist.xml.txt)

#### Unmodded Game
---------------------

For the unmodded game, the mod Custom Map Sizes was used to generate the 500x500 map (I don't think that mod should bother anything). Harmony is included as a prerequisite for that mod, and TicksPerSecond to monitor performance. Load order was; Harmony > RimThreaded > Core > Royalty > TicksPerSecond > Custom Map Sizes

The performance was around 760 TPS (I think, it crashed real soon), but I remember it hitting 100% on the fastest vanilla speed. The overall performance on the 500x500 map was fantastic but it did crash. Might have been load order.

The unmodded game threw an error upon saving and quitting to the main menu to install the TicksPerSecond mod. Something about audio.

[unmodded_console_output.txt](https://github.com/cseelhoff/RimThreaded/files/5200551/unmodded_console_output.txt)

Of course, it crashed, so here are the crash logs.

[error.log](https://github.com/cseelhoff/RimThreaded/files/5200587/error.log) 
[Player.log](https://github.com/cseelhoff/RimThreaded/files/5200588/Player.log) 
[crash.dmp.zip](https://github.com/cseelhoff/RimThreaded/files/5200589/crash.zip)

**Comment by cseelhoff** [comment]
This is great! Thank you so much for all of the included detail!

**Comment by cseelhoff** [comment]
Unmodded version should be fixed. Looks like your modded error is a problem with "Replace_Stuff" mod. I am marking this as an enhancement, since the mod author will probably need to adjust their code
