### ISSUE TITLE
an error message occur befor a quest 

### ISSUE THREAD

**Issue by 136068448** [cseelhoff/RimThreaded#312]
**Describe the bug**
when there have a quest, it will appear an error message and will make a lag if you use many mods,but if just vanilla it only have a little affect with performence

**To Reproduce**
1. make a quest in devmenu of just wait game give one
2. See error

**Error Log**
https://gist.github.com/136068448/913084b3f2ee8a2cedc0c33a33628564

**Comment by Niilo007** [comment]
Please try to reproduce this issue with the newest version of RT. if the errors persist, re open this issue
