### ISSUE TITLE
So I wanted to put a lot of pirates vs a lot of city guards and this popped up while the game became very VERY slow

### ISSUE THREAD

**Issue by Starteskash** [cseelhoff/RimThreaded#32]
RimWorld 1.2.2723 rev661
Verse.Log:Message(String, Boolean)
RimWorld.VersionControl:LogVersionNumber()
Verse.Root:CheckGlobalInit()
Verse.Root:Start()
Verse.Root_Entry:Start()

Tried loading mod with the same packageId multiple times: jecrell.jecstools. Ignoring the duplicates.
E:\Steamapps\steamapps\workshop\content\294100\2195729899
E:\Steamapps\steamapps\workshop\content\294100\932008009
Verse.Log:Error(String, Boolean)
Verse.ModLister:TryAddMod(ModMetaData)
Verse.ModLister:RebuildModList()
Verse.Steam.WorkshopItems:RebuildItemsList()
Verse.Steam.WorkshopItems:.cctor()
Verse.ModLister:RebuildModList()
Verse.ModLister:.cctor()
Verse.ModsConfig:.cctor()
Verse.LoadedModManager:InitializeMods()
Verse.LoadedModManager:LoadAllActiveMods()
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.<>c:<Start>b__6_1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

Tried loading mod with the same packageId multiple times: CP.RimmuNation.Clothing. Ignoring the duplicates.
E:\Steamapps\steamapps\workshop\content\294100\2200159709
E:\Steamapps\steamapps\workshop\content\294100\1541536041
Verse.Log:Error(String, Boolean)
Verse.ModLister:TryAddMod(ModMetaData)
Verse.ModLister:RebuildModList()
Verse.Steam.WorkshopItems:RebuildItemsList()
Verse.Steam.WorkshopItems:.cctor()
Verse.ModLister:RebuildModList()
Verse.ModLister:.cctor()
Verse.ModsConfig:.cctor()
Verse.LoadedModManager:InitializeMods()
Verse.LoadedModManager:LoadAllActiveMods()
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.<>c:<Start>b__6_1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

Tried loading mod with the same packageId multiple times: jecrell.jecstools. Ignoring the duplicates.
E:\Steamapps\steamapps\workshop\content\294100\2195729899
E:\Steamapps\steamapps\workshop\content\294100\932008009
Verse.Log:Error(String, Boolean)
Verse.ModLister:TryAddMod(ModMetaData)
Verse.ModLister:RebuildModList()
Verse.ModLister:.cctor()
Verse.ModsConfig:.cctor()
Verse.LoadedModManager:InitializeMods()
Verse.LoadedModManager:LoadAllActiveMods()
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.<>c:<Start>b__6_1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

Tried loading mod with the same packageId multiple times: CP.RimmuNation.Clothing. Ignoring the duplicates.
E:\Steamapps\steamapps\workshop\content\294100\2200159709
E:\Steamapps\steamapps\workshop\content\294100\1541536041
Verse.Log:Error(String, Boolean)
Verse.ModLister:TryAddMod(ModMetaData)
Verse.ModLister:RebuildModList()
Verse.ModLister:.cctor()
Verse.ModsConfig:.cctor()
Verse.LoadedModManager:InitializeMods()
Verse.LoadedModManager:LoadAllActiveMods()
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.<>c:<Start>b__6_1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

Key binding conflict: Dev_ChangeSelectedDebugAction and MainTab_Architect are both bound to Tab.
Verse.Log:Warning(String, Boolean)
Verse.KeyPrefsData:ErrorCheckOn(KeyBindingDef, BindingSlot)
Verse.KeyPrefsData:ErrorCheck()
Verse.KeyPrefs:Init()
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.<>c:<Start>b__6_1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

RimThreaded Harmony is loading...
Verse.Log:Message(String, Boolean)
RimThreaded.RimThreadedHarmony:.cctor()
System.Runtime.CompilerServices.RuntimeHelpers:RunClassConstructor(IntPtr)
System.Runtime.CompilerServices.RuntimeHelpers:RunClassConstructor(RuntimeTypeHandle)
Verse.StaticConstructorOnStartupUtility:CallAll()
Verse.<>c:<DoPlayLoad>b__4_2()
Verse.LongEventHandler:ExecuteToExecuteWhenFinished()
Verse.LongEventHandler:UpdateCurrentAsynchronousEvent()
Verse.LongEventHandler:LongEventsUpdate(Boolean&)
Verse.Root:Update()
Verse.Root_Entry:Update()

RimThreaded patching is complete.
Verse.Log:Message(String, Boolean)
RimThreaded.RimThreadedHarmony:.cctor()
System.Runtime.CompilerServices.RuntimeHelpers:RunClassConstructor(IntPtr)
System.Runtime.CompilerServices.RuntimeHelpers:RunClassConstructor(RuntimeTypeHandle)
Verse.StaticConstructorOnStartupUtility:CallAll()
Verse.<>c:<DoPlayLoad>b__4_2()
Verse.LongEventHandler:ExecuteToExecuteWhenFinished()
Verse.LongEventHandler:UpdateCurrentAsynchronousEvent()
Verse.LongEventHandler:LongEventsUpdate(Boolean&)
Verse.Root:Update()
Verse.Root_Entry:Update()

Initializing new game with mods:
  - brrainz.harmony
  - Ludeon.RimWorld
  - majorhoff.rimthreaded
Verse.Log:Message(String, Boolean)
Verse.Game:InitNewGame()
Verse.<>c:<Start>b__1_2()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

Toni started 10 jobs in one tick. newJob=Clean (Job_1180) jobGiver=RimWorld.JobGiver_Work jobList=(Clean (Job_1165)) (Clean (Job_1166)) (Clean (Job_1167)) (Clean (Job_1168)) (Clean (Job_1169)) (Clean (Job_1170)) (Clean (Job_1172)) (Clean (Job_1174)) (Clean (Job_1176)) (Clean (Job_1178)) (Clean (Job_1180)) 
Verse.Log:Error(String, Boolean)
Verse.AI.JobUtility:TryStartErrorRecoverJob(Pawn, String, Exception, JobDriver)
Verse.AI.Pawn_JobTracker:StartJob(Job, JobCondition, ThinkNode, Boolean, Boolean, ThinkTreeDef, Nullable`1, Boolean, Boolean)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob()
Verse.AI.Pawn_JobTracker:EndCurrentJob(JobCondition, Boolean, Boolean)
Verse.Pawn:Notify_Teleported(Boolean, Boolean)
Verse.AI.Pawn_PathFollower:TryRecoverFromUnwalkablePosition(Boolean)
RimThreaded.GenSpawn_Patch:Spawn(Thing&, Thing, IntVec3, Map, Rot4, WipeMode, Boolean)
Verse.GenSpawn:Verse.GenSpawn.Spawn_Patch1(Thing, IntVec3, Map, Rot4, WipeMode, Boolean)
RimWorld.Designator_Build:DesignateSingleCell(IntVec3)
Verse.Designator:DesignateMultiCell(IEnumerable`1)
Verse.DesignatorManager:ProcessInputEvents()
RimWorld.MapInterface:HandleMapClicks()
RimWorld.UIRoot_Play:UIRootOnGUI()
Verse.Root:OnGUI()

Bailey started 10 jobs in one tick. newJob=Clean (Job_1192) jobGiver=RimWorld.JobGiver_Work jobList=(Clean (Job_1171)) (Clean (Job_1173)) (Clean (Job_1175)) (Clean (Job_1177)) (Clean (Job_1179)) (Clean (Job_1182)) (Clean (Job_1184)) (Clean (Job_1186)) (Clean (Job_1188)) (Clean (Job_1190)) (Clean (Job_1192)) 
Verse.Log:Error(String, Boolean)
Verse.AI.JobUtility:TryStartErrorRecoverJob(Pawn, String, Exception, JobDriver)
Verse.AI.Pawn_JobTracker:StartJob(Job, JobCondition, ThinkNode, Boolean, Boolean, ThinkTreeDef, Nullable`1, Boolean, Boolean)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob()
Verse.AI.Pawn_JobTracker:EndCurrentJob(JobCondition, Boolean, Boolean)
Verse.Pawn:Notify_Teleported(Boolean, Boolean)
Verse.AI.Pawn_PathFollower:TryRecoverFromUnwalkablePosition(Boolean)
RimThreaded.GenSpawn_Patch:Spawn(Thing&, Thing, IntVec3, Map, Rot4, WipeMode, Boolean)
Verse.GenSpawn:Verse.GenSpawn.Spawn_Patch1(Thing, IntVec3, Map, Rot4, WipeMode, Boolean)
RimWorld.Designator_Build:DesignateSingleCell(IntVec3)
Verse.Designator:DesignateMultiCell(IEnumerable`1)
Verse.DesignatorManager:ProcessInputEvents()
RimWorld.MapInterface:HandleMapClicks()
RimWorld.UIRoot_Play:UIRootOnGUI()
Verse.Root:OnGUI()

Toni started 10 jobs in one tick. newJob=Clean (Job_1202) jobGiver=RimWorld.JobGiver_Work jobList=(Wait (Job_1181)) (Clean (Job_1183)) (Clean (Job_1185)) (Clean (Job_1187)) (Clean (Job_1189)) (Clean (Job_1191)) (Clean (Job_1194)) (Clean (Job_1196)) (Clean (Job_1198)) (Clean (Job_1200)) (Clean (Job_1202)) 
Verse.Log:Error(String, Boolean)
Verse.AI.JobUtility:TryStartErrorRecoverJob(Pawn, String, Exception, JobDriver)
Verse.AI.Pawn_JobTracker:StartJob(Job, JobCondition, ThinkNode, Boolean, Boolean, ThinkTreeDef, Nullable`1, Boolean, Boolean)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob()
Verse.AI.Pawn_JobTracker:EndCurrentJob(JobCondition, Boolean, Boolean)
Verse.Pawn:Notify_Teleported(Boolean, Boolean)
Verse.AI.Pawn_PathFollower:TryRecoverFromUnwalkablePosition(Boolean)
RimThreaded.GenSpawn_Patch:Spawn(Thing&, Thing, IntVec3, Map, Rot4, WipeMode, Boolean)
Verse.GenSpawn:Verse.GenSpawn.Spawn_Patch1(Thing, IntVec3, Map, Rot4, WipeMode, Boolean)
RimWorld.Designator_Build:DesignateSingleCell(IntVec3)
Verse.Designator:DesignateMultiCell(IEnumerable`1)
Verse.DesignatorManager:ProcessInputEvents()
RimWorld.MapInterface:HandleMapClicks()
RimWorld.UIRoot_Play:UIRootOnGUI()
Verse.Root:OnGUI()

Bailey started 10 jobs in one tick. newJob=Clean (Job_1214) jobGiver=RimWorld.JobGiver_Work jobList=(Wait (Job_1193)) (Clean (Job_1195)) (Clean (Job_1197)) (Clean (Job_1199)) (Clean (Job_1201)) (Clean (Job_1204)) (Clean (Job_1206)) (Clean (Job_1208)) (Clean (Job_1210)) (Clean (Job_1212)) (Clean (Job_1214)) 
Verse.Log:Error(String, Boolean)
Verse.AI.JobUtility:TryStartErrorRecoverJob(Pawn, String, Exception, JobDriver)
Verse.AI.Pawn_JobTracker:StartJob(Job, JobCondition, ThinkNode, Boolean, Boolean, ThinkTreeDef, Nullable`1, Boolean, Boolean)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob()
Verse.AI.Pawn_JobTracker:EndCurrentJob(JobCondition, Boolean, Boolean)
Verse.Pawn:Notify_Teleported(Boolean, Boolean)
Verse.AI.Pawn_PathFollower:TryRecoverFromUnwalkablePosition(Boolean)
RimThreaded.GenSpawn_Patch:Spawn(Thing&, Thing, IntVec3, Map, Rot4, WipeMode, Boolean)
Verse.GenSpawn:Verse.GenSpawn.Spawn_Patch1(Thing, IntVec3, Map, Rot4, WipeMode, Boolean)
RimWorld.Designator_Build:DesignateSingleCell(IntVec3)
Verse.Designator:DesignateMultiCell(IEnumerable`1)
Verse.DesignatorManager:ProcessInputEvents()
RimWorld.MapInterface:HandleMapClicks()
RimWorld.UIRoot_Play:UIRootOnGUI()
Verse.Root:OnGUI()

Geyser spray sustainer still playing after 1000 ticks. Force-ending.
Verse.Log:Message(String, Boolean)
RimWorld.Building_SteamGeyser:Tick()
RimThreaded.Ticklist_Patch:ProcessTicks()
RimThreaded.<>c:<CreateTickThreads>b__25_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

Thread: 30 did not finish within 1000ms. Restarting thread...
Verse.Log:Error(String, Boolean)
RimThreaded.<>c__DisplayClass25_0:<CreateTickThreads>b__1()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

Detected infinite stat recursion when evaluating Hearing
Verse.Log:Error(String, Boolean)
Verse.PawnCapacitiesHandler:GetLevel(PawnCapacityDef)
Verse.<>c__DisplayClass1_0:<DoClamor>b__1(Region)
RimThreaded.BFSWorker_Patch:BreadthFirstTraverseWork(Region, RegionEntryPredicate, RegionProcessor, Int32, RegionType)
RimThreaded.RegionTraverser_Patch:BreadthFirstTraverse(Region, RegionEntryPredicate, RegionProcessor, Int32, RegionType)
Verse.RegionTraverser:Verse.RegionTraverser.BreadthFirstTraverse_Patch1(Region, RegionEntryPredicate, RegionProcessor, Int32, RegionType)
Verse.GenClamor:DoClamor(Thing, IntVec3, Single, ClamorDef)
Verse.GenClamor:DoClamor(Thing, Single, ClamorDef)
Verse.AI.Pawn_PathFollower:TryEnterNextPathCell()
Verse.AI.Pawn_PathFollower:PatherTick()
Verse.Pawn:Tick()
RimThreaded.Ticklist_Patch:ProcessTicks()
RimThreaded.<>c:<CreateTickThreads>b__25_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

Thread: 31 did not finish within 1000ms. Restarting thread...
Verse.Log:Error(String, Boolean)
RimThreaded.<>c__DisplayClass25_0:<CreateTickThreads>b__1()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

Thread: 25 did not finish within 1000ms. Restarting thread...
Verse.Log:Error(String, Boolean)
RimThreaded.<>c__DisplayClass25_0:<CreateTickThreads>b__1()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

Thread: 22 did not finish within 1000ms. Restarting thread...
Verse.Log:Error(String, Boolean)
RimThreaded.<>c__DisplayClass25_0:<CreateTickThreads>b__1()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

Thread: 34 did not finish within 1000ms. Restarting thread...
Verse.Log:Error(String, Boolean)
RimThreaded.<>c__DisplayClass25_0:<CreateTickThreads>b__1()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

Thread: 28 did not finish within 1000ms. Restarting thread...
Verse.Log:Error(String, Boolean)
RimThreaded.<>c__DisplayClass25_0:<CreateTickThreads>b__1()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

Thread: 29 did not finish within 1000ms. Restarting thread...
Verse.Log:Error(String, Boolean)
RimThreaded.<>c__DisplayClass25_0:<CreateTickThreads>b__1()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

Thread: 32 did not finish within 1000ms. Restarting thread...
Verse.Log:Error(String, Boolean)
RimThreaded.<>c__DisplayClass25_0:<CreateTickThreads>b__1()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

Thread: 37 did not finish within 1000ms. Restarting thread...
Verse.Log:Error(String, Boolean)
RimThreaded.<>c__DisplayClass25_0:<CreateTickThreads>b__1()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

Thread: 38 did not finish within 1000ms. Restarting thread...
Verse.Log:Error(String, Boolean)
RimThreaded.<>c__DisplayClass25_0:<CreateTickThreads>b__1()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

Thread: 24 did not finish within 1000ms. Restarting thread...
Verse.Log:Error(String, Boolean)
RimThreaded.<>c__DisplayClass25_0:<CreateTickThreads>b__1()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

Thread: 35 did not finish within 1000ms. Restarting thread...
Verse.Log:Error(String, Boolean)
RimThreaded.<>c__DisplayClass25_0:<CreateTickThreads>b__1()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

Thread: 39 did not finish within 1000ms. Restarting thread...
Verse.Log:Error(String, Boolean)
RimThreaded.<>c__DisplayClass25_0:<CreateTickThreads>b__1()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

Thread: 36 did not finish within 1000ms. Restarting thread...
Verse.Log:Error(String, Boolean)
RimThreaded.<>c__DisplayClass25_0:<CreateTickThreads>b__1()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

Thread: 43 did not finish within 1000ms. Restarting thread...
Verse.Log:Error(String, Boolean)
RimThreaded.<>c__DisplayClass25_0:<CreateTickThreads>b__1()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

**Comment by Starteskash** [comment]
I do Not have any mods Installed. 
 Load Order
1.Harmony
2.Core
3. Rimthreaded

**Comment by cseelhoff** [comment]
This is very helpful. Were you able to save it and reproduce it when you load the save?

**Comment by Starteskash** [comment]
Oh I'm very sorry I didn't do that. But in another Colony I tried to spawn as many colonists as I could so here is the Crash Log:
[output_log.txt](https://github.com/cseelhoff/RimThreaded/files/5203534/output_log.txt)

**Comment by Natrukei** [comment]
@cseelhoff Can't tell by the logs, but the title seems about right.
