### ISSUE TITLE
Rebooting Game (Like After Changing Mod List or HugsLib QuickRestart) Sometimes Has 2 Instances of Game Running

### ISSUE THREAD

**Issue by maarxx** [cseelhoff/RimThreaded#321]
Rebooting Game (Like After Changing Mod List or HugsLib QuickRestart) Sometimes Has 2 Instances of Game Running

After rebooting game (like changing the mod list or using the hugslib quickrestart button), if you ALT+TAB around, I often (half the time?) find another instance of the game in the background, stuck at "Restarting..."

**Comment by Niilo007** [comment]
This has happened to me before, it happens even without rimthreaded. (Especially with big mod lists)
**so its not a rimthreaded bug.**
(commenting here in case mod devs don't know this and work on a bug that they can't effect or something like that)

**Comment by maarxx** [comment]
I consistently get this with RimThreaded enabled and have never gotten it with RimThreaded disabled, but I admit it could be a number of other factors too.

**Comment by Niilo007** [comment]
If you can get this to happen with just rimthreaded, re open this issue.
