### ISSUE TITLE
[Pure Vanilla + Easily Reproducible] Changing Many (100's) Animals to New Allowed Area Causes Extreme Performance Degradation Into Lockup

### ISSUE THREAD

**Issue by maarxx** [cseelhoff/RimThreaded#322]
### Changing Many (100's) Animals to New Allowed Area Causes Extreme Performance Degradation Into Lockup

![pureVanilla](https://user-images.githubusercontent.com/7416299/100550490-3ef1cc00-3248-11eb-9a54-610cdaa18fa5.png)

#### The Short Version

https://drive.google.com/file/d/1HhLyKeTBTGj21i4Ox5M-pQyquPKpdApQ/view?usp=sharing

1. Download this save file, load it up.
1. Unpause game, observe almost immediate extreme performance degradation into lockup.

#### The Long Version // What This Save Represents // How to Reproduce from Scratch

1. Start a new colony.
1. Pause the game.
1. Spawn many (couple hundred) tamed animals. The fastest way to do this with the dev console is to spam `Do Incident x10 (Map)...` -> `FarmAnimalsWanderIn`. Spam this until you get bored.
1. **Save this game** (lets say `TEST1`).
1. Unpause game, advance time, go ahead and hit DevMode Speed x4, convince yourself performance is still pretty good (I hit 900 ticks easy). The animals will wander towards your colonists / towards the middle, and wander around, unrestricted. Everything is fine.
1. **Load back to** `TEST1`.
1. Now, create a new Allowed Area, it'll be `Area 2` by default, make it a single square near the middle of the map.
1. Open the Animal tab, and change all the animals to `Area 2` allowed area.
1. **Save this game** (let's say `TEST2`).
1. Unpause the game, and observe almost immediate extreme performance degradation into lockup.

#### What we're NOT talking about

**Unrelated to this bug**, _even without Rimthreaded_, once the animals **arrive** at a very small Allowed Area, performance will degrade. This is because they can't Wander very far, so the game is having to constantly give them new Wander jobs, which is a non-constant-time operation to find a good square to wander to. This will degrade with-and-without Rimthreaded, and isn't what we're talking about here. The game depends on long Wander to defer job recalculation, and very small areas are taxing on that.

#### What we ARE talking about

But **before the animals arrive at the Allowed Area**, when they are "Moving" to the new Allowed Area, this is the one time that, _even without Rimthreaded_, vanilla performance actually **improves** for all of these animals, because they are all in the midst of a well-defined job to move to a new location, and don't need to be given new jobs for a while.

Yet **with Rimthreaded**, performance degrades _before even reaching the Allowed Area_, and that's the topic of this bug.

**Comment by bababooeyy** [comment]
Occurs in 1.3.0.7

Played with HugsLib on provided save, not sure if you encountered any errors while the performance degradation occurred, but I did. 

https://gist.github.com/e7e0634f48f353d6e28ceb6e09eb3795

**Comment by bababooeyy** [comment]
Fixed in 1.3.0.8

yay
