### ISSUE TITLE
"Stuffed Floors" have Compatible issue with StuffedFloors mod

### ISSUE THREAD

**Issue by 136068448** [cseelhoff/RimThreaded#326]
**Describe the bug**
When I strat a new game and I found that the strength of first raid is abnormal,usually the first raid will send a nude tribe with club or a pirates with knife,it is a normal 35point raid,but if use buth Stuffed floors and RT,the first raid will send 2-3 tribe with cloth and weapon or 2-3 pirates in a worse case,the pirates will have a simple range weapon.but that shouldn't happend because I use the EdB Prepare Carefully to make my start poing less than 10k, and I found the building wealthy in history tab said i have about the building I total have is worth 20k.then it is easy to find out which cause this,finally I find out is Stuffered Floors,but use the Stuffed Floors or RT separatly will not cause this issue

**To Reproduce**
1. active both Stuffered Floors and RT
2. start a new game
3. click the history tab
4. you can see the building wealth will have about 20k

**Error Log**
NO error log

**Mod List**
- brrainz.harmony
- Ludeon.RimWorld
- Ludeon.RimWorld.Royalty
- fluffy.stuffedfloors
- majorhoff.rimthreaded
- fluffy.modmanager

**Screenshots**
the first raid of pirate only active RT or Stuffed Floors:
![20201130201001_1](https://user-images.githubusercontent.com/74740183/100609162-83fd2780-3348-11eb-92ee-3ddbf3013b1c.jpg)
the weath of building:
![20201130200948_1](https://user-images.githubusercontent.com/74740183/100609204-92e3da00-3348-11eb-84b4-d0a61504112e.jpg)

the first raid of pirate active both RT and Stuffered Floors:
![20201130200821_1](https://user-images.githubusercontent.com/74740183/100609267-adb64e80-3348-11eb-8a3e-c90cf1d1ace3.jpg)
the wealth of building:
![20201130200749_1](https://user-images.githubusercontent.com/74740183/100609289-b9097a00-3348-11eb-89dc-d2b370da859d.jpg)

**Comment by Eldulac** [comment]
**[Tested on RT 1.3.2]**

I tested this issue on several fresh games with RT, and both with or without "Stuffed Floors". I was not able to reproduce the issue, and everything seemed to be working correctly. Depending on the circumstances, the first raider was either armed with a knife or a club. Either naked, or wearing simple clothing.

**Conclusion**
This issue has likely been fixed since the author experienced it, as it is no longer reproducible.
