### ISSUE TITLE
1.1.27 YELLOW&RED

### ISSUE THREAD

**Issue by llin2020** [cseelhoff/RimThreaded#327]
**Describe the bug**
HI，I am Chinese，My English is not good，So I use translation software
I really like your mod，I hope you will continue to work hard and I will cheer you on！

I've adjusted modlist several times
The hunting problem has been reported wrong in your latest versions
Just click hunt，It will stop for a while，And there are red words

Thank you for your hard work，I will always support you

**Error Log**
Link to contents of Player.log or Error.log (Please use something like gist or pastebin. DO NOT PASTE HERE)
[Player.log](https://github.com/cseelhoff/RimThreaded/files/5618131/Player.log)

**Mod List**
Paste contents of ModList used when bug occurred.

**Screenshots**

**Comment by pastorismylord** [comment]
looks like the problem is your modlist. Please take a look at this working modlist: https://github.com/pastorismylord/Community-Modpack/blob/main/Community-modpack-v1.xml
