### ISSUE TITLE
BUG (about raids possibly)

### ISSUE THREAD

**Issue by llin2020** [cseelhoff/RimThreaded#331]
- brrainz.harmony
  - Ludeon.RimWorld
  - Ludeon.RimWorld.Royalty
  - UnlimitedHugs.HugsLib
  - RWZH.ChinesePack.HugsLib
  - fluffy.modmanager
  - majorhoff.rimthreaded

Only these mod 

DEV MOD 10000 point empire and 10000 Centipede
Report mistakes crazily

**Error Log**
[Player.log](https://github.com/cseelhoff/RimThreaded/files/5620909/Player.log)

**Comment by cseelhoff** [comment]
I'm not sure I understand the steps to reproduce. Can you provide a bit more detail?

**Comment by Niilo007** [comment]
If this issue still happens on the new versions of rimthreaded, re open this issue
