### ISSUE TITLE
Elite Bionic Frame work issue

### ISSUE THREAD

**Issue by BadLucKWyvern** [cseelhoff/RimThreaded#334]
**Describe the bug**
Throwing red line in console

**To Reproduce**
 Starting a new game
Attempt to generate world
red line in console 

**Error Log**
[V1024-EBF]  Elite Bionics Framework has detected some mods using the unmodified GetMaxHealth() method, which violates the EBF protocol. The author(s) of the involved mod(s) should adopt the EBF to clarify their intentions.
For now, the unmodified max HP is returned.
The detected mod comes from: RimThreaded
Verse.Log:Verse.Log.Error_Patch1(String, Boolean)
EBF.EliteBionicsFrameworkMain:LogError(String, Boolean)
EBF.Patches.Prefix_BodyPart_GetMaxHealth:PreFix(BodyPartDef, Single, Pawn)
Verse.BodyPartDef:Verse.BodyPartDef.GetMaxHealth_Patch2(BodyPartDef, Pawn)
RimThreaded.PawnCapacityUtility_Patch:CalculatePartEfficiency(Single&, HediffSet, BodyPartRecord, Boolean, List`1)
Verse.PawnCapacityUtility:Verse.PawnCapacityUtility.CalculatePartEfficiency_Patch1(HediffSet, BodyPartRecord, Boolean, List`1)
Verse.PawnCapacityUtility:Verse.PawnCapacityUtility.CalculateTagEfficiency_Patch0(HediffSet, BodyPartTagDef, Single, FloatRange, List`1, Single)
RimWorld.PawnCapacityWorker_Consciousness:CalculateCapacityLevel(HediffSet, List`1)
Verse.PawnCapacityUtility:CalculateCapacityLevel(HediffSet, PawnCapacityDef, List`1, Boolean)
RimThreaded.PawnCapacitiesHandler_Patch:GetLevel(PawnCapacitiesHandler, Single&, PawnCapacityDef)
RimThreaded.PawnCapacitiesHandler_Patch:CapableOf(PawnCapacitiesHandler, Boolean&, PawnCapacityDef)
Verse.PawnCapacitiesHandler:Verse.PawnCapacitiesHandler.CapableOf_Patch1(PawnCapacitiesHandler, PawnCapacityDef)
Verse.Pawn_HealthTracker:ShouldBeDeadFromRequiredCapacity()
Verse.Pawn_HealthTracker:Verse.Pawn_HealthTracker.ShouldBeDead_Patch0(Pawn_HealthTracker)
Verse.Pawn_HealthTracker:CheckPredicateAfterAddingHediff(Hediff, Func`1)
Verse.Pawn_HealthTracker:WouldDieAfterAddingHediff(Hediff)
RimWorld.AgeInjuryUtility:RimWorld.AgeInjuryUtility.GenerateRandomOldAgeInjuries_Patch2(Pawn, Boolean)
Verse.PawnGenerator:Verse.PawnGenerator.GenerateInitialHediffs_Patch3(Pawn, PawnGenerationRequest)
Verse.PawnGenerator:Verse.PawnGenerator.TryGenerateNewPawnInternal_Patch0(PawnGenerationRequest&, String&, Boolean, Boolean)
Verse.PawnGenerator:Verse.PawnGenerator.GenerateNewPawnInternal_Patch1(PawnGenerationRequest&)
Verse.PawnGenerator:GenerateOrRedressPawnInternal(PawnGenerationRequest)
Verse.PawnGenerator:Verse.PawnGenerator.GeneratePawn_Patch4(PawnGenerationRequest)
RimWorld.Faction:TryGenerateNewLeader()
RimWorld.FactionGenerator:NewGeneratedFaction(FactionDef)
RimWorld.FactionGenerator:RimWorld.FactionGenerator.GenerateFactionsIntoWorld_Patch0()
RimWorld.Planet.WorldGenStep_Factions:GenerateFresh(String)
RimWorld.Planet.WorldGenerator:GenerateWorld(Single, String, OverallRainfall, OverallTemperature, OverallPopulation)
RimWorld.Page_CreateWorldParams:<CanDoNext>b__14_0()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

**Mod List**
    <li>arandomkiwi.rimthemes</li>
    <li>brrainz.harmony</li>
    <li>ludeon.rimworld</li>
    <li>automatic.startupimpact</li>
    <li>unlimitedhugs.hugslib</li>
    <li>jecrell.jecstools</li>
    <li>latta.fsharp.core</li>
    <li>fluffy.modmanager</li>
    <li>erdelf.humanoidalienraces</li>
    <li>edb.preparecarefully</li>
    <li>dubwise.dubsperformanceanalyzer</li>
    <li>gguake.ui.simplesearchbar</li>
    <li>albion.goexplore</li>
    <li>brrainz.cameraplus</li>
    <li>krafs.levelup</li>
    <li>arandomkiwi.powerpp</li>
    <li>notfood.outfitted</li>
    <li>uru.keomono.friends.hair</li>
    <li>atamandolinskaja.morecrashedshipparts</li>
    <li>ricofox233.touhoustyle.scarletdevil</li>
    <li>carnysenpai.traitraritycolors</li>
    <li>carnysenpai.rwbyworldofremnant</li>
    <li>roolo.whatthehack</li>
    <li>kikohi.forsakens</li>
    <li>mlie.modcheck</li>
    <li>vanillaexpanded.vfecore</li>
    <li>vanillaexpanded.vfemedical</li>
    <li>zzz.wallvitalsmonitor</li>
    <li>sumghaidubwise.replimat</li>
    <li>cabbage.rimcities</li>
    <li>fluffy.fluffybreakdowns</li>
    <li>daniledman.cyberfauna</li>
    <li>changedresser.kv.rw</li>
    <li>weaponstorage.kv.rw</li>
    <li>infinitestorage.kv.rw</li>
    <li>vanya.polarisbloc.corelab</li>
    <li>vanya.polarisbloc.securityforce</li>
    <li>vanya.polarisbloc.mechenemy</li>
    <li>qx.astramilitarum</li>
    <li>qx.astramilitarum.factions</li>
    <li>automatic.rimlaser</li>
    <li>automatic.gradienthair</li>
    <li>ravvy.amw</li>
    <li>gguake.alliesspot</li>
    <li>unlimitedhugs.allowtool</li>
    <li>sarg.alphabiomes</li>
    <li>ameiro.animehairs</li>
    <li>dylan.animalgear</li>
    <li>dylan.animalgearbasic</li>
    <li>fluffy.animaltab</li>
    <li>com.bymarcin.architecticons</li>
    <li>teok25.archotechexpanded</li>
    <li>razor2.3.anotherrimworldmod.autocutblight</li>
    <li>ben.automaticnightowl</li>
    <li>falconne.aff</li>
    <li>torann.arimworldofmagic</li>
    <li>lingluo.movesteamgeyser</li>
    <li>spoonshortage.adogsaidanimalprosthetics</li>
    <li>brrainz.achtung</li>
    <li>gewen.additionaltraits</li>
    <li>ogliss.admech.armoury</li>
    <li>mlie.advancedbiomes</li>
    <li>madeline.modmismatchformatter</li>
    <li>voult.betterpawncontrol</li>
    <li>v1024.ebframework</li>
    <li>frozensnowfox.vanillabionicsexpansionlegacy</li>
    <li>automatic.bionicicons</li>
    <li>fluffy.blueprints</li>
    <li>bos.milkableanimals</li>
    <li>torann.caravanoptions</li>
    <li>cp.chicken.mitchell.hairstyles</li>
    <li>wgflash55.circleandoval</li>
    <li>navyseal5.cleaningstation</li>
    <li>fluffy.colonymanager</li>
    <li>fluffy.commandpalette</li>
    <li>consolidatedtraits.kv.rw</li>
    <li>zerophoenix.contractorsarsenalfaction</li>
    <li>k.glitternet</li>
    <li>k.cybernet</li>
    <li>kikohi.cybernetic</li>
    <li>mlie.cyberneticwarfare</li>
    <li>caesarv6.damageindicators</li>
    <li>cp.doom</li>
    <li>jecrell.doorsexpanded</li>
    <li>bob.draggablecornerss</li>
    <li>gloomylynx.dragonianoriginal</li>
    <li>onyxae.dragonsdescent</li>
    <li>roolo.dualwield</li>
    <li>leafzxg.thrumboextension</li>
    <li>roolo.giddyupcore</li>
    <li>roolo.giddyupmechanoids</li>
    <li>dubwise.dubsbreakmod</li>
    <li>dubwise.dubsmintmenus</li>
    <li>dubwise.dubsmintminimap</li>
    <li>dubwise.dubspaintshop</li>
    <li>gt.sam.glittertech</li>
    <li>3tes.cgtwaa</li>
    <li>nilchei.dynamicdiplomacy</li>
    <li>ykara.epoe</li>
    <li>wit.expandedroofing</li>
    <li>rh.faction.uac</li>
    <li>mlie.fallouttraits</li>
    <li>wemd.fastmoisturepumps</li>
    <li>ssulunge.bbbodysupport</li>
    <li>mlie.fencesandfloors</li>
    <li>flyfire2002.fieldmedic</li>
    <li>firefoxpdm.rainbeausfishing</li>
    <li>uuugggg.fivesecondrule</li>
    <li>fluffy.followme</li>
    <li>gloomy.gloomyhairmk2</li>
    <li>avilmask.grazinglands</li>
    <li>chuiu.greenworld</li>
    <li>kage.growablemushrooms</li>
    <li>theinfinityiq.halo.forerunner</li>
    <li>theinfinityiq.halo.unsc</li>
    <li>daniledman.hardworkinganimals</li>
    <li>velc.hatsdisplayselection</li>
    <li>jkluch.haultostack</li>
    <li>orion.hospitality</li>
    <li>mlie.humanoidproject</li>
    <li>arandomkiwi.huntforme</li>
    <li>navyseal5.infestationbait</li>
    <li>notfood.infused</li>
    <li>latta.infusion</li>
    <li>paradies.invisiblehats</li>
    <li>arandomkiwi.killforme</li>
    <li>earthyturtle.letstrade</li>
    <li>smashphil.loadinginprogress</li>
    <li>vanya.agent.lolidrophairshop</li>
    <li>lanilor.lootboxes</li>
    <li>mlie.lordoftherimsdwarves</li>
    <li>mlie.lordoftherimselves</li>
    <li>mlie.lordoftherimshobbits</li>
    <li>lingluo.lovelyhairstyle</li>
    <li>leonapp.lslimes</li>
    <li>auxiliusm.luciferiumplus</li>
    <li>ratys.madskills</li>
    <li>uuugggg.mealsonwheels</li>
    <li>flypaste.disassemblyfix</li>
    <li>mlie.mechaniteaugmentation</li>
    <li>horo.mechaniteforge.11</li>
    <li>mlie.mechanoidpower</li>
    <li>spino.mechanoidsextraordinaire</li>
    <li>fluffy.medicaltab</li>
    <li>arandomkiwi.mercenariesforme</li>
    <li>mlie.mercerbackpacks</li>
    <li>bigveech.metalstrader</li>
    <li>haplo.miscellaneous.training</li>
    <li>navyseal5.moreharvestdesignators</li>
    <li>4loris4.morelinkables</li>
    <li>orion.moremechanoids</li>
    <li>moremonstergirls.rw</li>
    <li>moremonstergirls.enhanced.rw</li>
    <li>pinochemicali.moretradeships</li>
    <li>moretraitslots.kv.rw</li>
    <li>paradox.morevanillaturrets</li>
    <li>telkir.tmods.morefloors</li>
    <li>hobtook.mortaraccuracy</li>
    <li>babo.multilopes.multilopes</li>
    <li>nackbladinc.rimhair</li>
    <li>syrchalis.neuter</li>
    <li>babo.neutrolope.neutrolope</li>
    <li>com.yayo.combat3</li>
    <li>unon.noburnmetal</li>
    <li>myfharad.hair.menwomen</li>
    <li>horo.animaltrader.11</li>
    <li>mlie.pickupandhaul</li>
    <li>mlie.plasteelsurgery</li>
    <li>mlie.ponytailiskawaii</li>
    <li>nilchei.powerfulfactionbases</li>
    <li>reiquard.precisetime</li>
    <li>extracting.organs</li>
    <li>erdelf.prisonerransom</li>
    <li>syrchalis.prosthetictable</li>
    <li>pwg.bioweapons</li>
    <li>hatti.qualitybuilder</li>
    <li>hatti.qualitysurgeon</li>
    <li>ogliss.thewhitecrayon.quarry</li>
    <li>rah.rbse</li>
    <li>abraxas.mserevived</li>
    <li>mlie.raideremus</li>
    <li>raiderpedes.velcroboy333</li>
    <li>woolstrand.realruins</li>
    <li>wemd.realisticdarkness</li>
    <li>crlsniper.realisticrooms</li>
    <li>frozensnowfox.filthvanisheswithrainandtime</li>
    <li>twistedpacifist.reasonablecomponents</li>
    <li>automatic.recipeicons</li>
    <li>rearden.rnh</li>
    <li>ethereal.rejuvenate.surgery</li>
    <li>acruid.repairbench</li>
    <li>uuugggg.replacestuff</li>
    <li>notfood.researchpal</li>
    <li>rusticfox.chickenplucker.rr</li>
    <li>tfaivre.richtraders</li>
    <li>kato.rimofmadness.vampires</li>
    <li>mlie.rimofmadnesswerewolves</li>
    <li>uru.seraph.hair</li>
    <li>dubwise.rimatomics</li>
    <li>yoseisan.rimcolle</li>
    <li>rimfridge.kv.rw</li>
    <li>jaxe.rimhud</li>
    <li>mlie.rimquest</li>
    <li>arandomkiwi.rimsaves</li>
    <li>rimsenal.core</li>
    <li>rimsenal.federation</li>
    <li>rimsenal.feral</li>
    <li>rimsenal.hair</li>
    <li>rimsenal.storyteller</li>
    <li>survivalmaster.snake.rimtaserreloaded</li>
    <li>mlie.roadsoftherim</li>
    <li>match.roofsupport</li>
    <li>sakama.roppoihair</li>
    <li>ratys.rtfuse</li>
    <li>ratys.rtsolarflareshield</li>
    <li>roolo.runandgun</li>
    <li>user19990313.runtimegc</li>
    <li>nykot.rpgstyleinventory</li>
    <li>explodoboy.snsambitioncosmic</li>
    <li>roolo.searchanddestroy</li>
    <li>uuugggg.sharetheload</li>
    <li>targhetti.showdrafteesweapon</li>
    <li>showhair.kv.rw</li>
    <li>petetimessix.simplesidearms</li>
    <li>pinochemicali.skilledstonecutting</li>
    <li>sarg.smartspeed</li>
    <li>dhultgren.smarterconstruction</li>
    <li>marvinkosh.sometimesraidsgowrong</li>
    <li>albion.sparklingworlds.full</li>
    <li>spoonshortage.spoonshairmod</li>
    <li>smashphil.neceros.srtsexpanded</li>
    <li>indeed.stackxxl</li>
    <li>earthyturtle.stackablechunks</li>
    <li>sakama.storytellerhair</li>
    <li>auxiliusm.supersoil</li>
    <li>earthyturtle.therocktrade</li>
    <li>mlie.xndtinytweaks</li>
    <li>solaris.torgue</li>
    <li>meow.tradablemeals</li>
    <li>smashphil.dropspot</li>
    <li>timmyliang.tradehelper</li>
    <li>automatic.traderships</li>
    <li>tradingspot.kv.rw</li>
    <li>jelly.transportcargopod</li>
    <li>xeonovadan.turretextensions</li>
    <li>mlie.mechanoidmasterblaster</li>
    <li>hiztaar.optionnal.uscmxenomorphs</li>
    <li>mlie.xndusethatsniperscope</li>
    <li>nephlite.orbitaltradecolumn</li>
    <li>oskarpotocki.vanillafactionsexpanded.core</li>
    <li>vanillaexpanded.vee</li>
    <li>vanillaexpanded.vbookse</li>
    <li>oskarpotocki.vfe.insectoid</li>
    <li>vanillaexpanded.vhe</li>
    <li>phoenix.vanillasolarsheild</li>
    <li>vanillaexpanded.vanillatraitsexpanded</li>
    <li>vanillaexpanded.achievements</li>
    <li>sarg.alphaanimals</li>
    <li>halo.rsf</li>
    <li>mlie.spartanfoundrywarcraft</li>
    <li>mlie.variousspaceshipchunk</li>
    <li>lat.veehair</li>
    <li>dismarzero.vgp.vgpvegetablegarden</li>
    <li>dismarzero.vgp.vgpgardenfabrics</li>
    <li>dismarzero.vgp.vgpgardenmedicine</li>
    <li>dismarzero.vgp.vgpgardenresources</li>
    <li>dismarzero.vgp.vgpgardentools</li>
    <li>dismarzero.vgp.vgpmoreveggies</li>
    <li>dismarzero.vgp.vgpgardengourmet</li>
    <li>dismarzero.vgp.xtratreesandflowers</li>
    <li>murmur.walllight</li>
    <li>mlie.wehadatrader</li>
    <li>bodlosh.weaponstats</li>
    <li>co.uk.epicguru.whatsthatmod</li>
    <li>tammybee.whereismyweapon</li>
    <li>won.hair</li>
    <li>won2.hair</li>
    <li>orion.xevarimhair</li>
    <li>maxzicode.zitools</li>
    <li>zlevels1.1</li>
    <li>brrainz.zombieland</li>
    <li>mlie.holywasher</li>
    <li>sirkota.inventorytab</li>
    <li>revolus.whatsmissing</li>
    <li>trp.wealthytraders</li>
    <li>revolus.textilestats</li>
    <li>verdecaelum.sfpcore</li>
    <li>faryzal2020.dmctexpatch</li>
    <li>faryzal2020.dmc</li>
    <li>kure.arom</li>
    <li>roskii.callistans</li>
    <li>roskii.astoriel</li>
    <li>crashm.colorcodedmoodbar.11</li>
    <li>majorhoff.rimthreaded</li>

**Screenshots**

**Comment by Niilo007** [comment]
does not seem like a rimthreaded issue. plase see if the error occurs without rim threaded & try the newest version. you can re open this issue if the issue only happens when RimThreaded is active.
