### ISSUE TITLE
1.1.31 BUG

### ISSUE THREAD

**Issue by llin2020** [cseelhoff/RimThreaded#339]
- brrainz.harmony
  - Ludeon.RimWorld
  - Ludeon.RimWorld.Royalty
  - UnlimitedHugs.HugsLib
  - RWZH.ChinesePack.HugsLib
  - fluffy.modmanager
  - majorhoff.rimthreaded

Only these mod 

DEV MOD 10000 point empire and 10000 Centipede

Compared with the previous version, 1.1.31 still bug, but the game frame number is normal, thank you for your efforts!

**Error Log**
[Player.log](https://github.com/cseelhoff/RimThreaded/files/5634615/Player.log)

**Comment by cseelhoff** [comment]
Likely fixed at least 3 of the errors from your log. Will be in version 1.1.32. Closing bug. Please reopen if issue persists after updating to 1.1.32 or later
