### ISSUE TITLE
Bug with the mod: Turn it off and on 

### ISSUE THREAD

**Issue by GerryWildermuth** [cseelhoff/RimThreaded#340]
**Describe the bug**
Ones a electric device got used the mod throws an error and further actions with this device dosn`t work.

**To Reproduce**
1. Start a game use an electric device
2. un use the device and use again
3. Error occurs 

**Error Log**
https://gist.github.com/GerryWildermuth/0e87552f4e4c1246e39c2459ad40fe2d

**Mod List**
Version: 1
Name: ThreadedRimworldListe
Mods:
- Id: brrainz.harmony_copy_1
  Name: Harmony
- Id: ludeon.rimworld
  Name: Core
- Id: majorhoff.rimthreaded_copy
  Name: RimThreaded [1.2]
- Id: unlimitedhugs.hugslib_copy
  Name: HugsLib
- Id: fluffy.modmanager_copy
  Name: Mod Manager
- Id: razor2.3.anotherrimworldmod.autocutblight_copy
  Name: Auto-Cut Blight
- Id: meltup.beautifuloutdoors_copy
  Name: Beautiful Outdoors
- Id: falconne.bwm_copy
  Name: Better Workbench Management
- Id: uuugggg.buildfrominventory_copy
  Name: Build From Inventory
- Id: dhultgren.changecaravanloadout
  Name: Change Caravan Loadout
- Id: unlimitedhugs.defensivepositions_copy
  Name: Defensive Positions
- Id: bob.draggablecornerss_copy
  Name: '[1.1]DraggableCorners'
- Id: dubwise.dubsmintmenus
  Name: Dubs Mint Menus
- Id: edb.preparecarefully_copy
  Name: EdB Prepare Carefully
- Id: uuugggg.everybodygetsone_copy
  Name: Everybody Gets One
- Id: crlsniper.realisticrooms_copy
  Name: Realistic Rooms
- Id: frozensnowfox.filthvanisheswithrainandtime_copy
  Name: '[FSF] Filth Vanishes With Rain And Time'
- Id: roolo.giddyupcore_copy
  Name: Giddy-up! Core
- Id: roolo.giddyupbattlemounts_copy
  Name: Giddy-up! Battle Mounts
- Id: roolo.giddyupcaravan_copy
  Name: Giddy-up! Caravan
- Id: roolo.giddyuprideandroll_copy
  Name: Giddy-up! Ride and Roll
- Id: mlie.iclearlyhaveenough_copy
  Name: I Clearly Have Enough! (Continued)
- Id: jaxe.bubbles_copy
  Name: Interaction Bubbles
- Id: smashphil.loadinginprogress
  Name: Loading In Progress
- Id: unlimitedhugs.mapreroll_copy
  Name: Map Reroll
- Id: notfood.mendandrecycle_copy
  Name: MendAndRecycle
- Id: avilmask.microdesignations_copy
  Name: Micro Designations
- Id: haplo.miscellaneous.training_copy
  Name: Misc. Training
- Id: name.krypt.rimworld.moddiff_copy
  Name: ModDiff
- Id: sdknm2.qualityofbuilding_copy
  Name: Quality Of Building
- Id: longwater.smartstockpilecreation_copy
  Name: Quick Stockpile Creation
- Id: automatic.recipeicons_copy
  Name: Recipe icons
- Id: notfood.researchpal_copy
  Name: ResearchPal
- Id: rimfridge.kv.rw_copy
  Name: '[KV] RimFridge'
- Id: jaxe.rimhud_copy
  Name: RimHUD
- Id: bodlosh.weaponstats_copy
  Name: WeaponStats
- Id: murmur.walllight_copy
  Name: Wall Light
- Id: ogliss.toastehs.veinminer_copy
  Name: Veinminer R1.1
- Id: uuugggg.usebedrolls_copy
  Name: Use Bedrolls
- Id: ryder.turnitonoff_copy
  Name: Turn It On and Off
- Id: targhetti.transportdownedpawns_copy
  Name: Transport Downed Pawns
- Id: carnysenpai.traitraritycolors_copy
  Name: Trait Rarity Colors
- Id: tradingspot.kv.rw_copy
  Name: '[KV] Trading Spot'
- Id: uuugggg.stockpileranking_copy
  Name: Stockpile Ranking
- Id: linkolas.stabilize_copy
  Name: Stabilize
- Id: mlie.simplymorebridges_copy
  Name: Simply More Bridges (Continued)
- Id: pinochemicali.skilledstonecutting_copy
  Name: Skilled Stonecutting
- Id: mlie.simplestockpilepresets_copy
  Name: Simple Stockpile Presets (Continued)
- Id: erdelf.showmoddesignators_copy
  Name: ShowModDesignators
- Id: nykot.rpgstyleinventory_copy
  Name: Sandy's RPG Style Inventory [1.2]
- Id: yrtwof.rimpedia
  Name: Rimpedia
- Id: oblitus.animalslogic_copy
  Name: Animals Logic
- Id: neceros.badcanbegood_copy
  Name: Bad Can Be Good
- Id: voult.betterpawncontrol_copy
  Name: Better Pawn Control
- Id: crashm.colorcodedmoodbar.11_copy
  Name: Colour Coded Mood Bar - V's Lightweight Edit
- Id: caesarv6.damageindicators_copy
  Name: Damage Indicators [1.2]
- Id: jecrell.doorsexpanded
  Name: Doors Expanded (Dev)
- Id: dubwise.dubsmintminimap_copy
  Name: Dubs Mint Minimap
- Id: rikiki.fishindustry_copy
  Name: FishIndustry
- Id: falconne.heatmap_copy
  Name: Heat Map
- Id: dhultgren.keepbedownership_copy
  Name: Keep Bed Ownership
- Id: krafs.levelup_copy
  Name: Level Up!
- Id: fluffy.medicaltab_copy
  Name: Medical Tab
- Id: zyxabacab.nosympathyforprisoners_copy
  Name: No Sympathy for Prisoners
- Id: peppsen.pmusic_copy_1
  Name: P-Music
- Id: pausbrak.rangeddps_copy
  Name: Ranged DPS
- Id: com.yayo.racequestpawn_copy
  Name: Real Faction Guest
- Id: mlie.rimquest_copy
  Name: RimQuest (Continued)
- Id: targhetti.showdrafteesweapon_copy
  Name: Show Draftees Weapon
- Id: fluffy.worktab_copy
  Name: Work Tab
- Id: vanillaexpanded.vwe_copy
  Name: Vanilla Weapons Expanded
- Id: vanillaexpanded.vfeproduction_copy
  Name: Vanilla Furniture Expanded - Production
- Id: vanillaexpanded.vfepower_copy
  Name: Vanilla Furniture Expanded - Power
- Id: vanillaexpanded.vfemedical_copy
  Name: Vanilla Furniture Expanded - Medical Module
- Id: vanillaexpanded.vfefarming_copy
  Name: Vanilla Furniture Expanded - Farming
- Id: vanillaexpanded.vfecore_copy
  Name: Vanilla Furniture Expanded
- Id: vanillaexpanded.varme_copy
  Name: Vanilla Armour Expanded
- Id: gt.sam.tilledsoil_copy
  Name: Tilled Soil
- Id: dhultgren.smarterconstruction_copy
  Name: Smarter Construction
- Id: brrainz.rangefinder
  Name: Range Finder
- Id: mlie.pickupandhaul_copy
  Name: Pick Up And Haul (Continued)
- Id: sarg.smartspeed_copy
  Name: Smart Speed

**Comment by iViscosity** [comment]
I also have an issue with this mod, but I don't get that error. I get:

```
Exception in JobDriver tick for pawn Ironhead driver=JobDriver_DoBill (toilIndex=24) driver.job=(DoBill (Job_786902) A=Thing_ElectricStove534844 B=Thing_RawRice590458 C=(163, 0, 72))
System.Threading.ThreadAbortException
  at System.Collections.Generic.HashSet`1[T].AddIfNotPresent (T value) [0x00064] in <351e49e2a5bf4fd6beabb458ce2255f3>:0 
  at System.Collections.Generic.HashSet`1[T].Add (T item) [0x00000] in <351e49e2a5bf4fd6beabb458ce2255f3>:0 
  at TurnItOnandOff.TurnItOnandOff.AddBuildingUsed (Verse.Building building) [0x00000] in <3db2d1527d214478a71e9d3af2de1692>:0 
  at TurnItOnandOff.Building_WorkTable_UsedThisTick_Patch.UsedThisTick (RimWorld.Building_WorkTable __instance) [0x00000] in <3db2d1527d214478a71e9d3af2de1692>:0 
  at (wrapper dynamic-method) RimWorld.Building_WorkTable.RimWorld.Building_WorkTable.UsedThisTick_Patch1(RimWorld.Building_WorkTable)
  at RimWorld.Building_WorkTable_HeatPush.UsedThisTick () [0x00000] in <d72310b4d8f64d25aee502792b58549f>:0 
  at Verse.AI.Toils_Recipe+<>c__DisplayClass2_0.<DoRecipeWork>b__1 () [0x0009d] in <d72310b4d8f64d25aee502792b58549f>:0 
  at RimThreaded.JobDriver_Patch.DriverTick (Verse.AI.JobDriver __instance) [0x00318] in <46b1a8cab7904d27b8d8cd700a52845b>:0 
Verse.Log:Warning(String, Boolean)
Verse.AI.JobUtility:Verse.AI.JobUtility.TryStartErrorRecoverJob_Patch1(Pawn, String, Exception, JobDriver)
RimThreaded.JobDriver_Patch:DriverTick(JobDriver)
Verse.AI.JobDriver:Verse.AI.JobDriver.DriverTick_Patch1(JobDriver)
Verse.AI.Pawn_JobTracker:JobTrackerTick()
Verse.Pawn:Verse.Pawn.Tick_Patch2(Pawn)
RimThreaded.RimThreaded:ExecuteTicks()
RimThreaded.RimThreaded:ProcessTicks()
RimThreaded.<>c:<CreateWorkerThread>b__88_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()
```


Just causes lag spikes (thread stops responding) almost every time they try to cook.
