### ISSUE TITLE
Wall building region bug (pawns stuck) (null region)

### ISSUE THREAD

**Issue by Niilo007** [cseelhoff/RimThreaded#348]
**Describe the bug**
Pawns who are building rooms or walls sometimes (often) get stuck and it has something to do with regions

**To Reproduce**
1. Use mod list
2. Play normally
3. build buildings / rooms / walls
4. Pawns that were building said wall get stuck
5. if it doesn't happen right away build more walls

**Error Log**
https://gist.github.com/Niilo007/0155fa6dd2189006920a64e4335c6bfd

**Mod List**
brrainz.harmony
Mlie.ModCheck
MalteSchulze.RIMMSAssemble
Ludeon.RimWorld
Ludeon.RimWorld.Royalty
UnlimitedHugs.HugsLib
fluffy.modmanager
Madeline.ModMismatchFormatter
erdelf.HumanoidAlienRaces
EdB.PrepareCarefully
Nif.ToolBox
OskarPotocki.VanillaFactionsExpanded.Core
roolo.whatthehack
roolo.giddyupcore
roolo.giddyupbattlemounts
roolo.giddyupcaravan
roolo.giddyuprideandroll
roolo.giddyupmechanoids
UnlimitedHugs.MapReroll
madarauchiha.custommapsizes
Cabbage.RimCities
Woolstrand.RealRuins
moretraitslots.kv.rw
consolidatedtraits.kv.rw
VanillaExpanded.VanillaTraitsExpanded
DimonSever000.BackstoriesPlus.Specific
ChJees.Androids
syrchalis.scarremoval
Troopersmith1.DeathRattle
kongmd.qee
Troopersmith1.LifeSupport
Mlie.MedicalSupplements
MSE2.Core
spoonshortage.ADogSaidAnimalProsthetics
PeteTimesSix.SimpleSidearms
Bar0th.NoRandomRelations
Mlie.Wildfire
Mlie.BrrandPhew
falconne.AFF
Uuugggg.UseBedrolls
Uuugggg.MealsOnWheels
Uuugggg.BuildFromInventory
dhultgren.smarterconstruction
Mlie.BillysImprovedCaravanFormation
brrainz.achtung
brrainz.cameraplus
Undone.IgniteEverything
sirrandoo.wmb
hobtook.mortaraccuracy
EB.BetterCrashedShipParts
syrchalis.setupcamp
marvinkosh.ughyougotme
DarthSergeant.NurseJob
Shotgunfrenzy.PriorityTreatment
eagle0600.dressPatients
Mlie.LessArbitrarySurgery
ONegative.ReworkedTemperatureExtremeEvents
GHXX.TechAdvancing
Peppsen.PMusic
bishop.music
dontstopthemusic.kv.rw
notfood.FrameRateControl
Bar0th.PFC
Dubwise.DubsBreakMod
weilbyte.snapout
SF.Grim.Reality
com.yayo.suppression
dninemfive.d9framework
erdelf.MinifyEverything
dhultgren.useminifiedbuildings
FrozenSnowFox.FilthVanishesWithRainAndTime
roolo.RunAndGun
Mlie.RaidersNeverDie
neceros.badcanbegood
PinoChemicali.SkilledStonecutting
Doug.NoJobAuthors
ETRT.RoomSize
VanillaExpanded.VEE
avius.locks
showhair.kv.rw
adjustabletradeships.kv.rw
aRandomKiwi.HuntForMe
toywalrus.itemrequests
fluffy.fluffybreakdowns
Nandonalt.SnowyTrees
telefonmast.graphicssettings
automatic.bionicicons
com.bymarcin.ArchitectIcons
proxyer.optionalicons4ai
erdelf.PowerIndicators
Bichang.MoreSculpture
com.github.alandariva.moreplanning
Bar0th.NoDebris
Mlie.RoadsOfTheRim
wastelandr.BetterRoads
Uuugggg.SafelyHiddenAway
fluffy.relationstab
notfood.ResearchPal
fluffy.animaltab
fluffy.worktab
fluffy.pharmacist
Mlie.DrugResponse
Mlie.DrugPolicyFix
Mlie.ImmunitiesReset
Mehni.Misc.Modifications
tammybee.colonisthistory
gguake.areaninclusionexclusion
smashphil.loadinginprogress
UnlimitedHugs.DefensivePositions
UnlimitedHugs.AllowTool
Mlie.BestMix
razor2.3.AnotherRimworldMod.AutoCutBlight
fluffy.blueprints
savestoragesettings.kv.rw
tammybee.selectablesculpturegraphic
hatti.qualitybuilder
TheWireLord354.ConduitDeconstruct
falconne.HeatMap
weilbyte.renamecolony
automatic.recipeicons
CrashM.ColorCodedMoodBar.11
SaucyPigeon.PawnBadge
LadyElizabeth.Snake.MiscJobRanks
targhetti.ShowDrafteesWeapon
diddily.poweralerts
Mlie.FoodAlert
Mlie.BetterMessagePlacement
Storage.Search.RSA
gguake.ui.armorinfo
Jaxe.Bubbles
Jaxe.Reorderer
Krafs.LevelUp
erdelf.ShowModDesignators
automatic.autolinks
PeteTimesSix.CompactHediffs
Nykot.RPGStyleInventory
Wemd.PartiallyPassableWindTurbines
com.prostheticnomissingbodyparts.rimworld.mod
Uuugggg.ThickArmor
Supes.AutoSeller.Core
fluffy.colonymanager
Dubwise.DubsPaintShop
Saakra.Empire
kentington.saveourship2
ratys.rtfuse
ratys.rtpowerswitch
ratys.rtsolarflareshield
Phoenix.VanillaSolarSheild
Supes.PowerLogic.Core
wit.expandedroofing
Mlie.SignsAndMemorials
essecoisa.FlooredYASTO
fluffy.stuffedfloors
smashphil.dropspot
tradingspot.kv.rw
rimfridge.kv.rw
LWM.DeepStorage
Mlie.PickUpAndHaul
Mlie.StockpileStackLimit
Nif.ArchitectExpanded.Fences
4loris4.MoreLinkables
VanillaExpanded.VFECore
VanillaExpanded.VFEMedical
VanillaExpanded.VFESecurity
VanillaExpanded.VFEProduction
VanillaExpanded.VFESpacer
VanillaExpanded.VFEPropsandDecor
Mlie.XNDTinyTweaks
VanillaExpanded.VCEF
VanillaExpanded.VBooksE
Supes.ParallelPowerGrid
Murmur.SubsurfaceConduit
Murmur.WallLight
Smuffle.HarvestOrgansPostMortem
GT.Sam.TilledSoil
Jaxxa.ED.Embrasures
cucumpear.curtains
neceros.simpleturrets
SpessCarp.CommercialServer
Linkolas.ProgrammableVents
DoctorVanGogh.MiningShaft
Ogliss.TheWhiteCrayon.Quarry
Mlie.FireExtinguisher
Mlie.FireWarden
kikohi.TamingArtifact
helldragger.combattrainingforked
Janson.WeaponTech11
Flyfire2002.FieldMedic
VanillaExpanded.VAPPE
VanillaExpanded.VPlantsE
Oreno.VPlantsE.NoTilledSoil
VanillaExpanded.VAEBF
machine.betterinfestations
VanillaExpanded.VTEXE
codyspring.vtexeme
Ogre.OgreStack
neceros.ninetyninepercent
majorhoff.rimthreaded

**Screenshots**
NA

**Comment by Niilo007** [comment]
https://gist.github.com/040869931e503506ad48527c5517d037

here is another log

**Comment by Niilo007** [comment]
https://gist.github.com/Niilo007/f94e7d92dd0032a2215e39e7e851e6ad
and another player log in case it helps

**Comment by Niilo007** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=218777043

Here is a link to mods that i use. its not quite up to date but it should have most if not all the mods that i have active.
So if someone needs to do some testing with the same mods, this should help do that

**Comment by Niilo007** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2311892294
Screenshot of 2 pawns stuck in a freezer with split regions (where they are standing there is 5C and to the left its -9C

**Comment by kertiek** [comment]
i think this bug was targeted in 1.2.4 and if it was possible to be replicated, it would have happened when i was testing 1.2.5_preview last night

the only region error i was able to get was:


![unknown](https://user-images.githubusercontent.com/21158056/105914990-ec494c00-600d-11eb-9b02-8dd57c7f2f1d.png)

this save is ready to reproduce the current pathing issue , just let it play out at max speed until they finish building inside the mountain.

[vanilla_rt_test_3-preregionnull (1).zip](https://github.com/cseelhoff/RimThreaded/files/5876561/vanilla_rt_test_3-preregionnull.1.zip)

**Comment by Niilo007** [comment]
issue seems to have been fixed in this version: 1.2.6 v2.
