### ISSUE TITLE
`null` pawn faction job error

### ISSUE THREAD

**Issue by ZzZombo** [cseelhoff/RimThreaded#350]
**Describe the bug**
It seems a particular prisoner slave, an *independent* Combine soldier from Half-Rim 2, has an issue when he goes to work. It happens infrequently without this mod, but VERY often with RT, to the point I can barely close the debug output window but it already popped back with this error in the log. I looked at the slave using Character Editor, and the slave doesn't have any valid faction set, I guess that's what trips the game somehow; another _tribal_ slave captured earlier has been working as expected ever since, it's only once the second slave has started to perform any work this error came into existence.

**To Reproduce**
1. Capture an independent outsider. Mine came from a trader ship crash, I believe it's an event from Crash Landing or Vanilla Events Expanded.
2. With Prisoner Labour, set it to work. You might wanna fully heal him first.
3. Wait for errors.

**Error Log**
Unfortunately the error log isn't full as doesn't contain this particular error among some other messages for some reason (another RT bug?), but I managed to save a copy from the debug output of this error regardless:
<details>
<summary>Details</summary>
```
Called SpawnedPawnsInFaction with null faction.
Verse.Log:Error(String, Boolean)
Verse.MapPawns:SpawnedPawnsInFaction(Faction)
RimWorld.WorkGiver_RescueDowned:ShouldSkip(Pawn, Boolean)
PrisonLabor.Core.AI.JobGivers.JobGiver_Labor:PawnCanUseWorkGiver(Pawn, WorkGiver)
PrisonLabor.Core.AI.JobGivers.JobGiver_Labor:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Conditional:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_SubtreesByTag:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.DetermineNextJob_Patch5(Pawn_JobTracker, ThinkTreeDef&)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob()
Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.EndCurrentJob_Patch2(Pawn_JobTracker, JobCondition, Boolean, Boolean)
Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.JobTrackerTick_Patch1(Pawn_JobTracker)
Verse.Pawn:Verse.Pawn.Tick_Patch6(Pawn)
DTimeControl.TCTickList:TickThing(Thing)
DTimeControl.TCTickList:DoTick(Double, Boolean)
DTimeControl.TimeControlBase:TickManagerTick(TickManager, Boolean)
DTimeControl.Core_Patches.Patch_DoSingleTick_Prefix:Prefix(TickManager)
Verse.TickManager:Verse.TickManager.DoSingleTick_Patch3(TickManager)
Verse.TickManager:TickManagerUpdate()
Verse.Game:Verse.Game.UpdatePlay_Patch3(Game)
Verse.Root_Play:Update()
```
</details>

**Mod List**
https://gistpreview.github.io/?cb4de4e4964acb3e8aa833b00c17f5f9.

**Comment by Niilo007** [comment]
Please test with the new rim threaded versions

**Comment by Niilo007** [comment]
Re open this issue if you still experience the bug
