### ISSUE TITLE
Incompatible with mod Shield Generators by Frontier Developments

### ISSUE THREAD

**Issue by RedRayn** [cseelhoff/RimThreaded#351]
**Describe the bug**
RimThreaded is Incompatible with mod called 'Shield Generators by Frontier Developments':
https://steamcommunity.com/sharedfiles/filedetails/?id=1210535987
Why i ask to fix it? This mod is the best 'shield' mod and it is integrated to dub's hygiene, that makes it even more interesting. 

**To Reproduce**
Just activate both mods and it will show that its Incompatible with red triangle. 

**Error Log**
After exiting from the game to menu it crashes the game. 

**Mod List**
Core, Royality, RimtThreaded and Shield Generators by Frontier Developments

**Screenshots**
Obvious

**Comment by Niilo007** [comment]
1. Have you actually tested it in game? 2. does it give errors? 3. does it work? 
if 1. yes 2. yes & 3. no
re open this issue

PS: dubs bad hygiene seems to cause the unity crash
