### ISSUE TITLE
Corrupted Quest and Reduced Performance Following

### ISSUE THREAD

**Issue by LeninsCat** [cseelhoff/RimThreaded#362]
**Describe the bug**
A corrupted quest pops up on the side and has all of the fill-ins not filled in, instead has the "pawn_name" and others as such. It also reduces performance afterwards. (Something that happened at the same time is that getting a HugsLib log crashed my game.) Doesn't happen all the time and quests come in normally most of the time.

**To Reproduce**
Steps to reproduce the behaviour:
I really do not know, I'll go off on a limb and say get a pawn join quest because that always seems to be my problem.

**Error Log**
[Player (2).log](https://github.com/cseelhoff/RimThreaded/files/5669145/Player.2.log)

**Mod List**
[Mod list length: 173]
Harmony [https://steamcommunity.com/sharedfiles/filedetails/?id=2009463077]
BetterLoading [https://steamcommunity.com/sharedfiles/filedetails/?id=1999454301]
Core [https:// no link (local mod)]
Royalty [Official DLC] [https:// no link (local mod)]
SRTS Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1845423808]
HugsLib [https://steamcommunity.com/sharedfiles/filedetails/?id=818773962]
Save Our Ship 2 [https://steamcommunity.com/sharedfiles/filedetails/?id=1909914131]
D9 Framework [https://steamcommunity.com/sharedfiles/filedetails/?id=2037445541]
RimSaves [https://steamcommunity.com/sharedfiles/filedetails/?id=1713367505]
RimHUD [https://steamcommunity.com/sharedfiles/filedetails/?id=1508850027]
Rimocracy [https://steamcommunity.com/sharedfiles/filedetails/?id=2159080853]
RimCore [https:// no link (local mod)]
RimPy Mod Manager Database [https://steamcommunity.com/sharedfiles/filedetails/?id=1847679158]
Rimpedia [https://steamcommunity.com/sharedfiles/filedetails/?id=2145524536]
Vanilla Expanded Framework [https://steamcommunity.com/sharedfiles/filedetails/?id=2023507013]
[TRAHS]Framework [https://steamcommunity.com/sharedfiles/filedetails/?id=2251954192]
Mod Manager [https://steamcommunity.com/sharedfiles/filedetails/?id=1507748539]
Realistic Planets - Fan Update [https://steamcommunity.com/sharedfiles/filedetails/?id=2009542732]
More Vanilla Biomes [https://steamcommunity.com/sharedfiles/filedetails/?id=1931453053]
Vanilla Traits Expanded [https:// no link (local mod)]
Elite Bionics Framework [https://steamcommunity.com/sharedfiles/filedetails/?id=1665403571]
War Crimes Expanded 2 Core [https://steamcommunity.com/sharedfiles/filedetails/?id=2059450213]
Prostheses+ [https://steamcommunity.com/sharedfiles/filedetails/?id=2211789855]
Prostheses+ (Faction Addon) [https://steamcommunity.com/sharedfiles/filedetails/?id=2226643321]
A Dog Said... Animal Prosthetics [https://steamcommunity.com/sharedfiles/filedetails/?id=746425621]
LBE's A Dog Said Easy Patcher [https://steamcommunity.com/sharedfiles/filedetails/?id=944381237]
Combat Extended [https://steamcommunity.com/sharedfiles/filedetails/?id=1631756268]
Medical System Expansion 2 [https://steamcommunity.com/sharedfiles/filedetails/?id=2056706586]
Combat Extended Fixes [https://steamcommunity.com/sharedfiles/filedetails/?id=1776175645]
Mechanoid Nerf for Combat Extended [https://steamcommunity.com/sharedfiles/filedetails/?id=1820420747]
Chemical Distilling for Combat Extended [https://steamcommunity.com/sharedfiles/filedetails/?id=1701823638]
Combat Effects for Combat Extended (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2172612733]
Science Never Stops: Ambition of the Cosmic [https://steamcommunity.com/sharedfiles/filedetails/?id=1802857253]
SNS AOTC: Combat Extended Patch [https:// no link (local mod)]
DocPawnOverhaul [https://steamcommunity.com/sharedfiles/filedetails/?id=1975381493]
Tinker's Construct [https://steamcommunity.com/sharedfiles/filedetails/?id=1888512221]
Killfeed [https://steamcommunity.com/sharedfiles/filedetails/?id=1362098265]
ModDiff [https://steamcommunity.com/sharedfiles/filedetails/?id=2200054867]
Gunplay [https://steamcommunity.com/sharedfiles/filedetails/?id=2034896549]
Camera+ [https://steamcommunity.com/sharedfiles/filedetails/?id=867467808]
Achtung! [https://steamcommunity.com/sharedfiles/filedetails/?id=730936602]
Snap Out! [https://steamcommunity.com/sharedfiles/filedetails/?id=1319782555]
Diseases+ [https://steamcommunity.com/sharedfiles/filedetails/?id=2256624398]
Auto links [https://steamcommunity.com/sharedfiles/filedetails/?id=2059389912]
99 Percent [https://steamcommunity.com/sharedfiles/filedetails/?id=1267149586]
Mad Skills [https://steamcommunity.com/sharedfiles/filedetails/?id=731111514]
Pharmacist [https://steamcommunity.com/sharedfiles/filedetails/?id=1365242717]
More Steel [https://steamcommunity.com/sharedfiles/filedetails/?id=1245219876]
Allow Tool [https://steamcommunity.com/sharedfiles/filedetails/?id=761421485]
ResearchPal [https://steamcommunity.com/sharedfiles/filedetails/?id=946390822]
Bionic icons [https://steamcommunity.com/sharedfiles/filedetails/?id=1677616980]
RandomPlus [https://steamcommunity.com/sharedfiles/filedetails/?id=1434137894]
WeaponStats [https://steamcommunity.com/sharedfiles/filedetails/?id=974066449]
[NL] Dynamic Portraits [https://steamcommunity.com/sharedfiles/filedetails/?id=2253730555]
Non-Deadly Smokeleaf [https://steamcommunity.com/sharedfiles/filedetails/?id=872197723]
Stand Your Ground [https://steamcommunity.com/sharedfiles/filedetails/?id=2185757415]
Opened Doors Don't Block Light [https://steamcommunity.com/sharedfiles/filedetails/?id=1750069106]
Architect Icons [https://steamcommunity.com/sharedfiles/filedetails/?id=1195427067]
Relations Tab [https://steamcommunity.com/sharedfiles/filedetails/?id=709317151]
Research Info [https:// no link (local mod)]
Dress Patients [https://steamcommunity.com/sharedfiles/filedetails/?id=1667901146]
Thermal Units [https://steamcommunity.com/sharedfiles/filedetails/?id=2006814687]
Colonist History [https://steamcommunity.com/sharedfiles/filedetails/?id=2143758723]
Show Draftees Weapon [https://steamcommunity.com/sharedfiles/filedetails/?id=1690978457]
RunAndGun [https://steamcommunity.com/sharedfiles/filedetails/?id=1204108550]
Auto-Cut Blight [https://steamcommunity.com/sharedfiles/filedetails/?id=1885186534]
Real Drug Names [https://steamcommunity.com/sharedfiles/filedetails/?id=784325872]
Power Indicators [https://steamcommunity.com/sharedfiles/filedetails/?id=899714534]
Simple sidearms [https://steamcommunity.com/sharedfiles/filedetails/?id=927155256]
Stackable Chunks [https://steamcommunity.com/sharedfiles/filedetails/?id=1619558325]
More Trade Ships [https://steamcommunity.com/sharedfiles/filedetails/?id=725465444]
Faster Smoothing [https://steamcommunity.com/sharedfiles/filedetails/?id=1807439023]
Dubs Mint Menus [https://steamcommunity.com/sharedfiles/filedetails/?id=1446523594]
[SYR] More Slaves [https://steamcommunity.com/sharedfiles/filedetails/?id=2021510577]
Trait Rarity Colors [https://steamcommunity.com/sharedfiles/filedetails/?id=1751884355]
Simple Search Bar [https://steamcommunity.com/sharedfiles/filedetails/?id=1827546987]
More Components [https://steamcommunity.com/sharedfiles/filedetails/?id=1254970979]
Pawn Name Variety [https://steamcommunity.com/sharedfiles/filedetails/?id=2159633754]
[SYR] Harvest Yield [https://steamcommunity.com/sharedfiles/filedetails/?id=1461790308]
Wearing Armor Info [https://steamcommunity.com/sharedfiles/filedetails/?id=1839305669]
Interaction Bubbles [https://steamcommunity.com/sharedfiles/filedetails/?id=1516158345]
Awesome Inventory [https://steamcommunity.com/sharedfiles/filedetails/?id=2050289408]
Dubs Mint Minimap [https://steamcommunity.com/sharedfiles/filedetails/?id=1662119905]
Skilled Stonecutting [https://steamcommunity.com/sharedfiles/filedetails/?id=1207390617]
Everybody Gets One [https://steamcommunity.com/sharedfiles/filedetails/?id=1687566130]
Pawn Badge Fan Fork [https://steamcommunity.com/sharedfiles/filedetails/?id=2112663412]
Smarter Construction [https://steamcommunity.com/sharedfiles/filedetails/?id=2202185773]
ShowModDesignators [https://steamcommunity.com/sharedfiles/filedetails/?id=1399212509]
Vanilla Hair Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1888705256]
Locks 2: Lock Them Out! [https:// no link (local mod)]
Damage Indicators [1.2] [https://steamcommunity.com/sharedfiles/filedetails/?id=2016331497]
Vanilla Events Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1938420742]
Reasonable Components [https://steamcommunity.com/sharedfiles/filedetails/?id=1542915888]
Enhanced Combat Sounds [https://steamcommunity.com/sharedfiles/filedetails/?id=2095586726]
Pawn Badge - Soviet Navy [https://steamcommunity.com/sharedfiles/filedetails/?id=2112979470]
Pawn Badge - Soviet Army [https://steamcommunity.com/sharedfiles/filedetails/?id=2112979140]
Pawn Badge - XCOM Badge [https:// no link (local mod)]
AI Upscaled Textures - Core [https:// no link (local mod)]
[1.1, 1.2] Uninstall Rimworld [https://steamcommunity.com/sharedfiles/filedetails/?id=2018899948]
Death Rattle Continued [1.2] [https://steamcommunity.com/sharedfiles/filedetails/?id=2206107940]
AI Upscaled Textures - Plants [https:// no link (local mod)]
Compact Hediffs [https://steamcommunity.com/sharedfiles/filedetails/?id=2031734067]
Pawn Badge - Soviet Aviation [https://steamcommunity.com/sharedfiles/filedetails/?id=2112978863]
Pick Up And Haul (Continued) [https:// no link (local mod)]
Conduit Deconstruct [https://steamcommunity.com/sharedfiles/filedetails/?id=838336462]
Vanilla Hair Expanded - Beards [https://steamcommunity.com/sharedfiles/filedetails/?id=2187520791]
[SPK] Additional Vanilla Crafting [https://steamcommunity.com/sharedfiles/filedetails/?id=2122304719]
Vanilla Expanded - Royalty Patches [https://steamcommunity.com/sharedfiles/filedetails/?id=2260012940]
No Job Authors [https://steamcommunity.com/sharedfiles/filedetails/?id=2009825774]
OgreStack [https://steamcommunity.com/sharedfiles/filedetails/?id=1447140290]
RuntimeGC [https://steamcommunity.com/sharedfiles/filedetails/?id=2228430510]
Pawn Badge - Vietnamese People's Army [https://steamcommunity.com/sharedfiles/filedetails/?id=2114315356]
Vanilla Storytellers Expanded - Igor Invader [https://steamcommunity.com/sharedfiles/filedetails/?id=2249879548]
TD Enhancement Pack [https://steamcommunity.com/sharedfiles/filedetails/?id=1339135272]
Psionic+ [https://steamcommunity.com/sharedfiles/filedetails/?id=2266499836]
Glass+Lights [https://steamcommunity.com/sharedfiles/filedetails/?id=826153738]
Quarry 1.1 [https://steamcommunity.com/sharedfiles/filedetails/?id=2007576583]
Pocket Dimension [https:// no link (local mod)]
Cheap Woods [https://steamcommunity.com/sharedfiles/filedetails/?id=2174246865]
Prisoner Arena (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2022581505]
Project RimFactory Revived [https://steamcommunity.com/sharedfiles/filedetails/?id=2033979700]
Extra Ammunition [https:// no link (local mod)]
Gas Traps And Shells [https://steamcommunity.com/sharedfiles/filedetails/?id=2012627964]
Mosin-Nagant [https:// no link (local mod)]
Combat Extended Guns [https://steamcommunity.com/sharedfiles/filedetails/?id=1582570547]
Combat Extended Melee [https://steamcommunity.com/sharedfiles/filedetails/?id=1924933379]
Combat Extended: Weapons [https://steamcommunity.com/sharedfiles/filedetails/?id=2173744221]
Combat Extended - Chemical Warfare [https://steamcommunity.com/sharedfiles/filedetails/?id=2258417774]
Vanilla Weapons Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1814383360]
Vanilla Weapons Expanded - Laser [https://steamcommunity.com/sharedfiles/filedetails/?id=1989352844]
Vanilla Weapons Expanded - Grenades [https://steamcommunity.com/sharedfiles/filedetails/?id=2194472657]
Vanilla Weapons Expanded - Quickdraw [https://steamcommunity.com/sharedfiles/filedetails/?id=1906780517]
Vanilla Plants Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2134308522]
Vanilla Books Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2193152410]
Vanilla Cooking Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2134308519]
Vanilla Apparel Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1814987817]
Vanilla Armour Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1814988282]
Vanilla Factions Expanded - Insectoids [https://steamcommunity.com/sharedfiles/filedetails/?id=2149755445]
Vanilla Factions Expanded - Medieval [https://steamcommunity.com/sharedfiles/filedetails/?id=2023513450]
Vanilla Factions Expanded - Vikings [https://steamcommunity.com/sharedfiles/filedetails/?id=2231295285]
Execution Mod [https://steamcommunity.com/sharedfiles/filedetails/?id=2186151886]
Vanilla Furniture Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1718190143]
Vanilla Furniture Expanded - Art [https://steamcommunity.com/sharedfiles/filedetails/?id=1968134023]
Vanilla Furniture Expanded - Power [https://steamcommunity.com/sharedfiles/filedetails/?id=2062943477]
Vanilla Furniture Expanded - Farming [https://steamcommunity.com/sharedfiles/filedetails/?id=1957158779]
Vanilla Furniture Expanded - Security [https://steamcommunity.com/sharedfiles/filedetails/?id=1845154007]
Vanilla Furniture Expanded - Production [https://steamcommunity.com/sharedfiles/filedetails/?id=1880253632]
Vanilla Furniture Expanded - Spacer Module [https://steamcommunity.com/sharedfiles/filedetails/?id=2028381079]
Vanilla Furniture Expanded - Medical Module [https://steamcommunity.com/sharedfiles/filedetails/?id=1718191613]
Vanilla Furniture Expanded - Props and Decor [https://steamcommunity.com/sharedfiles/filedetails/?id=2102143149]
TMC All In One CE Patch [https://steamcommunity.com/sharedfiles/filedetails/?id=2208690237]
TMC Armory - SMGs #1 [https://steamcommunity.com/sharedfiles/filedetails/?id=2240610125]
TMC Armory - Shotguns #1 [https://steamcommunity.com/sharedfiles/filedetails/?id=2213739770]
Rim of Madness - Bones [https://steamcommunity.com/sharedfiles/filedetails/?id=1180573408]
TMC Armory - Sidearms #1 [https://steamcommunity.com/sharedfiles/filedetails/?id=2224658216]
TMC Armory - Sniper Rifles #1 [https://steamcommunity.com/sharedfiles/filedetails/?id=2264691528]
TMC Armory - Assault Rifles #1 [https://steamcommunity.com/sharedfiles/filedetails/?id=2208689786]
TMC Armory - Support Weapons #1 [https:// no link (local mod)]
Mechanoid+ [https://steamcommunity.com/sharedfiles/filedetails/?id=2233052841]
[KV] RimFridge [https://steamcommunity.com/sharedfiles/filedetails/?id=1180721235]
AI Upscaled Textures - Mods [https:// no link (local mod)]
RimHeli [https://steamcommunity.com/sharedfiles/filedetails/?id=2158396143]
RimNauts [https://steamcommunity.com/sharedfiles/filedetails/?id=2198026141]
[T] MoreFloors [https://steamcommunity.com/sharedfiles/filedetails/?id=1543561093]
[TRAHS]Blood [https://steamcommunity.com/sharedfiles/filedetails/?id=2170595802]
[WD] Reinforced Doors [https://steamcommunity.com/sharedfiles/filedetails/?id=1857597307]
Fast regen 1.2 [https://steamcommunity.com/sharedfiles/filedetails/?id=943925765]
Electric Braziers [https://steamcommunity.com/sharedfiles/filedetails/?id=2119557949]
Rimatomics [https://steamcommunity.com/sharedfiles/filedetails/?id=1127530465]
TMC Gun Accessories [https:// no link (local mod)]
TMC Armory - Community Pack  [https:// no link (local mod)]
TMC Modular Weapons [https:// no link (local mod)]
RimThreaded [1.2] [https://steamcommunity.com/sharedfiles/filedetails/?id=2222907981]

**Screenshots**
I'll capture one later, but for now, I'll keep with this.

**Comment by Niilo007** [comment]
it would be really helpful if you could try to get this issue to happen with less mods, or in vanilla.

it would help to know what mod causes the issue (if it is a mod issue)
