### ISSUE TITLE
Colonists and Androids not doing jobs.

### ISSUE THREAD

**Issue by SomeoneTookMyUsername1** [cseelhoff/RimThreaded#368]
**Describe the bug**
Colonists and Androids will not work on work stations, build, haul, plant, etc. Though will relax and play video games like a bunch of lazy bones. Androids will eat or charge their batteries when low and colonists will eat when hunger is low still.

**To Reproduce**
When every colonist is currently drafted a single error repeats in the Debug log: See Pastebin link 1.
When a single Android Colonist is undrafted two errors are reported in the Debug log: See Pastebin link 2.
When a single human Colonist is undrafted one error is reported in the Debug log: See Pastebin link 3.
**Error Log**
Pastebin link 1: https://pastebin.com/J5jcjzZp
Pastebin link 2: https://pastebin.com/7J61FtvC
Pastebin link 3: https://pastebin.com/wqanan6h

**Mod List**
IN ORDER:
Harmony
Core
Royalty
Craftsmanship
[SF] Priority treatment 1.1
Crash Landing
Home Mover
Hardworking animals 1.2
Roads of the Rim
Smarter Construction
Vanilla Hair Expanded
Everybody Gets One
Vanilla Expanded Framework
Vanilla Cooking Expanded
Vanilla Factions Expanded - Insectoids
Better Workbench Management
Rimefeller
Project Rimfactory Revived
[KV] Path Avoid
A Dog Said... Animal Prosthetics
Combat Extended
Combat Extended Guns
Allow Tool
Smart Speed
Gunplay
Raise The Roof 1.2
Compact Hediffs
[WD] Reinforced Doors
RimThemes
Reinforced Walls
Dynamic Diplomacy
Vanilla Furniture Expanded - Production
Vanilla Furniture Expanded - Farming
SRTS Expanded
Rimheli
Vanilla Plants Expanded
Interaction Bubbles
Vanilla Factions Expanded - Settlers
Go Explore!
Preemptive Strike (Fork)
Vanilla Events Expanded
Harvest Organs Post Mortem
RimSaves
Beutiful Outdoors
RimHUD
[KV] Adjustable Trade Ships
ItemListSelector
ShowModDesignators
Raids For Me
[FSF] Complex Jobs (Legacy Version)
Save Our Ship 2
Dubs Mint Minimap
Vanilla Furniture Expanded
Damage Indicators [1.2]
Common Sense
TD Enhancement Pack
Stabilize
Hospitality
Realistic Rooms
Recipe Icons
Wall Light
Expanded Prosthetics and Organ Engineering
Replace Stuff
EdB Prepare Carefully
Medical Tab
Snap out!
MendAndRecycle
Avoid Friendly Fire
Real Ruins
Share The Load
Smart Medicine
MinifyEverything
Combat Extended Melee
Locks
[1.2} DE Surgeries
ResearchPal
Heat Map
Grazing Lands
Mad Skills
Pharmacist
Show Drafees Weapon
Defensive Machine Gun Turret Pack
Dubs Mint Menus
Infestations Spawn in Darkness
Vanilla Fishing Expanded
[sd] Advanced Powergeneration (Continued)
Realistic Human Sounds (Continued)
Incident Person Stat
FuelBurning (Continued)
[FSF] Filth anishes Wiith Rain And Time
Prison Labor
Therapy
Dubs Break Mod
Level Up!
Humanoid Alien Races 2.0
Android tiers
Combat Extended: Shields
Ultra Vanilla Theme
[SRTS Expanded] Planes and Bombs
Android Tiers - Fixes + Tweaks
Increased Stack
CM Color Coded Mood Bar [1.1+]
Pick Up And Haul
Quality Builder
RimThreaded [1.2]
END OF LIST: sorry there is so many :(
**Screenshots**
Not sure if adding a screen shot would help.

**Comment by Niilo007** [comment]
Please test with the newest version of RimThreaded. the errors indicated "prison labor" as the cause

re open this issue if you still have this problem
