### ISSUE TITLE
"Combat Extended" RimThreaded with Combat Extended: explosives - massive log output

### ISSUE THREAD

**Issue by Awissowo** [cseelhoff/RimThreaded#370]
**Describe the bug**
With the explosion of the shells lots of errors appear

**To Reproduce**
1. Select a pawn
2. Equip them with a flamethrower
3. Select explosives to shoot
4. Shoot
5. See errors

**Error Log**
https://gist.github.com/a415209e663765afd3181a419183dc66

**Mod List**
-Harmony https://steamcommunity.com/sharedfiles/filedetails/?id=2009463077&searchtext=harmony
-Core
-Royalty
-HugsLib https://steamcommunity.com/sharedfiles/filedetails/?id=818773962&searchtext=hugs+lib
-Mod Manager https://steamcommunity.com/sharedfiles/filedetails/?id=1507748539&searchtext=mod+manager
-RimThreaded https://steamcommunity.com/sharedfiles/filedetails/?id=2222907981&searchtext=rimthreaded
-Combat Extended https://steamcommunity.com/sharedfiles/filedetails/?id=1631756268&searchtext=combat+extended

Load order: https://i.imgur.com/8HQbo7S.png

**Screenshots**
https://i.imgur.com/xOy3Tns.png
https://i.imgur.com/GFZu185.png
https://i.imgur.com/RB6XbIW.png
https://i.imgur.com/q9ORqkg.png
https://i.imgur.com/EdPPSqp.png

**Comment by pastorismylord** [comment]
tested with 2.2.8. Combat Extended seems to be working fine now. No massive logs for explosions anymore

**Comment by pastorismylord** [comment]
I was able to trigger some logs with 2.2.8, here are the logs: https://gist.github.com/32e61b150eca97efff4727e3478053dc

**Comment by pastorismylord** [comment]
closing this issue as we have better documented ones now
