### ISSUE TITLE
"Adeptus Mechanicus: Armoury" las weapons do not fire projectiles

### ISSUE THREAD

**Issue by ComputationalPotato** [cseelhoff/RimThreaded#371]
**Describe the bug**
The lasguns, longlas, and lascannons(including turrets), will fire as normal but the projectile will not be created so there is no damage. Pawns will aim, the muzzle flash is visible, the firing sound plays, and pawns can even level shooting, but the projectiles do not happen and no errors or warnings are produced. Disabling rimthreaded caused the weapons to work properly. Creating new saves had no effect.
**To Reproduce**
1. give a pawn a longlas or make a lascannon turret
2. have it fire at something
3. notice the lack of projectiles

**Error Log**
no errors or warnings are produced.
**Mod List**
[Mod list length: 7]
Harmony [https://steamcommunity.com/sharedfiles/filedetails/?id=2009463077]
Core [https:// no link (local mod)]
Royalty [Official DLC] [https:// no link (local mod)]
Startup impact [https://steamcommunity.com/sharedfiles/filedetails/?id=1684944322]
HugsLib [https://steamcommunity.com/sharedfiles/filedetails/?id=818773962]
Adeptus Mechanicus: Armoury [https://steamcommunity.com/sharedfiles/filedetails/?id=1541438614]
RimThreaded [1.2] [https://steamcommunity.com/sharedfiles/filedetails/?id=2222907981]

**Screenshots**

**Comment by Niilo007** [comment]
Please try with newest version of RT

**Comment by Niilo007** [comment]
should be fixed now.
