### ISSUE TITLE
Colonists can't operate on, or administer medication to the injured or sick 

### ISSUE THREAD

**Issue by Oakbo** [cseelhoff/RimThreaded#372]
**Describe the bug**

**To Reproduce**
1. Add a new medical bill (administer meds/operate on)
2. Colonist will attempt to complete over and over
3. See error

**Error Log**
[https://gist.github.com/HugsLibRecordKeeper/365ae81f94738b887181c0c77a251631](url)

**Mod List**
Version: 1
Name: Dec
Mods:
- Id: brrainz.harmony
  Name: Harmony
- Id: me.samboycoding.betterloading
  Name: BetterLoading
- Id: ludeon.rimworld
  Name: Core
- Id: ludeon.rimworld.royalty
  Name: Royalty
- Id: crustypeanut.rc2.core
  Name: '[1.0, 1.1] RimCuisine 2 Core'
- Id: fluffy.researchtree
  Name: Research Tree
- Id: jecrell.doorsexpanded
  Name: Doors Expanded
- Id: unlimitedhugs.hugslib
  Name: HugsLib
- Id: rimfridge.kv.rw
  Name: '[KV] RimFridge'
- Id: lwm.deepstorage
  Name: LWM's Deep Storage
- Id: mehni.pickupandhaul
  Name: Pick Up And Haul
- Id: sgc.quests
  Name: Quest Reward Rebalance
- Id: zylle.mapdesigner
  Name: Map Designer
- Id: indeed.stackxxl
  Name: Stack XXL
- Id: dubwise.dubsperformanceanalyzer
  Name: Dubs Performance Analyzer
- Id: mlie.simplymorebridges
  Name: Simply More Bridges (Continued)
- Id: oskarpotocki.vanillafactionsexpanded.core
  Name: Vanilla Expanded Framework
- Id: oskarpotocki.vfe.vikings
  Name: Vanilla Factions Expanded - Vikings
- Id: falconne.aff
  Name: Avoid Friendly Fire
- Id: vanillaexpanded.vfefarming
  Name: Vanilla Furniture Expanded - Farming
- Id: hobtook.mortaraccuracy
  Name: Mortar Accuracy
- Id: com.yayo.combat3
  Name: Yayo's Combat 3
- Id: tickspersecond.sparr.rw
  Name: TicksPerSecond
- Id: kikohi.cybernetic
  Name: Cybernetic Organism and Neural Network
- Id: ykara.epoe
  Name: Expanded Prosthetics and Organ Engineering
- Id: automatic.recipeicons
  Name: Recipe icons
- Id: fluffy.stuffedfloors
  Name: Stuffed Floors
- Id: murmur.pawnnamevariety
  Name: Pawn Name Variety
- Id: vanillaexpanded.vtexe
  Name: Vanilla Textures Expanded
- Id: vfme.caravanpacks
  Name: VFME - Caravan Packs!
- Id: targhetti.showdrafteesweapon
  Name: Show Draftees Weapon
- Id: oskarpotocki.vanillaexpanded.royaltypatches
  Name: Vanilla Expanded - Royalty Patches
- Id: 8z.dormitoriesnotbarracks
  Name: Dormitories Not Barracks
- Id: erdelf.humanoidalienraces
  Name: Humanoid Alien Races 2.0
- Id: atomicravioli.crystalloid
  Name: Crystalloid
- Id: com.yayo.racequestpawn
  Name: Real Faction Guest
- Id: porohkun.concretewalls
  Name: Concrete Walls
- Id: chjees.androids
  Name: Androids
- Id: atomicravioli.crystalloidandroids
  Name: Crystalloid Androids
- Id: nif.toolbox
  Name: ToolBox
- Id: nif.architectexpanded.fences
  Name: Architect Expanded - Fences
- Id: nykot.rpgstyleinventory
  Name: Sandy's RPG Style Inventory [1.2]
- Id: regrowth.botr.core
  Name: '[HLX] ReGrowth - Core'
- Id: regrowth.botr.temperateforestexpansion
  Name: '[HLX] ReGrowth - Temperate Forest Expansion'
- Id: regrowth.botr.borealforestexpansion
  Name: '[HLX] ReGrowth - Boreal Forest Expansion'
- Id: oskarpotocki.vfe.insectoid
  Name: Vanilla Factions Expanded - Insectoids
- Id: regrowth.botr.wasteland
  Name: '[HLX] ReGrowth - Wasteland'
- Id: regrowth.botr.tundraexpansion
  Name: '[HLX] ReGrowth - Tundra Expansion'
- Id: regrowth.botr.core.vpdp
  Name: '[HLX] ReGrowth - Vanilla Plant Density Patch'
- Id: regrowth.botr.extinctanimalspack
  Name: '[HLX] ReGrowth - Extinct Animals Pack'
- Id: regrowth.botr.wastelandfauna
  Name: '[HLX] ReGrowth - Mutated Animals Pack'
- Id: xeonovadan.turretextensions
  Name: '[XND] Turret Extensions'
- Id: vanillaexpanded.vfecore
  Name: Vanilla Furniture Expanded
- Id: gt.sam.glittertech
  Name: Glitter Tech
- Id: cattleya.furniturereskin
  Name: Furniture reskin
- Id: jecrell.jecstools
  Name: JecsTools (Unofficial)
- Id: mlie.lordoftherimselves
  Name: Lord of the Rims - Elves (Continued)
- Id: dianawinters.orassans
  Name: Orassans
- Id: vanillaexpanded.vfeproduction
  Name: Vanilla Furniture Expanded - Production
- Id: mlie.xndtinytweaks
  Name: '[XND] Tiny Tweaks (Continued)'
- Id: goudaquiche.ltfrockmenrace
  Name: Rockmen race
- Id: goudaquiche.laniusrace
  Name: Lanius race
- Id: goudaquiche.ltfmantisrace
  Name: Mantis race
- Id: goudaquiche.ltfengirace
  Name: Engi race
- Id: dimonsever000.rimcore.specific
  Name: RimCore
- Id: goudaquiche.ltfzoltanrace
  Name: Zoltan race
- Id: daemon976.stuffedsecurity
  Name: Stuffed Security
- Id: mlie.pickupandhaul
  Name: Pick Up And Haul (Continued)
- Id: mlie.roadsoftherim
  Name: Roads of the Rim (Continued)
- Id: xrushha.animagear
  Name: Anima Gear
- Id: derekbickley.legacyterrainoverhaulfinal
  Name: '[LTO] Terrain Overhaul'
- Id: xrushha.eldersfaction
  Name: Elders Faction
- Id: vanillaexpanded.vwe
  Name: Vanilla Weapons Expanded
- Id: mlie.cyberneticwarfare
  Name: Cybernetic Warfare and Special Weapons (Continued)
- Id: user19990313.runtimegc
  Name: RuntimeGC
- Id: fluffy.pharmacist
  Name: Pharmacist
- Id: crustypeanut.rc2.mame
  Name: RimCuisine 2 Meals and Munchies Expansion (Continued)
- Id: fluffy.modmanager
  Name: Mod Manager
- Id: k.glitternet
  Name: GlitterNet
- Id: k.cybernet
  Name: CyberNet
- Id: k.psitech
  Name: PsiTech
- Id: vanillaexpanded.vcooke
  Name: Vanilla Cooking Expanded
- Id: vanillaexpanded.vplantse
  Name: Vanilla Plants Expanded
- Id: caesarv6.damageindicators
  Name: Damage Indicators [1.2]
- Id: catachat.inspirationtweaks
  Name: Inspiration Tweaks
- Id: vanillaexpanded.vee
  Name: Vanilla Events Expanded
- Id: vse.perrypersistent
  Name: Vanilla Storytellers Expanded - Perry Persistent
- Id: vse.empressevil
  Name: Vanilla Storytellers Expanded - Empress Evil
- Id: void.charactereditor
  Name: Character Editor
- Id: crusader.ctf
  Name: Corpse To Fuel
- Id: sulusdacor.james76543.meltup.advancedpowerplus
  Name: Advanced Power Plus
- Id: vanillaexpanded.vbrewe
  Name: Vanilla Brewing Expanded
- Id: marvinkosh.sometimesraidsgowrong
  Name: Sometimes Raids Go Wrong
- Id: vanillaexpanded.vbookse
  Name: Vanilla Books Expanded
- Id: neceros.androidsexpanded
  Name: Androids Expanded
- Id: neceros.badcanbegood
  Name: Bad Can Be Good
- Id: neceros.fuseplus
  Name: Fuse Plus
- Id: vanillaexpanded.vweg
  Name: Vanilla Weapons Expanded - Grenades
- Id: hlx.rimworldalteredcarbon
  Name: 'Rimworld: Altered Carbon'
- Id: vanillaexpanded.vfespacer
  Name: Vanilla Furniture Expanded - Spacer Module
- Id: mlie.drugpolicyfix
  Name: Drug Policy Fix (Continued)
- Id: mlie.medicalsupplements
  Name: Medical Supplements (Continued)
- Id: grimm.unlimited
  Name: Un-Limited
- Id: joethetech.marinearmormaterials
  Name: Marine Armor Materials
- Id: falconne.heatmap
  Name: Heat Map
- Id: madeline.modmismatchformatter
  Name: Better ModMismatch Window
- Id: ratys.rtfuse
  Name: RT Fuse
- Id: haplo.miscellaneous.training
  Name: Misc. Training
- Id: wemd.simplecoal
  Name: '[WD] Simple Coal'
- Id: automatic.bionicicons
  Name: Bionic icons
- Id: vanillaexpanded.vfesecurity
  Name: Vanilla Furniture Expanded - Security
- Id: longwater.smartstockpilecreation
  Name: Quick Stockpile Creation
- Id: vanillaexpanded.varme
  Name: Vanilla Armour Expanded
- Id: telkir.tmods.morefloors
  Name: '[T] MoreFloors'
- Id: woolstrand.realruins
  Name: Real Ruins
- Id: fluffy.medicaltab
  Name: Medical Tab
- Id: fluffy.worktab
  Name: Work Tab
- Id: fluffy.animaltab
  Name: Animal Tab
- Id: fluffy.colonymanager
  Name: Colony Manager
- Id: fluffy.blueprints
  Name: Blueprints
- Id: albion.sparklingworlds.full
  Name: Sparkling Worlds - Full Mod
- Id: albion.sparklingworlds.bmchardcore
  Name: Sparkling Worlds Extension - BMC Hardcore Patch
- Id: albion.aiuplift
  Name: AI Uplifting Assistant
- Id: unlimitedhugs.allowtool
  Name: Allow Tool
- Id: crlsniper.realisticrooms
  Name: Realistic Rooms
- Id: vanillaexpanded.vfeart
  Name: Vanilla Furniture Expanded - Art
- Id: jaxe.rimhud
  Name: RimHUD
- Id: voult.betterpawncontrol
  Name: Better Pawn Control
- Id: oblitus.animalslogic
  Name: Animals Logic
- Id: peppsen.pmusic
  Name: P-Music
- Id: dubwise.dubsmintmenus
  Name: Dubs Mint Menus
- Id: vanillaexpanded.vfemedical
  Name: Vanilla Furniture Expanded - Medical Module
- Id: rah.rbse
  Name: Rah's Bionics and Surgery Expansion
- Id: automatic.startupimpact
  Name: Startup impact
- Id: notfood.mendandrecycle
  Name: MendAndRecycle
- Id: vanillaexpanded.vcef
  Name: Vanilla Fishing Expanded
- Id: ratys.madskills
  Name: Mad Skills
- Id: murmur.walllight
  Name: Wall Light
- Id: brrainz.achtung
  Name: Achtung!
- Id: crashm.colorcodedmoodbar.11
  Name: CM Color Coded Mood Bar [1.1+]
- Id: murmur.subsurfaceconduit
  Name: Subsurface Conduit
- Id: mlie.variousspaceshipchunk
  Name: Various Space Ship Chunk (Continued)
- Id: oskarpotocki.vanillafactionsexpanded.medievalmodule
  Name: Vanilla Factions Expanded - Medieval
- Id: vanillaexpanded.vwel
  Name: Vanilla Weapons Expanded - Laser
- Id: wit.expandedroofing
  Name: Expanded Roofing
- Id: petetimessix.compacthediffs
  Name: Compact Hediffs
- Id: oskarpotocki.vanillafactionsexpanded.settlersmodule
  Name: Vanilla Factions Expanded - Settlers
- Id: vanillaexpanded.vfepower
  Name: Vanilla Furniture Expanded - Power
- Id: machine.betterinfestations
  Name: Better Infestations 1.2
- Id: malteschulze.rimmsqol
  Name: RIMMSqol
- Id: daniledman.mechalitcore
  Name: Mechalit Core 1.2
- Id: daniledman.mechalitequipment
  Name: Mechalit Equipment + Faction 1.2
- Id: mlie.vanillachristmasexpanded
  Name: Vanilla Christmas Expanded (Continued)
- Id: eb.fineweaponry
  Name: Exotic's Fine Weaponry
- Id: mlie.electricfencesandfloors
  Name: Electric Fences and Floors (Continued)
- Id: isorex.geothermalcooler
  Name: Geothermal Cooler
- Id: slabby.wallheater
  Name: WallHeater
- Id: majorhoff.rimthreaded
  Name: RimThreaded [1.2]

**Comment by Oakbo** [comment]
Having the same problem using hoffs-favorite-mods:

[https://gist.github.com/HugsLibRecordKeeper/06c40bd133b5b0c851c95fb8fc8c28be](url)

**Comment by cseelhoff** [comment]
Please try v1.1.38 and let me know if this is fixed. Thanks!

**Comment by pastorismylord** [comment]
fixed on 1.1.38
