### ISSUE TITLE
"Hospitality" Repeating Thread Abortion Exceptions

### ISSUE THREAD

**Issue by popcorn95** [cseelhoff/RimThreaded#374]
**Describe the bug**
I have a bug in which the mod gets stuck in a loop doing what seems to be restarting a thread that has failed or timed out. If I load an auto-save, I can get further in the game, but it eventually gets stuck again.

**To Reproduce**
To see the error log. (How I find it.
1. Load the Monda Pact save 
2. Let run until the game's FPS drops (I think it should be almost instant for this save)
3. Pause and open debug log

The Autosave-4 file is 5 minutes before the Monda Pact save where the game runs fine. You can use this to test where or why this happens as I have no idea.
[Rimworld saves.zip](https://github.com/cseelhoff/RimThreaded/files/5705044/Rimworld.saves.zip)

**Error Log**
https://pastebin.com/CSiWam7C

**Mod List**
Version: 1
Name: 123456
Mods:
- Id: brrainz.harmony_steam
  Name: Harmony
- Id: ludeon.rimworld
  Name: Core
- Id: ludeon.rimworld.royalty
  Name: Royalty
- Id: automatic.startupimpact
  Name: Startup impact
- Id: user19990313.runtimegc
  Name: RuntimeGC
- Id: fluffy.modmanager_steam
  Name: Mod Manager
- Id: dubwise.dubsmintmenus
  Name: Dubs Mint Menus
- Id: erdelf.humanoidalienraces
  Name: Humanoid Alien Races 2.0
- Id: unlimitedhugs.hugslib
  Name: HugsLib
- Id: dylan.csl
  Name: Children, school and learning
- Id: vanillaexpanded.achievements
  Name: Vanilla Achievements Expanded
- Id: brrainz.achtung
  Name: Achtung!
- Id: unlimitedhugs.allowtool
  Name: Allow Tool
- Id: fs.reviarace
  Name: Revia Race
- Id: oblitus.animalslogic
  Name: Animals Logic
- Id: dhultgren.useminifiedbuildings
  Name: Use Minified Buildings
- Id: voult.betterpawncontrol
  Name: Better Pawn Control
- Id: owlchemist.bettervanillamasking
  Name: Better Vanilla Masking
- Id: falconne.bwm
  Name: Better Workbench Management
- Id: fluffy.blueprints
  Name: Blueprints
- Id: fluffy.colonymanager
  Name: Colony Manager
- Id: porquenolosdos.colorcodedmoodbar
  Name: Color Coded Mood Bar
- Id: petetimessix.compacthediffs
  Name: Compact Hediffs
- Id: caesarv6.damageindicators
  Name: Damage Indicators [1.2]
- Id: unlimitedhugs.defensivepositions
  Name: Defensive Positions
- Id: dubwise.dubsperformanceanalyzer
  Name: Dubs Performance Analyzer
- Id: dubwise.dubsskylights
  Name: Dubs Skylights
- Id: edb.preparecarefully
  Name: EdB Prepare Carefully
- Id: frozensnowfox.encountermapresources
  Name: '[FSF] Encounter Map Resources'
- Id: uuugggg.everybodygetsone
  Name: Everybody Gets One
- Id: vat.epoeforked
  Name: Expanded Prosthetics and Organ Engineering - Forked
- Id: tarojun.epoeforked.allowdirectcrafting
  Name: 'EPOE-Forked: Allow direct crafting'
- Id: factioncontrol.kv.rw
  Name: '[KV] Faction Control'
- Id: falconne.heatmap
  Name: Heat Map
- Id: fridgebaron.immortals
  Name: Immortals
- Id: automatic.incidenttweaker
  Name: Incident Tweaker
- Id: catachat.inspirationtweaks
  Name: Inspiration Tweaks
- Id: insertkey.itemlistselector
  Name: ItemListSelector
- Id: erdelf.minifyeverything
  Name: MinifyEverything
- Id: haplo.miscellaneous.robots
  Name: Misc. Robots
- Id: alaestor.miscrobots.plusplus
  Name: Misc. Robots++
- Id: jaxe.morefilters
  Name: More Filters
- Id: com.github.alandariva.moreplanning
  Name: More Planning
- Id: pinochemicali.moretradeships
  Name: More Trade Ships
- Id: doug.nojobauthors
  Name: No Job Authors
- Id: notfood.outfitted
  Name: Outfitted
- Id: pathavoid.kv.rw
  Name: '[KV] Path Avoid'
- Id: jaxe.pawnrules
  Name: Pawn Rules
- Id: fluffy.pharmacist
  Name: Pharmacist
- Id: odysseyscorpio.plantsandthings.20200314
  Name: Plants and Things
- Id: erdelf.prisonerransom
  Name: PrisonerRansom
- Id: hatti.qualitybuilder
  Name: QualityBuilder
- Id: uuugggg.replacestuff
  Name: Replace Stuff
- Id: notfood.researchpal
  Name: ResearchPal
- Id: rimfridge.kv.rw
  Name: '[KV] RimFridge'
- Id: lwm.deepstorage
  Name: LWM's Deep Storage
- Id: jaxe.rimhud
  Name: RimHUD
- Id: roolo.runandgun
  Name: RunAndGun
- Id: targhetti.showdrafteesweapon
  Name: Show Draftees Weapon
- Id: gguake.ui.simplesearchbar
  Name: Simple Search Bar
- Id: petetimessix.simplesidearms
  Name: Simple sidearms
- Id: uuugggg.smartmedicine
  Name: Smart Medicine
- Id: smashphil.neceros.srtsexpanded
  Name: SRTS Expanded
- Id: uuugggg.tdpack
  Name: TD Enhancement Pack
- Id: zilla.tilledsoil
  Name: Tilled Soil
- Id: tradingspot.kv.rw
  Name: '[KV] Trading Spot'
- Id: vanillaexpanded.vaeas
  Name: Vanilla Animals Expanded — Arid Shrubland
- Id: vanillaexpanded.vaeau
  Name: Vanilla Animals Expanded — Australia
- Id: vanillaexpanded.vaebf
  Name: Vanilla Animals Expanded — Boreal Forest
- Id: vanillaexpanded.vaecd
  Name: Vanilla Animals Expanded — Cats and Dogs
- Id: vanillaexpanded.vaed
  Name: Vanilla Animals Expanded — Desert
- Id: vanillaexpanded.vaeed
  Name: Vanilla Animals Expanded — Extreme Desert
- Id: vanillaexpanded.vaeis
  Name: Vanilla Animals Expanded — Ice Sheet
- Id: vanillaexpanded.vaetr
  Name: Vanilla Animals Expanded — Tropical Rainforest
- Id: vanillaexpanded.vaets
  Name: Vanilla Animals Expanded — Tropical Swamp
- Id: vanillaexpanded.vaet
  Name: Vanilla Animals Expanded — Tundra
- Id: vanillaexpanded.vappe
  Name: Vanilla Apparel Expanded
- Id: vanillaexpanded.varme
  Name: Vanilla Armour Expanded
- Id: vanillaexpanded.vee
  Name: Vanilla Events Expanded
- Id: oskarpotocki.vanillafactionsexpanded.core
  Name: Vanilla Expanded Framework
- Id: oskarpotocki.vanillaexpanded.royaltypatches
  Name: Vanilla Expanded - Royalty Patches
- Id: oskarpotocki.vanillafactionsexpanded.settlersmodule
  Name: Vanilla Factions Expanded - Settlers
- Id: vanillaexpanded.vcef
  Name: Vanilla Fishing Expanded
- Id: vanillaexpanded.vfecore
  Name: Vanilla Furniture Expanded
- Id: vanillaexpanded.vfeart
  Name: Vanilla Furniture Expanded - Art
- Id: vanillaexpanded.vfefarming
  Name: Vanilla Furniture Expanded - Farming
- Id: vanillaexpanded.vfemedical
  Name: Vanilla Furniture Expanded - Medical Module
- Id: vanillaexpanded.vfepower
  Name: Vanilla Furniture Expanded - Power
- Id: vanillaexpanded.vfeproduction
  Name: Vanilla Furniture Expanded - Production
- Id: vanillaexpanded.vfesecurity
  Name: Vanilla Furniture Expanded - Security
- Id: vanillaexpanded.vfespacer
  Name: Vanilla Furniture Expanded - Spacer Module
- Id: vanillaexpanded.vhe
  Name: Vanilla Hair Expanded
- Id: vanillaexpanded.vwe
  Name: Vanilla Weapons Expanded
- Id: vanillaexpanded.vweq
  Name: Vanilla Weapons Expanded - Quickdraw
- Id: oskarpotocki.vanillafactionsexpanded.medievalmodule
  Name: Vanilla Factions Expanded - Medieval
- Id: murmur.walllight
  Name: Wall Light
- Id: smashphil.carrycapacityfixed
  Name: Carry Capacity Fixed
- Id: revolus.whatsmissing
  Name: What's Missing?
- Id: fluffy.fluffybreakdowns
  Name: Fluffy Breakdowns
- Id: sarg.smartspeed
  Name: Smart Speed
- Id: mlie.simplymorebridges
  Name: Simply More Bridges (Continued)
- Id: skullywag.extendedstorage
  Name: Extended Storage
- Id: erdelf.showmoddesignators
  Name: ShowModDesignators
- Id: vanillaexpanded.vbookse
  Name: Vanilla Books Expanded
- Id: vanillaexpanded.vwel
  Name: Vanilla Weapons Expanded - Laser
- Id: ratys.madskills
  Name: Mad Skills
- Id: pinochemicali.skilledstonecutting
  Name: Skilled Stonecutting
- Id: murmur.subsurfaceconduit
  Name: Subsurface Conduit
- Id: ratys.rtfuse
  Name: RT Fuse
- Id: mlie.animalharvestingspot
  Name: AnimalHarvestingSpot (Continued)
- Id: brrainz.cameraplus
  Name: Camera+
- Id: rooboid.royalhair
  Name: Roo's Royalty Hairstyles
- Id: dhultgren.smarterconstruction
  Name: Smarter Construction
- Id: oskarpotocki.vfe.insectoid
  Name: Vanilla Factions Expanded - Insectoids
- Id: oskarpotocki.vfe.vikings
  Name: Vanilla Factions Expanded - Vikings
- Id: vse.perrypersistent
  Name: Vanilla Storytellers Expanded - Perry Persistent
- Id: unlimitedhugs.mapreroll
  Name: Map Reroll
- Id: zylle.mapdesigner
  Name: Map Designer
- Id: neceros.balancedeclipseandsolarflare
  Name: Balanced Eclipse and Solar Flare
- Id: odysseyscorpio.glitterworldprime.20200411
  Name: GlitterWorld Prime
- Id: syrchalis.harvestyieldpatch
  Name: '[SYR] Harvest Yield'
- Id: moretraitslots.kv.rw
  Name: '[KV] More Trait Slots'
- Id: consolidatedtraits.kv.rw
  Name: '[KV] Consolidated Traits'
- Id: netrve.dsgui
  Name: Netrve's DeepStorage GUI
- Id: ogre.ogrestack
  Name: OgreStack
- Id: community.psychology.unofficialupdate
  Name: 'Psychology (unofficial 1.1/1.2) '
- Id: crlsniper.realisticrooms
  Name: Realistic Rooms
- Id: grimm.unlimited
  Name: Un-Limited
- Id: frozensnowfox.filthvanisheswithrainandtime
  Name: '[FSF] Filth Vanishes With Rain And Time'
- Id: mlie.centralizedclimatecontrol
  Name: Centralized Climate Control (Continued)
- Id: uuugggg.roomfood
  Name: Room Food
- Id: shakeyourbunny.sometimesraidsgowrong
  Name: Sometimes Raids Go Wrong (patched) [1.2]
- Id: vse.igorinvader
  Name: Vanilla Storytellers Expanded - Igor Invader
- Id: nykot.rpgstyleinventory
  Name: Sandy's RPG Style Inventory [1.2]
- Id: hobtook.mortaraccuracy
  Name: Mortar Accuracy
- Id: com.yayo.racequestpawn
  Name: Real Faction Guest
- Id: fluffy.worktab
  Name: Work Tab
- Id: mlie.bestmix
  Name: Best Mix (Continued)
- Id: orion.hospitality
  Name: Hospitality
- Id: mlie.pickupandhaul
  Name: Pick Up And Haul (Continued)
- Id: neronix17.embrasures
  Name: '[O21] Seamless Embrasures'
- Id: vanillaexpanded.vplantsesucculents
  Name: Vanilla Plants Expanded - Succulents
- Id: vanillaexpanded.vplantse
  Name: Vanilla Plants Expanded
- Id: vanillaexpanded.vaetf
  Name: Vanilla Animals Expanded — Temperate Forest
- Id: vanillaexpanded.vbrewe
  Name: Vanilla Brewing Expanded
- Id: vanillaexpanded.vbrewecandt
  Name: Vanilla Brewing Expanded - Coffees and Teas
- Id: vanillaexpanded.vcooke
  Name: Vanilla Cooking Expanded
- Id: vanillaexpanded.vcookestews
  Name: Vanilla Cooking Expanded - Stews
- Id: vanillaexpanded.vcookesushi
  Name: Vanilla Cooking Expanded - Sushi
- Id: vanillaexpanded.vfepropsanddecor
  Name: Vanilla Furniture Expanded - Props and Decor
- Id: neitsa.preparelanding
  Name: Prepare Landing
- Id: spoonshortage.adogsaidanimalprosthetics
  Name: A Dog Said... Animal Prosthetics
- Id: majorhoff.rimthreaded
  Name: RimThreaded [1.2]

**Screenshots**

**Comment by Niilo007** [comment]
Could you try to get this to happen with less mods? if you can reduce the mod list at least a bit, it will be easier for our testers to test.

**Comment by Niilo007** [comment]
at Hospitality.GenericUtility.GetTravelDays (RimWorld.Faction faction, Verse.Map map) [0x00052] in <e43536b7e9794111ae228f0955444338>:0 
  at Hospitality.GenericUtility+<>c__DisplayClass7_0.<FillIncidentQueue>b__1 (RimWorld.Faction f) [0x00000] in 
  
  looks like hospitality errors. hospitality is incompatible with RimThreaded

**Comment by 15adhami** [comment]
Tested in RT 1.3.2 and 2.0.7. Loaded save file and waited a few minutes, no errors related to Hospitality were encountered. Seems to be fixed.
