### ISSUE TITLE
"Where is my weapon?" Thread did not finish "where is my weapon" mod errors

### ISSUE THREAD

**Issue by LacheLovesMuffin** [cseelhoff/RimThreaded#377]
**Describe the bug**
After the game crashes , i reload the file and i get this error , i have over 200 mods installed so i can't snipe easily which mod is giving problems , the game works fine when i create a new world so it's kinda tricky. 

**To Reproduce**
1. Open world map
2. Stay on world map for a while until the game crashes 
3. Reload save file
4. Profit

**Error Log**
[
[Player.log](https://github.com/cseelhoff/RimThreaded/files/5721735/Player.log)
](url)

**Mod List**
Too many mods

**Comment by cseelhoff** [comment]
WhereIsMyWeapon.Patch_Pawn_HealthTracker_HealthTick.Postfix

**Comment by Niilo007** [comment]
Please test with the new version, and re open this issue if needed

**Comment by pastorismylord** [comment]
tested with 2.2.17, unable to reproduce the issue. Mod works fine now
