### ISSUE TITLE
(1.3.1) Exception ticking, System.NullReferenceException, regionGrid is null for map: Map-0

### ISSUE THREAD

**Issue by MadPacMan** [cseelhoff/RimThreaded#378]
**Describe the bug**
Mechs (in this case) gets stuck.
The "regionGrid is null for map: Map-0" error is often in the mix.
There also tends to be a timeout error when the roof collapse in some cases.
AND mind you, there are 2 different "RegionCostCalculatorWrapper" errors, one with "RegionCostCalculator" and one without.

No other mods, just Harmony, core, Royalty, Rimthreaded.

**To Reproduce**
Load save.
After the wall is destroyed, it happens about 50% of the time.
In this case, it only happens to a handfull at max, sometimes just 1 or 2. But in a late game, it can affect half the map.
**Error Log**

**Screenshots**
[test_save2.zip](https://github.com/cseelhoff/RimThreaded/files/5723687/test_save2.zip)
![RimWorldWin64_2020-12-21_10-43-06](https://user-images.githubusercontent.com/2514893/102765543-09d72600-437d-11eb-83bc-766bd4d3eb77.png)

**Comment by cseelhoff** [comment]
Thanks for this post! I have been chasing this bug for a while. If you indeed found a way to reproduce it even 50% of the time, I will be thrilled! Trying out your save now...

**Comment by cseelhoff** [comment]
I may have figured this out. It no longer errors or seems to get anyone stuck in 1.1.38. Perhaps you would be willing to test and verify this for me once its released?

**Comment by cseelhoff** [comment]
Please try v1.1.38 and let me know if this is fixed. Thanks!

**Comment by MadPacMan** [comment]
I can still get it to happen, actually i found a way to reproduce it 100% of the time, first load the (new) save as normal, everything seems to be working, but then reload the save (dont restart) and multiple mechs get stuck including the closest one. You can reload it as many times as you want, it always happens.

Weird that it only happens after a reload...



![RimWorldWin64_2021-01-02_10-04-31](https://user-images.githubusercontent.com/2514893/103454201-f19ec980-4ce1-11eb-9938-6f177f3b7277.png)

[test_save3.zip](https://github.com/cseelhoff/RimThreaded/files/5759981/test_save3.zip)

**Comment by cseelhoff** [comment]
Thanks for your continued help with this. I am trying out the new save now

**Comment by MadPacMan** [comment]
**On 1.2.1 (test build):**

**Test save 3:** 
No longer produces any errors.

**Test save 2:** 
Its still a goldmine in terms of producing all kinds of errors lol...
The "timeout error when the roof collapse" is fixed.

Varius errors i have seen spammed in this save (see errors.txt file for full lines)

> `Exception ticking Mech_Pikeman82015 (at (108, 0, 150)): System.NullReferenceException: Object reference not set to an instance of an object`

> `Exception ticking Mech_Centipede80990 (at (115, 0, 116)): System.IndexOutOfRangeException: index + length > size`

> `Tried to maintain ended sustainer: FireBurning`

> `Exception in JobDriver tick for pawn Mech_Scyther81725 driver=JobDriver_AttackMelee (toilIndex=2) driver.job=(AttackMelee (Job_56261) A=Thing_Wall47755)`

> `Could not regenerate layer Verse.SectionLayer_BuildingsDamage: System.IndexOutOfRangeException: index + length > size`

> `Exception ticking Bullet_AutocannonTurret113298: System.IndexOutOfRangeException: index + length > size`

![RimWorldWin64_2021-01-08_20-16-04](https://user-images.githubusercontent.com/2514893/104055922-e0791f80-51ef-11eb-9149-f973c566fea7.png)
[Errors.txt](https://github.com/cseelhoff/RimThreaded/files/5789015/Errors.txt)


GLHF

**Comment by MadPacMan** [comment]
1.2.4:
![RimWorldWin64_2021-01-24_22-33-36](https://user-images.githubusercontent.com/2514893/105644187-63f36b80-5e94-11eb-94ae-3f3d76f2e8bc.png)
On save2.

**Comment by MadPacMan** [comment]
As of 1.2.7 Save2 No longer produces the error.

Created a new save, 100% chance to create new pathfinding errors.

[Hoffs Nightmare PathFinder_TortureTest.zip](https://github.com/cseelhoff/RimThreaded/files/5900851/Hoffs.Nightmare.PathFinder_TortureTest.zip)

![RimWorldWin64_2021-01-31_23-28-53](https://user-images.githubusercontent.com/2514893/106400110-e17f2480-641c-11eb-82c2-4bbca4cf2672.png)
![RimWorldWin64_2021-01-31_22-20-08](https://user-images.githubusercontent.com/2514893/106400112-e348e800-641c-11eb-92d1-f1885c13f508.png)


I was thinking of opening a new Issue and Close this but, eh.

**Comment by pastorismylord** [comment]
This bug still exists on 1.3.1

**Comment by pastorismylord** [comment]
Just tested 2.2.8 with the aforementioned save, Only got 2 errors which seem to be not related to the original regionGrid is Null error.

@MadPacMan & @cseelhoff please take a look at https://gist.github.com/e06f110ab5b7490b8e1cceaab77a6d84

And advise if you think the issue has been addressed now.

**Comment by pastorismylord** [comment]
should be fixed now
