### ISSUE TITLE
Colonist Standing Surgeon

### ISSUE THREAD

**Issue by bencixmen** [cseelhoff/RimThreaded#380]
**Colonist standing near target instead of doing operations.**
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report.  

**To Reproduce**

**Error Log**
Link to contents of Player.log or Error.log (Please use something like gist or pastebin. DO NOT PASTE HERE)

**Screenshots**

JobDriver threw exception in initAction for pawn Miksu driver=JobDriver_DoBill (toilIndex=24) driver.job=(DoBill (Job_39778) A=Thing_Human40267)
System.NullReferenceException: Object reference not set to an instance of an object
  at RimWorld.Bill_Medical.Notify_DoBillStarted (Verse.Pawn billDoer) [0x000f0] in <d72310b4d8f64d25aee502792b58549f>:0 
  at Verse.AI.Toils_Recipe+<>c__DisplayClass2_0.<DoRecipeWork>b__0 () [0x000a0] in <d72310b4d8f64d25aee502792b58549f>:0 
  at RimThreaded.JobDriver_Patch.TryActuallyStartNextToil (Verse.AI.JobDriver __instance) [0x0034d] in <51769ca731214358b508937cb2fc7e29>:0 
Verse.Log:Verse.Log.Warning_Patch1(String, Boolean)
Verse.AI.JobUtility:Verse.AI.JobUtility.TryStartErrorRecoverJob_Patch0(Pawn, String, Exception, JobDriver)
RimThreaded.JobDriver_Patch:TryActuallyStartNextToil(JobDriver)
Verse.AI.JobDriver:Verse.AI.JobDriver.TryActuallyStartNextToil_Patch1(JobDriver)
Verse.AI.JobDriver:ReadyForNextToil()
RimThreaded.JobDriver_Patch:TryActuallyStartNextToil(JobDriver)
Verse.AI.JobDriver:Verse.AI.JobDriver.TryActuallyStartNextToil_Patch1(JobDriver)
Verse.AI.JobDriver:ReadyForNextToil()
Verse.AI.JobDriver:Notify_PatherArrived()
Verse.AI.Pawn_PathFollower:PatherArrived()
Verse.AI.Pawn_PathFollower:Verse.AI.Pawn_PathFollower.StartPath_Patch0(Pawn_PathFollower, LocalTargetInfo, PathEndMode)
Verse.AI.<>c__DisplayClass1_0:<GotoThing>b__0()
RimThreaded.JobDriver_Patch:TryActuallyStartNextToil(JobDriver)
Verse.AI.JobDriver:Verse.AI.JobDriver.TryActuallyStartNextToil_Patch1(JobDriver)
Verse.AI.JobDriver:ReadyForNextToil()
Verse.AI.JobDriver:JumpToToil(Toil)
Verse.AI.<>c__DisplayClass1_0:<JumpIf>b__0()
RimThreaded.JobDriver_Patch:TryActuallyStartNextToil(JobDriver)
Verse.AI.JobDriver:Verse.AI.JobDriver.TryActuallyStartNextToil_Patch1(JobDriver)
Verse.AI.JobDriver:ReadyForNextToil()
RimThreaded.JobDriver_Patch:TryActuallyStartNextToil(JobDriver)
Verse.AI.JobDriver:Verse.AI.JobDriver.TryActuallyStartNextToil_Patch1(JobDriver)
Verse.AI.JobDriver:ReadyForNextToil()
RimThreaded.JobDriver_Patch:TryActuallyStartNextToil(JobDriver)
Verse.AI.JobDriver:Verse.AI.JobDriver.TryActuallyStartNextToil_Patch1(JobDriver)
Verse.AI.JobDriver:ReadyForNextToil()
RimThreaded.JobDriver_Patch:TryActuallyStartNextToil(JobDriver)
Verse.AI.JobDriver:Verse.AI.JobDriver.TryActuallyStartNextToil_Patch1(JobDriver)
Verse.AI.JobDriver:ReadyForNextToil()
RimThreaded.JobDriver_Patch:TryActuallyStartNextToil(JobDriver)
Verse.AI.JobDriver:Verse.AI.JobDriver.TryActuallyStartNextToil_Patch1(JobDriver)
Verse.AI.JobDriver:ReadyForNextToil()
Verse.AI.JobDriver:Notify_PatherArrived()
Verse.AI.Pawn_PathFollower:PatherArrived()
Verse.AI.Pawn_PathFollower:Verse.AI.Pawn_PathFollower.StartPath_Patch0(Pawn_PathFollower, LocalTargetInfo, PathEndMode)
Verse.AI.<>c__DisplayClass1_0:<GotoThing>b__0()
RimThreaded.JobDriver_Patch:TryActuallyStartNextToil(JobDriver)
Verse.AI.JobDriver:Verse.AI.JobDriver.TryActuallyStartNextToil_Patch1(JobDriver)
Verse.AI.JobDriver:ReadyForNextToil()
Verse.AI.JobDriver:JumpToToil(Toil)
Verse.AI.<>c__DisplayClass1_0:<JumpIf>b__0()
RimThreaded.JobDriver_Patch:TryActuallyStartNextToil(JobDriver)
Verse.AI.JobDriver:Verse.AI.JobDriver.TryActuallyStartNextToil_Patch1(JobDriver)
Verse.AI.JobDriver:ReadyForNextToil()
RimThreaded.JobDriver_Patch:TryActuallyStartNextToil(JobDriver)
Verse.AI.JobDriver:Verse.AI.JobDriver.TryActuallyStartNextToil_Patch1(JobDriver)
Verse.AI.JobDriver:ReadyForNextToil()
Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.StartJob_Patch1(Pawn_JobTracker, Job, JobCondition, ThinkNode, Boolean, Boolean, ThinkTreeDef, Nullable`1, Boolean, Boolean)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob()
Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.EndCurrentJob_Patch1(Pawn_JobTracker, JobCondition, Boolean, Boolean)
Verse.AI.Pawn_JobTracker:JobTrackerTick()
Verse.Pawn:Verse.Pawn.Tick_Patch2(Pawn)
RimThreaded.RimThreaded:ExecuteTicks()
RimThreaded.RimThreaded:ProcessTicks()
RimThreaded.<>c:<CreateWorkerThread>b__128_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

**Comment by cseelhoff** [comment]
Please try v1.1.38 and let me know if this is fixed. Thanks!
