### ISSUE TITLE
Degraded performance with Pirate events

### ISSUE THREAD

**Issue by Pandemic223** [cseelhoff/RimThreaded#386]
**Describe the bug**
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report.  
Hello, anytime that an event spawns from the pirate events that alter weather (smoke or toxic)
**To Reproduce**
1. Go to pirate events
2. Click on spawn event
3. Watch TPS Degrade, to sub 500 usually.

**Error Log**
Link to contents of Player.log or Error.log (Please use something like gist or pastebin. DO NOT PASTE HERE)
https://gist.github.com/Pandemic223/6a7b2d07b4ef26162c9d50fe73b3b992
**Screenshots**

**Comment by Niilo007** [comment]
fixed in 1.2.7
