### ISSUE TITLE
"A RimWorld of Magic" 1 frame every 8 seconds bug (rimworld of magic errors in log)

### ISSUE THREAD

**Issue by ColourlessAmiba** [cseelhoff/RimThreaded#389]
**Describe the bug**
This bug slows the game down to 1 frame every 8-14 seconds. I have tested this with and without specifically Rimthreaded, and this error only appears with rimthreaded.

**To Reproduce**
Download the save I put into this bug report so you can load the save in question.
Make sure the mods that are on  the save are activated and in the same order.
Load.
As soon as you load, you should be greeted with the error that I was experiencing.

**Error Log**
[Player.log](https://github.com/cseelhoff/RimThreaded/files/5774232/Player.log)

**Mod List**
[Mods.txt](https://github.com/cseelhoff/RimThreaded/files/5774236/Mods.txt)
I understand that quite a lot of mods on this list are incompatible, but this is a save made before adding rimthreaded. Cat told me to upload regardless.

**Screenshots**
I forgot to take a screenshot for this issue, but it has several messages regarding advanced power generators. You'll find the messages of the debug menu in the player.log file sent.

**Comment by Niilo007** [comment]
Torann.ARimworldOfMagic seems to be the cause of the errors. try to reproduce this issue with the newest RT version. and if it happens again try with only RimThreaded & a rimworld of magic
