### ISSUE TITLE
Exception ticking Megascarab6877576 (at (330, 0, 141)): System.Threading.ThreadAbortException

### ISSUE THREAD

**Issue by Tourman36** [cseelhoff/RimThreaded#390]
**Describe the bug**
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report.  

**To Reproduce**
Start the game in windowed mode
load save
click away from main window
wait a few seconds..
click back to game window
the game will constantly freeze on and off and throw an exception

**Error Log**
https://pastebin.com/NG5iUyQq

**Comment by Niilo007** [comment]
Test with less mods with the newest version of RT
