### ISSUE TITLE
Ticking world component TileTemperaturesCompSystem

### ISSUE THREAD

**Issue by thefriendlycacti** [cseelhoff/RimThreaded#393]
**Describe the bug**
Threads restart till save is reloaded

**Just error**
https://gist.github.com/thefriendlycacti/e2135885d964dadc2b73a5b1a8502386

**Huglib Log**
https://gist.github.com/74ea60d2a697093b6ef48a0da1a37250

**Comment by cseelhoff** [comment]
fixed in 1.3.0.9
