### ISSUE TITLE
"Graphics Settings - Fix your textures!" Graphic Settings+ is incompatible with RT

### ISSUE THREAD

**Issue by reaperisonline** [cseelhoff/RimThreaded#394]
Ive been having a UI bug for awhile. Even Hoff himself and a bunch of mods tried helping me find it but with no luck. Ive been stripping my mods for a few weeks/months now and finally narrowed it down to two mods BOTH causing the issue: Graphic Settings+ is a mod that improves texture quality. Camera+ allows the user to zoom in and out more. Both have an issue that causes one of the pawns to be unable to load their appearance and spam the console.

**To Reproduce**
1. Create a fresh game (with either mods installed)
2. Keep adding pawns through devmode (10x stranger in black joins)
3. Eventually ull see a box  without a pawn inside of it and the connsole spams 'out of range'
**Error Log**

Hubs log: https://gist.github.com/97f11308c97a3f21049b77cd828ac699
Player log: https://drive.google.com/file/d/18NN48_zrKSS6nfr_M1U_ZM9zlifN-VI0/view?usp=sharing

NOTE: I added Camera+ later and had the same issue with Graphic Settings+. Therefore edited my post to add this one too.
**Mod List**
Paste contents of ModList used when bug occurred.
Initializing new game with mods:
  - brrainz.harmony
  - Ludeon.RimWorld
  - Ludeon.RimWorld.Royalty
  - automatic.startupimpact
  - UnlimitedHugs.HugsLib
  - EdB.PrepareCarefully
  - fluffy.modmanager
  - Harkon.GunNut.Chapter1
  - Harkon.GunNut.Chapter2
  - Harkon.GunNut.Community
  - velc.AutoRecycling
  - Porohkun.ConcreteWalls
  - erdelf.ExportAgency
  - sumghai.medpod
  - sumghaiDubwise.Replimat
  - fed1sPlay.PawnTargetFix
  - automatic.recipeicons
  - gguake.ui.simplesearchbar
  - Murmur.SubsurfaceConduit
  - smashphil.dropspot
  - tradingspot.kv.rw
  - Knight.useyourgun
  - Murmur.WallLight
  - dninemfive.wildreproduction
  - Merthsoft.DesignatorShapes
  - fluffy.blueprints
  - com.bymarcin.ArchitectIcons
  - mireia.bodies
  - Buildable.Terrain
  - TheWireLord354.ConduitDeconstruct
  - zyxabacab.NoSympathyForPrisoners
  - syrchalis.setupcamp
  - Ryflamer.Misc.Drawabead_copy
  - pyrce.dire.raids
  - TMC.Armory.AssaultRifle.1
  - TMC.Armory.Shotguns.1
  - TMC.Armory.Sidearms.1
  - TMC.Armory.SMGs.1
  - TMC.Armory.RF.1
  - TMC.Armory.SW.1
  - TMC.Armory.CommunityPack
  - Lelbaro.VanillaArmorsRetexture.LBVAR
  - Lelbaro.SectorVII.LBSC7
  - LWM.DeepStorage
  - JangoDsoul.SimpleStorage
  - Mlie.DurableClothes
  - nilchei.powerfulfactionbases
  - lbmaian.begonemessage
  - WexMan.TrainingConsole1.2
  - SF.More.Steel.From.Slag
  - Bennington.DontDropWeapon_copy
  - torann.CaravanOptions
  - Albion.GoExplore
  - DerekBickley.LegacyTerrainOverhaulFinal
  - MattTheWaz.WeaponsTab
  - Albion.Youwilldie
  - sulusdacor.james76543.Meltup.AdvancedPowerPlus
  - phomor.CraftingQualityRebalanced
  - Hol.Extrematorium
  - crewd.AdvancedTransportPods
  - lc.cheatspot
  - Edwiesel.SISsecuritypack
  - Daniledman.CombatUpdate
  - automatic.gunplay
  - com.yayo.combat3
  - nilchei.dynamicdiplomacy
  - dninemfive.advancedshieldbelts
  - UnlimitedHugs.DefensivePositions
  - LingLuo.MoveSteamGeyser
  - Alaestor.QuantumCooling
  - Owlchemist.BetterVanillaMasking
  - razor2.3.AnotherRimworldMod.AutoCutBlight
  - Uuugggg.BuildFromInventory
  - FrozenSnowFox.FilthVanishesWithRainAndTime
  - jkluch.HaulToStack
  - automatic.bionicicons
  - kikohi.cybernetic
  - Ykara.EPOE
  - Wemd.ReinforcedDoors
  - Hanhinen.TablesPlus
  - Linkolas.Stabilize
  - neceros.simpleturrets
  - kikohi.WaveSurvival
  - fluffy.stuffedfloors
  - miyamiya.dooraccelerator
  - CarnySenpai.LootingManager
  - Arekan.EnhancedCombatSounds
  - roolo.RunAndGun
  - telefonmast.graphicssettings
  - majorhoff.rimthreaded

**Screenshots**
![image](https://user-images.githubusercontent.com/47637050/104498765-6fb17900-55dc-11eb-9f49-f04fe67a1c18.png)

**Comment by Eldulac** [comment]
**[Tested on RT 1.3.2]**

I tested this issue on several fresh games, spawning dozens of pawns each time. I was not able to reproduce this issue.
Everything worked normally, despite using both "Camera+" and "Graphics Settings+" in conjunction with RT.

**Conclusion**
This issue has likely been fixed since the author experienced it, as it is no longer reproducible.
