### ISSUE TITLE
"Smart Medicine" Shells cannot be located for mortar (smart medicine errors in log)

### ISSUE THREAD

**Issue by Tschuangtse** [cseelhoff/RimThreaded#397]
Colonists are unable to man a mortar even when shells are right next to it. 
Furthermore, when forced to pick up any stack of items the items vanish.
They are taken from the stockpile but not added to the inventory.
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report.  

**To Reproduce**
1. Take any one pawn
2. Force the pawn to either man a mortar or pick up a stack of items
3. See Rimworld message that mortar cannot be maned or empty inventory

Logs, Modlist and Screenshot as archive.
[Bug.zip](https://github.com/cseelhoff/RimThreaded/files/5826069/Bug.zip)

**Comment by Niilo007** [comment]
Seems like smart medicine errors. Please try without smart medicine.

**Comment by Tschuangtse** [comment]
Confirmed; removed SmartMedicine. Issue can no longer be reproduced.

**Comment by 15adhami** [comment]
Tested with RT 1.3.2 and 2.0.7. No issues were found with mortars or picking up items from a stockpile.
