### ISSUE TITLE
drug usage generates red errors constantly, and drops TPS

### ISSUE THREAD

**Issue by pastorismylord** [cseelhoff/RimThreaded#406]
**Describe the bug**
using vanilla rim threaded (harmony, rimworld, royality and RimThreaded) when a pawn uses or is about to use a drug (I tested with smokeleaf joints) lots of drug policy related exceptions appear and TPS decreases from 6k to 2500.

**To Reproduce**
1, Have pawns assigned to any drug policy
2, wait until they hit the policy frequency
3, errors will appear

**Error Log**
log attached to the report
[Player.log](https://github.com/cseelhoff/RimThreaded/files/5833812/Player.log)
[Player-prev.log](https://github.com/cseelhoff/RimThreaded/files/5833813/Player-prev.log)

**Screenshots**

**Comment by pastorismylord** [comment]
These errors are game breaking if there's beer or any other drug that is used frequently

**Comment by kertiek** [comment]
i was able to reproduce the bug, but its not extreme, i spawned 1000 smoke joints and changed the drug policy to 10 x day for 20+ pawns

after a few days of smoking i just got the exception a few  times.


log:
[Player.log](https://github.com/cseelhoff/RimThreaded/files/5875949/Player.log)

save to replicate

[vanilla_rt_drug_issue.zip](https://github.com/cseelhoff/RimThreaded/files/5875926/vanilla_rt_drug_issue.zip)

**Comment by Pandemic223** [comment]
[Autosave-2.zip](https://github.com/cseelhoff/RimThreaded/files/5889058/Autosave-2.zip)
This is a save from the community modpack V1, but this save soon after you complete the raid, have the drugpolicy error completely bring the save to a standstill

**Comment by Niilo007** [comment]
This is a vanilla non rimthreaded bug, if you can believe that.

**Comment by Niilo007** [comment]
Hoff added a fix in RT version 1.2.6 v2
(even tho its a vanilla bug)
