### ISSUE TITLE
Caravan Bug (when cancelling a caravan)

### ISSUE THREAD

**Issue by Punderful20** [cseelhoff/RimThreaded#407]
**Describe the bug**
Game breaking Caravan bug.

**To Reproduce**
1. Form Caravan using World Map.
2. Cancel Caravan immediately by clicking on Pawn and clicking cancel.

**Error Log**
Does not crash the game.

**Screenshots**

**Comment by thefriendlycacti** [comment]
I can reproduce this with the following mods in this order:
Harmony
HugsLib
RimThreaded(1.2.4)

Hugs lib log: https://gist.github.com/ce76593d2cc853c53e112c3e89cbdc46

When the caravan is formed and unformed before leaving the map all pawns that would have gone with the said caravan are unable to get assigned jobs. and get a think node duty no duty. The pawns are able to be drafted and ordered to do tasks manually but as soon as the queue is up they return to a form of wonder.

Pawns affected by this bug are also unable to travel to selected for a new caravan.
![image](https://user-images.githubusercontent.com/13293946/105780277-f6435000-5f24-11eb-8f47-9f27854eda6b.png)

**Comment by bababooeyy** [comment]
This still occurs on 1.2.6 preview

Error Log:
https://gist.github.com/73d9afa6edb4c348d9cab48db712ff5b

Save File: 
https://drive.google.com/file/d/1fL6T2AEbAasgRe7cPYaU0_mkLr__brlj/view?usp=sharing

Would also like to mention that saving and reloading fixes the issue.

**Comment by bababooeyy** [comment]
No longer happens on 1.2.7
