### ISSUE TITLE
Impossible to operate normal

### ISSUE THREAD

**Issue by Shootnik01** [cseelhoff/RimThreaded#408]
**Describe the bug**
If you manage to perform an operation on pawn, the doctor just coming to patient and trying to do an operation without any item he need.

**To Reproduce**
1. Choose an operation
2. Choose a pawn-medic and start an operation
3. See, how he just come to recipient and try to perform an operation without any required item

**Error Log**
https://yadi.sk/d/0nG31fIYLw6LiQ - Player
https://yadi.sk/d/478xuI4dHF1mVw - Player-prev

**Mod List**
https://yadi.sk/d/b85g7EjNJtQFBw

**Screenshots**
![image](https://user-images.githubusercontent.com/75479005/105040199-9b1be400-5a72-11eb-93dd-89b974d40d30.png)
![image](https://user-images.githubusercontent.com/75479005/105040320-c1da1a80-5a72-11eb-8fdd-970fe6bfc54b.png)
![image](https://user-images.githubusercontent.com/75479005/105041129-ac192500-5a73-11eb-9416-615de2411bd0.png)

**Comment by Shootnik01** [comment]
Sorry for russian interface :)

**Comment by Niilo007** [comment]
Try replacing "EPOE" mod with "EPOE Forked" Here is link: https://steamcommunity.com/workshop/filedetails/?id=1949064302

**Comment by Shootnik01** [comment]
Nope, Installed this, started a new game, but pawn still trying to operate without requirements

**Comment by Niilo007** [comment]
Make sure you have the latest version of Rimthreaded (1.2.4 or later) there was a surgery bug in one of the older versions

**Comment by Shootnik01** [comment]
> Make sure you have the latest version of Rimthreaded (1.2.4 or later) there was a surgery bug in one of the older versions

Still nothing :\

**Comment by pastorismylord** [comment]
@Shootnik01 can you try to do operations without mods? Try doing operations on a vanilla game with rimthreaded loaded

**Comment by Shootnik01** [comment]
> @Shootnik01 can you try to do operations without mods? Try doing operations on a vanilla game with rimthreaded loaded

Sorry for not answering. i'll send it in an hour

**Comment by Shootnik01** [comment]
https://www.d20pfsrd.com

**Comment by Shootnik01** [comment]
https://yadi.sk/d/Z5a6MvCFU3j1yg

**Comment by Shootnik01** [comment]
There can be a little difference in mod list, but my last mod config should work just fine
