### ISSUE TITLE
Pawns not extinguingishing fires

### ISSUE THREAD

**Issue by Wad67** [cseelhoff/RimThreaded#41]
No other mods enabled

Pawns will not automatically fight fires in their home region.
They will still fight fires when explicitly ordered to do so

**Comment by cseelhoff** [comment]
Thanks for the bug report! I have an idea what might be causing this

**Comment by cseelhoff** [comment]
Problem is in Pawn_WorkSettings_Patch.CacheWorkGiversInOrder()
