### ISSUE TITLE
"Adeptus Mechanicus: Magos Xenobiologis" CTD When Adeptus Mechanicus Mod creates Deep Strike raid type

### ISSUE THREAD

**Issue by TheIvoryDisaster** [cseelhoff/RimThreaded#410]
**Describe the bug**
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report.  

**To Reproduce**
1. Be using this other mod: https://steamcommunity.com/sharedfiles/filedetails/?id=1541499916&searchtext=adeptus+mechanicus
2. Let that mod trigger a raid event of the 'Deep Strike' variant (according to the logs, this seems to trigger some lightning / teleportation effects

**Error Log**
Player.log: https://pastebin.com/i6vegcmv
Error.log: https://pastebin.com/q40tFs70

**Mod List**
Paste contents of ModList used when bug occurred.
  - brrainz.harmony
  - Ludeon.RimWorld
  - Ludeon.RimWorld.Royalty
  - UnlimitedHugs.HugsLib
  - jecrell.jecstools
  - OskarPotocki.VanillaFactionsExpanded.Core
  - erdelf.HumanoidAlienRaces
  - GT.Sam.Furnace
  - fluffy.colonymanager
  - EdB.PrepareCarefully
  - Haplo.Miscellaneous.Core
  - Haplo.Miscellaneous.Endgame
  - aRandomKiwi.MercenariesForMe
  - twistedpacifist.ReasonableComponents
  - Dylan.CSL
  - Saakra.Empire
  - Goldminermac.Empireexpandedresourcebuildings
  - Orion.Hospitality
  - tammybee.statueofcolonist
  - Vanya.Polarisbloc.CoreLab
  - Vanya.Polarisbloc.SecurityForce
  - Vanya.Polarisbloc.Mechenemy
  - Vanya.Polarisbloc.StorytellerIncidentsPack
  - Babo.Multilopes.Multilopes
  - Ogre.NanoRepairTech
  - Uuugggg.ShareTheLoad
  - Uuugggg.UseBedrolls
  - Uuugggg.ThickArmor
  - tradingspot.kv.rw
  - Dubwise.Rimatomics
  - erdelf.MinifyEverything
  - leafzxg.ThrumboExtension
  - Indeed.StackXXL
  - hatti.qualitybuilder
  - spoonshortage.ADogSaidAnimalProsthetics
  - GHXX.TechAdvancing
  - ratys.rtfuse
  - TheBird956.DoublePopulation
  - Ykara.EPOE
  - PinoChemicali.MoreTradeShips
  - fluffy.medicaltab
  - Orion.XevaRimhair
  - Uuugggg.MealsOnWheels
  - Oblitus.AnimalsLogic
  - crlsniper.realisticroomslite
  - postrobcore.feedthecolonists
  - ratys.rtsolarflareshield
  - sargoskar.witcherhunt
  - dismarzero.VGP.VGPVegetableGarden
  - dismarzero.VGP.VGPGardenCanning
  - dismarzero.VGP.VGPGardenFabrics
  - dismarzero.VGP.VGPGardenDyes
  - dismarzero.VGP.VGPGardenDyesExpanded
  - dismarzero.VGP.VGPGardenGourmet
  - dismarzero.VGP.VGPGardenMedicine
  - dismarzero.VGP.VGPMoreVeggies
  - dismarzero.VGP.VGPGardenResources
  - dismarzero.VGP.VGPSoylentProduction
  - dismarzero.VGP.VGPThreeSistersPlants
  - dismarzero.VGP.VGPGardenTools
  - dismarzero.VGP.XtraTreesandFlowers
  - QX.AstraMilitarum
  - QX.AstraMilitarum.Factions
  - Ogliss.AdMech.Armoury
  - Ogliss.AdMech.Xenobiologis
  - Ogliss.TheWhiteCrayon.Quarry
  - VanillaExpanded.VCEF
  - kentington.saveourship2
  - factioncontrol.kv.rw
  - configurablemaps.kv.rw
  - Atlas.AndroidTiers
  - zzz.WallVitalsMonitor
  - Rikiki.MiningCo.Spaceship
  - Orion.MoreMechanoids
  - Rikiki.MiningCo.Mms
  - UnlimitedHugs.RemoteTech
  - Rikiki.MiningCo.DrillTurret
  - nephlite.orbitaltradecolumn
  - Supes.PowerLogic.Core
  - RadZerp.neoRimNauts
  - sarg.alphaships
  - 8Z.DormitoriesNotBarracks
  - Ogliss.Dalrae.BloodPack
  - zymex.prf.lite
  - OskarPotocki.VFE.Mechanoid
  - Dubwise.DubsPerformanceAnalyzer
  - majorhoff.rimthreaded
**Screenshots**
![image](https://user-images.githubusercontent.com/17211998/105580672-cbf26680-5d5b-11eb-8f66-8b7e68f6bdfa.png)

**Comment by pastorismylord** [comment]
@TheIvoryDisaster can you please try it again with the latest version of RimThreaded published on RimThreaded's Discord? version 2.X fixes most of the issues you were facing here.
