### ISSUE TITLE
facial animation mod (made by Nals) make saved and game new game freeze and crash the game

### ISSUE THREAD

**Issue by Vanquisher02** [cseelhoff/RimThreaded#414]
hello, 

as sayed in title i noticed incompality facial stuff mod ([NL] facial animation) making freeze and crash rim after load a saved (or not) game

To Reproduce
Steps to reproduce the behavior
1. install this mod from the link https://steamcommunity.com/sharedfiles/filedetails/?id=1635901197&searchtext=nl
2. activate the mentioned mod with rimthreaded
3. after reboot rim, load a saved game or star a new one, 
4. no problem during the loading, but when started the game, the game freeze quickly after ~3sec and CRASH

Error Log:
sorry i don't know how should i do but i hope the steps for reproducing bug is enough

Screenshots:
even with a screenshot that won't help much, like i sayed the game frezze and crach after loaded the game

i think i give all info you needed, i don't know if you plan to make a compatibility for this mod but please do something, your mod is awesome and i need the facial stuff for keep my game living and animated

thank in advance

**Comment by thefriendlycacti** [comment]
I am unable to reproduce any rimworld freeze, crash or TPS slowdown with the following mods in the following order:
Harmony
Core
Royalty
HugsLib
[NL] Facial Animation
RimThreaded(1.2.4)
---------------------------------
My hugs lib log upload can be found here https://gist.github.com/HugsLibRecordKeeper/0ebb2f45ebf07f17b089d3f1cd07a6a4 with nothing outside the normal.

This could be a mod load issue or two mods interacting with each other outside Rimthreaded. Should you need help with this please reach out on the discord for assistance. https://discord.gg/3JJuWK8
