### ISSUE TITLE
"Awesome Inventory" A bug in the opened door with "awesome inventory & achctung"

### ISSUE THREAD

**Issue by GitHubDeadTree** [cseelhoff/RimThreaded#415]
![20210125113902_1](https://user-images.githubusercontent.com/77949417/105658998-9feff600-5ebf-11eb-9d09-4d55c1089847.png)

everytimes i let my pawns right-click on an object between a opened door, a red letter will be appeared and there is no response so I had to remove the door to get the object

**To Reproduce**
I send a picture

**Error Log**
Root level exception in OnGUI(): System.NullReferenceException: Object reference not set to an instance of an object
  at (wrapper dynamic-method) RimWorld.FloatMenuMakerMap.RimWorld.FloatMenuMakerMap.ChoicesAtFor_Patch2(UnityEngine.Vector3,Verse.Pawn)
  at AchtungMod.MultiActions.AddColonist (AchtungMod.Colonist colonist) [0x0001f] in <831e973d9245449bbdebd2f42c6b55fa>:0 
  at AchtungMod.MultiActions.<.ctor>b__3_0 (AchtungMod.Colonist colonist) [0x00000] in <831e973d9245449bbdebd2f42c6b55fa>:0 
  at AchtungMod.Tools.Do[T] (System.Collections.Generic.IEnumerable`1[T] sequence, System.Action`1[T] action) [0x00014] in <831e973d9245449bbdebd2f42c6b55fa>:0 
  at AchtungMod.MultiActions..ctor (System.Collections.Generic.IEnumerable`1[T] colonists, UnityEngine.Vector3 clickPos) [0x00018] in <831e973d9245449bbdebd2f42c6b55fa>:0 
  at AchtungMod.Controller.MouseDown (UnityEngine.Vector3 pos) [0x00076] in <831e973d9245449bbdebd2f42c6b55fa>:0 
  at AchtungMod.Controller.HandleEvents () [0x0002f] in <831e973d9245449bbdebd2f42c6b55fa>:0 
  at AchtungMod.Selector_HandleMapClicks_Patch.Prefix () [0x00005] in <831e973d9245449bbdebd2f42c6b55fa>:0 
  at (wrapper dynamic-method) RimWorld.Selector.RimWorld.Selector.HandleMapClicks_Patch1(RimWorld.Selector)
  at RimWorld.Selector.SelectorOnGUI () [0x00000] in <d72310b4d8f64d25aee502792b58549f>:0 
  at RimWorld.MapInterface.HandleLowPriorityInput () [0x0000f] in <d72310b4d8f64d25aee502792b58549f>:0 
  at (wrapper dynamic-method) RimWorld.UIRoot_Play.RimWorld.UIRoot_Play.UIRootOnGUI_Patch1(RimWorld.UIRoot_Play)
  at (wrapper dynamic-method) Verse.Root.Verse.Root.OnGUI_Patch1(Verse.Root)
Verse.Log:Verse.Log.Error_Patch2(String, Boolean)
Verse.Root:Verse.Root.OnGUI_Patch1(Root)

**Mod List**
Version: 1
Name: ..
Mods:
- Id: brrainz.harmony
  Name: Harmony
- Id: ludeon.rimworld
  Name: Core（核心）
- Id: ludeon.rimworld.royalty
  Name: Royalty（皇权）
- Id: unlimitedhugs.hugslib
  Name: HugsLib
- Id: rwzh.chinesepack.hugslib
  Name: HugsLib_zh
- Id: saucypigeon.realisticplanets
  Name: Realistic Planets - Fan Update
- Id: ghsgkd.realisticplanetszh
  Name: Realistic Planets_ZH
- Id: shavius.vbookse.zh
  Name: Vanilla Books Expanded 原版书籍扩展 简繁汉化包
- Id: shavius.variousspaceshipchunk.zh
  Name: Various Space Ship Chunk 更多飞船残骸简繁汉化包
- Id: oblitus828.animalshlogicuzh
  Name: Animals Logic_zh
- Id: vanillaexpanded.vee
  Name: Vanilla Events Expanded
- Id: rwzh.chinesepack.vanillaexpandedvee
  Name: Vanilla_Events_Expanded_zh
- Id: xun.srtsexpanded
  Name: '[汉化包] SRTS-飞船拓展 SRTS Expanded'
- Id: xun.dubsmintmenus
  Name: '[汉化包] Dubs的详细菜单 Dubs Mint Menus'
- Id: captainsnafu.veanimalsallchinese
  Name: 原版扩展：动物合集 VE Animals — ALL Chinese Pack
- Id: notooshabby.awesomeinventory
  Name: Awesome Inventory
- Id: brrainz.achtung
  Name: Achtung!
- Id: rwzh.chinesepack.achtung
  Name: Achtung!_zh
- Id: shavius.vfemechanoids.zh
  Name: Vanilla Factions Expanded - Mechanoids 机械族派系扩展简繁汉化包
- Id: zephyr.pi.jfhj
  Name: Project Itzal 简繁汉化合集
- Id: itzal.pi.mp
  Name: Project Itzal - Main Pack
- Id: itzal.vw.cp
  Name: Project Itzal - Community Pack
- Id: itzal.pi.sd
  Name: Project Itzal - Special Delivery
- Id: itzal.vw.eg
  Name: Project Itzal - Extra Guns
- Id: itzal.pi.cp
  Name: Project Itzal - Charge Pack
- Id: itzal.vw.emg
  Name: Project Itzal - Even More Guns
- Id: vanillaexpanded.varme
  Name: Vanilla Armour Expanded
- Id: vanillaexpanded.vwe
  Name: Vanilla Weapons Expanded
- Id: vanillaexpanded.vweq
  Name: Vanilla Weapons Expanded - Quickdraw
- Id: rwzh.chinesepack.vwaae
  Name: Vanilla_Weapons_Apparel_Armour_Expanded_zh_pack
- Id: oskarpotocki.vanillafactionsexpanded.core
  Name: Vanilla Expanded Framework
- Id: oskarpotocki.vanillaexpanded.royaltypatches
  Name: Vanilla Expanded - Royalty Patches
- Id: vanillaexpanded.vfecore
  Name: Vanilla Furniture Expanded
- Id: vanillaexpanded.vfeart
  Name: Vanilla Furniture Expanded - Art
- Id: vanillaexpanded.vfemedical
  Name: Vanilla Furniture Expanded - Medical Module
- Id: vanillaexpanded.vfeproduction
  Name: Vanilla Furniture Expanded - Production
- Id: vanillaexpanded.vfesecurity
  Name: Vanilla Furniture Expanded - Security
- Id: vanillaexpanded.vfespacer
  Name: Vanilla Furniture Expanded - Spacer Module
- Id: rwzh.chinesepack.vfe
  Name: Vanilla_Furniture_Expanded_zh_pack
- Id: oskarpotocki.vfe.mechanoid
  Name: Vanilla Factions Expanded - Mechanoids
- Id: daniledman.cyberfauna
  Name: Cyber Fauna 1.2
- Id: rimsenal.core
  Name: Rimsenal - Core
- Id: rimsenal.hair
  Name: Rimsenal - Rimhair
- Id: rimsenal.security
  Name: Rimsenal - Security pack
- Id: rimsenal.feral
  Name: Rimsenal - Feral Faction Pack
- Id: rimsenal.federation
  Name: Rimsenal - Federation Faction Pack
- Id: rimsenal.evp
  Name: Rimsenal - Enhanced Vanilla Pack
- Id: rwzh.chinesepack.rimsenal
  Name: Rimsenal_zh_pack
- Id: brrainz.rangefinder
  Name: Range Finder
- Id: rwzh.chinesepack.rangefinder
  Name: Range_Finder_zh
- Id: nephlite.orbitaltradecolumn
  Name: Utility Columns
- Id: rwzh.chinesepack.orbitaltradecolumn
  Name: Utility_Columns_zh
- Id: timmyliang.tradehelper
  Name: TradeHelper
- Id: insertkey.itemlistselector
  Name: ItemListSelector
- Id: jecrell.jecstools
  Name: JecsTools
- Id: notooshabby.homemover
  Name: Home Mover
- Id: arandomkiwi.killforme
  Name: Kill For Me
- Id: mlie.lessarbitrarysurgery
  Name: Less Arbitrary Surgery (Continued)
- Id: mlie.lessstupidromanceattempt
  Name: Less Stupid Romance Attempt (Continued)
- Id: krafs.levelup
  Name: Level Up!
- Id: linkolas.stabilize
  Name: Stabilize
- Id: smashphil.loadinginprogress
  Name: Loading In Progress
- Id: com.prostheticnomissingbodyparts.rimworld.mod
  Name: Prosthetic No Missing Body Parts
- Id: ratys.madskills
  Name: Mad Skills
- Id: boxrsxx.morepracticaltraits
  Name: More Practical Traits
- Id: bichang.moresculpture
  Name: More Sculpture
- Id: hobtook.mortaraccuracy
  Name: Mortar Accuracy
- Id: lingluo.movesteamgeyser
  Name: '[Ling]Move Steam Geyser'
- Id: bar0th.norandomrelations
  Name: No Random Relations
- Id: paragon.hanul.utility
  Name: NoArmorPointCap
- Id: ogre.ogrestack
  Name: OgreStack
- Id: rwzh.chinesepack.ogrestack
  Name: OgreStack_zh
- Id: pathavoid.kv.rw
  Name: '[KV] Path Avoid'
- Id: fed1splay.pawntargetfix
  Name: PawnTargetFix
- Id: fluffy.pharmacist
  Name: Pharmacist
- Id: peppsen.pmusic
  Name: P-Music
- Id: shotgunfrenzy.prioritytreatment
  Name: '[SF] Priority treatment 1.1'
- Id: crlsniper.realisticrooms
  Name: Realistic Rooms
- Id: jaxe.rimhud
  Name: RimHUD
- Id: shouer.chinesepack.rimhud
  Name: RimHUD_zh
- Id: ryder.satisfiedstorage
  Name: SatisfiedStorage
- Id: savestoragesettings.kv.rw
  Name: '[KV] Save Storage, Outfit, Crafting, Drug, & Operation Settings'
- Id: uuugggg.sharetheload
  Name: Share The Load
- Id: targhetti.showdrafteesweapon
  Name: Show Draftees Weapon
- Id: showhair.kv.rw
  Name: '[KV] Show Hair With Hats or Hide All Hats'
- Id: erdelf.showmoddesignators
  Name: ShowModDesignators
- Id: dhultgren.keepbedownership
  Name: Keep Bed Ownership
- Id: gguake.ui.simplesearchbar
  Name: Simple Search Bar
- Id: petetimessix.simplesidearms
  Name: Simple sidearms
- Id: nilchei.powerfulfactionbases
  Name: Powerful Faction Bases
- Id: vanillaexpanded.vaeas
  Name: Vanilla Animals Expanded — Arid Shrubland
- Id: vanillaexpanded.vaeau
  Name: Vanilla Animals Expanded — Australia
- Id: vanillaexpanded.vaebf
  Name: Vanilla Animals Expanded — Boreal Forest
- Id: vanillaexpanded.vaecd
  Name: Vanilla Animals Expanded — Cats and Dogs
- Id: vanillaexpanded.vaed
  Name: Vanilla Animals Expanded — Desert
- Id: vanillaexpanded.vaeed
  Name: Vanilla Animals Expanded — Extreme Desert
- Id: vanillaexpanded.vaeis
  Name: Vanilla Animals Expanded — Ice Sheet
- Id: vanillaexpanded.vaetr
  Name: Vanilla Animals Expanded — Tropical Rainforest
- Id: vanillaexpanded.vaets
  Name: Vanilla Animals Expanded — Tropical Swamp
- Id: vanillaexpanded.vaet
  Name: Vanilla Animals Expanded — Tundra
- Id: mlie.variousspaceshipchunk
  Name: Various Space Ship Chunk (Continued)
- Id: neceros.antigrain
  Name: Antigrain
- Id: notfood.mendandrecycle
  Name: MendAndRecycle
- Id: rimfridge.kv.rw
  Name: '[KV] RimFridge'
- Id: murmur.walllight
  Name: Wall Light
- Id: leafzxg.thrumboextension
  Name: Thrumbo Extension
- Id: vat.epoeforked
  Name: Expanded Prosthetics and Organ Engineering - Forked
- Id: rwzh.chinesepack.epoeforked
  Name: Expanded_Prosthetics_and_Organ_Engineering_Forked_zh
- Id: troopersmith1.lifesupport
  Name: Life Support Continued [1.1][1.2]
- Id: smashphil.neceros.srtsexpanded
  Name: SRTS Expanded
- Id: won.hair
  Name: Won hair_men
- Id: won2.hair
  Name: 'Won hair_women '
- Id: vanya.tools.incidentpersonstat
  Name: Incident Person Stat
- Id: mlie.rimquest
  Name: RimQuest (Continued)
- Id: rwzh.chinesepack.rimquest
  Name: RimQuest_zh
- Id: fluffy.animaltab
  Name: Animal Tab
- Id: fluffy.worktab
  Name: Work Tab
- Id: fluffy.followme
  Name: Follow Me
- Id: nals.facialanimation
  Name: '[NL] Facial Animation - WIP'
- Id: lingluo.preparecarefully
  Name: EdB Prepare Carefully_zh
- Id: dubwise.dubsmintmenus
  Name: Dubs Mint Menus
- Id: eagle0600.dresspatients
  Name: Dress Patients
- Id: rwzh.chinesepack.dresspatients
  Name: Dress_Patients_zh
- Id: arandomkiwi.downforme
  Name: Down For Me
- Id: tikubonn.dontblockdoor
  Name: DontBlockDoor[1.0-1.2]
- Id: linq.deathrattle
  Name: Death Rattle Unofficial
- Id: unlimitedhugs.defensivepositions
  Name: Defensive Positions
- Id: nals.customportraits
  Name: '[NL] Custom Portraits'
- Id: uuugggg.gearupandgo
  Name: Gear Up And Go
- Id: awesomezh.inventory
  Name: ' Awesome Inventory - 超赞的RPG装备栏 - 汉化包'
- Id: mlie.pickupandhaul
  Name: Pick Up And Haul (Continued)
- Id: vanillaexpanded.vtexe
  Name: Vanilla Textures Expanded
- Id: meltup.beautifuloutdoors
  Name: Beautiful Outdoors
- Id: nals.chibifacemale
  Name: '[NL] Chibi Face Male only'
- Id: nals.chibifacefemale
  Name: '[NL] Chibi Face Female only'
- Id: dylan.csl
  Name: Children, school and learning
- Id: verdiss.fasteraging
  Name: Faster Aging
- Id: brrainz.cameraplus
  Name: Camera+
- Id: fluffy.blueprints
  Name: Blueprints
- Id: roolo.almostthere
  Name: Almost There!
- Id: odeum.wmbp
  Name: World Map Beautification Project
- Id: falconne.bwm
  Name: Better Workbench Management
- Id: madeline.modmismatchformatter
  Name: Better ModMismatch Window
- Id: voult.betterpawncontrol
  Name: Better Pawn Control
- Id: mlie.stockpilestacklimit
  Name: Stockpile Stack Limit (Continued)
- Id: neptimus7.progressrenderer
  Name: Progress Renderer
- Id: automatic.bionicicons
  Name: Bionic icons
- Id: co.uk.epicguru.timelapse2000
  Name: Timelapse 2000
- Id: oblitus.animalslogic
  Name: Animals Logic
- Id: unlimitedhugs.allowtool
  Name: Allow Tool
- Id: uuugggg.listeverything
  Name: List Everything
- Id: telefonmast.graphicssettings
  Name: Graphics Settings+
- Id: dubwise.dubsperformanceanalyzer
  Name: Dubs Performance Analyzer
- Id: majorhoff.rimthreaded
  Name: RimThreaded [1.2]
- Id: user19990313.runtimegc
  Name: RuntimeGC
- Id: fluffy.modmanager
  Name: Mod Manager

**Screenshots**
![20210125113902_1](https://user-images.githubusercontent.com/77949417/105659022-aaaa8b00-5ebf-11eb-8fa2-8640243a0d5d.png)
![20210125113902_1](https://user-images.githubusercontent.com/77949417/105659028-b007d580-5ebf-11eb-8ece-4f0c03506df4.png)

**Comment by pastorismylord** [comment]
that is an Achtung error, please try performing that action without Achtung on your modlist

**Comment by GitHubDeadTree** [comment]
> that is an Achtung error, please try performing that action without Achtung on your modlist

i found that reason is awesome inventory but i don't know why there can be a bug between them

**Comment by GitHubDeadTree** [comment]
after i remove awesome inventory,it backed to normal
here is the log

Root level exception in OnGUI(): System.NullReferenceException: Object reference not set to an instance of an object
  at AwesomeInventory.ApparelOptionUtility.CanWear (Verse.Pawn pawn, RimWorld.Apparel apparel) [0x00024] in <808a267935e34741873c701036871b19>:0 
  at AwesomeInventory.Common.HarmonyPatches.AddHumanlikeOrders_AwesomeInventory_Patch.Postfix (UnityEngine.Vector3 clickPos, Verse.Pawn pawn, System.Collections.Generic.List`1[T] opts) [0x002ef] in <808a267935e34741873c701036871b19>:0 
  at (wrapper dynamic-method) RimWorld.FloatMenuMakerMap.RimWorld.FloatMenuMakerMap.AddHumanlikeOrders_Patch9(UnityEngine.Vector3,Verse.Pawn,System.Collections.Generic.List`1<Verse.FloatMenuOption>)
  at RimWorld.FloatMenuMakerMap.ChoicesAtFor (UnityEngine.Vector3 clickPos, Verse.Pawn pawn) [0x0008c] in <d72310b4d8f64d25aee502792b58549f>:0 
  at RimWorld.FloatMenuMakerMap.TryMakeFloatMenu (Verse.Pawn pawn) [0x00056] in <d72310b4d8f64d25aee502792b58549f>:0 
  at RimWorld.Selector.HandleMapClicks () [0x000af] in <d72310b4d8f64d25aee502792b58549f>:0 
  at RimWorld.Selector.SelectorOnGUI () [0x00000] in <d72310b4d8f64d25aee502792b58549f>:0 
  at RimWorld.MapInterface.HandleLowPriorityInput () [0x0000f] in <d72310b4d8f64d25aee502792b58549f>:0 
  at (wrapper dynamic-method) RimWorld.UIRoot_Play.RimWorld.UIRoot_Play.UIRootOnGUI_Patch1(RimWorld.UIRoot_Play)
  at (wrapper dynamic-method) Verse.Root.Verse.Root.OnGUI_Patch1(Verse.Root)
Verse.Log:Verse.Log.Error_Patch2(String, Boolean)
Verse.Root:Verse.Root.OnGUI_Patch1(Root)

**Comment by pastorismylord** [comment]
@Niilo007 can you please retest with 2.2.8? you were the original tester for this issue, thanks

**Comment by pastorismylord** [comment]
PooperRulz mentions this issue has been solved on 2.3.6
