### ISSUE TITLE
"Dubs Bad Hygiene" "Hold open" doesn't work with "Dub's bad hygiene"

### ISSUE THREAD

**Issue by Niilo007** [cseelhoff/RimThreaded#416]
**Describe the bug**
"Hold open" toggle resets when a pawn walks thru the door.

**To Reproduce**
1. Load any save
2. Designate a door to be held open
3. Draft a pawn and make them walk thru it
4. The door is now held open
5. Make the pawn go thru the door again.
6. The door closes

**Comment by doc776** [comment]
I actually noticed if you click hold open again after they started walking out of the cell, it will stay open. Pls confirm

**Comment by Nextia-Git** [comment]
Did some more testing into this issue and have found Dub Bad Hygiene to be a near probable cause of this. Tested without Dubs and doors are held open just fine and are working as intended, enabled Dubs and this issue immediately came back. 

Very reproducable, all you need to do is enable both RT and Dubs Bad Hygiene, start a new world, force a door to be held open and bam, bug rears it's head. Recorded some footage below to show consistency of bug.

https://www.youtube.com/watch?v=kaXpNjXE7tE

**Comment by Niilo007** [comment]
Confirmed to be dubs hygiene 100%

**Comment by Niilo007** [comment]
Seems to have been fixed on the dubs side with their recent update

Tested by Nextia and me.
