### ISSUE TITLE
"Best Mix" mod Very Long Thread Timeout. (best mix breaks bills too)

### ISSUE THREAD

**Issue by bababooeyy** [cseelhoff/RimThreaded#419]
Threads timeout even when set to 30000ms when a quest expires with Best Mix active. This did not occur on the same save when it was only Vanilla + RT.
There was also a red error message described by ZeroesAesyr as 'really bad' on startup of RImworld after the addition of Best Mix.

**To Reproduce**
1. Open Rimworld with Best Mix and RT active
2. Observe any errors on startup.
3. Begin a new save or an already existing save.
4. Wait for a quest to expire.
5. Observe thread timeout error.

**Error Log**
https://gist.github.com/06884dc615fbdb2f8129939cc2c9a6ba

**Save File**
Attached below. Autosave is just before the thread timeout error occurs, named save is just after.

Autosave
https://drive.google.com/file/d/1eqdIg2JYA5O1P7P-1Qm2T36SCEeKGWKA/view?usp=sharing

Named Save
https://drive.google.com/file/d/1aiy3AS8oG7VG4fsoDDf51SK8Z_2_MC9I/view?usp=sharing

**Comment by Niilo007** [comment]
Best Mix is a known incompatible mod

**Comment by Niilo007** [comment]
i tested this with the 2.0.X previews this mod still doesn't work on RT 2.0.5

**Comment by Niilo007** [comment]
https://gist.github.com/a2967200ef5c7994194f5917229aca79

**Comment by pastorismylord** [comment]
@Niilo007 plase test with the latest 2.1.x and let us know

**Comment by bababooeyy** [comment]
[Tested with 2.1.5]

Error on startup: 
IL code instruction set 6 not found
Verse.Log:Error(String, Boolean)
RimThreaded.<TryFindBestBillIngredients>d__1:MoveNext()
System.Collections.Generic.List`1:.ctor(IEnumerable`1)
System.Linq.Enumerable:ToList(IEnumerable`1)
HarmonyLib.CodeTranspiler:GetResult(ILGenerator, MethodBase)
HarmonyLib.MethodBodyReader:FinalizeILCodes(Emitter, List`1, List`1, Boolean&)
HarmonyLib.MethodCopier:Finalize(Emitter, List`1, Boolean&)
HarmonyLib.MethodPatcher:CreateReplacement(Dictionary`2&)
HarmonyLib.PatchFunctions:UpdateWrapper(MethodBase, PatchInfo)
HarmonyLib.PatchProcessor:Patch()
HarmonyLib.Harmony:Patch(MethodBase, HarmonyMethod, HarmonyMethod, HarmonyMethod, HarmonyMethod)
RimThreaded.RimThreadedHarmony:Transpile(Type, Type, String, Type[], String[])
RimThreaded.WorkGiver_DoBill_Transpile:RunNonDestructivePatches()
RimThreaded.RimThreadedHarmony:PatchNonDestructiveFixes()
RimThreaded.RimThreadedHarmony:.cctor()
System.Runtime.CompilerServices.RuntimeHelpers:RunClassConstructor(IntPtr)
System.Runtime.CompilerServices.RuntimeHelpers:RunClassConstructor(RuntimeTypeHandle)
Verse.StaticConstructorOnStartupUtility:CallAll()
Verse.<>c:<DoPlayLoad>b__4_2()
Verse.LongEventHandler:ExecuteToExecuteWhenFinished()
Verse.LongEventHandler:UpdateCurrentAsynchronousEvent()
Verse.LongEventHandler:LongEventsUpdate(Boolean&)
Verse.Root:Verse.Root.Update_Patch1(Root)
Verse.Root_Entry:Update()

Bills are all still broken, when trying to manual prioritise a bunch of errors happen, GUI error and Cant HaulToStorageJob. 
Could not find good sleeping spot is also spammed, unrelated to priorotising jobs.
https://gist.github.com/86de56bbda9de57a1bb9f7f1c2c5f558

**Comment by Niilo007** [comment]
Still doesn't work in 2.2.7

**Comment by pO0P3R125** [comment]
it is working on beta 2.3.3.7, extensive testing may be needed but in community modpack put almost in the end is working correctly, I have used it quite a bit and haven't had any error
