### ISSUE TITLE
UI Disappearing after latest update

### ISSUE THREAD

**Issue by TheyCallMeAmi** [cseelhoff/RimThreaded#42]
Getting this spam in console on the latest update:

Exception drawing ThingOverlay for Ami: System.NullReferenceException: Object reference not set to an instance of an object
  at RimThreaded.Building_Door_Patch.get_DoorPowerOn (RimWorld.Building_Door __instance, System.Boolean& __result) [0x00011] in <3068906bf2df42b090c8d6bd4c889e43>:0 
  at (wrapper dynamic-method) RimWorld.Building_Door.RimWorld.Building_Door.get_DoorPowerOn_Patch1(RimWorld.Building_Door)
  at RimWorld.Building_Door.get_SlowsPawns () [0x00000] in <7b345446a85d4ed599f9c604ae61854b>:0 
  at Verse.AI.Pawn_PathFollower.NextCellDoorToWaitForOrManuallyOpen () [0x0001f] in <7b345446a85d4ed599f9c604ae61854b>:0 
  at Verse.PawnTweener.MovedPercent () [0x00048] in <7b345446a85d4ed599f9c604ae61854b>:0 
  at Verse.PawnTweener.TweenedPosRoot () [0x00021] in <7b345446a85d4ed599f9c604ae61854b>:0 
  at Verse.PawnTweener.ResetTweenedPosToRoot () [0x00000] in <7b345446a85d4ed599f9c604ae61854b>:0 
  at Verse.PawnTweener.PreDrawPosCalculation () [0x0001d] in <7b345446a85d4ed599f9c604ae61854b>:0 
  at (wrapper dynamic-method) Verse.Pawn_DrawTracker.Verse.Pawn_DrawTracker.get_DrawPos_Patch2(Verse.Pawn_DrawTracker)
  at Verse.Pawn.get_DrawPos () [0x00006] in <7b345446a85d4ed599f9c604ae61854b>:0 
  at Verse.GenMapUI.LabelDrawPosFor (Verse.Thing thing, System.Single worldOffsetZ) [0x00000] in <7b345446a85d4ed599f9c604ae61854b>:0 
  at (wrapper dynamic-method) Verse.PawnUIOverlay.Verse.PawnUIOverlay.DrawPawnGUIOverlay_Patch4(Verse.PawnUIOverlay)
  at Verse.Pawn.DrawGUIOverlay () [0x00006] in <7b345446a85d4ed599f9c604ae61854b>:0 
  at (wrapper dynamic-method) Verse.ThingOverlays.Verse.ThingOverlays.ThingOverlaysOnGUI_Patch1(Verse.ThingOverlays)
Verse.Log:Error(String, Boolean)
Verse.ThingOverlays:Verse.ThingOverlays.ThingOverlaysOnGUI_Patch1(ThingOverlays)
RimWorld.MapInterface:RimWorld.MapInterface.MapInterfaceOnGUI_BeforeMainTabs_Patch1(MapInterface)
RimWorld.UIRoot_Play:UIRootOnGUI()
Verse.Root:Verse.Root.OnGUI_Patch1(Root)

and this

Root level exception in OnGUI(): System.NullReferenceException: Object reference not set to an instance of an object
  at RimThreaded.Building_Door_Patch.get_DoorPowerOn (RimWorld.Building_Door __instance, System.Boolean& __result) [0x00011] in <3068906bf2df42b090c8d6bd4c889e43>:0 
  at (wrapper dynamic-method) RimWorld.Building_Door.RimWorld.Building_Door.get_DoorPowerOn_Patch1(RimWorld.Building_Door)
  at RimWorld.Building_Door.get_SlowsPawns () [0x00000] in <7b345446a85d4ed599f9c604ae61854b>:0 
  at Verse.AI.Pawn_PathFollower.NextCellDoorToWaitForOrManuallyOpen () [0x0001f] in <7b345446a85d4ed599f9c604ae61854b>:0 
  at Verse.PawnTweener.MovedPercent () [0x00048] in <7b345446a85d4ed599f9c604ae61854b>:0 
  at Verse.PawnTweener.TweenedPosRoot () [0x00021] in <7b345446a85d4ed599f9c604ae61854b>:0 
  at Verse.PawnTweener.ResetTweenedPosToRoot () [0x00000] in <7b345446a85d4ed599f9c604ae61854b>:0 
  at Verse.PawnTweener.PreDrawPosCalculation () [0x0001d] in <7b345446a85d4ed599f9c604ae61854b>:0 
  at (wrapper dynamic-method) Verse.Pawn_DrawTracker.Verse.Pawn_DrawTracker.get_DrawPos_Patch2(Verse.Pawn_DrawTracker)
  at Verse.Pawn.get_DrawPos () [0x00006] in <7b345446a85d4ed599f9c604ae61854b>:0 
  at Verse.TooltipGiverList.DispenseAllThingTooltips () [0x0009c] in <7b345446a85d4ed599f9c604ae61854b>:0 
  at (wrapper dynamic-method) RimWorld.MapInterface.RimWorld.MapInterface.MapInterfaceOnGUI_BeforeMainTabs_Patch1(RimWorld.MapInterface)
  at RimWorld.UIRoot_Play.UIRootOnGUI () [0x0001f] in <7b345446a85d4ed599f9c604ae61854b>:0 
  at (wrapper dynamic-method) Verse.Root.Verse.Root.OnGUI_Patch1(Verse.Root)
Verse.Log:Error(String, Boolean)
Verse.Root:Verse.Root.OnGUI_Patch1(Root)

Game crashed shortly after this started, not sure if related but I'll throw it in just in case.

========== OUTPUTTING STACK TRACE ==================

0x00007FFDC75ABD1A (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC057 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC2B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC2B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC2B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC2B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC2B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC2B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC2B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC2B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC2B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC2B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC2B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC2B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC2B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC2B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC2B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC2B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC2B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC2B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC2B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC2B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC2B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC2B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC06B (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75ABC78 (mono-2.0-bdwgc) mono_object_is_alive
0x00007FFDC75AC73D (mono-2.0-bdwgc) mono_unity_liveness_calculation_from_statics
0x00007FFDB17099AB (UnityPlayer) UnityMain
0x00007FFDB171DF36 (UnityPlayer) UnityMain
0x00007FFDB172013D (UnityPlayer) UnityMain
0x00007FFDB171FE6D (UnityPlayer) UnityMain
0x00007FFDB1709277 (UnityPlayer) UnityMain
0x00007FFDB1709319 (UnityPlayer) UnityMain
0x00007FFDB170B312 (UnityPlayer) UnityMain
0x00007FFDB14D39E5 (UnityPlayer) PAL_Thread_SupportsThreads
0x00007FFDB14D245A (UnityPlayer) PAL_Thread_SupportsThreads
0x00007FFDB14D6491 (UnityPlayer) PAL_Thread_SupportsThreads
0x00007FFDB14D9DDB (UnityPlayer) UnityMain
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FF70C9911F2)
0x00007FF70C9911F2 (RimWorldWin64) (function-name not available)
0x00007FFE0AA17BD4 (KERNEL32) BaseThreadInitThunk
0x00007FFE0AB6CE51 (ntdll) RtlUserThreadStart

========== END OF STACKTRACE ===========

If it helps I have 350+ mods, I can provide the mod list if you want.

**Comment by cseelhoff** [comment]
Thanks for the post! This is a tough one... modlist might be nice. I thought I fixed the "RimThreaded.Building_Door_Patch.get_DoorPowerOn" with an earlier patch. I have no idea how this bug could actually still be happening. If you are able to reproduce it consistently, that might help. 350+ mods though would take a lot of work to narrow it down. If we can produce this error on a lighter modded game, that might help too.

**Comment by SilentSkies** [comment]
Just had this issue with just rim threaded, tps and mod manager running.

Crashed shortly after spawning a raid.
[Player-prev.log](https://github.com/cseelhoff/RimThreaded/files/5208396/Player-prev.log)

**Comment by TheyCallMeAmi** [comment]
It happens literally every time I load into a save that has doors / about 5-10 secs after I build one on a new save.

The mod list xml is in the attached zip archive, as well as the log file from the game.
[ModsConfig.zip](https://github.com/cseelhoff/RimThreaded/files/5211464/ModsConfig.zip)

If you need any more info, I'd be happy to help! ^^

**Comment by TheyCallMeAmi** [comment]
Just to be safe I'll run the game again to see if it still occurs after the updates you added after I submitted this issue.

**Comment by TheyCallMeAmi** [comment]
Yep, still same issue, happens 5 seconds after I try to load / crate a save

**Comment by cseelhoff** [comment]
> Just had this issue with just rim threaded, tps and mod manager running.
> 
> UI disappeared shortly after spawning a raid and had to QTD.
> [Player-prev.log](https://github.com/cseelhoff/RimThreaded/files/5208396/Player-prev.log)

@SilentSkies 
Ok I see this in your log "Thread: 277 did not finish within 5ms. Restarting thread..." I would probably increase your thread timeout from 5ms back up to something like 100ms at a minimum. default is 1000ms. That is probably a different issue than the door issue is my guess.

**Comment by cseelhoff** [comment]
thanks for the modlist @TheyCallMeAmi . Reproducible is very good. I will look into it some. If you would care to help, you could temp disable ~half of your mods and see if it still happens. If it start working, then you know the culprit is in that "half." (otherwise try the other "half". Once you find out which half the mod is in, try doing a "quarter" until you can narrow it down. Does that make sense?

**Comment by SilentSkies** [comment]
> > Just had this issue with just rim threaded, tps and mod manager running.
> > UI disappeared shortly after spawning a raid and had to QTD.
> > [Player-prev.log](https://github.com/cseelhoff/RimThreaded/files/5208396/Player-prev.log)
> 
> @SilentSkies
> Ok I see this in your log "Thread: 277 did not finish within 5ms. Restarting thread..." I would probably increase your thread timeout from 5ms back up to something like 100ms at a minimum. default is 1000ms. That is probably a different issue than the door issue is my guess.

Ah sorry about that will adjust settings and take another look

**Comment by TheyCallMeAmi** [comment]
@cseelhoff Yes I can try that, tho it will take some time.
