### ISSUE TITLE
"Shield Generators by Frontier Developments" not working as intended

### ISSUE THREAD

**Issue by Psionic-Dragon** [cseelhoff/RimThreaded#422]
**Describe the bug**
In using the mod "Shield Generators by Frontier Developments," the shield generators within the mod do not function as intended. Typically, bullets are supposed to be stopped by the shield, and their damage absorbed by the generator. Currently, the shield generated by all 3 generator types stop line of sight into them. This causes pawns to not be able to fire into the shield, nor select any targets within it or through it. Pawns can still shoot out of the shield without issue.
This issue does not generate an error.

**To Reproduce**
1. Enter any colony.
2. Place any Shield Generator (make sure it's powered.)
3. Attempt to have a pawn shoot into it.

**Mod List**
Shield Generators by Frontier Developments

**Comment by pastorismylord** [comment]
@Psionic-Dragon can you please add a save with the conditions about to trigger? that would accelerate our time to resolution. thanks in advance!

**Comment by Niilo007** [comment]
this report does not have enough information
