### ISSUE TITLE
"ED-Shields" not working as intended

### ISSUE THREAD

**Issue by Psionic-Dragon** [cseelhoff/RimThreaded#423]
**Describe the bug**
In using the mod "ED-Shields," the shield generators within the mod do not function as intended. Typically, bullets are supposed to be stopped by the shield, and their damage absorbed by the generator. Currently, the shield generated by the generator simply does not stop gunfire. Bullets pass through the shield and deal damage to their target as if the shield was not there.
This issue does not generate an error.

**To Reproduce**
1. Enter any colony
2. Spawn or Craft a Shield Generator
3. Install the Shield Generator (make sure it's powered.)
4. Fire bullets into the shield.

**Mod List**
ED-Shields

**Comment by pastorismylord** [comment]
@Psionic-Dragon can you please add a save with the conditions about to trigger? that would accelerate our time to resolution. thanks in advance!

**Comment by bababooeyy** [comment]
I cannot seem, for the life of me, to reproduce your bugs. Please provide a save file so we can verify the actuality of this bug.

Tested with mod load order:
Harmony
Royalty / No Royalty
HugsLib
ED-Shields
RT[1.3.0.5],[1.2.7]

Shields functioned as intended for me.
