### ISSUE TITLE
"Vanilla Furniture Expanded - Security" not working as intended (shields don't work)

### ISSUE THREAD

**Issue by Psionic-Dragon** [cseelhoff/RimThreaded#424]
**Describe the bug**
In using the mod "Vanilla Furniture Expanded - Security," the shield generators within the mod do not function as intended. Typically, bullets are supposed to be stopped by the shield, and their damage absorbed by the generator. Currently, the shield generated by the generator does stop bullets, but only after 3-5 tiles of being inside the shield, and only sometimes - the bullets seem to randomly get destroyed, and randomly hit their target.
This issue does not generate an error.

**To Reproduce**
1. Enter any colony.
2. Place any Shield Generator (make sure it's powered, indoors, under 32 Fahrenheit, and a raid is active.)
3. Attempt to fire bullet into the shield.

**Mod List**
Vanilla Furniture Expanded - Security

**Comment by pastorismylord** [comment]
@Psionic-Dragon can you please add a save with the conditions about to trigger? that would accelerate our time to resolution. thanks in advance!

**Comment by bababooeyy** [comment]
I can't seem to reproduce this error, raiders seem to shoot the shield and it absorbs bullets as expected. Tested with both small and large shields. Even pawns I placed on the last cell of the shield's range were protected. One thing i noticed is that explosive ammunition directed on the shield produces errors, but does not seem to affect gameplay. 

Could you possibly attach the save that you encountered this bug on, preferably  like **patorismylord** asked so we can test under your exact conditions?

Worth mentioning I am playing with:
Harmony
Core
Royalty
HugsLib 
VFE Security
Rimthreaded[1.2.7]

Or could your reported effects possibly have something to do with the fact that the more damage shields take the more they shrink...

@Psionic-Dragon

**Comment by Niilo007** [comment]
Re open this issue if the problem persists
