### ISSUE TITLE
"What the hack?!" + Vanilla Modlist: Mechs from a raid attack a mechanoid cluster, spams errors

### ISSUE THREAD

**Issue by bababooeyy** [cseelhoff/RimThreaded#425]
**Bug Description**
The error is spammed when a mech from a raid attacks a mech of a mech cluster. It does not seem to affect performance or gameplay in any way and goes away after the one of the mechs is downed. Subsequent attempts to reproduce this by myself have all been met with expected behaviour(i.e. the mechs engage without errors, and fight as expected).
 
**Any help and input is greatly appreciated.**

**To Reproduce**
1. Devmode in a mech cluster
2. Devmode in and force flee pirate raids until you get a raid with mechs that is approaching from the direction of the cluster.  Alternatively, godmode a killbox that forces raids to path through the much cluster
3. ....
4. Profit.

**Error Log**
https://gist.github.com/bf4e3b90f85c2c6a0c0e97390ef04bd6

**Save File**
https://drive.google.com/file/d/1fL6T2AEbAasgRe7cPYaU0_mkLr__brlj/view?usp=sharing

**Mod List**
Harmony
Core
Royalty
HugsLib
What the Hack
Rimthreaded

**Comment by pastorismylord** [comment]
tested this savegame and 2.2.8, was unable to replicate the issue. Additional testing for WhattheHack is required, it might as well be compatible now.
