### ISSUE TITLE
Animal ticking error (animal stuck) save attached

### ISSUE THREAD

**Issue by Niilo007** [cseelhoff/RimThreaded#428]
**Describe the bug**
Ticking error, causes massive lag.

**To Reproduce**
1. Load the save
2. See errors

**Comment by Pandemic223** [comment]
[Broken Save.zip](https://github.com/cseelhoff/RimThreaded/files/5898593/Broken.Save.zip)

**Comment by Niilo007** [comment]
fixed in 1.2.7
