### ISSUE TITLE
Icon lost/bill error (community modpack)

### ISSUE THREAD

**Issue by Rogue-Dragon** [cseelhoff/RimThreaded#429]
**Describe the bug**
This bug came up when i was copy and paste make X per Colonist and with only alpaca wool as the ingredent i was pasting the bill on all of my things until i got to make leather armor and pasted in the bill, all icons and the bug log went nuts icons missing in the schedule for copy and past as well as the bottom right corner icons are missing

**To Reproduce** in description
1. Go to 'tailor bench'
2. Click on 'some bills and add leather armor last'
3. Scroll down 'threw them making them a non leather and paste the bill on the leather armor from vanilla exp'

**Error Log**
https://pastebin.com/Lsm1s4Di
https://pastebin.com/9r6J5zJ3
https://pastebin.com/KbcibP0X
**Screenshots**
![image](https://user-images.githubusercontent.com/68657583/106371690-38a9ca00-6335-11eb-8a6d-b5c01cd993d6.png)

**Comment by Rogue-Dragon** [comment]
TY Niilo

**Comment by Niilo007** [comment]
your error logs are not accessible, you may have them set to private or something.

**Comment by pastorismylord** [comment]
I was unable to reproduce the issue with 2.2.19 preview
