### ISSUE TITLE
"Prisoner Arena (Continued)" Crashing with Prisoner Arena mod

### ISSUE THREAD

**Issue by BKryth** [cseelhoff/RimThreaded#433]
**Describe the bug**
Using the Prisoner Arena's mod( https://steamcommunity.com/sharedfiles/filedetails/?id=2022581505 ), the game crashes every time it starts preparing the arena

**To Reproduce**
1. Make Prison Arena
2. Click Prison Arena
3. Choose Prisoners
4. Click Brawl
5. Game crashes when its in the prepare phase

**Mod List**
Modlist below

https://gist.github.com/HugsLibRecordKeeper/decbd0f496072a7abb3d0d00c3dad34a

**Screenshots**
![Rimworldcrash](https://user-images.githubusercontent.com/67372229/106612625-3f8a4400-65a4-11eb-9763-49e5d3ace709.png)
Rimworld crashing, i dont know what else to show other than that, no idea what logs I can give.

**Comment by Niilo007** [comment]
**Please see:**

* [Q&A](https://github.com/cseelhoff/RimThreaded/wiki/Q&A)

* [Mod Compatibility](https://github.com/cseelhoff/RimThreaded/wiki/Mod-Compatibility)

* [Known Issues](https://github.com/cseelhoff/RimThreaded/issues)

* The [Community Modpack](https://github.com/pastorismylord/Community-Modpack)

* This [Mod Order Guide](https://rwom.fandom.com/wiki/Mod_Order_Guide)

**Address the problems in your mod list before asking for help or submitting errors & bug reports!**

* You can submit a bug report [here](https://github.com/cseelhoff/RimThreaded/issues/new/choose)

**Comment by Niilo007** [comment]
we need the HugsLib log and player log if possible

**Comment by BKryth** [comment]
The link for the modlist is the hugslib log

HugsLib log:
https://gist.github.com/HugsLibRecordKeeper/decbd0f496072a7abb3d0d00c3dad34a

Player log:
[Player.log](https://github.com/cseelhoff/RimThreaded/files/5912482/Player.log)

**Comment by bababooeyy** [comment]
This occurs in 1.3.0.2.

Error Log:
[error.log](https://github.com/cseelhoff/RimThreaded/files/5918598/error.log)


Player Log(bruh i see kernel):
[Player.log](https://github.com/cseelhoff/RimThreaded/files/5918600/Player.log)


Save File (everything is set up, just go to the arena just above the hospital and click brawl.):
https://drive.google.com/file/d/1_wVE2svx-t3BsI8tPqd8NRiRFSTringJ/view?usp=sharing

**Comment by bababooeyy** [comment]
Still happens in 1.3.1.3

**Comment by pastorismylord** [comment]
tested with 2.1.5 following the instructions and savefiles provided by previous testers; the game crashed immediatelly after hitting brawl.

**Comment by pO0P3R125** [comment]
still happens in 2.3.6.7, I noticed something odd if you start a fight between an animal and a prisoner the game doesn't crash, but you cannot cancel it, if you cancel it th prisoner ai brokes and the animal atacks the prisoner until it downs them

**Comment by JoJo1541** [comment]
CTDs should be fixed but there may be some other race conditions in there I didn't catch. So Errors may occur in the log.
