### ISSUE TITLE
"Trader ships" Mod Incompatibility, Game Locks sometimes on Trader Ship Landing

### ISSUE THREAD

**Issue by bababooeyy** [cseelhoff/RimThreaded#435]
**Bug Description**
Trader ships(from mod trader ships), when landing, will cause a hard lock.

**To Reproduce**
1. Make any new colony or load up an existing colony.
2. Go into devmode, and go to 'Do incident' > TraderShipLanding
3. **SOMETIMES** this will only cause a thread timeout, sometimes a soft lock. So far, the bug seems random.
4. Game locks.

**Error Logs** :

Hugs Lib Log from soft lock:
https://gist.github.com/0554a82a205f6a49ee2901118f0b7ce5

The player.log logs from the hard lock.
[Player-prev.log](https://github.com/cseelhoff/RimThreaded/files/5916813/Player-prev.log)

Worth mentioning this bug is **game-breaking** and reloading a save will not bring the colony out of a soft lock or hard lock, as far as I've tested. I will attach a save with the bug active, but not one just before it activates as as soon as you touch the button to do the incident the game either soft locks, hard locks, or thread timeouts. To reproduce the bug is as simple as making a new colony and calling the event until you get it.

**Save File with Bug Active**
https://drive.google.com/file/d/1FntBXpwTJ6IS4Q7IDQHqf0SUa6m_Os3J/view?usp=sharing

**Mod List**
Harmony
Core
Royalty
HugsLib
Trader Ships : https://steamcommunity.com/sharedfiles/filedetails/?id=2046222331
RimThreaded[1.2.7] & RimThreaded[1.3.0.2] (i tried both, but the errors attached are from the 1.3.0.2 version. Both have identical errors.)

**Thanks to bob.blunderton for reporting this on the Discord!**

~**Apparently some people are having no problems with Trader Ships and RT, I'm not sure about that, but I'm definitely getting locks.**~
Ahem. My mistake. They're two different mods.

**Comment by 15adhami** [comment]
Was able to reproduce in RT 1.3. Could not encounter any problems in RT 2.0.7.

**Comment by pastorismylord** [comment]
Testing with 2.2.17, I was able to trigger the incident with no issues BUT there are red errors when trading with the ship.

here are the logs: https://gist.github.com/3ccafb9331320ce78f5c0d2572247d9c

**Comment by pastorismylord** [comment]
tested again with 2.2.19. This mod is compatible now.
