### ISSUE TITLE
Cannot assign prisoner beds.

### ISSUE THREAD

**Issue by bababooeyy** [cseelhoff/RimThreaded#436]
**BUG DESCRIPTION**
Prisoner beds are unable to be assigned as such when using Rimthreaded 1.3.0.2

**To Reproduce**
1. Create a new colony or load up an existing one.
2. Attempt to assign a bed as a prisoner bed.
3. Try again and again as it does not work...
4. ......
5. Contemplate your life choices.

**Error Log**
None to speak of

Harmony
Core 
HugsLib
RimThreaded

**Comment by cseelhoff** [comment]
seemed to work fine for me in 1.3.0.5. Can you confirm issue still exists?

**Comment by bababooeyy** [comment]
Can confirm, no longer occurs.
