### ISSUE TITLE
Grim reality error with 1.3.0 (possibly a new rt issue that needs to be fixed (1.3.X))

### ISSUE THREAD

**Issue by Niilo007** [cseelhoff/RimThreaded#440]
**Describe the bug**
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report.  

* when i launched the game i got an error

**To Reproduce (VERY IMPORTANT)**
1. use grim reality with RT
2. load the game
3. see error

**Error Log**

[SF Grim Reality] Patch operation Verse.PatchOperationAdd(*/ThoughtDef[defName = "CrashedTogether"]/nullifyingTraits) failed
file: D:\SteamLibrary\steamapps\workshop\content\294100\1543063349\1.2\Patches\Patches - Thoughts_Memory_Social.xml
Verse.Log:Error(String, Boolean)
Verse.PatchOperation:Complete(String)
Verse.LoadedModManager:ClearCachedPatches()
Verse.LoadedModManager:LoadAllActiveMods()
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.<>c:<Start>b__6_1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

**Mod List**
* My personal mod list, pretty sure this is just a grim reality / rt issue

**Screenshots**

![image](https://user-images.githubusercontent.com/75486261/106914050-4e403a80-670d-11eb-84ea-3d858ea1be6b.png)

**Comment by Niilo007** [comment]
might be issue with only grim reality, closing this issue for now

**Comment by kertiek** [comment]
grim reality got updates tonight, looks like the crashed together bug was a problem from the mod, not related to rt

Update: 4 Feb @ 11:25pm
[Auto-generated text]: Update on 2/4/2021 8:25:05 PM.

Edited the Chitchat value back to 1. Realized vanilla was .65 not 3 and moving it to 5 was a mistake. Deep Talk remains at 12 which, upon testing, seems to be working great.

Fixed Nullifying Trait error on Crashed together. Thanks Spürgelwürg for the help on finding the error. Thanks all of you for pointing it out so quickly.

Have fun.

**Comment by Niilo007** [comment]
> grim reality got updated tonight, looks like the crashed together bug was a problem from the mod, not related to rt
> 
> Update: 4 Feb @ 11:25pm
> [Auto-generated text]: Update on 2/4/2021 8:25:05 PM.
> 
> Edited the Chitchat value back to 1. Realized vanilla was .65 not 3 and moving it to 5 was a mistake. Deep Talk remains at 12 which, upon testing, seems to be working great.
> 
> Fixed Nullifying Trait error on Crashed together. Thanks Spürgelwürg for the help on finding the error. Thanks all of you for pointing it out so quickly.
> 
> Have fun.

yeah we noticed that. that is why i closed this issue
