### ISSUE TITLE
"Alpha Animals" Predators (?) causing considerable TPS drops when on map

### ISSUE THREAD

**Issue by Nextia-Git** [cseelhoff/RimThreaded#443]
**Describe the bug**
When spawned into the map, it seems like most predators from the mod Alpha Animals cause substantial TPS drops until either tamed or deleted.
Could be related to the below Dubs Analyser line (in screenshot section)

1. Load or start a world
2. Either have existing AA predators or spawn them in with dev mode
3. Speed up to max and see the TPS take a hit
4. Use dev mode to kill them again to see the TPS rise back up

**Error Log**
https://pastebin.com/zqCbfKSD
https://gist.github.com/5562bf31033885ba9946510b425d0c94

**Mod List**
https://pastebin.com/8ujm8sxc

**Screenshots**
https://i.gyazo.com/06cecc62e6c82c3bf4847e2b6f974bc8.png

**Comment by Niilo007** [comment]
Re open this issue if you get this issue again
