### ISSUE TITLE
"Jobs of Opportunity (While You're Up)" RT + Jobs of Opportunity 1.3.1.2 test. GUI completely disappears and Unity Crash upon Alt F4

### ISSUE THREAD

**Issue by bababooeyy** [cseelhoff/RimThreaded#449]
**Bug Description**
GUI completely disappears, game is still running. Pressing space to try and pause game does nothing, neither does any other key input register. A group of visitors had just arrived, maybe that had something to do with it. Only option was AltF4, which crashed Unity.

**To Reproduce**

Was unable to reproduce on the last autosave before the crash. I have no idea on this one.

**Player Log**
[Player.log](https://github.com/cseelhoff/RimThreaded/files/5938451/Player.log)

**Crash Log**
[error.log](https://github.com/cseelhoff/RimThreaded/files/5938452/error.log)

**Save File: Last Autosave**
Probably won't be of much help, but worth a shot.
https://drive.google.com/file/d/1aiy3AS8oG7VG4fsoDDf51SK8Z_2_MC9I/view?usp=sharing

**Mod List**
Harmony
Core
Royalty
HugsLib
Jobs of Opportunity
RimThreaded[1.3.1.2]

**Screenshots**
whoops may have forgotten to take screenshots before alt f4.. srry

**Edit:**
Supposedly fixed in 1.3.1.3

**Comment by Niilo007** [comment]
Might be fixed now, re open if needed
