### ISSUE TITLE
Blocks disappear after pre-existing world load (Multiplayer.Client.FactionContext.Pop)

### ISSUE THREAD

**Issue by gmanc2** [cseelhoff/RimThreaded#45]
Here is my log file:
https://gist.github.com/gmanc2/fa72207161d7bfe1be58a9b8b4bfe8d8

After loading a multiplayer world many of the walls and structures in my base were destroyed. Is there any solution to this?

**Comment by cseelhoff** [comment]
Thanks for the bug submission! It looks like this line may be the culprit: Multiplayer.Client.FactionContext.Pop... Basically RimThreaded is causing other mods to also do some things in parallel. In this case there is a stack that is probably being accessed concurrently. It might be an easy fix for the creator of the Multiplayer mod to change his stack to a "concurrentstack." I'm not saying that's the only problem, but it should fix at least that key error.

**Comment by gmanc2** [comment]
I've contacted the Multiplayer mod makers. Is this something that could be fixed on your end or?

**Comment by cseelhoff** [comment]
They would know their mod best I suppose. I will leave the enhancement open, just in case I can think of a way to solve this from my end.
