### ISSUE TITLE
Bestowing Ceremony Does not Work after some time in 1 session 1.3.1.3

### ISSUE THREAD

**Issue by bababooeyy** [cseelhoff/RimThreaded#452]
**Bug Description**
A bestowing ceremony does not work the first time it is done, and an error is spit out. Sometimes there is no error and the pawn simply stands at the ceremony dude for a little while and then goes away. Reloading the save fixes the problem, so I don't think a save will be beneficial here, but I will attach one anyway.

**Edit**
After further testing by **Numenar** on a modded playthrough in the discord, it appears the issue only occurs after some time in a single session. Exactly how long it takes for this to break is currently unknown. Any assistance in testing this is greatly appreciated.

**To Reproduce**
1.  Start a new game or load a game. 
2. Get a pawn to Acolyte rank or a rank that triggers a bestowing ceremony using devmode give honor. 
3. Accept quest, try to do ceremony. Observe as it does not work. 
4. Reload save. Should be able to do no problem now.

**HugsLib Log**
https://gist.github.com/78875a3a93a9b1538322057572a32c5c

**Save File**
https://drive.google.com/file/d/1rw8GWyOpsFecmliVhu5D_F9tiQYU4jzG/view?usp=sharing

Mod List
Harmony 
Core
Royalty 
HugsLib
RimThreaded[1.3.1.3]

**Comment by Nextia-Git** [comment]
Had the same bug happen to me today, got some footage of it too to showcase what actually happens (apologies if it's a bit choppy). Save file attached is prior to the bestower arriving so you'll just have to accept the quest to get them to come, then wait for them to go to the throne room and attempt the bestowing ritual. Tried it afterwards myself and for some reason it...works?

Unfortunately it is also a modded playthrough but I'll attach the modlist too. - https://pastebin.com/NPTYvWbA

Footage - https://www.youtube.com/watch?v=1XAslQVIOYo

Save file (essentially useless since bestowing works on it somehow but here none the less) - https://mega.nz/file/B0pQxTCZ#hpQgUugfqqcDY36ZxDHxn7IDVjnYwadnhU3E1SlsGUA

**Comment by bababooeyy** [comment]
It works because you reset your game session by reloading the save. As I mentioned in the edit, the time it takes for bestowing to break is unknown, but can be tested by your save I think.

**Comment by Numenar** [comment]
I have spent few hours speedrunning a test scenario to catch first red line that subsequently caused the bestowing to brake.
It was on Vanilla RT, Pheabe chillax, 5 tribals, quests ignored, no raids spawned, pawns were mostly meditating aroud anima tree.
Acolyte and throneroom not required. Can happen at Yeoman as well.
The fastest i made it to brake was like 30s at speed 4 with this errors:
[new_1.txt](https://github.com/cseelhoff/RimThreaded/files/5975039/new_1.txt)
After which game failed to load the base test save game.
I managed this few times with a longer run/error log.

Problem is afterwards i was able to run this for an hour or so, getting 450 anima grass on few loads, getting a multiple of this errors and bestowing still working.

**Comment by Nextia-Git** [comment]
Just had it happen again on a new save going the empire route, this time luckily remembered to grab logs-
https://gist.github.com/HugsLibRecordKeeper/3ce87b82f0d7664b1d37a495ec27aae2 

More footage-
https://www.youtube.com/watch?v=IhpgL8Gcjs8

**Comment by madmax3004** [comment]
Had it happen after ~4 irl hours / ~35 in-game days.

**Comment by cseelhoff** [comment]
Fixed in 2.1.2

**Comment by 15adhami** [comment]
Was able to perform the ceremony 1hr 30mins into a session with no issues. Tested in 2.2.11.
