### ISSUE TITLE
"Hospitality" / "Gastronomy" Error causing pausing every 1-2 minutes.

### ISSUE THREAD

**Issue by Gablers** [cseelhoff/RimThreaded#456]
Random pausing error.
 
Every 1-2 minutes the console dumps out a error, pausing the game. - It can be resumed after but is annoying.

**To Reproduce**
I don't know the cause, unfortunately.

**Error Log**
https://pastebin.com/ZucpU23q - Reupload
https://gist.github.com/44c7f666d987972739f0fb39e0f12ea4

**Mod List**
https://pastebin.com/jVSTVQVk

**Comment by MadPacMan** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2279786905

**Comment by MadPacMan** [comment]
Or Hospitality.

**Comment by pastorismylord** [comment]
can we get a test save for this one, please?

**Comment by pastorismylord** [comment]
Testing hospitality with 2.2.8. So far no errors, no stutters, entertaining guests seems to be working fine so far. Additional testing may be required.

**Comment by pastorismylord** [comment]
moving to fixed in preview as no reports were received during limited release
