### ISSUE TITLE
Crash every hour

### ISSUE THREAD

**Issue by PixelRave** [cseelhoff/RimThreaded#457]
* bug description here !!!
Game crashes after a hour of playing. Unable to figure out what mod is causing the issue.

**To Reproduce (VERY IMPORTANT)**
1. Start map.
2. Play for a hour.
3. Memory leak from error seems to cause crash.

**Error Log**
Playerlog
https://gist.github.com/PixelRave/896f73b576f87338378883f3a453a33c

Huglib
https://gist.github.com/34267dd5f910c7d19d90dbc4cff5061f

**Mod List**
  - brrainz.harmony
  - Ludeon.RimWorld
  - smashphil.neceros.srtsexpanded
  - UnlimitedHugs.HugsLib
  - com.yayo.combat3
  - VanillaExpanded.VWE
  - PeteTimesSix.SimpleSidearms
  - rimfridge.kv.rw
  - LWM.DeepStorage
  - fluffy.researchtree
  - fluffy.fluffybreakdowns
  - dubwise.dubsmintminimap
  - fluffy.colonymanager
  - krkr.locks2
  - fluffy.stuffedfloors
  - Buildable.Terrain
  - falconne.LabelsOnFloor
  - NanoCE.GlassLights
  - neceros.reinforcedwalls
  - fluffy.worktab
  - fluffy.modmanager
  - Ykara.EPOE
  - Haplo.Miscellaneous.Training
  - OskarPotocki.VanillaFactionsExpanded.Core
  - VanillaExpanded.VCookE
  - VanillaExpanded.VPlantsE
  - Dubwise.DubsMintMenus
  - Dubwise.Rimatomics
  - VanillaExpanded.VCEF
  - UnlimitedHugs.AllowTool
  - Dubwise.DubsBadHygiene
  - 4loris4.MoreLinkables
  - Invisible.Conduits
  - ratys.rtfuse
  - SoulfulPumpkin.TabletopTrove
  - Ogliss.TheWhiteCrayon.Quarry
  - Mlie.RoadsOfTheRim
  - Dubwise.DubsPerformanceAnalyzer
  - bishop.music
  - EdB.PrepareCarefully
  - Orion.Hospitality
  - majorhoff.rimthreaded

**Comment by bababooeyy** [comment]
Don't use hospitality for now, it's incompatible. Fluffy breakdowns also. Also your hugs lib is loaded after srts expanded. 
In this case the error seems to be caused by breakdowns. Maybe don't use it for the time being.

**Comment by PixelRave** [comment]
> 
> 
> Don't use hospitality for now, it's incompatible. Fluffy breakdowns also. Also your hugs lib is loaded after srts expanded.
> In this case the error seems to be caused by breakdowns. Maybe don't use it for the time being.

OK thank you for looking into it. I tired to disable fluffy but i didn't try both .

**Comment by PixelRave** [comment]
Ok so i removed those incompatible mods . Now I have these errors... 

Seems like harmony is causing issues.
And the human error is still going.

New log.

https://gist.github.com/7a35542d64e948124d066e546810e3f4

**Comment by PixelRave** [comment]
> 
> 
> Don't use hospitality for now, it's incompatible. Fluffy breakdowns also. Also your hugs lib is loaded after srts expanded.
> In this case the error seems to be caused by breakdowns. Maybe don't use it for the time being.

Ok so i removed those incompatible mods . Now I have these errors...

Seems like harmony is causing issues.
And the human error is still going.

New log.

https://gist.github.com/7a35542d64e948124d066e546810e3f4

**Comment by Niilo007** [comment]
please re open this issue if you still have the problem, also make sure your load order is ok. it looks like your SRTS is not above hugslib https://github.com/cseelhoff/RimThreaded/wiki/Mod-Order-Guide

**Comment by Niilo007** [comment]
remember to go through the incompatible mods: https://github.com/cseelhoff/RimThreaded/wiki/Mod-Compatibility
