### ISSUE TITLE
Animals and Pawns freezing in place

### ISSUE THREAD

**Issue by GracieTheLatias** [cseelhoff/RimThreaded#460]
**Describe the bug**

My game froze for ~15 seconds and every one of my pawns stopped moving, even the animals couldn't move. 

**To Reproduce**
Have not tried to reproduce this.

**Error Log**
https://gist.github.com/HugsLibRecordKeeper/000566f5a3e8f94fbaa207333f02f69b

**Mod List**
* Paste contents of ModList used when bug occurred.
Harmony
Core
RuntimeGC
HugsLib
Mod Manager 
Vanilla Expanded Framework
Humanoid Alien Races 2.0
Vanilla Furniture Expanded
Expanded Prosthetics and Organ Engineering
RIMMSqol
Animal Tab
Vanilla Furniture Expanded - Production
RimHUD
Achtung!
Vanilla Furniture Expanded - Medical Module
Recipe icons
Vanilla Furniture Expanded - Security
Vanilla Weapons Expanded
Android tiers
A Dog Said... 
Smarter Construction
RunAndGun
Vanilla Apparel Expanded
[KV] Show Hair With Hats or Hide All Hats
Vanilla Furniture Expanded - Art
Vanilla Animals Expanded — Cats and Dogs
Vanilla Animals Expanded — Boreal Forest
Vanilla Animals Expanded — Desert
Vanilla Animals Expanded — Ice Sheet
Vanilla Animals Expanded — Tundra
Vanilla Animals Expanded — Extreme Desert
Vanilla Animals Expanded — Tropical Swamp
Vanilla Animals Expanded — Tropical Rainforest
Vanilla Animals Expanded — Arid Shrubland
Vanilla Cooking Expanded
Door Mat
DontBlockDoor
Animal Variety Coats
Dub's Paint Shop
Vanilla Factions Expanded - Settlers
Vanilla Fishing Expanded
Map Reroll
Just Ignore Me Passing
MendAndRecycle
Skilled Stonecutting
Misc. Robots
Misc. Robots++
More Faction Interaction (Continued)
More Trade Ships
[KV] More Trait Slots
More Vanilla Biomes
Numbers
OgreStack
QualitySurgeon
Quarry 1.1
ResearchPal
Share The Load
Show Draftees Weapon
Simple sidearms
Snap Out!
Sparkling Worlds 
Stabilize
Vanilla Animals Expanded — Endangered
Vanilla Animals Expanded — Australia
Vanilla Factions Expanded - Medieval
Vanilla Factions Expanded - Insectoids
Vanilla Factions Expanded - Mechanoids
Vanilla Factions Expanded - Vikings
Vanilla Traits Expanded
WeaponStats
Hunt for Me
QualityBuilder
Vanilla Plants Expanded
More Sculpture
Metal Doesn't Burn
Vanilla Animals Expanded — Temperate Forest
Vanilla Furniture Expanded - Power
Animals Logic
Wall Light
Replace Stuff
Realistic Rooms
[FSF] Filth Vanishes With Rain And Time
Vanilla Weapons Expanded - Heavy Weapons
EdB Prepare Carefully
Level Up!
[T] MoreFloors
Avoid Friendly Fire
[KV] Adjustable Trade Ships
Common Sense
Beautiful Outdoors
RimThreaded

**Comment by tommytang213** [comment]
I got the same issue as above. Everytime I restart Rimworld, the same thing happens again.

HugsLib Error Log: https://gist.github.com/4d9d0f0c5faf32bb81b9de223f1d33a6

my player.log: https://gist.github.com/tommytang213/e68d236e86067c69e096186df2d038d3

Video of redoing what happened: https://drive.google.com/file/d/1vlyKmyTqEulCgDX3wOrUq2x8mN3guhpP/view?usp=sharing

my mod list:
Hamony
Core
Royalty
JecsTools (unofficial)
Mod Manager
HugsLib
Humoniod Alien Race 2.0
[O21] Toolbox
Advanced Bioics Expansion
Advanced Power Plus
Animal Tab
Auto-Cut Blight
Better Electronics
Better ModMismatch Window
Blueprints
Ceramics
Children, school and learning
Colony Manger
Color Coded Mood Bar
Combat Extended
Combat Effects for Combat Extended
Conduit Deconstruct
Craft Glitterworld Meds
Deep Stack
Dual Wield
Dubs Bad Hygiene
EdB Prepare Carefully
Empire
Feeding Tubes
Realistic Rooms
Filth Vanishes With Rain And Time
SRTS Expanded
Get to the Chopper!
Gliddy-up! Core
Gliddy-up! Battle Mounts
Gliddy-up! Caravan
Gliddy-up! Ride and Roll
Go Explore!
Jobs of Opportunity (While You're Up)
Kill For Me
Expanded Prosthetics and Organ Engineering
Medical Tab
Metals Trader
Miniature Nuclear Generator
Misc. Robots
Misc. Robots++
Tinker's Construct
No Tremendous saddness with death of prisoner
Pharmacist
Prisoner Capture and Manipulation
Prisoner Harvesting
PrisonerRansom
Quick Stockpile Creation
RPG Style Level Up Mod
Search and Destroy
Simply More Bridges (Continued)
Tiled Soil
Trading Control
Trait Rarity Colors
Vanilla Books Expanded
Vanilla Furniture Expanded
Vanilla Furniture Expanded - Medical Module
Vanilla Furniture Expanded - Security
VGP Vegetable Garden
VGP Garden Canning
VGP Garden Fabrics
VGP Garden Gourmet
VGP Garden Medicine
VGP Garden Resources
VGP Garden Tools
VGP More Veggies
VGP Xtra Trees and Flowers
Weapon and Apparel Quality Indicators
Sun Lights [1.0+]
Project Itzal - Launchers
Project Itzal - Launchers CE Patch
Combat Extended Guns
Guns Nut - Chapter #1
Guns Nut - Chapter #2
Guns Nut - Community Pack
Modularization Weapon
Modularization Weapon CE Patch
Combat Extended - Chemical Warfare
Gas Traps And Shells
Animal Food Restriction
Bug Finder: Better ReportProbablyMissingAttributes (patched)
Colony Groups
Immortals
Prisoner Arena (continued)
ResearchPal - Forked
Star Wars - Factions (Continued)
Star Wars - Fully Functional Light Sabers (Continued)
Star Wars - The Force (Continued)
TMC All In One CE Patch
TMC Armory - Assault Rifles #1
TMC Armory - Shotguns #1
TMC Armory - Sidearms #1
TMC Armory - SMGs #1
TMC Armory - Sniper Rifles #1
TMC Armory - Support Weapons #1
BondageBed Torture
More Factional Interaction (Continued)
War Crimes Expanded 2 Core
RimThreaded

**Comment by pastorismylord** [comment]
@GracieTheLatias this is not a bug. You're using a number of incompatible mods on your modlist. Please verify the compatibility of your mods by contrasting your modlist against the mod compatibility section in our wiki.

**Comment by pastorismylord** [comment]
@tommytang213 this is not a bug. You're using a number of incompatible mods on your modlist. Please verify the compatibility of your mods by contrasting your modlist against the mod compatibility section in our wiki.
