### ISSUE TITLE
"Alpha Animals" Pawns can't get into the door

### ISSUE THREAD

**Issue by GervyMaglina** [cseelhoff/RimThreaded#461]
**Describe the bug**
They can't get into the door but can freely pass through them.
Bug caused by **Alpha Animals**.

**To Reproduce (VERY IMPORTANT)**
1. Go to existing save file or make a new world
2. Turn on dev mode and build a door.
3. Select any pawn and right click the door

**Error Log**
Player.log : https://gist.github.com/GervyMaglina/53862c0d76d77cd6bcdb6e73d0e041a1
HugsLib log : https://gist.github.com/e079dd34d162723e76a96b6fdfa030c7

**Mod List**
Harmony
Core
HugsLib
Vanilla Expanded Framework
Alpha Animals
Mod Manager
Rimthreaded [1.2]

**Comment by pastorismylord** [comment]
@GervyMaglina can you please attach a save file where the error is reproduced? that would accelerate resolution time. Thanks in advance!

**Comment by GervyMaglina** [comment]
Is it this?
https://www.dropbox.com/s/st8tarc69rdanhe/Error.rws?dl=0

**Comment by GervyMaglina** [comment]
It was only for a test since the origin of it contained a lot of mods. Even my pawn bedroom temperature was forced to stay atleast 100 C despite having no steam geyser or bad weather, I don't know what actually cause that to happen but it can happen when i load it the next time

**Comment by GervyMaglina** [comment]
The bug came when Vanilla Expanded Framework merged a new mod called MVCF into their mod, then Alpha Animals follow suit by overhauling all of their ranged animal system which produce the bug

**Comment by Nextia-Git** [comment]
Confirmed to be Alpha Animals, tested for myself and got the exact same error as Gervy when attempted to move a drafted pawn onto an open/closed door. Moving a pawn through the door doesn't cause the error, only when clicked directly on top of it.

Tested with vanilla RT with Vanilla Expanded Framework and Alpha Animals.
![1fb2e49f7acfe7f4058080522d17ac6d](https://user-images.githubusercontent.com/10771689/109577897-4e560f00-7aee-11eb-9bb9-824aabbd64d6.png)

**Comment by pastorismylord** [comment]
issue has been fixed on 2.3.9
