### ISSUE TITLE
Restarting Thread Spam from Roofing

### ISSUE THREAD

**Issue by Jasiniok** [cseelhoff/RimThreaded#463]
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report.  

* So, I encountered a bug where I was under a mountain "fort" and there were like 15 bugged shells where if my colonists would step close to the spot in which the shell exploded (The mountain roofs weren't broken), the colonists will die, I lost like 10 colonists until I could find the issue and the spots. But anyway, I removed all the roofs with the debug mode, rebuilt them and now after like 5 minutes of gameplay, I'm getting a RimThreaded restart error which can't be reproduced.
TLDR: Removed roofs, built roofs same spot, thread restarting.

**To Reproduce**
1. Start the game with the modlist
2. Load in a savegame (https://easyupload.io/6nbd8q) - couldn't upload it in zippyshare,
3. Wait for like 2-3 minutes or something (That's what it took me)
4. Enjoy your game being broken with your colonists just standing.

**Error Log**
* Link to contents of Player.log or Error.log (https://www114.zippyshare.com/v/6rQLV9Hx/file.html)
* Link to HugsLib log. (https://gist.github.com/HugsLibRecordKeeper/66e0f8f58950587f17bfd7c84c5e6a15)

**Mod List**
https://www58.zippyshare.com/v/jB0taSIS/file.html

**Screenshots**
N/A

**Comment by Jasiniok** [comment]
Also to note: There's a bug with Dub's Minimap where alerts, enemies and stuff still show up even after they've been dealt with, most of the time there's a circle stuck in the minimap, you can reproduce that bug in the exact same save-game and modlist, just let it run, produce a threat, and the dead alerts and stuff will still show up. This doesn't happen in a non-RT game, though.

**Comment by pastorismylord** [comment]
@Jasiniok you're using some mods known incompatible with rimthreaded like runtimeGC. Can you please reproduce the error in vanilla+Rimthreaded and share a save ready to reproduce the issue?

**Comment by Jasiniok** [comment]
> @Jasiniok you're using some mods known incompatible with rimthreaded like runtimeGC. Can you please reproduce the error in vanilla+Rimthreaded and share a save ready to reproduce the issue?

This bug isn't reproducible in RT + Vanilla, the thing is - I used to play with this mod list without any issues, but some recent update broke something with the roofing threads, I don't really think this is a RuntimeGC issue as I have not used it in my savegame except a few times cleaning the world, and to my knowledge runtimegc doesn't have anything to do with roofing, but I could be wrong, excuse me if that isn't the case.

**Comment by Jasiniok** [comment]
Mod incompatibility reported with Expanded Roofing, this was fixed once I removed Expanded Roofing from my modlist.
