### ISSUE TITLE
(2.2.1) Hard Crash on Building Wooden Floors

### ISSUE THREAD

**Issue by Pandemic223** [cseelhoff/RimThreaded#464]
**Describe the bug**
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report.  

So for this bug, if you set a group of workers to build wooden floors, there is a large chance that the game will crash to desktop. Sometimes you may have to deconstruct the floors and replace them, but it will eventually crash.

**To Reproduce (VERY IMPORTANT)**
1. Place Stockpile
2. Spawn Pawns of All Sizes
3. Spawn Many Stacks of Wood
4. Build large area of wooden floors
5. Game Crash

**Error Log**
* Link to contents of Player.log or Error.log (MUST BE LINK)
* https://gist.github.com/5ddf9dcb15341fbb5fb89c21021060e0
* Link to HugsLib log. (MUST BE LINK)

**Screenshots**
* If applicable, add screenshots to help explain your problem.

**Comment by pastorismylord** [comment]
@Pandemic223 can you please get a save ready for this one? Please attach the save when you have a chance.

**Comment by bababooeyy** [comment]
Got a save with a crash happening most of the time when colonists move on to building the big section of wooden floors. Not sure if it's the same though, cause I'm not get Root exceptions. 

Save File: 
https://drive.google.com/file/d/1W2N01f4n_UxIwGAcb-AUvhty-hnRjdlV/view?usp=sharing

Mod List:
Harmony 
Core
Royalty
HugsLib
RimThreaded[1.3.1.3]

Player.log: 
[Player-prev.log](https://github.com/cseelhoff/RimThreaded/files/6019608/Player-prev.log)

Crash.log
[error.log](https://github.com/cseelhoff/RimThreaded/files/6019617/error.log)

**Comment by MadPacMan** [comment]
[Floor_save.zip](https://github.com/cseelhoff/RimThreaded/files/6023686/Floor_save.zip)
Happens every time, more or less, if needed.

**Comment by pastorismylord** [comment]
Tested with 2.2.1, The error seems to not trigger anymore, but additional errors related to Breath First traverse trigger almost as soon as loading the save provided by @MadPacMan. @cseelhoff Please take a look at the breath First Traverse errors included in this log.

[Player.log](https://github.com/cseelhoff/RimThreaded/files/6524429/Player.log)

**Comment by pastorismylord** [comment]
tested with 2.2.5. Issue has been resolved.
