### ISSUE TITLE
"Standalone Hot Spring [BAL]" Crash to Desktop with Mod Standalone Hot Springs

### ISSUE THREAD

**Issue by bababooeyy** [cseelhoff/RimThreaded#467]
**BUG DESCRIPTION**
A crash happens when two colonists try to use the hot spring at the same time, or when one gets out. 

**To Reproduce**
1. Open up provided save
2. Run Game
3. Observe crash, or force crash by manually asking two or more colonists to bathe in the spring.

**Player.Log**
[Player.log](https://github.com/cseelhoff/RimThreaded/files/6022358/Player.log)

**Crash.log**
[error.log](https://github.com/cseelhoff/RimThreaded/files/6022363/error.log)

**Mod List**
Harmony
Core
Royalty
HugsLib
Standalone Hot Springs [BAL] https://steamcommunity.com/sharedfiles/filedetails/?id=2205980094&searchtext=Standalone+Hot+Springs
RimThreaded[1.3.1.3]

**Save File**
https://drive.google.com/file/d/1PP6UucjamLgzrIQgwna0N9jsim4gAz3-/view?usp=sharing

**Comment by fridgeBaron** [comment]
This also affects the hot spring in the Kijin 2.0 mod as they use the same underlying code.

**Comment by pastorismylord** [comment]
tested with 2.2.5, and the provided save. Was able to bring the colonists into the hot spring but once I hit speed 4, the game crashed. Will Try to test again to better identify the reason for the crash.

**Comment by pastorismylord** [comment]
was able to reproduce cash with 2.2.5 and only one colonist. Crash consistently happens after some time has passed after the colonist gets into the hot spring.

**Comment by pastorismylord** [comment]
tested with 2.2.19. Pawns were able to use the hot spring at the same time.

Started testing on speed 1
Took the 3 pawns provided with the save and one by one ordered them to enter the hot spring.
all 3 pawns got into the hot spring with no issues.
then hit speed 2, pawns are stable enjoying the hot spring
Then hit speed 3. As soon as speed 3 TPS were achieved, the game froze and thread time-out started to happen

The hot spring feature can be used on speed 1 and 2.
