### ISSUE TITLE
World temperature changing mid-save, after world gen, and affects all saves.

### ISSUE THREAD

**Issue by kaoeamorim** [cseelhoff/RimThreaded#472]
EDIT 2: I've been playing for two days without this bug occuring. I just generated a map without changing temperature and rainfall sliders. I may or may not have save scummed a lot on Commitment Mode, so client restarts were very common, and not once the world temp bugged.

EDIT: New developments. It doesn't seem to be related to Dubs Bad Hygiene, although I could reproduce said bug very reliably with the steps mentioned for some reason.

I managed to reproduce the issue with only RT on. And couldn't on Vanilla. Here are the screenshots of the setup:

[Mods](https://cdn.discordapp.com/attachments/789343958727786557/814593490675695646/unknown.png)

[World generation settings and seed](https://cdn.discordapp.com/attachments/789343958727786557/814593531649720350/unknown.png)

[Bugged tile](https://media.discordapp.net/attachments/789343958727786557/814593548967346266/unknown.png?width=436&height=701)

[Same exact tile, but on Vanilla](https://media.discordapp.net/attachments/789343958727786557/814596975692611636/unknown.png?width=760&height=702)

[General location of that tile for ease of reproduction](https://media.discordapp.net/attachments/789343958727786557/814597239259136010/unknown.png?width=1394&height=587)

Note that it's not a single tile issue. The whole world, when it bugs, have weird temperatures. I can see Tundras with year-round growing period, and arid shrublands and extreme deserts with "never". Also, there are cases like the following screenshots, where two adjacent tiles are "year-round" and "never", which shouldn't happen normally. 

[Tile 1 year-round](https://media.discordapp.net/attachments/789343958727786557/814406575141683210/unknown.png?width=847&height=702)

[Tile 2 never](https://media.discordapp.net/attachments/789343958727786557/814406605058736128/unknown.png?width=890&height=702)

I don't have the seed specifically for these last images, but this anomaly can be seen on any bugged world.

I can't figure out what causes it or what triggers it. It seems random on my end. 
_________

This issue happens exclusively with Dubs Bad Hygiene mod. I didn't see it happen with Dubs alone, so there are other mods at play. But removing Dubs makes the issue go away completely. I remember at least once reproducing this issue with only Dubs, VE and RuntimeCG and nothing else. 

I can reproduce it very consistently. I'll annex the related files. All issues happen after restarting the game.

This is NOT related to world generation.

Save 1 has Dubs natively.
Save 2 doesn't have dubs natively.

Case 1: Loading Save 1 with Dubs on the modlist, breaks temperature. 
If I then load Save 2 without restarting the game, tempreatures are broken there too.

Case 2: Loading Save 2 with Dubs on the modlist, doesn't break temperature.
I can even load Save 1 and temperatures will be normal.

Case 3: Loading Save 2 without Dubs on the modlist never breaks temperature.
I cant load Save 1 without Dubs because it breaks the whole save.

 
[Player.log](https://github.com/cseelhoff/RimThreaded/files/6045057/Player.log)

https://gist.github.com/HugsLibRecordKeeper/4a6038c1e6c9aa4a49e734dd7bdfadd0

[issue_modlist.zip](https://github.com/cseelhoff/RimThreaded/files/6045068/issue_modlist.zip)

[Saves.zip](https://github.com/cseelhoff/RimThreaded/files/6045059/Saves.zip)

**Comment by pastorismylord** [comment]
this issue seems to be similar to https://github.com/cseelhoff/RimThreaded/issues/513 which was fixed in 2.2.12 preview. Additional testing is required to confirm this issue is not related to the other one and to confirm if 2.2.12 solves this issue as well.
