### ISSUE TITLE
"Visitors leaving" before they actually leave (Exception while ticking lord with job RimWorld.LordJob_VisitColony)

### ISSUE THREAD

**Issue by potjeh** [cseelhoff/RimThreaded#475]
I tried searching for a few keywords in the Issues list but nothing popped up.

**Describe the bug**

In my third colony on the world map there are some visitors. After about 9 hours (game save time) they start leaving even before the notification message "Visitors from the Thrombo (insert correct faction name here) are leaving" appears. When the actual message does appear the game throws the following exception, pauses and can not be unpaused again because the same exception happens immediately. At this point they have already left the map hours ago.

`Exception while ticking lord with job RimWorld.LordJob_VisitColony`

**Some remarks**

I have just installed RimThreaded mid-game to try it out and have not actually been playing with it from the beginning.

I have tried unloading all the mods except Harmony and RimThreaded and the same thing happens .

**Steps to reproduce the behavior (VERY IMPORTANT)**

Just unpause the game and after about 10 in-game hours the notification that the visitors are leaving will appear. At that point the game should pause and throw the exception.

**Error Log**
Player log: https://pastebin.com/v9sRtHV1
HugsLib log: https://pastebin.com/8VtqesX8

**Save file**
[save.zip](https://github.com/cseelhoff/RimThreaded/files/6056813/save.zip)

**Mod list (Preferably a RimPy compatible list.)**

I assume you can get the modlist from the logs or the save. I do not use RimPy but for the sake of convenience I shall paste the list here. This is from the game save:

brrainz.harmony
me.samboycoding.betterloading
ludeon.rimworld
unlimitedhugs.hugslib
maarx.modbuttons
kapitanoczywisty.changemapedge
voult.betterpawncontrol
gguake.areaninclusionexclusion
pathavoid.kv.rw
improvedloadtransportpods.rw
mlie.pickupandhaul
avilmask.commonsense
dhultgren.smarterconstruction
uuugggg.gearupandgo
uuugggg.smartmedicine
uuugggg.usebedrolls
smashphil.loadinginprogress
syrchalis.setupcamp
fluffy.blueprints
smuffle.harvestorganspostmortem
jaxe.rimhud
sandy.rpgstyleinventory
mehni.numbers
uuugggg.listeverything
gguake.ui.simplesearchbar
jaxe.morefilters
supes.autoseller.core
supes.autoseller.caravanequip
timmyliang.tradehelper
longwater.quicklinks
fluffy.followme
maarx.firefightingcontrols
avilmask.microdesignations
dubwise.dubsmintmenus
dubwise.dubsmintminimap
jaxe.reorderer
tradingspot.kv.rw
rimfridge.kv.rw
automatic.bionicicons
madeline.pathoverlay
ryder.satisfiedstorage
hatti.qualitybuilder
kikohi.whatsforsale
majorhoff.rimthreaded

**Final note**

I am really impressed that you are even attempting to make such a complicated mod as this one and if I can help with more data about this error, I shall be happy to help with additional information that I might have not mentioned.

To help further I shall also share the complete Mods directory so you can, hopefully, just unpack the archive, load the save and be on your (debugging) way.

Archived Mods directory: https://tinyurl.com/yb853pgg

**Comment by 15adhami** [comment]
Tested in RT 1.3.2 and 2.0.7. Issue happens in both versions.

**Comment by pastorismylord** [comment]
@cseelhoff this save looks ready to generate hauling errors. Lots of hauling issues with this save and 2.1.5

**Comment by pastorismylord** [comment]
issue still happens on 2.1.5

**Comment by pastorismylord** [comment]
should be fixed now
