### ISSUE TITLE
"Alpha Animals" Chameleon Yak "AlphaBehavioursAndEvents.ChameleonSkins" Error Spam

### ISSUE THREAD

**Issue by Nextia-Git** [cseelhoff/RimThreaded#477]
Occasionally when Chameleon Yaks from Alpha Animals enter a different terrain square that would change their colour, the log will throw a red error as shown below in the log provided.

Easily reproducable and very consistent-
1. Create new world, preferably in the arid shrublands to get it to trigger quicker because of varied terrain types
2. Spawn a bunch of yaks around near two different terrain types
3. Speed up the game and watch the errors flood in

Log-
https://gist.github.com/HugsLibRecordKeeper/7c114d8bb540586545db1f914d4e2b77

Save-
[RT Chameleon Yak Bug.zip](https://github.com/cseelhoff/RimThreaded/files/6087416/RT.Chameleon.Yak.Bug.zip)

Modlist-
  - brrainz.harmony
  - Ludeon.RimWorld
  - Ludeon.RimWorld.Royalty
  - UnlimitedHugs.HugsLib
  - OskarPotocki.VanillaFactionsExpanded.Core
  - sarg.alphaanimals
  - fluffy.modmanager
  - majorhoff.rimthreaded

**Comment by pastorismylord** [comment]
Tested with 2.2.17

Chamaleon Yak does not change colors and does not throw errors.

**Comment by pastorismylord** [comment]
[chamaleonyak.zip](https://github.com/cseelhoff/RimThreaded/files/6680146/chamaleonyak.zip)

After testing with 2.3.9 was able to reproduce the issue, please find attached a save ready to trigger, just ad RimThreaded to the modlist

**Comment by cseelhoff** [comment]
Stangely enough this is not an alpha animals bug. It is a bug with Vanilla Expanded Framework. GraphicRequest.Get was not thread safe. This should now be fixed upon next release (2.5.13)
