### ISSUE TITLE
Can't right click and force jobs on door tiles

### ISSUE THREAD

**Issue by Bs990** [cseelhoff/RimThreaded#479]
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report!  

**Describe the bug**
I can't right click and force jobs on door tiles. (for example can't clean or deconstruct by hand) But pawns can decide to do the work by themselves.

**Steps to reproduce the behavior (VERY IMPORTANT)**
I have no idea how to reproduce the bug.

**Error Log**
https://justpaste.it/8ldbq
https://gist.github.com/HugsLibRecordKeeper/31250903920fd64224b85c1a2264bc00

**Save file**
https://www39.zippyshare.com/v/0SvV4uqB/file.html

**Screenshots**

**Mod list (For vanilla report, it has to be same as below list.)**
 brrainz.harmony
  - user19990313.RuntimeGC
  - UnlimitedHugs.HugsLib
  - smashphil.neceros.srtsexpanded
  - erdelf.HumanoidAlienRaces
  - mobius.royaltytweaks
  - notfood.MendAndRecycle
  - fluffy.modmanager
  - OskarPotocki.VanillaFactionsExpanded.Core
  - leafzxg.ThrumboExtension
  - roolo.giddyupcore
  - vanillaexpanded.achievements
  - EdB.PrepareCarefully
  - Dylan.AnimalGear
  - OhGodSpidersNo.AnimalArmor.Vanilla
  - Meltup.BeautifulOutdoors
  - fuglypump.bulkstonecutting
  - 8Z.CallForIntel
  - smashphil.carrycapacityfixed
  - jelly.craftsmanship
  - neceros.badcanbegood
  - CaesarV6.DamageIndicators
  - spincrus.dinosauria
  - Saakra.Empire
  - factioncontrol.kv.rw
  - Torann.RimWar
  - ari.forcedmarch
  - zylle.Gemstones
  - sarg.geneticrim
  - sarg.geneticrimdinosauria
  - roolo.giddyupcaravan
  - roolo.giddyupbattlemounts
  - Albion.GoExplore
  - Goldminermac.Empireexpandedresourcebuildings
  - kittahkhan.grazeup
  - catachat.inspirationtweaks
  - lbeaston.ADogSaidEasyPatcher
  - Mlie.LessArbitrarySurgery
  - ratys.madskills
  - UnlimitedHugs.MapReroll
  - fluffy.medicaltab
  - ac.mw.sad
  - Haplo.Miscellaneous.Robots
  - FrozenSnowFox.MoreQuests
  - PinoChemicali.MoreTradeShips
  - Oblitus.MyLittlePlanet
  - Ogre.OgreStack
  - brucethemoose.OptimizationMeats
  - OskarPotocki.VFE.Insectoid
  - fluffy.pharmacist
  - dninemfive.qualitycooldown
  - hatti.qualitybuilder
  - Woolstrand.RealRuins
  - VinaLx.ResearchPalForked
  - rimsenal.core
  - Uuugggg.ShareTheLoad
  - rimsenal.security
  - gguake.ui.simplesearchbar
  - PeteTimesSix.SimpleSidearms
  - Oblitus.AnimalsLogic
  - Despenso.HiThechResearchBench
  - Despenso.SimpleResearchBench
  - Linkolas.Stabilize
  - balistafreak.StopDropAndRoll
  - GT.Sam.TilledSoil
  - VanillaExpanded.VBooksE
  - VanillaExpanded.VCookE
  - VanillaExpanded.VEE
  - OskarPotocki.VanillaExpanded.RoyaltyPatches
  - OskarPotocki.VFE.Mechanoid
  - VanillaExpanded.VWE
  - OskarPotocki.VanillaFactionsExpanded.MedievalModule
  - OskarPotocki.VanillaFactionsExpanded.SettlersModule
  - OskarPotocki.VFE.Vikings
  - VanillaExpanded.VFECore
  - VanillaExpanded.VFEMedical
  - VanillaExpanded.VFEPower
  - VanillaExpanded.VFESecurity
  - VanillaExpanded.VFESpacer
  - VanillaExpanded.VTEXE
  - VanillaExpanded.VTEXGR
  - isorex.mechanoidsaddon
  - roolo.whatthehack
  - tammybee.whereismyweapon
  - com.yayo.combat3
  - Ogliss.WanderJoinsPlus
  - Murmur.WallLight
  - Jaxe.Bubbles
  - spoonshortage.ADogSaidAnimalProsthetics
  - sarg.alphabiomes
  - razor2.3.AnotherRimworldMod.AutoCutBlight
  - UnlimitedHugs.AllowTool
  - KYD.QuieterSounds
  - crlsniper.realisticrooms
  - syrchalis.setupcamp
  - HC.AnimalReskins.Complete
  - hobtook.mortaraccuracy
  - Rooboid.Royalhair
  - CaptainMuscles.Callouts
  - azuraal.choiceofpsycasts
  - SGC.quests
  - automatic.prisonerbedsetowner
  - Uuugggg.SmartMedicine
  - syrchalis.coffeeandtea
  - kentington.saveourship2
  - sarg.alphaships
  - Murmur.TCU
  - CP.Rimdeed
  - vat.epoeforked
  - sarg.rimbees
  - sarg.geneticrimrimbees
  - CaptainMuscles.GrabYourTool
  - sirrandoo.bettersliders
  - lurmey.foundations
  - Mlie.PickUpAndHaul
  - majorhoff.rimthreaded
  - Community.Psychology.UnofficialUpdate
  - Orion.Hospitality
  - VSE.PerryPersistent
  - Uuugggg.ReplaceStuff
  - ChJees.Androids
  - tachyonite.pawnmorpherpublic
  - tachyonite.pawnmorpher.insects
  - smashphil.loadinginprogress
  - sarg.alphaanimals
  - vat.epoeforkedroyalty
  - sarg.geneticrimalphaanimals
  - Mlie.RimQuest
  - dhultgren.keepbedownership

**Comment by Niilo007** [comment]
---

**Please see:**

* [Q&A](https://github.com/cseelhoff/RimThreaded/wiki/Q&A)

* [Mod Compatibility](https://github.com/cseelhoff/RimThreaded/wiki/Mod-Compatibility)

* [Known Issues](https://github.com/cseelhoff/RimThreaded/projects/1?fullscreen=true)

* The [Community Modpack](https://github.com/pastorismylord/Community-Modpack)

* This [Mod Order Guide](https://rwom.fandom.com/wiki/Mod_Order_Guide)

**Address the problems in your mod list before asking for help or submitting errors & bug reports!**

* You can submit a bug report [here](https://github.com/cseelhoff/RimThreaded/issues/new/choose)

* If your submitted issue gets closed and the bug is still happening you can re open the issue.

---

**Comment by Niilo007** [comment]
you mod order is a disaster. i'm closing this issue, read the wiki

**Comment by Niilo007** [comment]
https://github.com/cseelhoff/RimThreaded/wiki/Mod-Order-Guide

you really need this

**Comment by Bs990** [comment]
Ok thanks!
