### ISSUE TITLE
Smokepopbelt BulletImpactNearby Error

### ISSUE THREAD

**Issue by geojak** [cseelhoff/RimThreaded#482]
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report!  
--> Searched and didnt see it/

**Describe the bug**
When a smokepop belt is lying around on the ground and bullets impact nearby than the error log will show reds.

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Start new Coliny
2. Spawn in a smokepop belt 
3. Draft a colinist and let him stand next to the belt on the ground
4. Shoot at that colonist standing next to the belt with another colonist

**Error Log**
[playerlog.txt](https://github.com/cseelhoff/RimThreaded/files/6133395/playerlog.txt)

----------------------------------------
Hugslib log
https://gist.github.com/4ea4cb9e179491cfdbe5e96f1aa752c3

**Save file**
!!! Please add a save file where the issue occurs to speed up testing and fixing of the issue !!!
added a safefile named Smokepoperror.rws in an zip in comment below

**Screenshots**
!!! Add screenshots to help explain your problem here !!!
![image](https://user-images.githubusercontent.com/25199983/110998724-904d4380-837f-11eb-8cf4-9d217a6cd5cd.png)
added a screenshot

**Mod list (For vanilla report, it has to be same as below list.)**
* Harmony
* Core
* Royalty (optional)
* HugsLib
* RimThreaded

i used this exact modlist with rovalty, rimthreaded version 1.3

**Comment by geojak** [comment]
somehow i cant add that safefile here. if you need it, ping me in your discord, my name is clark there and i send it to you

**Comment by geojak** [comment]
The same error can be trigger with the royaltry low-shield pack item

Exception ticking Bullet_ChargeRifle24201: System.NullReferenceException: Object reference not set to an instance of an object
  at RimWorld.BroadshieldPack.Notify_BulletImpactNearby (RimWorld.BulletImpactData impactData) [0x0000e] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at RimWorld.Bullet.NotifyImpact (Verse.Thing hitThing, Verse.Map map, Verse.IntVec3 position) [0x00074] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at RimWorld.Bullet.Impact (Verse.Thing hitThing) [0x0004a] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at Verse.Projectile.ImpactSomething () [0x00329] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at Verse.Projectile.Tick () [0x000ed] in <c36f9493c9844ddaa7fb5c788416098f>:0

**Comment by geojak** [comment]
[Smokepoperror.zip](https://github.com/cseelhoff/RimThreaded/files/6133404/Smokepoperror.zip)

**Comment by Eldulac** [comment]
**[Tested on RT 1.3.2]**
I tested the save provided here, and was able to reproduce the error...However, the same error happened even without RimThreaded.

**Conclusion**
This is an issue with RimWorld itself, and is not related to RimThreaded.

**Comment by geojak** [comment]
Oh sorry about that. I had too much trust in Tynan apparently... #foxyourgamegoddammit

**Comment by Eldulac** [comment]
> 
> 
> Oh sorry about that. I had too much trust in Tynan apparently... #foxyourgamegoddammit

It's okay, that's why we test these. But do keep this issue open, as there is a reason we didn't close it ourselves. ;)
It is now labeled as a Vanilla Bug and will be forwarded to Tynan, I believe.

**Comment by geojak** [comment]
oh you will forward it? let me edit that # out real quick :P
