### ISSUE TITLE
"Alpha Animals" Unable to right click to prioritize deconstruction of doors

### ISSUE THREAD

**Issue by taranjlu** [cseelhoff/RimThreaded#483]
**Description**
Unable to right-click to force pawn to prioritize deconstruction of doors.

**Steps to reproduce**
1. Start new colony, crash land, build a wooden door.
2. Set wooden door to be deconstructed while paused so that pawn doesn't immediately attempt to start deconstructing.
3. Right-click on door.
4. Nothing comes up. No menu option to "force prioritize deconstruction."

**Other Notes**
- The below modlist without RimThreaded works as expected (able to right-click and force prioritize).
- Seems like this might be related to #461

**Mod list**
* Harmony
* Core
* Royalty (optional)
* Vanilla Expanded Framework
* Alpha Animals
* RimThreaded

**Comment by Niilo007** [comment]
yes, this is most likely the same bug as #461 
thank you for the report

**Comment by Bs990** [comment]
Same issue was dismissed as bad mod order, It persisted after I fixed it. Also had Alpha Animals enabled. #479

**Comment by bababooeyy** [comment]
Modlist:
Harmony
Core
Royalty
HugsLib
Vanilla Framework Expanded
Alpha Animals
Rimthreaded[Preview 2.0.5]

*Issue no longer occurs on preview 2.0.5. The behaviour is as expected.*

There was error when right clicking doors and autodoors in 1.3.2 though. It probably isn't relevant, but here are the errors.
https://gist.github.com/8aafc3c44d2483e0e7db2d59706889c5
