### ISSUE TITLE
"Dubs Mint Minimap" Pings & Alerts don't disappear

### ISSUE THREAD

**Issue by Endur1el** [cseelhoff/RimThreaded#484]
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report!  

**Describe the bug**
When playing with RT and the minimap, alerts and pings on the map do not disappear. aka if an enemy fires somewhere on the map, you will have a red circle on the minimap until you reload the save.

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Load up new/old save with RT and minimap
2. Either wait for an enemy to fire during raid OR
3. Click on cog next to minimap to open settings menu, then bind ping button to something and click that button on the map.
4. See that the yellow/red circle on the map is not disappearing.

**Error Log**
Does not cause any errors that I can find

**Save file**
Any save file works and as the alerts disappear after reloading a save (I assume they aren't serialized) there's no point in adding a save.

**Screenshots**
![image](https://user-images.githubusercontent.com/50383024/111030376-c7603b00-83f9-11eb-927a-348a263b50e9.png)

**Mod list (Preferably a RimPy compatible list.)**
* Harmony
* Core
* Royalty (optional)
* HugsLib
* Dubs Mint Minimap
* RimThreaded

Edit: I have seen this issue be discussed in the discord and even saw someone claim to make a report about it but as I couldn't find the report and the issue still persists I decided to make one myself.

**Comment by Eldulac** [comment]
**[Tested on RT 1.3.2]**

I tested this issue on a fresh game, and I was able to reproduce it. It is exactly as the author of this issue described it.
The pings get stuck in the map and can only be reset by loading a save back into the game.
This issue only occurs if RT and "Dubs Mint Minimap" are used in conjunction. No errors were logged.

**Conclusion**
This issue is confirmed as reported.

**Comment by Eldulac** [comment]
This issue still occurs with the experimental version 2.0

**Comment by bababooeyy** [comment]
This issue no longer occurs with experimental preview 2.0.5

**Comment by pastorismylord** [comment]
As per @bababooeyy this issue no longer happens in current code train. Closing issue.

**Comment by pastorismylord** [comment]
As per @bababooeyy this issue no longer happens in current code train. Closing issue.
