### ISSUE TITLE
Verse.AI.Pawn_PathFollower; System.NullReferenceException; Error

### ISSUE THREAD

**Issue by Eldulac** [cseelhoff/RimThreaded#485]
**Describe the bug**
After spawning a bunch of trader caravans and waiting a while, these errors happened. There was no noticeable effect apart from the error messages. This is one of two errors that happened during the test.

**Steps to reproduce the behavior**
1. Start a new game
2. Use dev- mode to spawn 10x TraderCaravans
3. Speed up
4. Errors should happen eventually

**Error Log**
https://gist.github.com/Eldulac/afd545e34d6d56df423d42aea8fb6f37
https://gist.github.com/HugsLibRecordKeeper/debf7fe938f19fc88592163e7524cb7d

**Save file**
[TraderCaravanIssue.zip](https://github.com/cseelhoff/RimThreaded/files/6142172/TraderCaravanIssue.zip)

**Mod list**
* Harmony
* Core
* Royalty (optional)
* HugsLib
* Mod Manager
* RimThreaded

**Comment by pastorismylord** [comment]
Unable to reproduce this issue after trying several times with different saves and calling up to 10 merchants. Could be fixed already. Tested with 2.2.17 preview
