### ISSUE TITLE
Verse.AI.ThinkNode_Priority TryIssueJobPackage; Error

### ISSUE THREAD

**Issue by Eldulac** [cseelhoff/RimThreaded#486]
**Describe the bug**
After spawning a bunch of trader caravans and waiting a while, these errors happened. There was no noticeable effect apart from the error messages. This is one of two errors that happened during the test.

**Steps to reproduce the behavior**

1. Start a new game
2. Use dev- mode to spawn 10x TraderCaravans
3. Speed up
4. Errors should happen eventually

**Error Log**
https://gist.github.com/Eldulac/d58ecf801ecd5d6f04e3f719faafe107
https://gist.github.com/HugsLibRecordKeeper/debf7fe938f19fc88592163e7524cb7d

**Save file**
[TraderCaravanIssue.zip](https://github.com/cseelhoff/RimThreaded/files/6142167/TraderCaravanIssue.zip)

**Mod list**
* Harmony
* Core
* Royalty (optional)
* HugsLib
* Mod Manager
* RimThreaded

**Comment by pastorismylord** [comment]
issue no longer present since 2.1.2, re-tested with 2.2.8 to confirm. Issue no longer present with 2.2.8
