### ISSUE TITLE
Errors while Loading a Second Caravan

### ISSUE THREAD

**Issue by Eldulac** [cseelhoff/RimThreaded#487]
**Describe the bug**
When loading a caravan while another caravan is already on the world map, these errors happen. I have added two separate error logs here, because both happened at the same time, and are possibly related. These errors occurred when I was testing another issue regarding caravan traveling errors.

**Steps to reproduce the behavior**
1. Start a new game
2. Form a caravan with a pawn and wait for it to reach the world map
3. Form another caravan
4. The errors should occur before the second caravan reaches the world map

**Error Logs**
https://gist.github.com/Eldulac/caf4ef870ba5a7213299350e37ce456c
https://gist.github.com/Eldulac/e1e6428560c4fd6670588a61a703411a
https://gist.github.com/HugsLibRecordKeeper/ba089d203ed05536c3cd7e5aafb424d5

**Save file**
[Second Caravan Loading issue.zip](https://github.com/cseelhoff/RimThreaded/files/6144408/Second.Caravan.Loading.issue.zip)

**Mod list**
* Harmony
* Core
* Royalty (optional)
* HugsLib
* Mod Manager
* RimThreaded

**Comment by bababooeyy** [comment]
occurs in 2.0.5 preview

**Comment by bababooeyy** [comment]
occurs in 2.0.7 preview

**Comment by cseelhoff** [comment]
Fixed in 2.1.4

**Comment by pastorismylord** [comment]
confirmed fix works on 2.1.5
