### ISSUE TITLE
"Turn it On and Off" Occasional Thread Restart and Errors

### ISSUE THREAD

**Issue by Enduriel** [cseelhoff/RimThreaded#488]
**Describe the bug**
When cooking food for long enough, eventually the thread will time out and restart, causing hang-ups and throwing errors.
Additionally the power consumption of workbenches flickers when they are in use.

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Set a pawn to cook food (seems more reliable with food that requires 2 sources, eg fine/lavish meals)
2. Wait for some time, fairly random but will happen eventually (max 3-5 min)
3. See game freeze, then continue and errors in log

**Error Log**
[Player.log](https://gist.github.com/Endur1el/5673931f3554ef873b240175ca90f27e)
[HugsLib log](https://gist.github.com/921240129018be80c9a3b9aba1177946)

**Save file**
Test save file I made to make the testing process faster zip
[Turn it On and Off Test.zip](https://github.com/cseelhoff/RimThreaded/files/6145221/Turn.it.On.and.Off.Test.zip)

**Mod List**
[Mod list length: 6]
Harmony [https://steamcommunity.com/sharedfiles/filedetails/?id=2009463077]
Core [https:// no link (local mod)]
Royalty [Official DLC] [https:// no link (local mod)]
HugsLib [https://steamcommunity.com/sharedfiles/filedetails/?id=818773962]
Turn It On and Off [https://steamcommunity.com/sharedfiles/filedetails/?id=2007163386]
RimThreaded [1.2] [https://steamcommunity.com/sharedfiles/filedetails/?id=2222907981]

Other Turn it On and Off bug reports were closed by their OPs and do not seem to be getting worked on but this issue persists.

**Comment by bababooeyy** [comment]
Does not occur in 2.0.5 preview

**Comment by pastorismylord** [comment]
loaded the provided save with 2.2.17. Random Red errors related to HugsLib and System.Collections are happening with this mod.
It does seem compatible but with errors

here are the logs: https://gist.github.com/e581add631f1e2cccc88210632deb20c
