### ISSUE TITLE
"Rimworld - Witcher Monster Hunt" - Unable to prioritize jobs in doorframe

### ISSUE THREAD

**Issue by KongMD-Steam** [cseelhoff/RimThreaded#493]
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report!  

**Describe the bug**
This bug involves a 100% reproducible error where jobs inside of doorframes throw an error if you right-click them with a pawn selected. The details on the error message, a save file, and reproduction steps for the error are below.

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Start a new colony. Default settings are fine. Location doesn't matter.
2. Turn on God Mode and build a Door over any Chunk object.
3. Select the chunk and mark it to be hauled.
4. Select a colonist > Right-click the chunk
5. Observe the error in the log

**Alternate Repro steps**
1. Start a new colony. Default settings are fine. Location doesn't matter.
2. Turn on God Mode and build a Door over any non-tiled terrain, like Dirt
3. Turn off God Mode and queue up an order to build any floor tile on the Door
4. Select a colonist > Right-click the floor tile
5. Observe the error in the log

**Error Log**
https://gist.github.com/HugsLibRecordKeeper/b88aa0d9754d49bd3494be361ca810c5

**Save file**
[Monster Hunter Door Error.zip](https://github.com/cseelhoff/RimThreaded/files/6217511/Monster.Hunter.Door.Error.zip)

**Screenshots**
![Monster Hunter Error](https://user-images.githubusercontent.com/36478131/112756743-19968400-8fd6-11eb-9d00-d99f0deb41ea.png)

**Mod list (Preferably a RimPy compatible list.)**
RimPy modlist Attached.
[Monster Hunter Door Bug Modlist.zip](https://github.com/cseelhoff/RimThreaded/files/6217492/Monster.Hunter.Door.Bug.Modlist.zip)

**Comment by 15adhami** [comment]
Tested in RT 1.3.2 and 2.0.7. Was able to reproduce bug in 1.3.2, could not find a way to reproduce in 2.0.7; seems to be fixed.
