### ISSUE TITLE
Crash to Desktop after RimThreaded.CompletePostWorkLists() function calls

### ISSUE THREAD

**Issue by KongMD-Steam** [cseelhoff/RimThreaded#494]
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report!  

**Describe the bug**
I was playing the game with an early colony (2nd quadrum) when it crashed to desktop. I'm running 144 mods, none of which are in the Incompatible Mods list.

**Steps to reproduce the behavior (VERY IMPORTANT)**
No known reproduction steps.

**Error Log**
[Player.zip](https://github.com/cseelhoff/RimThreaded/files/6217999/Player.zip)

**Save file**
I loaded up my autosave before the crash, but the in-game time progressed past that day and I couldn't reproduce the problem. I also didn't get a crash when harvesting that same set of berry bushes again.

**Screenshots**
![Screenshot - 3_28_2021 , 4_14_57 PM](https://user-images.githubusercontent.com/36478131/112766956-bb809580-9003-11eb-842a-fcc521cb6bce.png)

**Mod list (Preferably a RimPy compatible list.)**
[RimPy ModList.zip](https://github.com/cseelhoff/RimThreaded/files/6218001/RimPy.ModList.zip)

**Comment by pastorismylord** [comment]
most of the errors present in the log are no longer present in the 2.x codebase.
