### ISSUE TITLE
Sparta rimthread 670 colonists 

### ISSUE THREAD

**Issue by TheVillageGuy** [cseelhoff/RimThreaded#50]
Look at all the 1000ms errors, it was set at 9999. I've changed it to 10000 again, after the thread 89 did not finish line

So strange I was getting a lot better performance this morning. Like I said spikes of about of a second while now it's taking very long in between ticks.

[Player.log](https://github.com/cseelhoff/RimThreaded/files/5209638/Player.log)
[modlist.txt](https://github.com/cseelhoff/RimThreaded/files/5209640/modlist.txt)

2nd attempt, with 32 threads
[modlist.txt](https://github.com/cseelhoff/RimThreaded/files/5209669/modlist.txt)
[Player.log](https://github.com/cseelhoff/RimThreaded/files/5209672/Player.log)

3rd attempt. no mods, will probably give a lot of errors due to that, but should not really mess the game up as I don't use mods that change the game. I want it to be able to load without mods.

[Player.log](https://github.com/cseelhoff/RimThreaded/files/5209696/Player.log)

Regards!

**Comment by cseelhoff** [comment]
Added all the bugs I found in your logs as separate issues. Time to tackle them now!

**Comment by cseelhoff** [comment]
Also, I think TD_Enhancements might be causing some issues. Also turning fluffy manager BACK ON might help

**Comment by TheVillageGuy** [comment]
Can't look right now but I think I only turned off av free mods once just
to see if they were causing the problem, I never saved the game with those
mods disabled,v so they shouldn't be now. Correct me if I'm wrong.
