### ISSUE TITLE
"SS Researchable Stat Upgrades (Reupload)" repetable research error

### ISSUE THREAD

**Issue by casinodoug** [cseelhoff/RimThreaded#500]
**Describe the bug**
researching repeatable research only currently tested on SS Researchable Stat Upgrades (Reupload) final research with multiple researchers at the same time causes error

**Steps to reproduce the behavior (VERY IMPORTANT)**
1:have more then once pawn researching at the same time
2:finish researching repeatable research
3:check logs

**Error Log**
https://pastebin.com/mgPUcczR

**Save file**
[newtest.zip](https://github.com/cseelhoff/RimThreaded/files/6332814/newtest.zip)

**Screenshots**
!!! Add screenshots to help explain your problem here !!!

**Mod list (Preferably a RimPy compatible list.)**
* Harmony
* Core
* HugsLib
*SS Researchable Stat Upgrades (Reupload)
* RimThreaded

**Comment by 15adhami** [comment]
Tested in 1.3.2 and 2.0.7. Happens in both versions.
1.3.2: https://gist.github.com/HugsLibRecordKeeper/b715ede6df7d18a5621c5cb1251ca279
2.0.7: https://gist.github.com/HugsLibRecordKeeper/095f1394e334b5560944b33216ecff29

**Comment by pastorismylord** [comment]
solved on 2.3.5 preview
