### ISSUE TITLE
"Project RimFactory Revived" sound related errors bloat player log, planter drones throw yellow and some red errors

### ISSUE THREAD

**Issue by pO0P3R125** [cseelhoff/RimThreaded#501]
**Log is spammed and bloated in sound ticks and Planter Drones**
!!! The entire log is filled and bloated in errors about a sound having to run in the main thread, Planter Drones throwed some yellow errors too they stole each other reserved works and occasionally it threw some red !!!

**To reproduce Sound Bug**
1. Have any machine in the mod
2. Will not show in console but it will start spamming sound related errors in the player log

**To reproduce Planter Drone**
1. Have Planter Drones mk iii (fastest one)
2. Overclock them at maximum
3. Let them plant for a while
4. They start to steal each other reserved jobs

**Error Log**
In game log:
https://drive.google.com/file/d/1XRAhpIHVTXlVPO8-yeaijyltCQBCXOET/view?usp=drivesdk
Player log:
https://drive.google.com/file/d/1x-lJ-nwWHs8OkPqIEl7E9oyZ_vET717f/view?usp=drivesdk
Didn't let me upload, it throw me an error in hugslib

**Save file**
https://drive.google.com/file/d/1Bt4J_dC3j9ogiYu8sTIwi8u60e58CfSC/view?usp=sharing

**Screenshots**
Later (sorry ;-;)

**Mod list (Preferably a RimPy compatible list.)**
* Harmony
* Core
* Royalty (optional)
* HugsLib
* Not Steam Alert (Inconsequential)
* Project RimFactory Reloaded
* RimThreaded

**Comment by LeninsCat** [comment]
### Testers Synopsis

Testing each issue, I shall address what did first;
For the Cultivator Drone Mark III error, I did manage to reproduce it, although it wasn't as often as this post put forward.
Also, for some reason, the Huglib log was un-uploadable, which is strange and suggests a larger issue. 
![image](https://user-images.githubusercontent.com/66055549/116833563-9e4d6280-ab7f-11eb-80da-41572df56a4b.png)

I was completely unable to reproduce the sound error, the Player.log had nothing to say and only repeated what was seen in the normal log.

TESTER'S LOG:
https://gist.github.com/LeninsCat/4f882ab0378a6698eb778c8c7eeca15b

**Comment by 15adhami** [comment]
Tested on 1.3.2 and 2.0.7. Was able to reproduce the bug in 1.3.2, although it didn't seem to have any affect on gameplay: https://gist.github.com/HugsLibRecordKeeper/c7208b13faadeeda8603671857869f8a.
Could not reproduce it anymore in 2.0.7.
Also wasn't able to reproduce the sound bug at all.

**Comment by pO0P3R125** [comment]
Sorry Maybe too late but here is one save with the error
https://drive.google.com/file/d/1Bt4J_dC3j9ogiYu8sTIwi8u60e58CfSC/view?usp=sharing

**Comment by pastorismylord** [comment]
unable to reproduce with 2.1.5 and this save. Further testing is required to confirm full compatibility with RimFactory
