### ISSUE TITLE
2.0.7 Unable to change animal's master or train some animals

### ISSUE THREAD

**Issue by 15adhami** [cseelhoff/RimThreaded#502]
Found in RT 2.0.7, seems to be working correctly in 1.3.2. You are unable to change the master of animals, and sometimes you can't train your animals. I found that sometimes when you tame a new animal, you are able to train them, but in other cases you are unable to. This issue doesn't cause any error messages.

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Create new save file
2. Try to train your starting animal, or change its master
3. Doesn't work. 
4. Alternatively, load the save file in this issue to reproduce.

**Save file**
[AnimalTraining.zip](https://github.com/cseelhoff/RimThreaded/files/6390772/AnimalTraining.zip)

**Mod list (For vanilla report, it has to be same as below list.)**
* Harmony
* Core
* Royalty (optional)
* HugsLib
* RimThreaded

**Comment by Niilo007** [comment]
i had this issue while testing the bulk assignment issue #502

**Comment by cseelhoff** [comment]
Fixed in 2.1.3

**Comment by pastorismylord** [comment]
verified fix with 2.1.5, issue is solved.
