### ISSUE TITLE
(2.2.1) Anima tree produces multiple patches of grass instead of one

### ISSUE THREAD

**Issue by Xsardi** [cseelhoff/RimThreaded#506]
When multiple pawns meditate near anima tree and grass progress reaches 100% it sometime spawns more than one patch of anima grass, with error popping up in log. Game speed affects probability of this error happening and amount of spawned grass. Max amount of grass spawned at a time seems to match with amount of working threads. In some cases progress untill the next spawn resets to -100%.

1. Start a new game with tribal pawns
2. Place meditation spots around anima tree
3. Put multiple colonists on schedule to meditate
4. Wait for them to meditate until anima 'progress' reaches 100%
5. Check on amount of spawned anima grass 
6. Repeat steps 4-5 until it produces more than one

Error Log
player.log: https://gist.github.com/Xsardi/77a15a85986d96c40d529c9fbfcad78f
HugsLib log: https://gist.github.com/f05aa2638089ec5f66d23093c5e4e9b0

Save file
[rw_bug.zip](https://github.com/cseelhoff/RimThreaded/files/6489662/rw_bug.zip)
"The Laorro Covenant BAD.rws" - where I first encountered it and where logs were taken from
"test2" - fresh start with testing setup

Screenshot before/after reaching 100% progress on the tree:
![image](https://user-images.githubusercontent.com/17524224/118406421-ae3b6b00-b684-11eb-81e6-f22c1a1fb0e2.png)

Grass patches appear on the same tile:
![image](https://user-images.githubusercontent.com/17524224/118406660-610bc900-b685-11eb-9fe5-0eb9c8c9e339.png)

Mod list:
Harmony
Core
Royalty
HugsLib
RimThreaded

**Comment by pastorismylord** [comment]
tested with attached files and 2.2.0. Issue Persist on 2.2.0

**Comment by pastorismylord** [comment]
Just tested with 2.2.5. Anima tree still has negative percentages and now, when completing anima grass the game breaks. I tested used the provided saves on this issue.

**Comment by pastorismylord** [comment]
this issue has been solved on 2.2.8, verified by using both attached savegames
