### ISSUE TITLE
(2.2.7) Double bed issues.

### ISSUE THREAD

**Issue by Niilo007** [cseelhoff/RimThreaded#507]
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report!  

**Describe the bug**
When having two pawns assigned to a double bed, one of the pawns will either get a new bed or sleep on the floor if no spare beds are avaible. so two lovers assigned to a double bed will not sleep together because of this

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Load save
2. assign the lover pawns to the double bed
3. when night comes, one of them will opt to sleep on the floor or go to an unoccupied bed, if there are spare beds.
4. there should be an error when the bug happens
5. it might take a few tries, but its easy to reproduce, it happened to me during normal play

**Error Log**
!!! Link to contents of Player.log or Error.log (MUST BE LINK) !!!
https://gist.github.com/HugsLibRecordKeeper/1e7999e246d05ca98cb011a92d122d3d

**Save file**
[Goan (Permadeath).zip](https://github.com/cseelhoff/RimThreaded/files/6510802/Goan.Permadeath.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/75486261/118861025-b85ba480-b8e4-11eb-911f-dbb6ae5f850b.png)

**Mod list (For vanilla report, it has to be same as below list.)**
* Harmony
* Core
* Royalty (optional)
* HugsLib
* RimThreaded

**Comment by bababooeyy** [comment]
Confirmed 

Vanilla Save with minimal modlist:
https://drive.google.com/file/d/1LMfCmdpTOVBFhImi8JxVWbFjn2KVrl6H/view?usp=sharing

**Comment by pastorismylord** [comment]
bug still present on 2.2.1

**Comment by Niilo007** [comment]
still broken on 2.2.2

**Comment by Niilo007** [comment]
still happens on 2.2.7 hoff is looking into it

**Comment by pastorismylord** [comment]
fixed on 2.2.8, confirmed by running existing saves and trying new colonies.
