### ISSUE TITLE
(2.2.1) Plant / Tree generation is broken

### ISSUE THREAD

**Issue by Niilo007** [cseelhoff/RimThreaded#508]
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report!  

**Describe the bug**
I generated a couple of maps and 2/2 generated without trees, berries or healroot

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Generate a world (i used seed "beet" globe coverage 50%)
![image](https://user-images.githubusercontent.com/75486261/118866574-d0cebd80-b8ea-11eb-8550-80020aa9e7ca.png)
Coordinates in image
2. Click on the same tile
3. land
4. map will gen with no trees or berries or any other plants of that kind. only grass

**Error Log**
!!! Link to contents of Player.log or Error.log (MUST BE LINK) !!!
https://gist.github.com/3357a59bbc1eb31bea6d27161d55a002

**Save file**
[Thioresuay Strong League (Permadeath).zip](https://github.com/cseelhoff/RimThreaded/files/6510965/Thioresuay.Strong.League.Permadeath.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/75486261/118866394-9f55f200-b8ea-11eb-9b46-506764ebee37.png)

**Mod list (For vanilla report, it has to be same as below list.)**
* Harmony
* Core
* Royalty (optional)
* HugsLib
* RimThreaded

**Comment by pastorismylord** [comment]
tested this issue in parallel with @Niilo007, was able to replicate the issue with a different seed, different altitudes and different biomes. No trees, berries and medicine plants generated with Rimthreaded during map generation.

**Comment by pastorismylord** [comment]
bug still present on 2.2.1

**Comment by pastorismylord** [comment]
fixed on 2.2.5
