### ISSUE TITLE
(2.2.8) Colonists wont farm area after first time

### ISSUE THREAD

**Issue by Rakaesa** [cseelhoff/RimThreaded#509]
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report!  

**Describe the bug**
After loading any colony / save file, colonists will only sow/harvest an area a single time. After that, they will never automatically interact with the area again. Colonists can still be forced to sow in that area by selecting them and right-clicking the spot, but they will not prioritize it automatically. Farmers will go idle even if there is sowing area available and they are set to priority 1 on growing work. This makes farming nigh impossible without reloading the game after every round of sowing/harvesting, and reloading a save sometimes causes an error on map generation and requires a complete game restart.

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Start or load a game.
2. Let farmers sow/harvest once.
3. They wont automatically sow/harvest the same area again.

**Error Log**
https://gist.github.com/dc03ec4435be237e1fef8f2f2b875270

**Save file**
Literally any colony, including the 'Agriculture and Animals' tester save file.

**Screenshots**
[image](https://user-images.githubusercontent.com/54375203/119274397-b2640d00-bbdd-11eb-86af-e6255a6ebacd.png)

**Mod list (For vanilla report, it has to be same as below list.)**
* Harmony
* Core
* Royalty (optional)
* HugsLib
* RimThreaded

**Comment by Niilo007** [comment]
confirmed in 2.2.7 with the farming test save

**Comment by 15adhami** [comment]
Still happens somewhat in 2.2.13. The colonists will initially sow the crops, but when you change it to a different plant they will sow the plants in "chunks" it seems. Like they would sow a few plants, then go idle for a few seconds, then sow a few plants again, etc.
