### ISSUE TITLE
(2.2.8) Failed find all necesary river flow data

### ISSUE THREAD

**Issue by pastorismylord** [cseelhoff/RimThreaded#511]
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report!  

**Describe the bug**
Maps with rivers are not generating correctly

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Generate a new world
2. use any seed, any size
3. select a tile with river
4. issue will trigger

**Error Log**
!!! Link to contents of Player.log or Error.log (MUST BE LINK) !!!
https://gist.github.com/c42cc7e886d4c8906b81850a50d852dc

**Save file**
!!! Please add a save file where the issue occurs to speed up testing and fixing of the issue !!!
This is a map generation issue, no way to provide a save for this one

**Screenshots**
!!! Add screenshots to help explain your problem here !!!

**Mod list (For vanilla report, it has to be same as below list.)**
* Harmony
* Core
* Royalty (optional)
* HugsLib
* RimThreaded

**Comment by cseelhoff** [comment]
does this happen in vanilla? rivers work fine for me...
![image](https://user-images.githubusercontent.com/22664374/119422860-f0415e00-bccf-11eb-8c4c-0649c582e39b.png)

**Comment by pastorismylord** [comment]
tried with only vanilla RT, no errors that way. Further investigation is needed
