### ISSUE TITLE
(2.2.8) Colonists won't haul

### ISSUE THREAD

**Issue by pastorismylord** [cseelhoff/RimThreaded#512]
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report!  

**Describe the bug**
When hunting animals, colonists will not haul the carcass for processing inside the colony. 
[will not haul dead animals.zip](https://github.com/cseelhoff/RimThreaded/files/6530158/will.not.haul.dead.animals.zip)

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. load attached savefile
2. The issue has already triggered

To trigger from scratch
1. Start a new game
2. Create a stockpile zone to accept animal carcass
3. designate a hunter
4. designate a wild animal to hunt
5. hunter will hunt the animal but will not haul the carcass
6. when trying to order a colonist to haul the animal, the option will not be available due to no storage space available

**Error Log**
!!! Link to contents of Player.log or Error.log (MUST BE LINK) !!!
!!! Link to HugsLib log. (MUST BE LINK) !!!
https://gist.github.com/b138e30c462033c6eb3d6b4c7689800f

**Save file**
!!! Please add a save file where the issue occurs to speed up testing and fixing of the issue !!!
included save file
**Screenshots**
!!! Add screenshots to help explain your problem here !!!
![screenshot6](https://user-images.githubusercontent.com/53154863/119303948-24fbd980-bc2c-11eb-918e-94825d959d7c.png)

**Mod list (For vanilla report, it has to be same as below list.)**
* Harmony
* Core
* Royalty (optional)
* HugsLib
* RimThreaded

**Comment by pastorismylord** [comment]
[exception plant spawner.zip](https://github.com/cseelhoff/RimThreaded/files/6536411/exception.plant.spawner.zip)
in this save, after the colonists finish building a wall, they will not prioritize hauling miscellaneous items into the stockpile zone. This save seems easier to trigger.

**Comment by 15adhami** [comment]
Hauling doesn't work properly in 2.2.13 either. On a new save I created a stockpile and set it to medicine. Then I unforbid the medicine on the ground but no pawns haul the medicine until I manually force them to.

**Comment by cseelhoff** [comment]
sorry guys, I just can't seem to reproduce this issue, even with the provided saves. Hopefully later, you can demo this to me live, when you have some time

**Comment by pastorismylord** [comment]
> 
> 
> Hauling doesn't work properly in 2.2.13 either. On a new save I created a stockpile and set it to medicine. Then I unforbid the medicine on the ground but no pawns haul the medicine until I manually force them to.

can you please make another report for that one?
 
I was able to reproduce the issue

**Comment by pastorismylord** [comment]
marking this one as closed
