### ISSUE TITLE
(2.2.9) Temperature of tiles change when world is generated multiple times

### ISSUE THREAD

**Issue by 15adhami** [cseelhoff/RimThreaded#513]
Happens in earlier versions as well, but currently tested in 2.2.9. When you generate a world for the first time upon booting the game up, everything will work as intended. But if you go back and change the seed, then the next world you will generate will have incorrect temperatures on many of its tiles. For example, you can find tundras will year-round growing, or an ice sheet with 10 days for growing. No error message will be in the logs.

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Generate a world (I chose "stone" as the seed, and left everything else default)
2. Check tundra and ice sheet tiles, everything will be ok. (Tundras can only have up to 20 days growing, and ice sheet can never grow.)
3. Go back, and change your seed (I had "gore")
4. Check tiles, you will find some tundras and ice sheets with the incorrect temperatures (in the "gore" seed, I found some 30 day tundras in the small patches of tundra biome in the desert)

If you try generating with the seed "gore" first, you will see that it won't have any 30-day growing season tundra tiles. So it seems like it only happens on the second planet you generate. Doing the same seed twice in a row doesn't seem to cause any issues, such as stone then stone again. If doing stone, then gore, then back to stone, the tiles will have the correct temperature still even though they were incorrect in gore.

**Mod list (For vanilla report, it has to be same as below list.)**
* Harmony
* Core
* Royalty (optional)
* HugsLib
* RimThreaded 2.2.9

**Comment by pastorismylord** [comment]
This issue was solved on 2.2.12, additional testing is required to validate fix.
