### ISSUE TITLE
(2.2.11) Growing zones will not trigger boulder hauling

### ISSUE THREAD

**Issue by pastorismylord** [cseelhoff/RimThreaded#515]
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report!  

**Describe the bug**
when creating a growing zone, and the area of the zone includes boulders, the game will not trigger hauling orders automatically to move the boulders out of the way for sowing the growing zone.

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Open the attached save
2. hit 4

Recreating without the save:
1. Create a sowing/growing zone on top of boulders
2. when the colonists start sowing, they will ignore the boulders and not move them (in vanilla, the colonists will move the boulders to the edge of the growing zone)

**Error Log**
!!! Link to contents of Player.log or Error.log (MUST BE LINK) !!!
!!! Link to HugsLib log. (MUST BE LINK) !!!
No errors triggered

**Save file**
!!! Please add a save file where the issue occurs to speed up testing and fixing of the issue !!!
[growin zones boulder hauling.zip](https://github.com/cseelhoff/RimThreaded/files/6536462/growin.zones.boulder.hauling.zip)

**Screenshots**
!!! Add screenshots to help explain your problem here !!!

**Mod list (For vanilla report, it has to be same as below list.)**
* Harmony
* Core
* Royalty (optional)
* HugsLib
* RimThreaded

**Comment by 15adhami** [comment]
Tested in 2.2.13. On a new save I created a few growing zones over boulders and bushes, and the pawns moved the boulders and cut the bushes.
