### ISSUE TITLE
(2.2.11) Slaughtering an predators throws an error

### ISSUE THREAD

**Issue by 15adhami** [cseelhoff/RimThreaded#516]
Slaughtering an animal throws an error.  Not sure if it causes an impact in gameplay or not.

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Create new save
2. Slaughter your animal
3. See error

**Error Log**
https://gist.github.com/90fa4513c70a885872684b5fabeadd32

**Mod list (For vanilla report, it has to be same as below list.)**
* Harmony
* Core
* Royalty (optional)
* HugsLib
* RimThreaded

**Comment by cseelhoff** [comment]
I am having trouble reproducing this one. Is this consistently happening?

**Comment by 15adhami** [comment]
> I am having trouble reproducing this one. Is this consistently happening?

I am on 2.2.14 and I can reproduce it by simply creating a new colony with the crashlanded scenario, and slaughtering my animal.

**Comment by pastorismylord** [comment]
I was unable to recreate the issue with 2.2.14, still figuring out a way to reproduce it.

**Comment by pastorismylord** [comment]
testing with 2.2.14:

-  I generated a new colony, 
- Used the debug tool to tame wild animals,
- Tamed a raccoon, 2 deer, 2 caribous.
- Proceeded to slaughter them all

No errors were triggered during this test.

**Comment by pastorismylord** [comment]
Finally able to reproduce the error. Seems to be triggered by slaughtering predators.

Save attached is ready to trigger

[slaughter error.zip](https://github.com/cseelhoff/RimThreaded/files/6542457/slaughter.error.zip)

**Comment by 15adhami** [comment]
Tested in 2.2.15. Attempted slaughtering animals multiple times, both with and without the animal tab open. Wasn't able to get an error.
