### ISSUE TITLE
(2.2.13) Caravan moving very slowly and not updating needs

### ISSUE THREAD

**Issue by 15adhami** [cseelhoff/RimThreaded#517]
In 2.2.13, when there is a caravan on the world map, it will be moving extremely slowly. Also the colonists will never eat anything no matter how hungry they are, and their rest need doesn't go up when resting. No errors in log.

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Create new save
2. Create caravan and bring some food
3. See how slow caravan is. Fast forward and wait until pawn needs to eat.
4. They won't eat.

**Mod list (For vanilla report, it has to be same as below list.)**
* Harmony
* Core
* Royalty (optional)
* HugsLib
* RimThreaded

**Comment by pO0P3R125** [comment]
Confirmed, also I noticed pawns dont eat while in the caravan and they still have all the food they pick up

**Comment by 15adhami** [comment]
Tested multiple times in 2.2.17. Caravans seem to work without issues, including having multiple caravans at the same time.
