### ISSUE TITLE
Hauling Stops Working (RT 2.2.19)

### ISSUE THREAD

**Issue by pO0P3R125** [cseelhoff/RimThreaded#520]
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report!  

**Describe the bug**
Pawns will not haul all items to the stockpile, sometimes they will haul some and ignore specific items, some others, they will first haul some things and then they dont seem to do hauling again (example: they will haul some steel once and then not haul other stacks of steel)

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Create new colony or load the save provided
2. Create an stockpile
3. Allow some items
4. Pawns will haul some items and ignore others

**Error Log**
There is not

**Save file**
https://drive.google.com/file/d/1AA8X-AXAgRb6tWd5ap88k9E6lKx4DcWt/view?usp=sharing

**Screenshots**
<img width="320" alt="RimWorldWin64_GLR5prYuYQ" src="https://user-images.githubusercontent.com/43865463/119555410-7490f100-bd63-11eb-9126-b74388fe5c19.png">
<img width="578" alt="RimWorldWin64_OXp86Uw96X" src="https://user-images.githubusercontent.com/43865463/119555420-76f34b00-bd63-11eb-8308-f2faa0e6f864.png">
![RimWorldWin64_DSEqXOlnl5](https://user-images.githubusercontent.com/43865463/119555450-7e1a5900-bd63-11eb-90d4-294eb0b0eeba.jpg)
<img width="415" alt="RimWorldWin64_C2sv7fhQUj" src="https://user-images.githubusercontent.com/43865463/119555458-81154980-bd63-11eb-9243-d77d2442f129.png">
<img width="518" alt="RimWorldWin64_KDBlge3DwV" src="https://user-images.githubusercontent.com/43865463/119555478-86729400-bd63-11eb-9723-2c3e1416f832.png">
<img width="534" alt="RimWorldWin64_eJRiwmmlxn" src="https://user-images.githubusercontent.com/43865463/119555500-8a061b00-bd63-11eb-8518-f0e44384ac50.png">
<img width="448" alt="RimWorldWin64_wPQO1DGAdF" src="https://user-images.githubusercontent.com/43865463/119555517-8ffbfc00-bd63-11eb-8fe2-8ead777ead3a.png">
<img width="617" alt="RimWorldWin64_UcIJgyE31Z" src="https://user-images.githubusercontent.com/43865463/119555532-95594680-bd63-11eb-8613-4172294a9bdd.png">

**Mod list (For vanilla report, it has to be same as below list.)**
* Harmony
* Core
* Royalty (optional)
* HugsLib
* RimThreaded

**Comment by 15adhami** [comment]
Still happens in 2.2.17. I created a stockpile on a new save and allowed some items so the pawns could haul them, but they would only haul a few items then stop.

**Comment by 15adhami** [comment]
Occurs in 2.2.19. Create new save file, create a stockpile zone, then allow some of the items that you spawned with. The pawns won't haul all of them.

**Comment by pastorismylord** [comment]
[imranfish hauling test.zip](https://github.com/cseelhoff/RimThreaded/files/6611144/imranfish.hauling.test.zip)

this test is ready to trigger some of the issues with hauling

**Comment by cseelhoff** [comment]
fixed in 2.3.6
