### ISSUE TITLE
Crash when wearing certain clothes while using Facial Stuff 1.1

### ISSUE THREAD

**Issue by CrazySnapDragon** [cseelhoff/RimThreaded#521]
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report!  

**Describe the bug**
When wearing ceartain clothing/hats while using the facial stuff 1.1 mod the game crashes. Facial stuff works fine without rimthreaded on

**Steps to reproduce the behavior (VERY IMPORTANT)**
1.Start any colony with any storyteller
2.Turn on developer mode
3.Spawn Eltex Skullcap
4.Wait or force a colonist to wear the Eltex Skullcap
5.Game Crash

**Error Log**
Player.log https://pastebin.com/rDr1gyxG
Hugslib.log https://pastebin.com/5sVZ74FR

**Save file**
Colonist already selected to wear the eltex skullcap
https://drive.google.com/file/d/1rytHTu4X5ZbLQUfXBWEETfqvBUFzKW7n/view?usp=sharing

**Screenshots**
I didn't screenshot but i recorded the whole process
https://www.youtube.com/watch?v=UPe_fZAyASQ

**Mod list (Preferably a RimPy compatible list.)**
* Harmony
* Core
* Royalty 
* HugsLib
* Facial Stuff 1.1 https://steamcommunity.com/workshop/filedetails/?id=818322128
* RimThreaded (I am using the newest Version 1.3.2)

**Comment by pastorismylord** [comment]
this issue was fixed on 2.2.19
