### ISSUE TITLE
Pawns only sow the fisrt tile of hydroponics basin

### ISSUE THREAD

**Issue by Xsardi** [cseelhoff/RimThreaded#522]
Pawns will only sow the first (left/bottom) tile of hydroponics basin automatically. It's possible to force them to sow other tiles manually. While there's a tile in basin that needs sowing game will produce warnings for each pawn assigned to grow.

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Build hydroponics basin
2. Assign pawn to grow job
3. Wait for pawn to plant a crop in the first tile
4. Observe that pawns won't plant other tiles
5. Check log for warnings

**log**
Player.log: https://gist.github.com/Xsardi/af025b6b418a3e0e28c96b6331d13910
HugsLib log: https://gist.github.com/ed94b9c9e46b1c5037c6e50cb3f15d85

**Save file**
[sowing_save.zip](https://github.com/cseelhoff/RimThreaded/files/6555293/sowing_save.zip)
The Laorro Covenant BAD.rws - where I first encountered an issue. Screen focused on a couple of basins that will be gathered and re-sown with a single rice tile each.
test.rws - fresh start with testing setup.

**Screenshots**
Before/after gathering and replanting a couple of basins:
![image](https://user-images.githubusercontent.com/17524224/119859224-e01ebe00-bf1d-11eb-8487-7744168148eb.png)
Crops that weren't grown enough to be cut are still present after replanting.

Before/after planting in fresh built basins:
![image](https://user-images.githubusercontent.com/17524224/119859685-47d50900-bf1e-11eb-969b-731e1e72988e.png)

Game produces warnings while there's a tile in basin that must be sown:
![image](https://user-images.githubusercontent.com/17524224/119860088-a8fcdc80-bf1e-11eb-8c11-7392e80f433c.png)

You can manually force pawns to sow tiles. If there are no tiles without a crop then warning goes away.
![image](https://user-images.githubusercontent.com/17524224/119860389-ee210e80-bf1e-11eb-8824-cffb26ce353e.png)

**Mod list**
* Harmony
* Core
* Royalty
* HugsLib
* RimThreaded

**Comment by cseelhoff** [comment]
fixed in 2.3.4
