### ISSUE TITLE
Vanilla Weapons Expanded: Triple Rocket Launcher's missiles on impact can cause a red error RT 2.2.18

### ISSUE THREAD

**Issue by pO0P3R125** [cseelhoff/RimThreaded#525]
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report!  

**Describe the bug**
When shooting the missiles of the triple rocket launcher when the explosions occurs it will log an error

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Load Save provided or do your own test setup (new colony, spawn rocket launcher, spawn some raiders)
2. Shoot the raiders (it has to impact several of them for a better chance of happening)
3. See error

**Error Log**
https://gist.github.com/b3f506dbf6afadf20e43eef750e73101

**Save file**
https://drive.google.com/file/d/1SW_s-KMCfWMTkCjLQnfGstILvf7AjuZ_/view?usp=sharing

**Screenshots**
<img width="40" alt="RimWorldWin64_j1tX6tmMQ2" src="https://user-images.githubusercontent.com/43865463/120029857-46f2b480-bfbc-11eb-9f37-ecc5d86bdac9.png">
<img width="167" alt="RimWorldWin64_cY4gdjGWut" src="https://user-images.githubusercontent.com/43865463/120029865-49550e80-bfbc-11eb-8a0d-535e198c0607.png">
![RimWorldWin64_RTonCZsRnl](https://user-images.githubusercontent.com/43865463/120029874-4e19c280-bfbc-11eb-97fd-7fc692270af5.jpg)
<img width="564" alt="RimWorldWin64_Z0NhNlJTGh" src="https://user-images.githubusercontent.com/43865463/120029889-540fa380-bfbc-11eb-8d63-f087f309e480.png">

**Mod list (Preferably a RimPy compatible list.)**
* Harmony
* Core
* Royalty (optional)
* HugsLib
* Vanilla Weapons Expanded
* RimThreaded

**Comment by Niilo007** [comment]
pretty sure this happens with just vanilla + RT

**Comment by Niilo007** [comment]
please specify what version this is

**Comment by 15adhami** [comment]
Confirmed in vanilla + RT 2.2.19. Loaded the provided save then told the pawns to shoot the raiders.

**Comment by pastorismylord** [comment]
@pO0P3R125 please re-test with latest preview. Also, try to reproduce on a fresh save.

**Comment by pO0P3R125** [comment]
solved
