### ISSUE TITLE
(2.2.19) Beauty tabs not showing numbers

### ISSUE THREAD

**Issue by Courier6Lau** [cseelhoff/RimThreaded#528]
A minor bug with beauty tab, it doesn't show the numbers of each plot

Steps to reproduce the behavior 
1. Click on beauty tab
2. Choose a plot to check

![image](https://user-images.githubusercontent.com/85052635/120101443-b2818100-c178-11eb-860d-a760215a3132.png)

Mod list 
* Harmony
* Core
* HugsLib
* RimThreaded (2.2.19)

**Comment by 15adhami** [comment]
Confirmed in 2.2.19. Created a new save and enabled beauty display, but the numbers on top of each tile weren't there.

**Comment by cseelhoff** [comment]
I think this is fixed in 2.3.4 
![image](https://user-images.githubusercontent.com/22664374/121987610-d216cd00-cd66-11eb-9e03-4286aaa01e91.png)
