### ISSUE TITLE
(2.2.19) "It's not possible to reach the tile from the last waypoint" when trying to caravan

### ISSUE THREAD

**Issue by 15adhami** [cseelhoff/RimThreaded#529]
Very rarely when you try to caravan, when you right-click on a tile for your destination you get a message saying "It's not possible to reach the tile from the last waypoint" and you can't form the caravan. I don't know how to reproduce, it has happened once before on a fresh vanilla save, and twice on a modded save. There are no errors. Reloading fixes the issue, so I can't provide a save.

**Mod list (For vanilla report, it has to be same as below list.)**
* Harmony
* Core
* Royalty (optional)
* HugsLib
* RimThreaded

**Comment by SylenMG** [comment]
(2.2.19) same issue and error with SRTS Expanded.

**Comment by pastorismylord** [comment]
This issue seems related to https://github.com/cseelhoff/RimThreaded/issues/527
