### ISSUE TITLE
Game freezing due to ticks (as per log says)

### ISSUE THREAD

**Issue by alighahremani97** [cseelhoff/RimThreaded#530]
**Describe the bug**
I don't know what happened, but I was running rimthreaded with mods before, and added the following mods mid game:
SRTS Expanded
Gun nut chapter 1
Gun nut chapter 2
Gun nut community pack
Gun nut fn-Scar
misc robots++
WorldEdit 2.0
Auto-cut Blight
Trader Ships
Trader Ship Drop Spot
Simple sidearms

and then, upon loading the save file, I got game freezes of 5 seconds, every 2-3 seconds (so frames realistically dropped to maybe 60 per minute). Upon pausing the game (mid freeze or not) game would be paused ok (with the freezes it would happen as the game unfroze). Upon removing Rimthreaded and launching the game again, problem was solved. I generated the log report, and apparently a pawn tick (Exception ticking Oli (at (93, 0, 121)): System.Threading.ThreadAbortException) is throwing threadabortexception (which would make sense with my timeout of 5000 milliseconds) I do not know what exactly is causing this issue

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Simply use RimPy's mod manager to reactivate "Rimthreaded" (I assume you guys either pull from the mod list, or from the save for the rest of the mods)
2. Sort the mods
3. launch the game
4. load the save file
5. the freezing should show upon unpausing, and the log should throw the exception

**Error Log**
https://gist.github.com/HugsLibRecordKeeper/e264d9e29584103a6c78123042488946

**Save file**
!!! Please add a save file where the issue occurs to speed up testing and fixing of the issue !!!
(I know very creative, sue me)
[Terran Expedition.zip](https://github.com/cseelhoff/RimThreaded/files/6574017/Terran.Expedition.zip)

**Screenshots**
None

**Mod list (Preferably a RimPy compatible list.)**
[terran expedition mod list.txt](https://github.com/cseelhoff/RimThreaded/files/6574003/terran.expedition.mod.list.txt)

**Comment by pastorismylord** [comment]
Please try again with the latest version of rimthreaded published as a preview in our discord server.

**Comment by alighahremani97** [comment]
So far the issue seems resolved with the latest release on discord. Is there a reason as to why steam version is not updated?

**Comment by pastorismylord** [comment]
There are small bugs yet to be fixed. Need more testers to find any undiscovered bugs before release. Also, there's a few mod incompatibilities we want to straight up before launch.

**Comment by alighahremani97** [comment]
Good to know, thank you for your help
