### ISSUE TITLE
RimThreaded Stockpile Zone Bug

### ISSUE THREAD

**Issue by yeems16** [cseelhoff/RimThreaded#534]
**Describe the bug**
Sometimes when switching from 3 to 4 speed, you can get errors when attempting to expand stockpile zones. Sometimes, it will reduce your ability to expand the stockpile zones only by one tile at a time.

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Create new game
2. Create stockpile zones, and expand them while switching between 3 and 4 speed. Enable auto log pop-up as well to make it easier.
3. See error after about 15 minutes of doing this. Could be shorter or longer, that was just about the time it took for me.

**Error Log**
Error Log: https://gist.github.com/yeems16/45b3726b8791742e45c93deef71cea9a

**Save file**
Save File: https://drive.google.com/file/d/1_4HQeJTv3fw30P3AwmsjW2V-WxvckeOH/view?usp=sharing

**Screenshots**
![image](https://user-images.githubusercontent.com/85475900/121121993-7fbd3580-c7d5-11eb-957c-74c33357923e.png)

**Mod list (For vanilla report, it has to be same as below list.)**
* Harmony
* Core
* Royalty
* RimThreaded

I am using the latest build of RimThreaded from the discord releases channel. This also happens to me on my modded playthrough, just much more frequently and the tile-by-tile expansion problem happens a whole lot more. Reloading the save generally fixes the issue.

**Comment by pastorismylord** [comment]
verified this issue is fixed on the 2.x release. All good
