### ISSUE TITLE
Error when expanding stockpiles RT 2.2.19

### ISSUE THREAD

**Issue by pO0P3R125** [cseelhoff/RimThreaded#537]
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report!  

**Describe the bug**
When trying to expand an existing stockpile over a wall tile it will log an error and expand the stockpile a single, fixes on reloading so am not able to provide a save (please change category if it doesn't meet the requirements)

**Steps to reproduce the behavior (VERY IMPORTANT) {Note: not very accurate and inconsistent}**
1. Create an stockpile near a wall (preferably inside a mountain for more reliable results)
2. Click on expand stockpile button from menu
3. When seleccting the area to expand the stockpile hover cursor over mountains

**Error Log**
Player log not logged anything related just sound errors
Hugs lib log, lost it, tried to isolate the issue
[Error.txt](https://github.com/cseelhoff/RimThreaded/files/6633311/Error.txt)

**Save file**
Not able to provide with current method as it is inconsistent but it has happened before doing the same

**Screenshots**
video yay :D
https://user-images.githubusercontent.com/43865463/121557477-62a58400-c9da-11eb-8ef0-5f24d1ada838.mp4
(notice how when I clicked create stockpile in the orbital beacon nothing happened)

**Mod list (For vanilla report, it has to be same as below list.)**
* Harmony
* Core
* Royalty (optional)
* HugsLib
* RimThreaded

**Comment by pastorismylord** [comment]
verified this issue is fixed on the 2.x release. All good
