### ISSUE TITLE
Map Reroll Previews Showing Blank (RT 2.2.19)

### ISSUE THREAD

**Issue by EoinBanas** [cseelhoff/RimThreaded#541]
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report!  

**Describe the bug**
Starting a new colony with only RT and Map Reroll on, Rerolling the map causes the previews to show blank and the Log to pop up with Red and Yellow text

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Start new colony with RT and Map Reroll
2. Click on Dice in top right corner after choosing a landing location
3. Without RT there is a 3x3 grid of potential new maps to choose from similar to the one you are playing. With RT they show up as Black squares
4. Error log pops up behind it.

**Error Log**
[https://gist.github.com/2229674d4ec42e065e59d78a2e648261](url)
(Last chunk of the log is the same thing in every instance)

**Screenshots**
!!! Add screenshots to help explain your problem here !!!
![2021-06-14 (1)](https://user-images.githubusercontent.com/84687200/121978404-1fd70980-cd56-11eb-8639-15b38750a216.png)
![2021-06-14 (2)](https://user-images.githubusercontent.com/84687200/121978364-0766ef00-cd56-11eb-97ea-0b66f0433183.png)
![2021-06-14 (3)](https://user-images.githubusercontent.com/84687200/121978386-13eb4780-cd56-11eb-8547-72adbe4a0453.png)

**Mod list (Preferably a RimPy compatible list.)**
* Harmony
* Core
* Royalty (optional)
* HugsLib
* Map Reroll
* RimThreaded

**Comment by pastorismylord** [comment]
this issue was fixed before release.
