### ISSUE TITLE
Doors Expanded (Dev) red errors ( RT 2.3.6.7 )

### ISSUE THREAD

**Issue by Courier6Lau** [cseelhoff/RimThreaded#550]
When using a door that isn't a 1x1 for Doors expanded it throws out a red error when being used 

**Steps to reproduce the behavior**
1. Install Doors expanded
2.  Place a door that isn't a 1x1
3. Draft a pawn or let he pawn use it

Screenshots of error happening
![image](https://user-images.githubusercontent.com/85052635/122589253-9d6e8280-d092-11eb-8e58-cf6b5a23ffbe.png)

**Error Log**
https://gist.github.com/3225bf5e7a43ee6bf7b29be6f5bc1a00

**Mod list (Preferably a RimPy compatible list.)**
* Harmony
* Core
* Royalty (optional)
* HugsLib
* Doors Expanded (Dev) 
* RimThreaded ( 2.3.6.7 )

**Comment by pastorismylord** [comment]
@Courier6Lau can you please attach a savefile for this one?

**Comment by Courier6Lau** [comment]
Sorry took a while been busy stuff lately here 
[TestingRT.zip](https://github.com/cseelhoff/RimThreaded/files/6689374/TestingRT.zip)

**Comment by cseelhoff** [comment]
Appears to be fixed when using non-dev version of Doors EXP and RT version 2.5.12

**Comment by LlamaDuckGoose** [comment]
It looks like the Mod is still flagged as incompatibleWith jecrell.doorsexpanded

**Comment by MattRethyu** [comment]
Issue still occurs with RT 2.6.4 and non-dev Doors Expanded
