### ISSUE TITLE
Rimthreaded Anima grass on save causes an exception

### ISSUE THREAD

**Issue by pO0P3R125** [cseelhoff/RimThreaded#556]
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report!  

**Describe the bug**
When an anima tree has grass and you save the game it it will log a red error

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Start new colony (or load save provided)
2. Find the anima tree and make some grass grow by meditating or dev mode
3. Save the game

**Error Log**
[Player.log](https://github.com/cseelhoff/RimThreaded/files/6679834/Player.log)
https://gist.github.com/11a45bf88598487d1938dd682a2d8eba
[Anima Tree Error.txt](https://github.com/cseelhoff/RimThreaded/files/6679840/Anima.Tree.Error.txt)

**Save file**
[anima tree.zip](https://github.com/cseelhoff/RimThreaded/files/6679837/anima.tree.zip)

**Screenshots**
<img width="511" alt="RimWorldWin64_v0bSIeNKCh" src="https://user-images.githubusercontent.com/43865463/122628418-81abb200-d07b-11eb-9dce-edcde3067885.png">
<img width="451" alt="RimWorldWin64_jkW4kscLoC" src="https://user-images.githubusercontent.com/43865463/122628421-840e0c00-d07b-11eb-993d-a99e0435258c.png">

**Mod list (For vanilla report, it has to be same as below list.)**
* Harmony
* Core
* Royalty (optional)
* HugsLib
* RimThreaded

**Comment by pastorismylord** [comment]
verified this issue is fixed on the 2.x release. All good
