### ISSUE TITLE
available exits error while forming caravan with map designer (RT 2.3.9)

### ISSUE THREAD

**Issue by doc776** [cseelhoff/RimThreaded#560]
RT 2.3.9

**Describe the bug**
Happens during forming a caravan when you click 'send'. Throws red error mentioning map exits. In top left says the caravan is unable to leave the area and make sure there is at least one side reachable. 

_(side note: Pretty sure the previous version RT available on github, didn't have this specific issue, but together with world beautification project it just flat out rejected me clicking to set routes in worldmap.)_

**Steps to reproduce the behavior (VERY IMPORTANT)**
assuming mods been loaded from mod list already

1. map-designer **options for 'mountains'** set to max for **amount to alsmot solid** and **size to huge** attached picture below
2. generate map through regular means or dev means from titles screen
3. attempt to form caravan gives error: there is no exits / same with dev show exits button

**extra tests**

_trying different settings in map designer:_
generate map with map-designer (max mountains) **and RT**
same error
change mountain settings to default
use map reroll or start new game
no error

_trying to start with mountain map then switching mods up:_
generate map with map-designer (max mountains) and **no RT**
no error
save game
disable map-designer, enable RT
load game
same error
disable RT and map-designer
load game
no error

_create game with error then try saving it with out  mods on and loading back with rt:_
generate map with map-designer (max mountains) and RT
same error
save game
disable map-designer
load game
same error
disable RT
load game
no error
save game
enable RT
load game
same error

at all instances when error was observed, disabling RT made no errors about the no available exits on map

said error is always mentioning that it cant find exits:
```
~~~~~~~~~~~~
Verse.CellFinder.Verse.CellFinder.TryFindRandomEdgeCellWith_Patch0(System.Predicate`1<Verse.IntVec3>,Verse.Map,Verse.Rot4,single,Verse.IntVec3&)
  at RimWorld.Planet.CaravanExitMapUtility.AvailableExitTilesAt (Verse.Map map) [0x000b1] in 
~~~~~~~~~~~~ rest in log
```

**Error Log**
player:
https://pastebin.pl/view/41fbccf2
huglib:
https://pastebin.pl/view/4cdfd470

(was getting http400 errors trying to upload the default github way)

**Save file** both same error
map with scattered mountains and few exits visible
https://drive.google.com/file/d/1_wF4j0SF1lnixw5iUW-BxacibxIZeewg/view?usp=sharing
rerolling map again to mountain on one side so half the map is empty
https://drive.google.com/file/d/1sktiz7rIwp14xo7AsoBpuVfpZ7BD4PqM/view?usp=sharing

**Screenshots**
Not sure how I would screenshot this. When creating caravan: it simply says in top left that there is no available exits off the current map. If in development mode, clicking the show available exits button in world, no tiles are highlighted around my settlement.
here are settings for map reroll https://imgur.com/a/BhhXAVi

**Mod list (RimPy)**
https://rentry.co/t28eu
or copy it here:

[Mod list length: 8]
Harmony [https://steamcommunity.com/sharedfiles/filedetails/?id=2009463077]
Core [https:// no link (local mod)]
Royalty [Official DLC] [https:// no link (local mod)]
Mod Manager [https://steamcommunity.com/sharedfiles/filedetails/?id=1507748539]
HugsLib [https://steamcommunity.com/sharedfiles/filedetails/?id=818773962]
Map Designer [https://steamcommunity.com/sharedfiles/filedetails/?id=2111424996]
Map Reroll [https://steamcommunity.com/sharedfiles/filedetails/?id=761315214]
RimThreaded [https://steamcommunity.com/sharedfiles/filedetails/?id=2222907981]

**Comment by pastorismylord** [comment]
@doc776 should be fixed on 2.4.2
