### ISSUE TITLE
(2.3.9) Rim War index out of range

### ISSUE THREAD

**Issue by pastorismylord** [cseelhoff/RimThreaded#562]
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report!  

**Describe the bug**
!!! bug description here !!!
Not sure

**Steps to reproduce the behavior (VERY IMPORTANT)**

**Error Log**
!!! Link to contents of Player.log or Error.log (MUST BE LINK) !!!
!!! Link to HugsLib log. (MUST BE LINK) !!!

https://gist.github.com/f1423b5eb7465b89538abe3a38c9af6a

**Save file**
!!! Please add a save file where the issue occurs to speed up testing and fixing of the issue !!!

**Screenshots**
!!! Add screenshots to help explain your problem here !!!

[rim war.zip](https://github.com/cseelhoff/RimThreaded/files/6681105/rim.war.zip)

**Comment by cseelhoff** [comment]
Please retest with RT>=2.5.12 and include steps to reproduce. Closing until then.
