### ISSUE TITLE
cannot send caravan, cant leave map, no reachable sides (RT 2.3.9)

### ISSUE THREAD

**Issue by doc776** [cseelhoff/RimThreaded#564]
NOTE: i tried deleting game and reinstalling, deleting the config folder in appdata, did I really bork my game?

**Describe the bug**
When creating new caravan, i cannot click send. One red error. The top left says: "Your caravan is unable to leave the area. Make sure that at least one side is reachable." 

**Steps to reproduce the behavior**
1. Create a new game normally.
2. Choose Mountainouis tile. **!important!**
4. Atempt to create caravan and click send. (dev mode 'show available exits same error)

NOTE
I mined with godmode into the mountain to the edge, and error stopped appearing and was able to send caravan with no error, and show exits also highlighted all tiles around my settlement. Filling the tunnel back brings back the error.

**Primitive Workaround** 
- Dig a tunnel in dev mode to the walled off side of the map. FIlling it back will revert to error again.
- map-designer or other to create a mountain in centre of map ... if u still want that mountain base while waiting for fix.

**Error Log** 
player log
https://controlc.com/3b4c8bae
hugslib
https://gist.github.com/441413913fdaffdb44a347732ce723a6

**Save file**
https://drive.google.com/file/d/1bDddvX5-W2XfS4cbniuFwH_Pz7LvZDXF/view?usp=sharing

**Screenshots**
noting of note to show with this one

**Mod list (For vanilla report, it has to be same as below list.)**
* Harmony
* Core
* Royalty (optional)
* HugsLib
* RimThreaded

^ same thing used

**Comment by KonaeAkira** [comment]
I found that this bug also occurs on normal map sizes as long as the path to an edge is sufficiently long.

**Comment by kerdv** [comment]
Having the same issue on a medium-large map.

**Comment by pO0P3R125** [comment]
confirmed, big issue, easily reproduceable, not much to add more than illustrative screenshots
<img width="98" alt="RimWorldWin64_n2djVXGAtA" src="https://user-images.githubusercontent.com/43865463/123012476-ecb0fd80-d387-11eb-92e7-d2ddc8cb6df5.png">
<img width="450" alt="RimWorldWin64_Tj9iJ2fyGT" src="https://user-images.githubusercontent.com/43865463/123012489-f3d80b80-d387-11eb-9812-6a3dd758ddad.png">
<img width="426" alt="RimWorldWin64_sQlkLi7dBN" src="https://user-images.githubusercontent.com/43865463/123012506-f9355600-d387-11eb-9e4e-eb9d73d94759.png">
<img width="278" alt="RimWorldWin64_bUI6zyM1iF" src="https://user-images.githubusercontent.com/43865463/123012517-fdfa0a00-d387-11eb-900e-a79be846b772.png">

**Comment by pastorismylord** [comment]
@doc776 should be fixed on 2.4.2
