### ISSUE TITLE
Vanilla Expanded Events Constant red error logging, due to constant fertility grid recalculations

### ISSUE THREAD

**Issue by pO0P3R125** [cseelhoff/RimThreaded#565]
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report!  

**Describe the bug**
 Game can crash thanks to recalculations in the fertility grid, otherwise will log a wall of red errors until it stops to avoid spam

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Create new map in a jungle biome, preferably with no mountains (or load save provided)
2. In dev mode spawn the event "VEE Drought"
3. Let the game run in speed 1 for error logging, above speed 1 will crash
3. See error

**Error Log**
[Player-prev.log](https://github.com/cseelhoff/RimThreaded/files/6681553/Player-prev.log)
https://gist.github.com/4412688732d92015dbecccd2f3451fce

**Save file**
[VEE.zip](https://github.com/cseelhoff/RimThreaded/files/6681560/VEE.zip)

**Screenshots**
<img width="177" alt="RimWorldWin64_EydW6ArPn3" src="https://user-images.githubusercontent.com/43865463/122659780-dbc27b00-d140-11eb-99df-b5a24414d87b.png">
<img width="32" alt="RimWorldWin64_cXhtnOvj3C" src="https://user-images.githubusercontent.com/43865463/122659781-e1b85c00-d140-11eb-94b6-2a232d8887b3.png">
<img width="436" alt="RimWorldWin64_RVAFEcqB3o" src="https://user-images.githubusercontent.com/43865463/122659785-e54be300-d140-11eb-9afb-790fa8bab8e5.png">

**Mod list (Preferably a RimPy compatible list.)**
* Harmony
* Core
* Royalty (optional)
* HugsLib
* Vanilla Expanded Framework
* Vanilla Expanded Events
* RimThreaded

**Comment by KennethHoff** [comment]
I'm assuming disabling the drought event would be a bandaid fix this issue then?

**Comment by pO0P3R125** [comment]
it affects other mods trying to change fertility of the ground, like fertile grounds

**Comment by cseelhoff** [comment]
Fixed in 2.5.6
