### ISSUE TITLE
Throught handler bug because of too many objects affecting at once (index array out of bounds)

### ISSUE THREAD

**Issue by pO0P3R125** [cseelhoff/RimThreaded#567]
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report!  

**Describe the bug**
Game starts to log exceptions if there is too many objects affecting the throught array of a pawn (can lead to crash and game destabilization)

Affecting: Call of Cthulhu - Cosmic Horrors and possibly Vanilla Social Interactions

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Start new world (or load "Testing" save)
2. Trap pawns on a box with god mode
3. Spawn ton of Deep Ones and Great Deep Ones and let the game run
4. See error (or load the save with it already triggered)

**Error Log**
[Player.log](https://github.com/cseelhoff/RimThreaded/files/6684668/Player.log)
https://gist.github.com/bb354b9760a9626153551e419db2c0eb

**Save file**
[Saves.zip](https://github.com/cseelhoff/RimThreaded/files/6684675/Saves.zip)

**Screenshots**
<img width="193" alt="RimWorldWin64_mTM7eOOMmi" src="https://user-images.githubusercontent.com/43865463/122721507-5de09b80-d236-11eb-9382-50b39065b46c.png">
<img width="451" alt="RimWorldWin64_gyD9JppvrC" src="https://user-images.githubusercontent.com/43865463/122721557-6fc23e80-d236-11eb-854d-8363b5418a7a.png">

**Mod list (Preferably a RimPy compatible list.)**
* Harmony
* Core
* Royalty (optional)
* HugsLib
* JecsTools (Unofficial)
* Call of Cthulhu - Cosmic Horrors (Continued)
* RimThreaded

**Comment by pO0P3R125** [comment]
**This a very extreme case where the game gets unstable due to the sheer spam of this exception:**

Startup
<img width="450" alt="RimWorldWin64_2JhyIXsKad" src="https://user-images.githubusercontent.com/43865463/122807527-500c3400-d291-11eb-9e44-a9f71975fbfe.png">
Pawns Affected
<img width="206" alt="RimWorldWin64_rer4tsaryG" src="https://user-images.githubusercontent.com/43865463/122807548-57cbd880-d291-11eb-909e-49b7b15425e4.png">
Letting game run for some ticks
<img width="463" alt="RimWorldWin64_lTe9RHnwNc" src="https://user-images.githubusercontent.com/43865463/122807605-64e8c780-d291-11eb-8e43-5bf8f8cdab15.png">
Trying to see a pawn's mood
<img width="227" alt="RimWorldWin64_wj2R4FEFWH" src="https://user-images.githubusercontent.com/43865463/122807830-ad07ea00-d291-11eb-85cf-80684fe2875f.png">

**Comment by pO0P3R125** [comment]
tried on vanilla with RT the error logs but its yellow
<img width="464" alt="RimWorldWin64_uZrylt6Nv4" src="https://user-images.githubusercontent.com/43865463/122812346-2ce48300-d297-11eb-8476-8d288a446bb6.png">

**Comment by pastorismylord** [comment]
should be fixed now
