### ISSUE TITLE
Issue with reinstalling storage containers from Deep Storage.  The container disappears on move.

### ISSUE THREAD

**Issue by kerdv** [cseelhoff/RimThreaded#568]
**Describe the bug**
Reinstalling a Deep Storage container removes the container, leaves the task.

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Build Tall Shelves from LWM's Deep Storage (did not test other containers, probably bugged the same way)
2. Reinstall that container, filled or empty.
3. The container vanishes, leaving a partial task left.
4. Tested without RimThreaded, no error.  Tested without GUI mod and Rimthreaded, same error.

**Error Log**
https://1drv.ms/u/s!Aod_D-BVggAygd0t83UREpG-RKmo0g?e=76uNjm (Link to player.log, minimal mod test save, screenshots)
https://gist.github.com/4264d46c36ab156cd5a5270bfc2afa22

**Save file**
https://1drv.ms/u/s!Aod_D-BVggAygd0t83UREpG-RKmo0g?e=76uNjm

**Screenshots**
https://1drv.ms/u/s!Aod_D-BVggAygd0t83UREpG-RKmo0g?e=76uNjm

**Mod list (Preferably a RimPy compatible list.)**
https://rentry.co/pct6e
[Mod list length: 7]
Harmony [https://steamcommunity.com/sharedfiles/filedetails/?id=2009463077]
Core [https:// no link (local mod)]
Royalty [Official DLC] [https:// no link (local mod)]
HugsLib [https://steamcommunity.com/sharedfiles/filedetails/?id=818773962]
LWM's Deep Storage [https://steamcommunity.com/sharedfiles/filedetails/?id=1617282896]
Netrve's DeepStorage GUI [https://steamcommunity.com/sharedfiles/filedetails/?id=2169841018]
RimThreaded [https://steamcommunity.com/sharedfiles/filedetails/?id=2222907981]

**Comment by kerdv** [comment]
In addition, mortar shells stored on a vanilla shelf could not be accessed by the pawn operating the mortar.  Something with how Deep Storage addresses the storage isn't playing well with RT.  Didn't grab an error report of the incident, sorry.

**Comment by sevs44936** [comment]
I'm having the same issue, latest RimThreaded (2.4.1) and a long list of mods.
Happens with both Uninstall and Reinstall actions, container disappears, leaving behind only its shadow. 
Happens not only with Deep Storage containers, but also ones from Vanilla Furniture Expanded, Project RimFactory Lite and the Vanilla shelf.
Only storage buildings seem to be affected, I tested moving a tool cabinet and fabrication bench and that worked without issue.

**Comment by doc776** [comment]
This behaviour happens in vanilla+RT with regular shelves too.

**Comment by pastorismylord** [comment]
should be fixed now
