### ISSUE TITLE
Incompatibility with Share the Load

### ISSUE THREAD

**Issue by BigBadE** [cseelhoff/RimThreaded#572]
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report!  

**Describe the bug**
!!! bug description here !!!
RimThreaded and Share The Load causes the float menu for hauling items to not appear. Though I cannot recreate it, this also seems to affect other things like cleaning, tending, and growing. I am unsure if it is Share The Load causing the other cases.

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Force a pawn to haul steel to the wall blueprints
2. Attempt to force another pawn to haul steel to the wall blueprints

**Error Log**
!!! Link to contents of Player.log or Error.log (MUST BE LINK) !!!
!!! Link to HugsLib log. (MUST BE LINK) !!!
https://git.io/Jny5D

**Save file**
!!! Please add a save file where the issue occurs to speed up testing and fixing of the issue !!!
https://www.dropbox.com/s/g1n63kguwur740o/Float%20Menu%20Bug.rws?dl=1

**Screenshots**
!!! Add screenshots to help explain your problem here !!!
Doesn't show anything

**Mod list (Preferably a RimPy compatible list.)**
* Harmony
* Core
* Royalty (optional)
* HugsLib
* Share The Load
* RimThreaded

**Comment by pastorismylord** [comment]
this issue has been fixed
