### ISSUE TITLE
Red error when deconstructing Shelf ( 2.4.1)

### ISSUE THREAD

**Issue by Courier6Lau** [cseelhoff/RimThreaded#575]
**Describe the bug**
When placing a shelf and deconstructing it log throws a red error and all of the materials made from it are not recovered. It also leaves a shadow of where it was deconstructed from. 

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Don't pause the game and let on 1x speed or any speed
2. Place a shelf of any material
3. Deconstruct it 

**Error Log**
https://gist.github.com/d417917c72106d96811ddd914c65b7a0

**Save file**
[Shelferror.zip](https://github.com/cseelhoff/RimThreaded/files/6705324/Shelferror.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/85052635/123179792-af01c100-d4bc-11eb-89e4-88ea6d5b401e.png)
A screenshot of the error happening, the shadow of the now deconstructed shelf, and missing materials after deconstruction.

**Mod list**
* Harmony
* Core
* Royalty (optional)
* HugsLib
* RimThreaded

**Comment by pastorismylord** [comment]
additionally, when re-installing a shelf, the shelf will dissapear.

**Comment by campos-ddc** [comment]
The same *IssuePackage error happens when moving [LWM's Deep Storage](https://steamcommunity.com/workshop/filedetails/?id=1617282896) containers, might be related.

**Comment by cseelhoff** [comment]
Fixed in 2.5.6
