### ISSUE TITLE
Explosions cause crashes and multiple errors (RT 2.4.2)

### ISSUE THREAD

**Issue by pO0P3R125** [cseelhoff/RimThreaded#580]
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report!  

**Describe the bug**
Explosions log several errors, when it tries to affect some cells with pawns it will cause an error in console, also trying to affect things that were destroyed at the same time the explosion is created and calculated, if too many pawns are affected by lots of explosions or big modded explosions it may crash the game
TESTED ON OLD VERSION (RT 2.3.10 tester beta), MY BAD IS WORSE IN NEWER VERSION (RT 2.4.2)
This same test replicated in new version will cause the game to become unstable spam console like crazy

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Load save provided or start a colony
2. Make an enclosed box
3. Spawn human pawns in box
4. Fill it with chemfuel
5. Make explosion (bomb) inside the box
6. See error
7. ({EDIT:WILL CAUSE CRASH ON NEW VERSION} Can cause crash or game logic freezing in extreme conditions, just spawn lots of pawns with armor in the box, but lots {+20} and spawn some high explosive shells {stacks of 25} your game should logic freeze or crash)

**OLD VERSION Error Logs**
[Player.log](https://github.com/cseelhoff/RimThreaded/files/6721123/Player.log)
https://gist.github.com/ca145c2e6816a25c1f95c82a458ae076
**NEWER VERSION Error Logs**
[Player.log](https://github.com/cseelhoff/RimThreaded/files/6721176/Player.log)
Cannot get hugs game crashes

**Save file**
Old version
[Explosions.zip](https://github.com/cseelhoff/RimThreaded/files/6721124/Explosions.zip)
NEWER VERSION
[Explosions NEW VERSION.zip](https://github.com/cseelhoff/RimThreaded/files/6721166/Explosions.NEW.VERSION.zip)

**Screenshots**
<img width="292" alt="RimWorldWin64_56DVjl23o1" src="https://user-images.githubusercontent.com/43865463/123535428-506d5a80-d6e9-11eb-98c0-628928c61165.png">
<img width="98" alt="RimWorldWin64_bX0BPJnnOn" src="https://user-images.githubusercontent.com/43865463/123535439-611dd080-d6e9-11eb-8896-7f5c80512697.png">
OLD ERRORS (cannot get new screenshots if game crashes
<img width="282" alt="RimWorldWin64_pZCo62puk6" src="https://user-images.githubusercontent.com/43865463/123535441-63802a80-d6e9-11eb-8b43-8ca5ce4f709f.png">
<img width="448" alt="RimWorldWin64_shMkN5VFgh" src="https://user-images.githubusercontent.com/43865463/123535444-667b1b00-d6e9-11eb-9abd-49946666effa.png">
Crash with newer version
![RimWorldWin64_vOWvjU77f8](https://user-images.githubusercontent.com/43865463/123535967-333a8b00-d6ed-11eb-81ae-11aab9bc94d8.jpg)

**Mod list (For vanilla report, it has to be same as below list.)**
* Harmony
* Core
* Royalty (optional)
* HugsLib
* RimThreaded

**Comment by pastorismylord** [comment]
fixed on 2.5.7
