### ISSUE TITLE
Harvesting bugged in 2.4.2

### ISSUE THREAD

**Issue by SethDusek** [cseelhoff/RimThreaded#581]
**Describe the bug**
Colonists do not cut fully grown plants, unless they're manually given the harvest order. 

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Create new save (vanilla)
2. Designate a grow zone
3. Wait for it to be fully harvestable, make sure a colonist has plant cutting job assigned to them

**Error Log**
https://p.teknik.io/hqPw9
**Save file**
[harvest bug.rws](https://gist.github.com/SethDusek/50363283cc85e6910e0c31eb798f7ecf)
**Screenshots**
![image](https://user-images.githubusercontent.com/9436380/123537626-dfaa5a80-d749-11eb-9d25-271e9a0f2c07.png)
![image](https://user-images.githubusercontent.com/9436380/123537653-0799be00-d74a-11eb-87c7-5c6d43ad13b0.png)

**Mod list (For vanilla report, it has to be same as below list.)**
* Harmony
* Core
* Royalty 
* RimThreaded

**Comment by bababooeyy** [comment]
I was not able to reproduce the error after several tries, however i can confirm that the issue occurs.

**Comment by SethDusek** [comment]
To add additional information, it seems that having a colonist prioritize cutting is not the only way, you can also mark the plant for harvest by pressing H and it'll be harvested

**Comment by SethDusek** [comment]
Hi, after testing the new patch, it seems it fixes harvesting, but breaks colonists who try to harvest. It outputs these errors for a while
![image](https://user-images.githubusercontent.com/9436380/123569940-b5f04280-d7e0-11eb-8d29-95e2fae6c2d8.png)

Afterwards, colonists behavior seems to be broken somewhat. Instead of wandering, they just stand in one place until they have some work to do, and they don't seem to do all work (?) like one colonist would not sow plants until I manually had them do it.

This is the log file https://gist.github.com/HugsLibRecordKeeper/686fa589155bfbb7fd0938bfa8d80d56

**Comment by hopeseekr** [comment]
I have to tell them to cut the plants. Then they rush to do it. On their own, they will literally "Wander" around before they harvest anything, even when locked in the grow zone.
