### ISSUE TITLE
Random 'Exception ticking {bullet]' NullReferenceException during combat

### ISSUE THREAD

**Issue by anton-argunov** [cseelhoff/RimThreaded#589]
**Describe the bug**
During combat, sometimes an exception is thrown. Example message: 
Exception ticking Bullet_LMG44714 (at (144, 0, 229)): System.NullReferenceException: Object reference not set to an instance of an object
Full exception with stack trace: https://drive.google.com/file/d/1KVntMoNuwTf8Z9ySmY9pb4K9pikreWTL/view?usp=sharing

**Steps to reproduce the behavior**
1. Start a new game in dev. mode
2. Spawn lots of pawns that would fight each other (e.g. pirates and empire fighters)
3. Note the logs during combat

Note: the issue is quite random so it can reproduce several times per combat or not reproduce at all

**Error Log**
!!! Link to contents of Player.log: https://drive.google.com/file/d/1Kg3ph5FSE2TGfamKJRRy7dkUK14m7_R0/view?usp=sharing
!!! Link to HugsLib log: (forgot to upload, will do this when the issue reproduces next time)

**Mod list**
[Mod list length: 6]
Harmony [https://steamcommunity.com/sharedfiles/filedetails/?id=2009463077]
Core [https:// no link (local mod)]
Royalty [Official DLC] [https:// no link (local mod)]
Mod Manager [https://steamcommunity.com/sharedfiles/filedetails/?id=1507748539]
HugsLib [https://steamcommunity.com/sharedfiles/filedetails/?id=818773962]
RimThreaded [https://steamcommunity.com/sharedfiles/filedetails/?id=2222907981]

**Comment by pastorismylord** [comment]
should be fixed on current steam release (2.5.7)
