### ISSUE TITLE
Threads not finishing on haul job, causes ~8 seconds freezes to the game

### ISSUE THREAD

**Issue by ChananM** [cseelhoff/RimThreaded#591]
Hi,
Let me just start by thanking you for this amazing mod
Now, for the matter at hand - the game freezes for ~8 seconds at a time on certain hauling jobs
It reproduces for me after big raids / manhunter packs / etc.
I finish the event, killing any hostiles and shortly after start hauling the bodies to wherever they supposed to go.

**Steps to reproduce the behavior**
1. On a mid-late game scenario, generate a large raid / manhunter pack
2. Successfully finish the event
3. Wait for your colonists to haul the bodies
4. See the game starts to freeze, errors appear in the log:

**Error Log**
Player.log: https://pastebin.pl/view/668be512
HugsLib log: https://gist.github.com/ae51f2208e4eb2f3fd754933834415b8

**Save file**
https://easyupload.io/74tm4g (will expire in 30 days, please contact me for re-upload)
_Edit: I continued playing after posting the bug and the Jaguars were hauled without further freezes. In case I get a big raid and it happens again I'll be sure to reupload a more relevant save file_

**Screenshots**
![image](https://user-images.githubusercontent.com/19833937/125919510-a7d976c9-b745-4229-aa42-fe67c6a1c28c.png)

**Mod list (Preferably a RimPy compatible list.)**
https://pastebin.com/yWc8U5CC (Not sure what RimPy compatible means, feel free to reach out if you need it in some other form)

Thank you very much!

**Comment by pastorismylord** [comment]
this issue has been fixed
