### ISSUE TITLE
Psycasts"Word of Love"Not work

### ISSUE THREAD

**Issue by Indigo-L** [cseelhoff/RimThreaded#593]
Word of Love increases the relationship by +40 in Vanilla, but could not be confirmed with Rim Threaded installed.

1. Use Word of Love.
2. Check the social tab of the Pown you used.
3. Psychic love by +40 in Vanilla, but could not be confirmed with Rim Threaded installed.

**Save file**
I checked this save file in developer mode, but I can check it as well after the game progresses.
https://drive.google.com/file/d/1MEfQcrZkhlNUyq1jTEpWglyqigWFzuae/view?usp=sharing

**Screenshots**
Vanilla
![スクリーンショット (34)](https://user-images.githubusercontent.com/40560811/126875550-8d7f6f7c-854d-442c-8adf-708f753b7c41.png)

 Rim Threaded 
![スクリーンショット (33)](https://user-images.githubusercontent.com/40560811/126875604-ce689fb6-887c-4e70-8d73-b50766a0bae0.png)

**Mod list (For vanilla report, it has to be same as below list.)

* Harmony
* Core
* Royalty
* HugsLib
* RimThreaded

Since I am Japanese, the above sentence was created using google translate.

**Comment by pastorismylord** [comment]
this issue is reported as fixed on the latest steam release
