### ISSUE TITLE
Ticking plant error with VFECore

### ISSUE THREAD

**Issue by robmart** [cseelhoff/RimThreaded#595]
**Describe the bug**
A conflict with VFE causes the plant threads to throw an error and restart endlessly.

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Press play on the supplied save file (don't know if error triggers on a new save)
2. Wait a bit
3. Game freezes, wait for it to unfreeze

**Error Log**
Player.log: https://gist.github.com/robmart/9d8516cf6221b323579b563a1de27455

**Save file**
https://easyupload.io/evmhxa

**Mod list (Preferably a RimPy compatible list.)**
File is a RimPy exported mod list, just change it to a xml to import it. [Highly Modded 1.3.txt](https://github.com/cseelhoff/RimThreaded/files/6873767/Highly.Modded.1.3.txt)

**Comment by Sernior** [comment]
This one gets fixed by my last commit on 2.5.12

**Comment by Sernior** [comment]
You are using RT 2.5.7 this issue was fixed in the latest RT versions. This issue can be closed
