### ISSUE TITLE
Pawns in drop pods immediately leave

### ISSUE THREAD

**Issue by UplinkPhobia** [cseelhoff/RimThreaded#596]
**Describe the bug**
Pawns crashing in drop pods with an event never have injuries and just leave immediately.
As soon as RimThreaded is removed, the bug disappears.

**Steps to reproduce the behavior**
1. Using dev mode to speed up things
2. Create a game, settings are not important (with dev mode, clicking next until planet generation, with random map selected and picking randomly one of the existing ideologies)
3. Spawn a RefugeePodCrash incident or 10 (or wait for one), the pawn(s) walks away as they have no injuries, at most scars or addictions that don't prevent moving.

**Error Log**
HugsLib log: https://gist.github.com/HugsLibRecordKeeper/528210bde92ab672bcbfcd26ca944eb6

**Screenshots**
![Capture d’écran du 2021-07-25 23-48-15](https://user-images.githubusercontent.com/24713223/126914505-8e9202c0-6875-4f7e-aad0-7fa603456fcc.png)
![Capture d’écran du 2021-07-25 23-48-36](https://user-images.githubusercontent.com/24713223/126914506-895d46bb-2533-433e-a16d-fc4d0dedc2d9.png)

**Mod list (For vanilla report, it has to be same as below list.)**
* Harmony
* Core
* Ideology
* HugsLib
* RimThreaded

For info, I'm on Linux, through Steam, without Royalty.

**Comment by pastorismylord** [comment]
@UplinkPhobia can you please add a savefile?

**Comment by UplinkPhobia** [comment]
[PodBug.rws.zip](https://github.com/cseelhoff/RimThreaded/files/6896993/PodBug.rws.zip)

It's just a new game without any specific option, and I spawned 10 drop pods, with all pawns leaving
