### ISSUE TITLE
The shuttle won't take off

### ISSUE THREAD

**Issue by 136068448** [cseelhoff/RimThreaded#597]
**Describe the bug**
When receiving any mission that requires a shuttle to take any animal or person, the shuttle will still not take off even if the required items have been loaded in, resulting in a very large portion of the Empire's mission can't complete. Unfortunately, there is no error log when this occurs.

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Start a new game
2. Wait the first empire mission(usually a crazy animal catch a noble)
3. Kill that animal and send noble to shuttle
4. the shuttle not land off

**Error Log**
No errors log, but I'll post my player.log anyway

Loading game from file Autosave-3 with mods:
  - brrainz.harmony
  - Ludeon.RimWorld
  - Ludeon.RimWorld.Royalty
  - Ludeon.RimWorld.Ideology
  - majorhoff.rimthreaded
RimThreaded is building new Reservations Dictionary...
Unloading 0 Unused Serialized files (Serialized files now loaded: 2)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 19268.
Total: 187.782000 ms (FindLiveObjects: 0.616200 ms CreateObjectMapping: 1.013000 ms MarkObjects: 186.074400 ms  DeleteObjects: 0.077900 ms)

RimThreaded is caching Harvest Plant Cells...
RimThreaded is caching Sowing Plant Cells...
Unloading 3 Unused Serialized files (Serialized files now loaded: 2)
UnloadTime: 0.403500 ms

Unloading 4055 unused Assets to reduce memory usage. Loaded Objects now: 15720.
Total: 163.132700 ms (FindLiveObjects: 0.950100 ms CreateObjectMapping: 1.079200 ms MarkObjects: 156.889100 ms  DeleteObjects: 4.214100 ms)

**Save file**
It is very easy to reproduct so i think no need the save file

**Screenshots**
no

**Mod list (For vanilla report, it has to be same as below list.)**
  - brrainz.harmony
  - Ludeon.RimWorld
  - Ludeon.RimWorld.Royalty
  - Ludeon.RimWorld.Ideology
  - majorhoff.rimthreaded

**Comment by pastorismylord** [comment]
@136068448 can you please add a save file?

**Comment by 136068448** [comment]
Here you are
[Alliance of Tejader.zip](https://github.com/cseelhoff/RimThreaded/files/6898360/Alliance.of.Tejader.zip)

**Comment by pastorismylord** [comment]
solved, published on https://discord.com/channels/754090371654483999/754090372317052961/871635771092774922
