### ISSUE TITLE
[Dubs Skylights] Dubs Skylight error

### ISSUE THREAD

**Issue by Palius84** [cseelhoff/RimThreaded#598]
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report!  

**Describe the bug**
Getting Red error when running RimThreaded with Dubs Skylights

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Load game with mod list.
2. Error in log.

**Error Log**
Player Log    https://gist.github.com/Palius84/67121a82a147073a5ba73f35e1f34abf
Hugslib Log https://gist.github.com/71d48c56c29f7e752afdb83650657e24

**Save file**
Main Menu error log no saved game.

**Screenshots**
https://prnt.sc/1gayexm

**Mod list (Preferably a RimPy compatible list.)**
* Harmony
* Core
* Royalty 
* Ideology
* HugsLib
*Dubs Skylights
*RimThreaded

**Comment by Niilo007** [comment]
Dubs Skylight issues
#598
#622

**Comment by Niilo007** [comment]
This issue is now closed

For tracking see this issue: #622
