### ISSUE TITLE
Jobs of Opportunity error

### ISSUE THREAD

**Issue by Palius84** [cseelhoff/RimThreaded#599]
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report!

Describe the bug
Getting Red error when running RimThreaded with Jobs of Opportunity
Steps to reproduce the behavior (VERY IMPORTANT)

Load game with mod list.
Error in log.

Error Log
Player Log    https://gist.github.com/Palius84/0f4eee8c496e40eff1b8d2b4a1b655b4
Hugslib Log https://gist.github.com/8a2f65462ad98475cb7bda4d5d2e23ff

Save file
Main Menu error log no saved game.

Screenshots
https://prnt.sc/1gbk5mv

Mod list (Preferably a RimPy compatible list.)

Harmony
Core
Royalty
Ideology
HugsLib
*Jobs of Opportunity(While You're Up)
*RimThreaded

**Comment by cseelhoff** [comment]
Fixed in 2.5.12. Somewhat of a false positive.
