### ISSUE TITLE
Room is not registered as roofed after building and roofing

### ISSUE THREAD

**Issue by FurtherV** [cseelhoff/RimThreaded#600]
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report!  

**Describe the bug**
Building a room and roofing it does not register the room as roofed until the game is save and the save loaded again.

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Start a RimWorld session with RimThreaded
2. Let your pawns build a room of any size, for example 5x5
3. Let your pawns roof the room you just build
4. => Bug happens. Game shows at the bottom left the room as unroofed and items decay inside because unroofed.

**Error Log**
!!! Link to contents of Player.log or Error.log (MUST BE LINK) !!!
https://pastebin.com/fx8ZxQcb

**Save file**
!!! Please add a save file where the issue occurs to speed up testing and fixing of the issue !!!
https://drive.google.com/file/d/1oWdVchDCkucNp8ek_Fys691qt82oIqDU/view?usp=sharing

NOTE: You have to a build a new room in this save file because well... loading a save fixes the bug.

**Screenshots**
!!! Add screenshots to help explain your problem here !!!
https://prnt.sc/1hp5vt8

**Mod list (For vanilla report, it has to be same as below list.)**
* Harmony
* Core
* Royalty (optional)
* RimThreaded

**Comment by pastorismylord** [comment]
Fixed on 2.5.7.2
