### ISSUE TITLE
Harvesting from Hydroponics 

### ISSUE THREAD

**Issue by JacksonMichaelin** [cseelhoff/RimThreaded#601]
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report!  

**Describe the bug**
The Pawn is just stuck "Standing" while he/she is harvesting from a Hydroponic

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Build Hydroponic
2. Plant Anything(I've been planting Rice)
3. After two or three harvest, the pawn bugs out and is stuck on standing

**Error Log**
https://drive.google.com/file/d/19CDrjZXa-iQ3yn4DCldoSnEkriggSE_g/view?usp=sharing
https://gist.github.com/77abc62de2a6b57193105264faaba9ef

**Save file**
https://drive.google.com/file/d/1zBki8qqAe8xhklGVlei-tWrSQ2iHi1KB/view?usp=sharing

**Screenshots**
![Bug](https://user-images.githubusercontent.com/88168202/127592337-c3e85ef3-6401-4e43-b1a1-2f032c920656.PNG)

**Mod list (Preferably a RimPy compatible list.)**
* Harmony
* Core
* Royalty
* HugsLib
* [1.3] No Infestation
* JecsTools
* Life Support (Fan Update)
* OgreStack
* Where is my weapon?
* Bulk Smelting 
* MendAndRecycle
* Hospitality
* ETRT: Medicine Production
* Research+500
* Infinite Turrets
* Snap Out!
* RT Solar Flare Shield
* Cultured Meat
* Electric Butcher Table
* Clothes To Cloths
* CleaningStation
* Crafting Quality Rebalanced
* Sparkling World - Full Mod
* Mad Skills
* CarryingCapacity10000
* Quantum Cooling (Continued)
* Fire Extinguisher (Continued)
* Electric Stonecutting Table
* Rimefeller
* Rimatomic
* Non-Flammable Metal (1.0-1.3)
* More Faction Interaction (Continued)
* FH70 Howitzer Artillery System [1.3+]
*  Ore Yield (Continued)
* EdB Prepare Carefully
* Craftable Luciferium
* Sun Lamp+
* Resource Replicator [1.0->1.2]
* Growable Neutroamine
* Advanced Hydroponics
* [1.1] Resource Generators
* [CP] Rimmu-Nation - Weapons
* [CP] Rimmu-Nation - Clothing
* SRTS Expanded
* [CP] Get to the Chopper!
* ED-CheatReactor
* RimTraits - General Traits
* [RH2] Hand-To-Hand
* RimThreaded
* [SR] Raid Extension

**Comment by Dan00** [comment]
Just wanted to add, I've found that I get the same error with Bonsai pots when a pawn tries to harvest the grown tree.
