### ISSUE TITLE
a lot of sounds sound to be missing, all weapons are silent and drop pods are silent too v1.0.11

### ISSUE THREAD

**Issue by cseelhoff** [cseelhoff/RimThreaded#61]

**Comment by SilentSkies** [comment]
Also having this issue.
See video for example. [Link (Youtube)](https://www.youtube.com/watch?v=ExYOlogazLY)
Music is set at 0% so you can hear everything. Sounds like UI SFX are there but no pawn/weapon/move sounds.

**Comment by KiameV** [comment]
Most sounds should be fixed
