### ISSUE TITLE
Warden job ignores slaves

### ISSUE THREAD

**Issue by Araxiel** [cseelhoff/RimThreaded#611]
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report!  

**Describe the bug**
As title says; with RimThread wardens won't do any of the slave-specific actions. This includes anything from suppression to emancipation.

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Have a slave
2. Have someone be a warden (e.g. disable every other job but Warden)
3. Have slave on any of the slave interactions (e.g. Emancipation)
4. Warden will remain idle.

**Error Log**
[Player.log](https://pastebin.com/GZB0hYF5)
HugsLib.log doesn't exist on my computer.

**Save file**
[Rimthread slave debug.zip](https://github.com/cseelhoff/RimThreaded/files/6928584/Rimthread.slave.debug.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/11295969/128121408-0569bc41-e6c1-4c13-9041-30fe1c2a7bb4.png)

**Mod list (Preferably a RimPy compatible list.)**
<details>
  <summary>Mod List</summary>
  Sorry, hadn't heard of RimPy until now.
  
- brrainz.harmony
- Ludeon.RimWorld
- Ludeon.RimWorld.Ideology
- automatic.gradienthair
- automatic.startupimpact
- Fluffy.ModManager
- UnlimitedHugs.HugsLib
- UnlimitedHugs.AllowTool
- erdelf.HumanoidAlienRaces
- CarnySenpai.EnableOversizedWeapons
- Atlas.AndroidTiers
- Fluffy.AnimalTab
- Oblitus.AnimalsLogic
- Mlie.Apothecary
- Fluffy.AreaUnlocker
- automatic.autolinks
- Fluffy.BackupPower
- Meltup.BeautifulOutdoors
- VouLT.BetterPawnControl
- Goalie.BetterSandbags.1
- automatic.bionicicons
- Fluffy.Blueprints
- Mlie.CentralizedClimateControl
- void.charactereditor
- 5katz.CommsChat
- CrashM.ColorCodedMoodBar.11
- Fluffy.ColonyManager
- Dubwise.DubsBadHygiene
- avilmask.CommonSense
- Fluffy.DesirePaths
- 7H28J.dirtpaths
- Dubwise.DubsSkylights
- nilchei.dynamicdiplomacy
- Hauvega.EquiumsSeries.Equiums
- Erin.Hairredux
- Erin.Mountain
- factioncontrol.kv.rw
- crlsniper.realisticrooms
- VanillaExpanded.VCEF
- ReGrowth.BOTR.Core
- FrozenSnowFox.FilthVanishesWithRainAndTime
- Mlie.FlagsAndBanners
- Mlie.GnollRace
- Brunin.GreenRim
- Smuffle.HarvestOrgansPostMortem
- Orion.Hospitality
- OskarPotocki.VanillaFactionsExpanded.Core
- OskarPotocki.VFE.Mechanoid
- dhultgren.keepbedownership
- Mlie.KnotRoot
- Krafs.LevelUp
- rimfridge.kv.rw
- LWM.DeepStorage
- ratys.madskills
- zylle.MapDesigner
- UnlimitedHugs.MapReroll
- pyrce.mass.graves
- Fluffy.MedicalTab
- notfood.MendAndRecycle
- hobtook.mortaraccuracy
- pathavoid.kv.rw
- Meltup.PolyamoryBeds.Vanilla
- erdelf.PowerIndicators
- Uuugggg.ReplaceStuff
- Haplo.PowerSwitch
- neitsa.PrepareLanding
- spdskatr.projectrimfactory
- spdskatr.projectrimfactory.drones
- automatic.recipeicons
- ReGrowth.BOTR.ExtinctAnimalsPack
- OskarPotocki.VFE.Insectoid
- ReGrowth.BOTR.Wastelands
- ReGrowth.BOTR.WastelandFauna
- Dubwise.Rimatomics
- Dubwise.Rimefeller
- MalteSchulze.RIMMSqol
- rimsenal.core
- rimsenal.EVP
- rimsenal.federation
- rimsenal.feral
- rimsenal.hair
- rimsenal.security
- rimsenal.storyteller
- jecrell.jecstools
- ratys.rtfuse
- Mlie.RFRumorHasIt
- PeteTimesSix.SimpleSidearms
- Mlie.SimplyMoreBridges
- dhultgren.smarterconstruction
- weilbyte.snapout
- Murmur.SubsurfaceConduit
- sun.reducer
- SoulfulPumpkin.TabletopTrove
- Kerevan.OttoDrow
- tradingspot.kv.rw
- nephlite.orbitaltradecolumn
- VanillaExpanded.VAPPE
- VanillaExpanded.VARME
- OskarPotocki.VFE.Vikings
- VanillaExpanded.VFECore
- VanillaExpanded.VFEArt
- VanillaExpanded.VFEFarming
- VanillaExpanded.VFEMedical
- VanillaExpanded.VFEPower
- VanillaExpanded.VFEProduction
- VanillaExpanded.VFEPropsandDecor
- VanillaExpanded.VFESecurity
- VanillaExpanded.VFESpacer
- VanillaExpanded.VHE
- VanillaExpanded.VPlantsE
- VanillaExpanded.VTEXE
- VanillaExpanded.VWE
- VanillaExpanded.VWEG
- Murmur.WallLight
- verdiss.fasteraging
- SF.More.Steel.From.Slag
- neceros.undergroundsoil
- Mlie.O21BarbedWire
- majorhoff.rimthreaded

</details>

**Comment by cseelhoff** [comment]
I tried to reproduce. But I think I may be having some issues with the modlist. Any way to recreate a save for me with Vanilla+RT?

**Comment by Niilo007** [comment]
#656
has a vanilla save file and more info about this issue

**Comment by Niilo007** [comment]
Closing this issue as we have 2 about the same thing, the other one is in vanilla
See #656 for tracking/progress
