### ISSUE TITLE
[2.5.8.2] Caravans and raiders will leave the map after reloading, without actually doing their interaction.

### ISSUE THREAD

**Issue by Pustalorc** [cseelhoff/RimThreaded#616]
**Describe the bug**
Although caravans and raiders finally do not instantly leave the map right after they arrive, they will leave the map as soon as they can if you reload the save whilst they are in the map.

**Expected behaviour of caravans after a reload (Tested it with this same mod list but without RimThreaded):**
1) Walk to the designated trade spot (which they were already walking towards).
2) Stay in designated trade spot for x time and then leave.

**Actual behaviour of caravans with RimThreaded:**
1) Walk to the designated trade spot.
2) Instantly leave, not staying for the x seconds they should be.

**Expected behaviour of raiders after a reload (Tested it with this same mod list but without RimThreaded):**
1) Walk towards the base and continue the raid.
2) Leave if injured, or if raid is complete.

**Actual behaviour of raiders with RimThreaded:**
1) Walk out of the map and leave the colony.

**Steps to reproduce the behavior (VERY IMPORTANT)**
1) Create any new save.
2) Debug spawn a caravan or raid.
3) Once the caravan or raid is in the map and moving towards you, save the game and load the save file.
4) See the caravan/raiders leave after reloading.

**Save file**
Save files: [Radier & Caravan tests.zip](https://github.com/cseelhoff/RimThreaded/files/6969024/Radier.Caravan.tests.zip)
(Github for some reason dislikes .rws)

**Mod list**
* Harmony
* Core
* Royalty (optional)
* HugsLib
* Mod Manager
* RimThreaded

**Comment by Sernior** [comment]
Thank you for your report this particular bug was already fixed in 2.5.10... it simply wasn't released anywhere as we are getting ready for a steam release. I ll drop some dlls into discord.
