### ISSUE TITLE
I see other centipedes firing at my colonists, but the colonists don't fire back automatically

### ISSUE THREAD

**Issue by cseelhoff** [cseelhoff/RimThreaded#62]
I see other centipedes firing at my colonists, but the colonists don't fire back automatically. It seems that I can draft a colonist and direct fire back and that works.

**Comment by Wad67** [comment]
Can confirm this one, had some drafted colonists not shooting at a raider unless explicitly ordered to do so.

I had their default threat action to attack rather than flee so maybe that ties into it.
