### ISSUE TITLE
[Dubs Skylights] Error with Dubs skylights when planting crops under a skylight

### ISSUE THREAD

**Issue by IRelaxxx** [cseelhoff/RimThreaded#622]
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report!  

**Describe the bug**
When using Dubs Skylights and Rimthreaded the following error occures after running the game for some time 

`Exception ticking WildPlantSpawner: System.NullReferenceException: Object reference not set to an instance of an object`

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Start a new colony
2. build a skylight
3. plant a field below the skylight
4. let the game run for a bit

**Error Log**
https://gist.github.com/IRelaxxx/cc2d3acc615ade818db0769a441f9816
hugslib not used

**Save file**
[skylights error.zip](https://github.com/cseelhoff/RimThreaded/files/6987168/skylights.error.zip)

**Screenshots**
!!! Add screenshots to help explain your problem here !!!

**Mod list (Preferably a RimPy compatible list.)**
  - brrainz.harmony
  - Ludeon.RimWorld
  - Ludeon.RimWorld.Royalty
  - Ludeon.RimWorld.Ideology
  - Dubwise.DubsSkylights
  - majorhoff.rimthreaded

**Comment by Niilo007** [comment]
Dubs Skylight issues
#598
#622

**Comment by Niilo007** [comment]
![image](https://user-images.githubusercontent.com/75486261/133113076-4f44c77e-0bf8-4444-afd5-e6f5fdaac2ba.png)

**Comment by Niilo007** [comment]
![image](https://user-images.githubusercontent.com/75486261/133117153-24e93893-5fa1-4252-a06e-13d5edc01cac.png)
