### ISSUE TITLE
Animals and pawns failing to die from hunting by animals.

### ISSUE THREAD

**Issue by DurekuRyuu** [cseelhoff/RimThreaded#625]
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report!  

**Describe the bug**
!!! bug description here !!!
I've had a couple examples where either manhunter or predator animals have 'killed' a pawn, or another animal, such as the horse blood cloud save you'll find attatched.
It looks to me like the animal is failing to register as dead, and producing an unimaginably large blood cloud.
In this case, saving and loading seems to resolve the issue on a case by case basis; but I have a log from immediately before the save in case that helps for determining what's happening.

**Steps to reproduce the behavior (VERY IMPORTANT)**
Try spawning a manhunter pack event of Predators, that should re-create the conditions i've observed this occuring under.

**Error Log**
!!! Link to contents of Player.log or Error.log (MUST BE LINK) !!!
!!! Link to HugsLib log. (MUST BE LINK) !!!
[Horse_blood_cloud_log.txt](https://github.com/cseelhoff/RimThreaded/files/6988621/Horse_blood_cloud_log.txt)

**Save file**
!!! Please add a save file where the issue occurs to speed up testing and fixing of the issue !!!
[Saves.zip](https://github.com/cseelhoff/RimThreaded/files/6988625/Saves.zip)

**Screenshots**
!!! Add screenshots to help explain your problem here !!!
previously mentioned horse, after loading save.
![image](https://user-images.githubusercontent.com/3818817/129488360-181dd762-5f76-4266-b592-efed40a08e66.png)

**Mod list (Preferably a RimPy compatible list.)**
(Feel free to trim/ignore any local mods, but I'll track the download sources down for you if you want them.)

[Mod list length: 106]
Harmony [https://steamcommunity.com/sharedfiles/filedetails/?id=2009463077]
Visual Exceptions [https://steamcommunity.com/sharedfiles/filedetails/?id=2538411704]
Core [https:// no link (local mod)]
Royalty [Official DLC] [https:// no link (local mod)]
Startup impact [https://steamcommunity.com/sharedfiles/filedetails/?id=1684944322]
HugsLib [https://steamcommunity.com/sharedfiles/filedetails/?id=818773962]
Graphics Settings+ [https://steamcommunity.com/sharedfiles/filedetails/?id=1678847247]
AI Upscaled Textures - Core [https://steamcommunity.com/sharedfiles/filedetails/?id=2307494117]
Vanilla Expanded Framework [https://steamcommunity.com/sharedfiles/filedetails/?id=2023507013]
Vanilla Factions Expanded - Mechanoids [https://steamcommunity.com/sharedfiles/filedetails/?id=2329011599]
Combat Extended [https://steamcommunity.com/sharedfiles/filedetails/?id=1631756268]
LWM's Deep Storage [https://steamcommunity.com/sharedfiles/filedetails/?id=1617282896]
AI Upscaled Textures - Mods [https://steamcommunity.com/sharedfiles/filedetails/?id=2323211835]
Adjacent Light [https://steamcommunity.com/sharedfiles/filedetails/?id=2517853803]
Advanced Moisture Pump [https://steamcommunity.com/sharedfiles/filedetails/?id=2274680538]
Allow Tool [https://steamcommunity.com/sharedfiles/filedetails/?id=761421485]
Almost There! [https://steamcommunity.com/sharedfiles/filedetails/?id=2372543327]
Animals Logic [https://steamcommunity.com/sharedfiles/filedetails/?id=1098354593]
Apparel Patch for Aya races [https://steamcommunity.com/sharedfiles/filedetails/?id=2398947154]
Apparel Tainted Only When Corpse Rots [https://steamcommunity.com/sharedfiles/filedetails/?id=2413156320]
Avoid Friendly Fire [https://steamcommunity.com/sharedfiles/filedetails/?id=1134165362]
Bed Rest For Food Poisoning [https:// no link (local mod)]
Better Linkable Colors [https://steamcommunity.com/sharedfiles/filedetails/?id=2519621745]
Better Workbench Management [https://steamcommunity.com/sharedfiles/filedetails/?id=935982361]
BetterNutrientPasteDispenserControls [https://steamcommunity.com/sharedfiles/filedetails/?id=2324531554]
Blueprints [https://steamcommunity.com/sharedfiles/filedetails/?id=708455313]
Camera+ [https://steamcommunity.com/sharedfiles/filedetails/?id=867467808]
Categorized Crafting Bills [https://steamcommunity.com/sharedfiles/filedetails/?id=2403595130]
Character Editor [https://steamcommunity.com/sharedfiles/filedetails/?id=1874644848]
Clothing Sorter [https://steamcommunity.com/sharedfiles/filedetails/?id=2275655161]
Combat Extended Guns [https://steamcommunity.com/sharedfiles/filedetails/?id=1582570547]
Drop All Inventory [https://steamcommunity.com/sharedfiles/filedetails/?id=2336610918]
Erin's Hairstyles - Redux [https://steamcommunity.com/sharedfiles/filedetails/?id=2361911135]
EvolvedOrgansRedux [https://steamcommunity.com/sharedfiles/filedetails/?id=2424381146]
Expanded Prosthetics and Organ Engineering [https://steamcommunity.com/sharedfiles/filedetails/?id=725956940]
Fluffy Breakdowns [https://steamcommunity.com/sharedfiles/filedetails/?id=726244033]
Heat Map (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2552838384]
Injured Carry [https://steamcommunity.com/sharedfiles/filedetails/?id=2413690575]
Interaction Bubbles [1.3] [https://steamcommunity.com/sharedfiles/filedetails/?id=2553619439]
InventoryTab (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2326678767]
Mad Skills [https://steamcommunity.com/sharedfiles/filedetails/?id=731111514]
Medical Tab [https://steamcommunity.com/sharedfiles/filedetails/?id=715565817]
MendAndRecycle [https://steamcommunity.com/sharedfiles/filedetails/?id=735241897]
Metal Don't Burn (UNOFFICIAL 1.3 PATCH) [https://steamcommunity.com/sharedfiles/filedetails/?id=2557145474]
More Planning 1.3 [https://steamcommunity.com/sharedfiles/filedetails/?id=2551225702]
Mx three hairs  [https://steamcommunity.com/sharedfiles/filedetails/?id=2554075734]
Humanoid Alien Races [https://steamcommunity.com/sharedfiles/filedetails/?id=839005762]
[1.3]Nearmare Race [https://steamcommunity.com/sharedfiles/filedetails/?id=2198830432]
Nearmare [ENG Translation] [https://steamcommunity.com/sharedfiles/filedetails/?id=2213525330]
Need Bar Overflow [https://steamcommunity.com/sharedfiles/filedetails/?id=2566316158]
No Lazy Doctors [https://steamcommunity.com/sharedfiles/filedetails/?id=2476396157]
No One Left Behind [https://steamcommunity.com/sharedfiles/filedetails/?id=2401146569]
Optimization: Meats - C# Edition [https://steamcommunity.com/sharedfiles/filedetails/?id=2542931556]
Packs Are Not Belts [https://steamcommunity.com/sharedfiles/filedetails/?id=2509511179]
Perspective Trees [https:// no link (local mod)]
ProxyHeat [https://steamcommunity.com/sharedfiles/filedetails/?id=2365526329]
Quality Colors [https://steamcommunity.com/sharedfiles/filedetails/?id=2420141361]
Quest Reward Rebalance [https://steamcommunity.com/sharedfiles/filedetails/?id=2312419897]
RPG Style Inventory Revamped [https://steamcommunity.com/sharedfiles/filedetails/?id=2478833213]
RT Fuse [https://steamcommunity.com/sharedfiles/filedetails/?id=728314182]
Rah's Bionics and Surgery Expansion [https://steamcommunity.com/sharedfiles/filedetails/?id=850429707]
Realistic Rooms [1.3] [https://steamcommunity.com/sharedfiles/filedetails/?id=2553724273]
Replace Stuff [https://steamcommunity.com/sharedfiles/filedetails/?id=1372003680]
ResearchPal - Forked [https://steamcommunity.com/sharedfiles/filedetails/?id=2351393394]
Roads of the Rim (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2280318231]
Ruined by temperature filter [https://steamcommunity.com/sharedfiles/filedetails/?id=2554476852]
Save Our Ship 2 [https://steamcommunity.com/sharedfiles/filedetails/?id=1909914131]
Simple Utilities: Ceiling [https:// no link (local mod)]
Smarter Construction [https://steamcommunity.com/sharedfiles/filedetails/?id=2202185773]
Smarter Deconstruction and Mining [https://steamcommunity.com/sharedfiles/filedetails/?id=2398365712]
Stackable Chunks [1.3+] [https://steamcommunity.com/sharedfiles/filedetails/?id=2373632580]
Stockpile Stack Limit (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2274678322]
Tech Advancing [https://steamcommunity.com/sharedfiles/filedetails/?id=735268789]
VFE-M: Add-On [https://steamcommunity.com/sharedfiles/filedetails/?id=2329025520]
VFE - Mechanoids : Tab [https://steamcommunity.com/sharedfiles/filedetails/?id=2368220087]
Vanilla Furniture Expanded - Power [https://steamcommunity.com/sharedfiles/filedetails/?id=2062943477]
AI Upscaled Textures - Plants [https://steamcommunity.com/sharedfiles/filedetails/?id=2307592039]
Vanilla Textures Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2016436324]
Vanilla Furniture Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1718190143]
Vanilla Textures Expanded - Variations [https://steamcommunity.com/sharedfiles/filedetails/?id=2493234474]
Weapons Sorter [https://steamcommunity.com/sharedfiles/filedetails/?id=2290406586]
What the hack?! [https://steamcommunity.com/sharedfiles/filedetails/?id=1505914869]
What the hack - A little expansion [https://steamcommunity.com/sharedfiles/filedetails/?id=2456962656]
What's for sale? [https://steamcommunity.com/sharedfiles/filedetails/?id=2396808851]
Windows [https:// no link (local mod)]
World Map Beautification Project [https://steamcommunity.com/sharedfiles/filedetails/?id=2314407956]
[1.3]Neclose Race [https://steamcommunity.com/sharedfiles/filedetails/?id=2394460334]
[1.2,1.3]Neclose Race (English translation) [https://steamcommunity.com/sharedfiles/filedetails/?id=2396877772]
[1.3]Silkiera Race [https://steamcommunity.com/sharedfiles/filedetails/?id=2233666290]
[1.2,1.3]Silkiera Race(English) [https://steamcommunity.com/sharedfiles/filedetails/?id=2282193710]
[LTO] Terrain Overhaul [https://steamcommunity.com/sharedfiles/filedetails/?id=2284769535]
[NL] Facial Animation - WIP [https://steamcommunity.com/sharedfiles/filedetails/?id=1635901197]
RimJobWorld [https:// no link (local mod)]
RimNudeWorld [https:// no link (local mod)]
RimJobWorld - Licentia Labs [https:// no link (local mod)]
RJW_RBSE [https:// no link (local mod)]
OTY Bodies for Alien Races [https:// no link (local mod)]
OTY_NUDE Unofficial Update [https:// no link (local mod)]
Chaeren's Female Apparel [https:// no link (local mod)]
RJW - RaceSupport [https:// no link (local mod)]
Rimworld-Animations [https:// no link (local mod)]
Dubs Performance Analyzer [https://steamcommunity.com/sharedfiles/filedetails/?id=2038874626]
RJWAnimAddons-VoicePatch [https:// no link (local mod)]
RJWAnimAddons-XtraAnims [https:// no link (local mod)]
RJWAnimAddons-AnimalPatch [https:// no link (local mod)]
RimThreaded [https://steamcommunity.com/sharedfiles/filedetails/?id=2222907981]

**Comment by cseelhoff** [comment]
I loaded your save game and modlist in RimPy. There seem to be errors. Can you reproduce this bug with something more vanilla? Or even with a modlist that checks out in RimPy as error free? Thanks. Closing until new save is attached. (or steps to reproduce on vanilla+RT)

**Comment by DurekuRyuu** [comment]
> I loaded your save game and modlist in RimPy. There seem to be errors. Can you reproduce this bug with something more vanilla? Or even with a modlist that checks out in RimPy as error free? Thanks. Closing until new save is attached. (or steps to reproduce on vanilla+RT)

Will try that in a few days, busy until friday.
