### ISSUE TITLE
RimThreaded and Android Tiers Completely Breaking Game, Not Even Main Menus Loading on Launch

### ISSUE THREAD

**Issue by Royscw** [cseelhoff/RimThreaded#627]
Hi, I have a major issue! Android Tiers with RimThreaded is causing Rimworld to not load properly at all, **on game launch it freezes on the menu background with no menus loaded and prevents any actions.**
I just get the background with no text, menus, options or anything. The log shows an error spamming on repeat. The error is repeated over and over until I force close and the log file gets HUGE; I left this for a while and got a 7GB log file of 99.99% the same error

My main mod list gives the same results. I resorted to deleting EVERYTHING (mods, config, uninstall rimworld, reinstall from scratch and use only core, rotalty and Android Tiers) still the same issue.

I'm running 1.2 latest. This started happening after getting a latest game and mod update on 13th August.

Please please help! I consider Adroid Tiers one of my core mods, yet Rimhtreaded is essential to making the game playable. So I'm basically prevented from playing until this is fixed as any game without Android Tiers will make make me not want to play... I'm in Rimwithdrawals! Help!

I got a HugsLib Trace which included a couple of Android Tiers dependancies, but the same behaviour happens if those are removed.

Hugslib and Player.log for the issue:
https://gist.github.com/HugsLibRecordKeeper/322e2c2d6842d9c068f4ec4e0dafddc0
[Player.log](https://github.com/cseelhoff/RimThreaded/files/6991891/Player.log)

Here is the error on repeat:

> Root level exception in Update(): System.NullReferenceException: Object reference not set to an instance of an object
> at (wrapper dynamic-method) RimWorld.Pawn_MeleeVerbs.RimWorld.Pawn_MeleeVerbs.PawnMeleeVerbsStaticUpdate_Patch0()
> at (wrapper dynamic-method) Verse.Root.Verse.Root.Update_Patch1(Verse.Root)
> 
> (Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)
> 
> Root level exception in OnGUI(): System.NullReferenceException: Object reference not set to an instance of an object
> at (wrapper dynamic-method) Verse.GrammarResolverSimpleStringExtensions.Verse.GrammarResolverSimpleStringExtensions.Formatted_Patch0(string,Verse.NamedArgument)
> at Verse.GrammarResolverSimpleStringExtensions.Formatted (Verse.TaggedString str, Verse.NamedArgument arg1) [0x00007] in <12a8d1a0a5a64eae86579edb3a3b30c7>:0
> at Verse.TranslatorFormattedStringExtensions.Translate (System.String key, Verse.NamedArgument arg1) [0x00006] in <12a8d1a0a5a64eae86579edb3a3b30c7>:0
> at (wrapper dynamic-method) RimWorld.VersionControl.RimWorld.VersionControl.DrawInfoInCorner_Patch1()
> at RimWorld.MainMenuDrawer.MainMenuOnGUI () [0x00000] in <12a8d1a0a5a64eae86579edb3a3b30c7>:0
> at Verse.UIRoot_Entry.DoMainMenu () [0x0001f] in <12a8d1a0a5a64eae86579edb3a3b30c7>:0
> at (wrapper dynamic-method) Verse.UIRoot_Entry.Verse.UIRoot_Entry.UIRootOnGUI_Patch1(Verse.UIRoot_Entry)
> at (wrapper dynamic-method) Verse.Root.Verse.Root.OnGUI_Patch1(Verse.Root)

I cant produce a save file as I cant load the game menus to do ANYTHING!

Screenshot of Rimworld not loading at all. It stayed like this all last night giving me a 7.3GB log file of the same errors on repeat:
![image](https://user-images.githubusercontent.com/7825107/129555144-26350161-42ce-4c22-b4ef-50a5a5c698b2.png)

**Mod list (For vanilla report, it has to be same as below list.)**
Described above.

Let me know if I missed anything, thanks guys. I've been meaning to give a small donation as appreciation of your work, can I be cheeky, make it a bit larger and associate it ot this?? :)

p.s. I LOVE the work you do and am so impressed with what you've pulled off! Keep up the good work :)

**Comment by Sernior** [comment]
It seems you are using the release for 1.3 version of rw as the patch that is causing your error is not meant do be done on 1.2.
I strongly suggest you start playing on 1.3 as every mod author us included is focussing at the moment on 1.3.
Android tiers in particular has been patched heavily by kiwi and made a lot more performant in 1.3 and we already patched it to be compatible... it is this 1.3 patch infact that is causing you this crash. The next steam release will fix you this problem sorry I am having toubles at the moment to compile a 1.2 version. Surely Hoff can compile one for you without that patch easily... sorry again it was me infact who wrote that patch.

**Comment by cseelhoff** [comment]
I think this was fixed in 2.5.12. If it is still an issue, please reopen the ticket or message me on discord
