### ISSUE TITLE
A big spam error and the infinite log error

### ISSUE THREAD

**Issue by Lukitas471** [cseelhoff/RimThreaded#632]
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report!  

**Describe the bug**
When i start the save and 1 of my colonis have a chance of major break the game spam the message of mental break risk every seconds and the log repeats a error at the same time, this make the game lag and unplayable. when i deinstall the Threaded mod the game works fine. My save game is from 1 year and i didn´t know why the problem it´s generated because the game doesn´t present this error before.

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Load the save with the mods
2. wait 10 seconds in 1x
3. the spam of messages generates
4. See the log and the infinite progressive messages generate

**Error Log**
[Error.txt](https://github.com/cseelhoff/RimThreaded/files/7009827/Error.txt
https://gist.github.com/31a930393b4b1ca10c2558f66921bf0d

**Save file**
[Heaven.zip](https://github.com/cseelhoff/RimThreaded/files/7009705/Heaven.zip)

**Screenshots**
![WhatsApp Image 2021-08-18 at 15 45 08](https://user-images.githubusercontent.com/89160730/129962349-5e99c1a6-c1de-4ca0-82fe-a11b3dcab509.jpeg)
https://user-images.githubusercontent.com/89160730/129962371-0078cf37-b02b-4b55-989e-2fc128e64250.mp4

**Mod list (Preferably a RimPy compatible list.)**
*Harmony
*Realistic Rooms [1.3]
*Damage Indicators [1.3]
*Vanilla Expanded Framework
*Vanilla Weapons Expanded
*Vanilla Weapons Expanded - Quickdraw
*Vanilla Weapons Expanded - Laser
*Vanilla Weapons Expanded - Heavy Weapons
*Vanilla Weapons Expanded - Coilguns
*Vanilla Factions Expanded - Settlers
*Vanilla Weapons Expanded - Frontier
*Vanilla Factions Expanded - Mechanoids
*Vanilla Factions Expanded - Medieval
*No Lazy Doctors
*Quest Reward Rebalance
*Vanilla Traits Expanded
*Smarter Construction
*Dubs Performance Analyzer
*[FSF] More Quest
*Expanded Prosthetics and Organ Engineering - Forked
*RimSaves
*Startup impact
*Dire Raids
*RuntimeGC [1.3]
*Replace Stuff
*Snap Out!
*Pick Up And Haul
*RunAndGun
*Sparkling Worlds - Full Mod
*Animals Logic
*Vanilla Expanded - Royalty Patches
*Vanilla Furniture Expanded
*Vanilla Furniture Expanded - Medical Module
*No Shadows
*Repair Workbench
*No Debris
*Vanilla Apparel Expanded — Accessories
*Vanilla Fishing Expanded
*Vanilla Fishing Expanded - Fishing Treasures AddOn
*Vanilla Weapons Expanded - Tribal
*Vanilla Weapons Expanded - Non-Lethal
*Vanilla Social Interactions Expanded
*Vanilla Weapons Expanded - Makeshift
*Vanilla Factions Expanded - Vikings
*Vanilla Weapons Expanded - Grenades
*Vanilla Books Expanded
*Vanilla Factions Expanded - Insectoids
*Vanilla Furniture Expanded - Power
*Vanilla Furniture Expanded - Spacer Module
*No ZzZ
*Vanilla Furniture Expanded - Art
*Vanilla Furniture Expanded - Farming
*Vanilla Furniture Expanded - Production
*Vanilla Furniture Expanded - Security
*Vanilla Armour Expanded
*Vanilla Apparel Expanded
*No More Filth
*[SYR] Harvest Yield (1.3)
*Melee Psycasts
*Graphics Settings+
*Specialists Can Work!
*Ducks' No Limits - Ideology
*Go Explore!
*Stack XXL
*Faster Biosculpting Pod
*[FSF] Better Ancient Complex Loot
*Vanilla Plants Expanded
*RimThreaded

**Comment by Niilo007** [comment]
Try updating your Rimworld and validating files
seems like your issues are not related to rimthreaded
