### ISSUE TITLE
Spam of log and major break risk| REOPEN 

### ISSUE THREAD

**Issue by Lukitas471** [cseelhoff/RimThreaded#633]
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report!
I send this because the first time mi report was closed and the bug is still there 
Describe the bug
When i start the save and 1 of my colonis have a chance of major break the game spam the message of mental break risk every seconds and the log repeats a error at the same time, this make the game lag and unplayable. when i deinstall the Threaded mod the game works fine. My save game is from 1 year and i didn´t know why the problem it´s generated because the game doesn´t present this error before.

Steps to reproduce the behavior (VERY IMPORTANT)

Load the save with the mods
wait 10 seconds in 1x
the spam of messages generates
See the log and the infinite progressive messages generate
Error Log
[Error.txt](https://github.com/cseelhoff/RimThreaded/files/7009827/Error.txt
https://gist.github.com/31a930393b4b1ca10c2558f66921bf0d

Save file
Heaven.zip

Screenshots
WhatsApp Image 2021-08-18 at 15 45 08
https://user-images.githubusercontent.com/89160730/129962371-0078cf37-b02b-4b55-989e-2fc128e64250.mp4

Mod list (Preferably a RimPy compatible list.)
*Harmony
*Realistic Rooms [1.3]
*Damage Indicators [1.3]
*Vanilla Expanded Framework
*Vanilla Weapons Expanded
*Vanilla Weapons Expanded - Quickdraw
*Vanilla Weapons Expanded - Laser
*Vanilla Weapons Expanded - Heavy Weapons
*Vanilla Weapons Expanded - Coilguns
*Vanilla Factions Expanded - Settlers
*Vanilla Weapons Expanded - Frontier
*Vanilla Factions Expanded - Mechanoids
*Vanilla Factions Expanded - Medieval
*No Lazy Doctors
*Quest Reward Rebalance
*Vanilla Traits Expanded
*Smarter Construction
*Dubs Performance Analyzer
*[FSF] More Quest
*Expanded Prosthetics and Organ Engineering - Forked
*RimSaves
*Startup impact
*Dire Raids
*RuntimeGC [1.3]
*Replace Stuff
*Snap Out!
*Pick Up And Haul
*RunAndGun
*Sparkling Worlds - Full Mod
*Animals Logic
*Vanilla Expanded - Royalty Patches
*Vanilla Furniture Expanded
*Vanilla Furniture Expanded - Medical Module
*No Shadows
*Repair Workbench
*No Debris
*Vanilla Apparel Expanded — Accessories
*Vanilla Fishing Expanded
*Vanilla Fishing Expanded - Fishing Treasures AddOn
*Vanilla Weapons Expanded - Tribal
*Vanilla Weapons Expanded - Non-Lethal
*Vanilla Social Interactions Expanded
*Vanilla Weapons Expanded - Makeshift
*Vanilla Factions Expanded - Vikings
*Vanilla Weapons Expanded - Grenades
*Vanilla Books Expanded
*Vanilla Factions Expanded - Insectoids
*Vanilla Furniture Expanded - Power
*Vanilla Furniture Expanded - Spacer Module
*No ZzZ
*Vanilla Furniture Expanded - Art
*Vanilla Furniture Expanded - Farming
*Vanilla Furniture Expanded - Production
*Vanilla Furniture Expanded - Security
*Vanilla Armour Expanded
*Vanilla Apparel Expanded
*No More Filth
*[SYR] Harvest Yield (1.3)
*Melee Psycasts
*Graphics Settings+
*Specialists Can Work!
*Ducks' No Limits - Ideology
*Go Explore!
*Stack XXL
*Faster Biosculpting Pod
*[FSF] Better Ancient Complex Loot
*Vanilla Plants Expanded
*RimThreaded

**Comment by Sernior** [comment]
You are not using the latest rimworld build. Enable auto updates if it keeps happening comment here again.

**Comment by Lukitas471** [comment]
I updated, but the problem is here 
nothing changes, even i dowloaded again the most of the mods

**Comment by Lukitas471** [comment]
i´m using the new 1.3.3093 and stills there

**Comment by Sernior** [comment]
Post the logs now please something may have changed with you updating.

**Comment by Niilo007** [comment]
#646
#647

**Comment by Niilo007** [comment]
Unless this happens in vanilla + RT.
it might be one of these mods (based on process of elimination (or something like that))


*Realistic Rooms [1.3]
*Vanilla Expanded Framework
*Vanilla Weapons Expanded
*Vanilla Factions Expanded - Settlers
*Vanilla Factions Expanded - Medieval
*No Lazy Doctors                                           <-- Maybe this?
*Vanilla Traits Expanded
*Smarter Construction
*Replace Stuff
*Snap Out!
*Pick Up And Haul
*RunAndGun
*Vanilla Expanded - Royalty Patches
*Vanilla Furniture Expanded
*Vanilla Furniture Expanded - Medical Module
*No Debris
*Vanilla Fishing Expanded
*Vanilla Factions Expanded - Vikings
*Vanilla Books Expanded
*Vanilla Furniture Expanded - Power
*Vanilla Furniture Expanded - Spacer Module
*Vanilla Furniture Expanded - Art
*Vanilla Furniture Expanded - Farming
*Vanilla Furniture Expanded - Production
*Vanilla Furniture Expanded - Security
*Vanilla Apparel Expanded

**Comment by Sernior** [comment]
is the ritual obligation spam again is fixed.
