### ISSUE TITLE
Medical emergency spam probably related to #646

### ISSUE THREAD

**Issue by Niilo007** [cseelhoff/RimThreaded#647]
## **IMPORTANT:**  
**Please first search existing bugs to ensure you are not creating a duplicate bug report!**   
**Make sure you have the latest version of Rimworld!**  

### **Describe the bug**
Medical emergency warning is spamming

### **Steps to reproduce the behavior (VERY IMPORTANT)**
1. load save
2. prisoner is close to bleeding out (medical emergency)
3. warning spam (most likely the same or at least related to #646 )

#### **Player.log**
!!! Link to contents of Player.log or Error.log (MUST BE LINK) !!!  
#### **HugsLib log**
https://gist.github.com/a4a5bfb5613d106d3355d9043b2eb19f

### **Save file**
[Funera Empire (Permadeath).zip](https://github.com/cseelhoff/RimThreaded/files/7079963/Funera.Empire.Permadeath.zip)

### **Screenshots**
![image](https://user-images.githubusercontent.com/75486261/131414705-2f8d244c-83ca-4201-be0e-7633ed336afd.png)

### **Mod list (For vanilla report, it has to be same as below list.)**
* Harmony
* Core
* Royalty (Optional)
* Ideology (Optional)
* HugsLib
* RimThreaded

### **For the save**
[Mod list length: 217]
Harmony [https://steamcommunity.com/sharedfiles/filedetails/?id=2009463077]
BetterLoading [https://steamcommunity.com/sharedfiles/filedetails/?id=1999454301]
RIMMSAssemble [https://steamcommunity.com/sharedfiles/filedetails/?id=1780241645]
Core [https:// no link (local mod)]
Royalty [Official DLC] [https:// no link (local mod)]
Ideology [Official DLC] [https:// no link (local mod)]
SRTS Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1845423808]
HugsLib [https://steamcommunity.com/sharedfiles/filedetails/?id=818773962]
Mod Manager [https://steamcommunity.com/sharedfiles/filedetails/?id=1507748539]
EdB Prepare Carefully [https://steamcommunity.com/sharedfiles/filedetails/?id=735106432]
Enable Oversized Weapons [https://steamcommunity.com/sharedfiles/filedetails/?id=2543371889]
Yayo's Combat 3 [Adopted] [https://steamcommunity.com/sharedfiles/filedetails/?id=2513695736]
Humanoid Alien Races [https://steamcommunity.com/sharedfiles/filedetails/?id=839005762]
ToolBox (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2576079360]
Vanilla Expanded Framework [https://steamcommunity.com/sharedfiles/filedetails/?id=2023507013]
Vanilla Expanded - Royalty Patches [https://steamcommunity.com/sharedfiles/filedetails/?id=2260012940]
RWLayout [https://steamcommunity.com/sharedfiles/filedetails/?id=2209393954]
ModDiff [https://steamcommunity.com/sharedfiles/filedetails/?id=2200054867]
Achtung! [https://steamcommunity.com/sharedfiles/filedetails/?id=730936602]
Camera+ [https://steamcommunity.com/sharedfiles/filedetails/?id=867467808]
What the hack?! [https://steamcommunity.com/sharedfiles/filedetails/?id=1505914869]
What the hack - A little expansion [https://steamcommunity.com/sharedfiles/filedetails/?id=2456962656]
Giddy-up! Core [https://steamcommunity.com/sharedfiles/filedetails/?id=1216999901]
Giddy-up! Battle Mounts [https://steamcommunity.com/sharedfiles/filedetails/?id=1217001091]
Giddy-up! Caravan [https://steamcommunity.com/sharedfiles/filedetails/?id=1253251478]
Giddy-up! Ride and Roll [https://steamcommunity.com/sharedfiles/filedetails/?id=1331961995]
Giddy-up! Mechanoids [https://steamcommunity.com/sharedfiles/filedetails/?id=1518932357]
More Vanilla Biomes [https://steamcommunity.com/sharedfiles/filedetails/?id=1931453053]
Prepare Landing [https://steamcommunity.com/sharedfiles/filedetails/?id=1095331978]
Map Reroll [https://steamcommunity.com/sharedfiles/filedetails/?id=761315214]
Better Map Sizes [https://steamcommunity.com/sharedfiles/filedetails/?id=2099101052]
RimCities [https://steamcommunity.com/sharedfiles/filedetails/?id=1775170117]
Real Ruins [https://steamcommunity.com/sharedfiles/filedetails/?id=1552146295]
[KV] Consolidated Traits [https://steamcommunity.com/sharedfiles/filedetails/?id=1507384362]
Vanilla Traits Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2296404655]
[KV] More Trait Slots [https://steamcommunity.com/sharedfiles/filedetails/?id=1508292711]
Backstories+ [https://steamcommunity.com/sharedfiles/filedetails/?id=2289854459]
Misc. Robots [https://steamcommunity.com/sharedfiles/filedetails/?id=724602224]
Misc. Craftable Robots Retexture [https://steamcommunity.com/sharedfiles/filedetails/?id=2140349611]
[SYR] Scar Removal Plus [https://steamcommunity.com/sharedfiles/filedetails/?id=1507367510]
Death Rattle Continued [1.2] [https://steamcommunity.com/sharedfiles/filedetails/?id=2206107940]
Life Support Continued [1.1][1.2] [https://steamcommunity.com/sharedfiles/filedetails/?id=2213696082]
Medical Supplements (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2195037369]
A Dog Said... Animal Prosthetics [https://steamcommunity.com/sharedfiles/filedetails/?id=746425621]
Medical System Expansion 2 [https://steamcommunity.com/sharedfiles/filedetails/?id=2056706586]
Locks [https://steamcommunity.com/sharedfiles/filedetails/?id=1157085076]
Prison Labor [https://steamcommunity.com/sharedfiles/filedetails/?id=1899474310]
Dubs Bad Hygiene [https://steamcommunity.com/sharedfiles/filedetails/?id=836308268]
Simple sidearms [https://steamcommunity.com/sharedfiles/filedetails/?id=927155256]
Suppression (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2559826227]
Brrr and Phew (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2195938471]
Avoid Friendly Fire [https://steamcommunity.com/sharedfiles/filedetails/?id=1134165362]
Replace Stuff [https://steamcommunity.com/sharedfiles/filedetails/?id=1372003680]
Smarter Construction [https://steamcommunity.com/sharedfiles/filedetails/?id=2202185773]
Common Sense [https://steamcommunity.com/sharedfiles/filedetails/?id=1561769193]
Ugh You Got Me [https://steamcommunity.com/sharedfiles/filedetails/?id=1542424705]
No Lazy Doctors [https://steamcommunity.com/sharedfiles/filedetails/?id=2476396157]
Stabilize [https://steamcommunity.com/sharedfiles/filedetails/?id=2023407836]
Injured Carry [https://steamcommunity.com/sharedfiles/filedetails/?id=2413690575]
Dubs Break Mod [https://steamcommunity.com/sharedfiles/filedetails/?id=1722398508]
Snap Out! [https://steamcommunity.com/sharedfiles/filedetails/?id=1319782555]
SF Grim Reality [https://steamcommunity.com/sharedfiles/filedetails/?id=1543063349]
Use Minified Buildings [https://steamcommunity.com/sharedfiles/filedetails/?id=2185809028]
RunAndGun [https://steamcommunity.com/sharedfiles/filedetails/?id=1204108550]
Search and Destroy [https://steamcommunity.com/sharedfiles/filedetails/?id=1467764609]
[KV] Path Avoid [https://steamcommunity.com/sharedfiles/filedetails/?id=1180719857]
Guards For Me [https://steamcommunity.com/sharedfiles/filedetails/?id=1855885448]
Bad Can Be Good [https://steamcommunity.com/sharedfiles/filedetails/?id=2025857053]
Raiders Never Die (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2024330186]
Hunt for Me [https://steamcommunity.com/sharedfiles/filedetails/?id=1593245720]
Ignite Everything [https://steamcommunity.com/sharedfiles/filedetails/?id=1607884210]
Where's My Bed? [https://steamcommunity.com/sharedfiles/filedetails/?id=1919873778]
Defensive Positions [https://steamcommunity.com/sharedfiles/filedetails/?id=761219125]
Dress Patients [https://steamcommunity.com/sharedfiles/filedetails/?id=1667901146]
Auto-Cut Blight [https://steamcommunity.com/sharedfiles/filedetails/?id=1885186534]
[KV] Save Storage, Outfit, Crafting, Drug, & Operation Settings [https://steamcommunity.com/sharedfiles/filedetails/?id=1180718516]
Selectable Sculpture Graphic [https://steamcommunity.com/sharedfiles/filedetails/?id=1537873717]
QualityBuilder [https://steamcommunity.com/sharedfiles/filedetails/?id=754637870]
Best Mix (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2195986094]
Conduit Deconstruct [https://steamcommunity.com/sharedfiles/filedetails/?id=838336462]
4M Mehni's Misc Modifications [1.2-1.3] [https://steamcommunity.com/sharedfiles/filedetails/?id=2228765246]
Music on the Rim [https://steamcommunity.com/sharedfiles/filedetails/?id=1872570102]
P-Music [https://steamcommunity.com/sharedfiles/filedetails/?id=725130005]
[KV] Don't stop the music [https://steamcommunity.com/sharedfiles/filedetails/?id=1210224966]
FrameRateControl [https://steamcommunity.com/sharedfiles/filedetails/?id=1591142767]
[D] Ignorance Is Bliss [https://steamcommunity.com/sharedfiles/filedetails/?id=2554423472]
[KV] Adjustable Trade Ships [https://steamcommunity.com/sharedfiles/filedetails/?id=1369828656]
A Petition for Provisions (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2444190820]
Area Inclusion & Exclusion [https://steamcommunity.com/sharedfiles/filedetails/?id=2033828736]
[KV] Show Hair With Hats or Hide All Hats [https://steamcommunity.com/sharedfiles/filedetails/?id=1180826364]
Vanilla Events Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1938420742]
Dynamic Diplomacy [https://steamcommunity.com/sharedfiles/filedetails/?id=1875168898]
Nurse Job [https://steamcommunity.com/sharedfiles/filedetails/?id=1820501433]
ResearchPal - Forked [https://steamcommunity.com/sharedfiles/filedetails/?id=2351393394]
Animal Tab [https://steamcommunity.com/sharedfiles/filedetails/?id=712141500]
Work Tab [https://steamcommunity.com/sharedfiles/filedetails/?id=725219116]
Grouped Pawns Lists [https://steamcommunity.com/sharedfiles/filedetails/?id=2340773428]
More Graphs [https://steamcommunity.com/sharedfiles/filedetails/?id=1966250412]
Drug Response (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2196401201]
Blueprints [https://steamcommunity.com/sharedfiles/filedetails/?id=708455313]
Allow Tool [https://steamcommunity.com/sharedfiles/filedetails/?id=761421485]
Architect Icons [https://steamcommunity.com/sharedfiles/filedetails/?id=1195427067]
Optional Icons for Architect Icons [https://steamcommunity.com/sharedfiles/filedetails/?id=1966995052]
Power Indicators [https://steamcommunity.com/sharedfiles/filedetails/?id=899714534]
Snowy Trees [https://steamcommunity.com/sharedfiles/filedetails/?id=1322101066]
Bionic icons [https://steamcommunity.com/sharedfiles/filedetails/?id=1677616980]
More Sculpture [https://steamcommunity.com/sharedfiles/filedetails/?id=1612316880]
World Map Beautification Project [https://steamcommunity.com/sharedfiles/filedetails/?id=2314407956]
World Map Beautification Project - for More Vanilla Biomes [https://steamcommunity.com/sharedfiles/filedetails/?id=2381830973]
Better Roads [https://steamcommunity.com/sharedfiles/filedetails/?id=1489564822]
High quality textures [https://steamcommunity.com/sharedfiles/filedetails/?id=1676969930]
No Debris 1.1/1.2 [https://steamcommunity.com/sharedfiles/filedetails/?id=2010756536]
Recipe icons [https://steamcommunity.com/sharedfiles/filedetails/?id=1616643195]
Interaction Bubbles [https://steamcommunity.com/sharedfiles/filedetails/?id=1516158345]
RenameColony [https://steamcommunity.com/sharedfiles/filedetails/?id=1359645236]
Heat Map [https://steamcommunity.com/sharedfiles/filedetails/?id=947972722]
CM Color Coded Mood Bar [1.1+] [https://steamcommunity.com/sharedfiles/filedetails/?id=2006605356]
Pawn Badge Fan Fork [Adopted] [https://steamcommunity.com/sharedfiles/filedetails/?id=2526040241]
Job In Bar [https://steamcommunity.com/sharedfiles/filedetails/?id=2086300611]
Pawn Badge - (MISC) Job Icons [https://steamcommunity.com/sharedfiles/filedetails/?id=1734233154]
Show Draftees Weapon [https://steamcommunity.com/sharedfiles/filedetails/?id=1690978457]
Wearing Armor Info [https://steamcommunity.com/sharedfiles/filedetails/?id=1839305669]
Compact Hediffs [https://steamcommunity.com/sharedfiles/filedetails/?id=2031734067]
Better Message Placement (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2259516339]
Power Alerts [https://steamcommunity.com/sharedfiles/filedetails/?id=1664714758]
Fixable Mood Debuffs Alert [https://steamcommunity.com/sharedfiles/filedetails/?id=1307316672]
Food Alert (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2017538067]
Level Up! [https://steamcommunity.com/sharedfiles/filedetails/?id=1701592470]
Auto links [https://steamcommunity.com/sharedfiles/filedetails/?id=2059389912]
De-generalize Work [https://steamcommunity.com/sharedfiles/filedetails/?id=2011655761]
Drug Policy Fix (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2195390245]
Immunities Reset (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2195961535]
Grazing Lands [https://steamcommunity.com/sharedfiles/filedetails/?id=1770268130]
Reworked Temperature Extreme Events [1.3] [https://steamcommunity.com/sharedfiles/filedetails/?id=1372130541]
Tech Advancing [https://steamcommunity.com/sharedfiles/filedetails/?id=735268789]
Skilled Stonecutting [https://steamcommunity.com/sharedfiles/filedetails/?id=1207390617]
No Job Authors [https://steamcommunity.com/sharedfiles/filedetails/?id=2009825774]
Less Arbitrary Surgery (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2018250654]
MinifyEverything [https://steamcommunity.com/sharedfiles/filedetails/?id=872762753]
ETRT: Room Size Tweaks [https://steamcommunity.com/sharedfiles/filedetails/?id=1544557907]
Mortar Accuracy [https://steamcommunity.com/sharedfiles/filedetails/?id=1729446857]
Exotic's Better Crashed Ship Parts [https://steamcommunity.com/sharedfiles/filedetails/?id=1239138840]
[FSF] Filth Vanishes With Rain And Time [https://steamcommunity.com/sharedfiles/filedetails/?id=1508341791]
Loading In Progress [https://steamcommunity.com/sharedfiles/filedetails/?id=1975622772]
[WD] Partially-Passable Wind Turbines [https://steamcommunity.com/sharedfiles/filedetails/?id=1621527381]
Save Our Ship 2 [https://steamcommunity.com/sharedfiles/filedetails/?id=1909914131]
Communicable Diseases [1.3] [https://steamcommunity.com/sharedfiles/filedetails/?id=2016577520]
Dub's Paint Shop [https://steamcommunity.com/sharedfiles/filedetails/?id=1579516669]
Architect Expanded - Fences (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2576081324]
[O21] Seamless Embrasures [https://steamcommunity.com/sharedfiles/filedetails/?id=2290689449]
Door Curtains [https://steamcommunity.com/sharedfiles/filedetails/?id=1541139150]
Signs and Memorials (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2071681396]
Roads of the Rim (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2280318231]
Auto Seller [https://steamcommunity.com/sharedfiles/filedetails/?id=1440321094]
Colony Manager [https://steamcommunity.com/sharedfiles/filedetails/?id=715565262]
Dubs Rimatomics [https://steamcommunity.com/sharedfiles/filedetails/?id=1127530465]
Rimefeller [https://steamcommunity.com/sharedfiles/filedetails/?id=1321849735]
RimHeli [https://steamcommunity.com/sharedfiles/filedetails/?id=2158396143]
Simple Turrets [https://steamcommunity.com/sharedfiles/filedetails/?id=1790155285]
Project RimFactory Revived [https://steamcommunity.com/sharedfiles/filedetails/?id=2033979700]
Omni Core Drill (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2562491370]
Quarry [https://steamcommunity.com/sharedfiles/filedetails/?id=2007576583]
Reclaim, Reuse, Recycle (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2567364887]
Commercial Server [https://steamcommunity.com/sharedfiles/filedetails/?id=1714455977]
[KV] RimFridge [https://steamcommunity.com/sharedfiles/filedetails/?id=1180721235]
LWM's Deep Storage [https://steamcommunity.com/sharedfiles/filedetails/?id=1617282896]
Pick Up And Haul [https://steamcommunity.com/sharedfiles/filedetails/?id=1279012058]
Jobs of Opportunity (While You're Up) [https://steamcommunity.com/sharedfiles/filedetails/?id=2034960453]
Stockpile Stack Limit (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2274678322]
Floored - Yellow and Striped Tiles Only [1.0+] [https://steamcommunity.com/sharedfiles/filedetails/?id=1543195051]
Tilled Soil [https://steamcommunity.com/sharedfiles/filedetails/?id=725747149]
Trade Ships Drop Spot [https://steamcommunity.com/sharedfiles/filedetails/?id=1969732297]
[KV] Trading Spot [https://steamcommunity.com/sharedfiles/filedetails/?id=1180719658]
ProgrammableVents [https://steamcommunity.com/sharedfiles/filedetails/?id=824131713]
Diagonal Walls [https://steamcommunity.com/sharedfiles/filedetails/?id=2521631479]
RT Fuse [https://steamcommunity.com/sharedfiles/filedetails/?id=728314182]
RT Power Switch [https://steamcommunity.com/sharedfiles/filedetails/?id=728314859]
RT Solar Flare Shield [https://steamcommunity.com/sharedfiles/filedetails/?id=728315620]
Vanilla RT Solar Flare Shield Retexture [https://steamcommunity.com/sharedfiles/filedetails/?id=1941652952]
Power Logic [https://steamcommunity.com/sharedfiles/filedetails/?id=812653710]
Power++ [https://steamcommunity.com/sharedfiles/filedetails/?id=1771402217]
Parallel Power Grid (Parallel Conduits) [https://steamcommunity.com/sharedfiles/filedetails/?id=1277677885]
Subsurface Conduit [https://steamcommunity.com/sharedfiles/filedetails/?id=1609226728]
Wall Light [https://steamcommunity.com/sharedfiles/filedetails/?id=1423699208]
Gimmicks (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2168169520]
Weapon Tech [https://steamcommunity.com/sharedfiles/filedetails/?id=2005456121]
Fire Extinguisher (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2195996970]
Fire Warden (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2197425463]
Taming Artifact [https://steamcommunity.com/sharedfiles/filedetails/?id=1769917767]
Expanded Roofing [https://steamcommunity.com/sharedfiles/filedetails/?id=2568893936]
Vanilla Fishing Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1914064942]
Vanilla Books Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2193152410]
Vanilla Apparel Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1814987817]
Vanilla Plants Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2134308522]
VPE - No Tilled Soil [https://steamcommunity.com/sharedfiles/filedetails/?id=2165594621]
Vanilla Furniture Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1718190143]
Vanilla Furniture Expanded - Production [https://steamcommunity.com/sharedfiles/filedetails/?id=1880253632]
Vanilla Furniture Expanded - Medical Module [https://steamcommunity.com/sharedfiles/filedetails/?id=1718191613]
Vanilla Furniture Expanded - Spacer Module [https://steamcommunity.com/sharedfiles/filedetails/?id=2028381079]
Vanilla Furniture Expanded - Props and Decor [https://steamcommunity.com/sharedfiles/filedetails/?id=2102143149]
Vanilla Factions Expanded - Medieval [https://steamcommunity.com/sharedfiles/filedetails/?id=2023513450]
Vanilla Furniture Expanded - Security [https://steamcommunity.com/sharedfiles/filedetails/?id=1845154007]
[XND] Tiny Tweaks (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2270049772]
More Linkables [https://steamcommunity.com/sharedfiles/filedetails/?id=1103809207]
Vanilla Hair Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1888705256]
Vanilla Animals Expanded — Boreal Forest [https://steamcommunity.com/sharedfiles/filedetails/?id=1895364938]
Better Infestations 1.3 [https://steamcommunity.com/sharedfiles/filedetails/?id=1319614331]
Better Vanilla Masking [https://steamcommunity.com/sharedfiles/filedetails/?id=1736114368]
[SYR] Terrain [https://steamcommunity.com/sharedfiles/filedetails/?id=1544439671]
Children, school and learning [https://steamcommunity.com/sharedfiles/filedetails/?id=1541438230]
Vanilla Textures Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2016436324]
Bradson's Main Button Icons for Vanilla Textures Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2361775777]
Quality Of Building [https://steamcommunity.com/sharedfiles/filedetails/?id=2101676323]
OgreStack [https://steamcommunity.com/sharedfiles/filedetails/?id=1447140290]
What's That Mod [https://steamcommunity.com/sharedfiles/filedetails/?id=2258431182]
Dubs Performance Analyzer [https://steamcommunity.com/sharedfiles/filedetails/?id=2038874626]
RimThreaded [https://steamcommunity.com/sharedfiles/filedetails/?id=2222907981]

**Comment by Niilo007** [comment]
also happens with "Major break risk" alert message
![image](https://user-images.githubusercontent.com/75486261/131415255-cb70b73e-c397-4770-977b-554af69b0f97.png)
i think we can assume that all alerts are broken in the same way

**Comment by Niilo007** [comment]
Unless this happens in vanilla + RT.
it might be one of these mods (based on process of elimination (or something like that))

*Realistic Rooms [1.3]
*Vanilla Expanded Framework
*Vanilla Weapons Expanded
*Vanilla Factions Expanded - Settlers
*Vanilla Factions Expanded - Medieval
*No Lazy Doctors <--------------------------------- Maybe this?
*Vanilla Traits Expanded
*Smarter Construction
*Replace Stuff
*Snap Out!
*Pick Up And Haul
*RunAndGun
*Vanilla Expanded - Royalty Patches
*Vanilla Furniture Expanded
*Vanilla Furniture Expanded - Medical Module
*No Debris
*Vanilla Fishing Expanded
*Vanilla Factions Expanded - Vikings
*Vanilla Books Expanded
*Vanilla Furniture Expanded - Power
*Vanilla Furniture Expanded - Spacer Module
*Vanilla Furniture Expanded - Art
*Vanilla Furniture Expanded - Farming
*Vanilla Furniture Expanded - Production
*Vanilla Furniture Expanded - Security
*Vanilla Apparel Expanded

**Comment by Sernior** [comment]
seems another ritual exception issue fixed.
