### ISSUE TITLE
[Save Our Ship 2] Infinite Projectiles 

### ISSUE THREAD

**Issue by IK3Holy** [cseelhoff/RimThreaded#651]
### **Describe the bug**
During some ship battles there will be a bug where infinite projectiles are spawns and the screen goes grey when the game is unpaused.  Issue will end in a crash since too many projectiles are spawned.

### **Steps to reproduce the behavior (VERY IMPORTANT)**
1. Enter a SOS2 ship battle with a large ship 
2. If the bug happens it will happen immediately, the screen should turn grey and the game will start lagging badly.

#### **Player.log**
https://github.com/IK3Holy/Misc/blob/main/Player%20(1).log
#### **HugsLib log**
https://gist.github.com/23e23fa506f0334033cc6bdc90e0148e

### **Save file**
[Angelic Army.zip](https://github.com/cseelhoff/RimThreaded/files/7101545/Angelic.Army.zip)

### **Screenshots**
![image](https://user-images.githubusercontent.com/89318060/131910245-95de0115-1e69-4b6a-b9d5-2003e8eb9400.png)
![image](https://user-images.githubusercontent.com/89318060/131910275-14cc71d9-af40-4d01-88a7-e4d649a71b5d.png)

### **Mod list (Preferably a RimPy compatible list.)**
[Modlist.zip](https://github.com/cseelhoff/RimThreaded/files/7101559/Modlist.zip)

[Mod list length: 162]
Harmony [https://steamcommunity.com/sharedfiles/filedetails/?id=2009463077]
Core [https:// no link (local mod)]
Royalty [Official DLC] [https:// no link (local mod)]
Ideology [Official DLC] [https:// no link (local mod)]
HugsLib [https://steamcommunity.com/sharedfiles/filedetails/?id=818773962]
Dual Wield [https://steamcommunity.com/sharedfiles/filedetails/?id=1628211313]
Vanilla Expanded Framework [https://steamcommunity.com/sharedfiles/filedetails/?id=2023507013]
Vanilla Factions Expanded - Mechanoids [https://steamcommunity.com/sharedfiles/filedetails/?id=2329011599]
Vanilla Textures Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2016436324]
Vanilla Furniture Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1718190143]
Vanilla Furniture Expanded - Art [https://steamcommunity.com/sharedfiles/filedetails/?id=1968134023]
Vanilla Weapons Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1814383360]
Vanilla Weapons Expanded - Quickdraw [https://steamcommunity.com/sharedfiles/filedetails/?id=1906780517]
Vanilla Apparel Expanded — Accessories [https://steamcommunity.com/sharedfiles/filedetails/?id=2521176396]
Vanilla Armour Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1814988282]
Vanilla Furniture Expanded - Medical Module [https://steamcommunity.com/sharedfiles/filedetails/?id=1718191613]
Vanilla Furniture Expanded - Spacer Module [https://steamcommunity.com/sharedfiles/filedetails/?id=2028381079]
Vanilla Weapons Expanded - Coilguns [https://steamcommunity.com/sharedfiles/filedetails/?id=2375692535]
Vanilla Weapons Expanded - Grenades [https://steamcommunity.com/sharedfiles/filedetails/?id=2194472657]
Vanilla Furniture Expanded - Security [https://steamcommunity.com/sharedfiles/filedetails/?id=1845154007]
Vanilla Weapons Expanded - Non-Lethal [https://steamcommunity.com/sharedfiles/filedetails/?id=2454918354]
Vanilla Traits Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2296404655]
Mortar Accuracy [https://steamcommunity.com/sharedfiles/filedetails/?id=1729446857]
Vanilla Furniture Expanded - Production [https://steamcommunity.com/sharedfiles/filedetails/?id=1880253632]
RuntimeGC [1.3] [https://steamcommunity.com/sharedfiles/filedetails/?id=2559582557]
Vanilla Weapons Expanded - Heavy Weapons [https://steamcommunity.com/sharedfiles/filedetails/?id=2329126791]
Compact Hediffs [https://steamcommunity.com/sharedfiles/filedetails/?id=2031734067]
ResearchPal - Forked [https://steamcommunity.com/sharedfiles/filedetails/?id=2351393394]
UnLimitedArmor [https://steamcommunity.com/sharedfiles/filedetails/?id=1695493009]
Camping Tent [https://steamcommunity.com/sharedfiles/filedetails/?id=2407128339]
Yayo's Combat 3 [Adopted] [https://steamcommunity.com/sharedfiles/filedetails/?id=2513695736]
Alpha Animals [https://steamcommunity.com/sharedfiles/filedetails/?id=1541721856]
Better Pawn Control [https://steamcommunity.com/sharedfiles/filedetails/?id=1541460369]
Quarry [https://steamcommunity.com/sharedfiles/filedetails/?id=2007576583]
Rimsenal - Core [https://steamcommunity.com/sharedfiles/filedetails/?id=725947920]
Save Our Ship 2 [https://steamcommunity.com/sharedfiles/filedetails/?id=1909914131]
[NL] Chibi Face Male only [https://steamcommunity.com/sharedfiles/filedetails/?id=1562135044]
[NL] Compatible Body 2 [https://steamcommunity.com/sharedfiles/filedetails/?id=1906148376]
Mod Manager [https://steamcommunity.com/sharedfiles/filedetails/?id=1507748539]
Graphics Settings+ [https://steamcommunity.com/sharedfiles/filedetails/?id=1678847247]
JecsTools (Unofficial) [https://steamcommunity.com/sharedfiles/filedetails/?id=2195729899]
[NL] Facial Animation - WIP [https://steamcommunity.com/sharedfiles/filedetails/?id=1635901197]
Allow Tool [https://steamcommunity.com/sharedfiles/filedetails/?id=761421485]
Humanoid Alien Races [https://steamcommunity.com/sharedfiles/filedetails/?id=839005762]
Androids [https://steamcommunity.com/sharedfiles/filedetails/?id=1541064015]
Auto-Cut Blight [https://steamcommunity.com/sharedfiles/filedetails/?id=1885186534]
Avoid Friendly Fire [https://steamcommunity.com/sharedfiles/filedetails/?id=1134165362]
Blueprints [https://steamcommunity.com/sharedfiles/filedetails/?id=708455313]
Centralized Climate Control (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2007268173]
CM Color Coded Mood Bar [1.1+] [https://steamcommunity.com/sharedfiles/filedetails/?id=2006605356]
Dubs Bad Hygiene [https://steamcommunity.com/sharedfiles/filedetails/?id=836308268]
Common Sense [https://steamcommunity.com/sharedfiles/filedetails/?id=1561769193]
Rimsenal - Federation Faction Pack [https://steamcommunity.com/sharedfiles/filedetails/?id=736172213]
Rimsenal - Rimhair [https://steamcommunity.com/sharedfiles/filedetails/?id=725949967]
Rimsenal - Security pack [https://steamcommunity.com/sharedfiles/filedetails/?id=736139206]
Rimsenal - Storyteller pack [https://steamcommunity.com/sharedfiles/filedetails/?id=725952322]
Achtung! [https://steamcommunity.com/sharedfiles/filedetails/?id=730936602]
Beautiful Outdoors [https://steamcommunity.com/sharedfiles/filedetails/?id=2011794898]
Change map edge limit [https://steamcommunity.com/sharedfiles/filedetails/?id=1546494565]
Character Editor [https://steamcommunity.com/sharedfiles/filedetails/?id=1874644848]
Subsurface Conduit [https://steamcommunity.com/sharedfiles/filedetails/?id=1609226728]
Cybernetic Organism and Neural Network [https://steamcommunity.com/sharedfiles/filedetails/?id=2045064990]
Tilled Soil [https://steamcommunity.com/sharedfiles/filedetails/?id=725747149]
Damage Indicators [1.3] [https://steamcommunity.com/sharedfiles/filedetails/?id=2016331497]
Defensive Positions [https://steamcommunity.com/sharedfiles/filedetails/?id=761219125]
Designator Shapes [https://steamcommunity.com/sharedfiles/filedetails/?id=1235181370]
Dire Raids [https://steamcommunity.com/sharedfiles/filedetails/?id=1542379675]
DontBlockDoor [https://steamcommunity.com/sharedfiles/filedetails/?id=1691076769]
Dubs Mint Menus [https://steamcommunity.com/sharedfiles/filedetails/?id=1446523594]
Dubs Mint Minimap [https://steamcommunity.com/sharedfiles/filedetails/?id=1662119905]
Dubs Performance Analyzer [https://steamcommunity.com/sharedfiles/filedetails/?id=2038874626]
Eccentric Extras - Angel Hairs [https://steamcommunity.com/sharedfiles/filedetails/?id=2014890320]
Expanded Prosthetics and Organ Engineering - Forked [https://steamcommunity.com/sharedfiles/filedetails/?id=1949064302]
GlitterNet [https://steamcommunity.com/sharedfiles/filedetails/?id=1725544583]
Harvest Organs Post Mortem [https://steamcommunity.com/sharedfiles/filedetails/?id=1204502413]
Haul to Stack [https://steamcommunity.com/sharedfiles/filedetails/?id=949498803]
Locks [https://steamcommunity.com/sharedfiles/filedetails/?id=1157085076]
Interaction Bubbles [https://steamcommunity.com/sharedfiles/filedetails/?id=1516158345]
Jobs of Opportunity (While You're Up) [https://steamcommunity.com/sharedfiles/filedetails/?id=2034960453]
Just Ignore Me Passing [https://steamcommunity.com/sharedfiles/filedetails/?id=1231617602]
KanbanStockpile [https://steamcommunity.com/sharedfiles/filedetails/?id=2287142613]
Mad Skills [https://steamcommunity.com/sharedfiles/filedetails/?id=731111514]
Map Reroll [https://steamcommunity.com/sharedfiles/filedetails/?id=761315214]
More Sculpture [https://steamcommunity.com/sharedfiles/filedetails/?id=1612316880]
More Utility Packs [https://steamcommunity.com/sharedfiles/filedetails/?id=2357611837]
Nals Facial Animation for HAR [https://steamcommunity.com/sharedfiles/filedetails/?id=2280607572]
Nano Repair Tech [https://steamcommunity.com/sharedfiles/filedetails/?id=1447372624]
No Lazy Doctors [https://steamcommunity.com/sharedfiles/filedetails/?id=2476396157]
OgreStack [https://steamcommunity.com/sharedfiles/filedetails/?id=1447140290]
LegoBricks [https://steamcommunity.com/sharedfiles/filedetails/?id=2548933983]
Packs Are Not Belts [https://steamcommunity.com/sharedfiles/filedetails/?id=2509511179]
Perfect Pathfinding [https://steamcommunity.com/sharedfiles/filedetails/?id=2341486509]
Eccentric Tech - Core [https://steamcommunity.com/sharedfiles/filedetails/?id=2552623545]
Eccentric Tech - Cosmetic Modifications 2.0 [https://steamcommunity.com/sharedfiles/filedetails/?id=2552628984]
Polarisbloc - Core LAB [https://steamcommunity.com/sharedfiles/filedetails/?id=1500244593]
Polarisbloc - Security Force [https://steamcommunity.com/sharedfiles/filedetails/?id=1500248421]
Polarisbloc - Mechenemy [https://steamcommunity.com/sharedfiles/filedetails/?id=1498573216]
Power++ [https://steamcommunity.com/sharedfiles/filedetails/?id=1771402217]
[KV] RimFridge [https://steamcommunity.com/sharedfiles/filedetails/?id=1180721235]
LWM's Deep Storage [https://steamcommunity.com/sharedfiles/filedetails/?id=1617282896]
Quality Colors [https://steamcommunity.com/sharedfiles/filedetails/?id=2420141361]
QualityBuilder [https://steamcommunity.com/sharedfiles/filedetails/?id=754637870]
Quest Reward Rebalance [https://steamcommunity.com/sharedfiles/filedetails/?id=2312419897]
Netrve's DeepStorage GUI [https://steamcommunity.com/sharedfiles/filedetails/?id=2169841018]
RT Fuse [https://steamcommunity.com/sharedfiles/filedetails/?id=728314182]
RT Solar Flare Shield [https://steamcommunity.com/sharedfiles/filedetails/?id=728315620]
Raise The Roof 1.3 [https://steamcommunity.com/sharedfiles/filedetails/?id=1776143665]
Recipe icons [https://steamcommunity.com/sharedfiles/filedetails/?id=1616643195]
Replace Stuff [https://steamcommunity.com/sharedfiles/filedetails/?id=1372003680]
RimPy Mod Manager Database [https://steamcommunity.com/sharedfiles/filedetails/?id=1847679158]
Dubs Rimatomics [https://steamcommunity.com/sharedfiles/filedetails/?id=1127530465]
RimThemes [https://steamcommunity.com/sharedfiles/filedetails/?id=1668983184]
RimSaves [https://steamcommunity.com/sharedfiles/filedetails/?id=1713367505]
Rimefeller [https://steamcommunity.com/sharedfiles/filedetails/?id=1321849735]
Search and Destroy [https://steamcommunity.com/sharedfiles/filedetails/?id=1467764609]
Selectable Sculpture Graphic [https://steamcommunity.com/sharedfiles/filedetails/?id=1537873717]
Show Draftees Weapon [https://steamcommunity.com/sharedfiles/filedetails/?id=1690978457]
Simple sidearms [https://steamcommunity.com/sharedfiles/filedetails/?id=927155256]
SimplyMoreFloors [https://steamcommunity.com/sharedfiles/filedetails/?id=1639883955]
CyberNet [https://steamcommunity.com/sharedfiles/filedetails/?id=1725545225]
Medical System Expansion 2 [https://steamcommunity.com/sharedfiles/filedetails/?id=2056706586]
Smarter Construction [https://steamcommunity.com/sharedfiles/filedetails/?id=2202185773]
Sparkling Worlds - Full Mod [https://steamcommunity.com/sharedfiles/filedetails/?id=1123043922]
Statue of Colonist [https://steamcommunity.com/sharedfiles/filedetails/?id=1539031321]
Statue Of Colonist Alien Race Patch [https://steamcommunity.com/sharedfiles/filedetails/?id=1846741408]
Utility Columns [https://steamcommunity.com/sharedfiles/filedetails/?id=2013476665]
Utility Columns Royalty Patch [https://steamcommunity.com/sharedfiles/filedetails/?id=2513552690]
VFE-M: Add-On [https://steamcommunity.com/sharedfiles/filedetails/?id=2329025520]
VFE Mechanoids - Craftable Mechanoid Components (Alternative) [https://steamcommunity.com/sharedfiles/filedetails/?id=2351501245]
Wall Light [https://steamcommunity.com/sharedfiles/filedetails/?id=1423699208]
Share The Load [https://steamcommunity.com/sharedfiles/filedetails/?id=2576277142]
[I3] Combat Sounds (I3CS) [https://steamcommunity.com/sharedfiles/filedetails/?id=2147296730]
Traders Have Money [https://steamcommunity.com/sharedfiles/filedetails/?id=2022959333]
Camera+ [https://steamcommunity.com/sharedfiles/filedetails/?id=867467808]
What's That Mod [https://steamcommunity.com/sharedfiles/filedetails/?id=2258431182]
Where is my weapon? [https://steamcommunity.com/sharedfiles/filedetails/?id=1539028008]
Work Tab [https://steamcommunity.com/sharedfiles/filedetails/?id=725219116]
[O21] Seamless Embrasures [https://steamcommunity.com/sharedfiles/filedetails/?id=2290689449]
[FSF] Filth Vanishes With Rain And Time [https://steamcommunity.com/sharedfiles/filedetails/?id=1508341791]
RimBank (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2071695947]
Ameiro anime hairs [https://steamcommunity.com/sharedfiles/filedetails/?id=1207934602]
[KV] Show Hair With Hats or Hide All Hats [https://steamcommunity.com/sharedfiles/filedetails/?id=1180826364]
[SR]Factional War [https://steamcommunity.com/sharedfiles/filedetails/?id=2534328163]
FE3H Black Eagles Hair [https://steamcommunity.com/sharedfiles/filedetails/?id=1962075314]
Show Me Your Hands [https://steamcommunity.com/sharedfiles/filedetails/?id=2475965842]
Project RimFactory Revived [https://steamcommunity.com/sharedfiles/filedetails/?id=2033979700]
[NL] Chibi Body [https://steamcommunity.com/sharedfiles/filedetails/?id=1556214130]
Roppoi hair [https://steamcommunity.com/sharedfiles/filedetails/?id=1100547661]
Gloomy Hair mk2 [https://steamcommunity.com/sharedfiles/filedetails/?id=1870678335]
Gw hair mod [hair only] [https://steamcommunity.com/sharedfiles/filedetails/?id=1352123439]
Polyamory Beds (Vanilla Edition) [https://steamcommunity.com/sharedfiles/filedetails/?id=2008138191]
[SS]Lovely Hair Style [https://steamcommunity.com/sharedfiles/filedetails/?id=1498706339]
[NL] Chibi Face Female only [https://steamcommunity.com/sharedfiles/filedetails/?id=1540475285]
[NL] Compatible Body -WIP [https://steamcommunity.com/sharedfiles/filedetails/?id=1533944446]
Eyes back to 1.2! [https://steamcommunity.com/sharedfiles/filedetails/?id=2538702875]
[WD] Fast Moisture Pumps [https://steamcommunity.com/sharedfiles/filedetails/?id=1164753788]
[WD] Realistic Darkness [https://steamcommunity.com/sharedfiles/filedetails/?id=1531882210]
RunAndGun [https://steamcommunity.com/sharedfiles/filedetails/?id=1204108550]
Comigo's Nutrition [https://steamcommunity.com/sharedfiles/filedetails/?id=2546863371]
Pawns Just Don't Die [https://steamcommunity.com/sharedfiles/filedetails/?id=2239397152]
RimJobWorld [https:// no link (local mod)]
RimThreaded [https://steamcommunity.com/sharedfiles/filedetails/?id=2222907981]

**Comment by Sernior** [comment]
Fixed with my PR
