### ISSUE TITLE
RopeToPen not working, errors

### ISSUE THREAD

**Issue by Niilo007** [cseelhoff/RimThreaded#652]
## **IMPORTANT:**  
**Please first search existing bugs to ensure you are not creating a duplicate bug report!**   
**Make sure you have the latest version of Rimworld!**  

### **Describe the bug**
Colonists cant lead animals to pens, it errors out

### **Steps to reproduce the behavior (VERY IMPORTANT)**
1. have a colonist try to lead a group of animals to a pen
2. it will error and the ropes will disappear
3. the colonist will try again forever

#### **Player.log**
!!! Link to contents of Player.log or Error.log (MUST BE LINK) !!!  
#### **HugsLib log**
https://gist.github.com/cf68fc57a61259b087c19f6260cc14e6

### **Save file**
[Kotiin Independent Federation (Permadeath).zip](https://github.com/cseelhoff/RimThreaded/files/7110018/Kotiin.Independent.Federation.Permadeath.zip)

### **Screenshots**
![image](https://user-images.githubusercontent.com/75486261/132098720-ce675d4e-6cdb-4b5a-aa8e-3514a444f9fb.png)

### **Mod list (For vanilla report, it has to be same as below list.)**
* Harmony
* Core
* Royalty (Optional)
* Ideology (Optional)
* HugsLib
* RimThreaded

### **For provided save File:**

[Mod list length: 32]
Harmony [https://steamcommunity.com/sharedfiles/filedetails/?id=2009463077]
Core [https:// no link (local mod)]
Royalty [Official DLC] [https:// no link (local mod)]
Ideology [Official DLC] [https:// no link (local mod)]
HugsLib [https://steamcommunity.com/sharedfiles/filedetails/?id=818773962]
Allow Tool [https://steamcommunity.com/sharedfiles/filedetails/?id=761421485]
Better Map Sizes [https://steamcommunity.com/sharedfiles/filedetails/?id=2099101052]
Bradson's Main Button Icons for Vanilla Textures Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2361775777]
CM Color Coded Mood Bar [1.1+] [https://steamcommunity.com/sharedfiles/filedetails/?id=2006605356]
Camera+ [https://steamcommunity.com/sharedfiles/filedetails/?id=867467808]
Compact Hediffs [https://steamcommunity.com/sharedfiles/filedetails/?id=2031734067]
EdB Prepare Carefully [https://steamcommunity.com/sharedfiles/filedetails/?id=735106432]
Heat Map [https://steamcommunity.com/sharedfiles/filedetails/?id=947972722]
Pick Up And Haul [https://steamcommunity.com/sharedfiles/filedetails/?id=1279012058]
While You're Up / PUAH+ [https://steamcommunity.com/sharedfiles/filedetails/?id=2034960453]
Map Reroll [https://steamcommunity.com/sharedfiles/filedetails/?id=761315214]
ModDiff [https://steamcommunity.com/sharedfiles/filedetails/?id=2200054867]
No Debris 1.1/1.2 [https://steamcommunity.com/sharedfiles/filedetails/?id=2010756536]
OgreStack [https://steamcommunity.com/sharedfiles/filedetails/?id=1447140290]
Architect Icons [https://steamcommunity.com/sharedfiles/filedetails/?id=1195427067]
Optional Icons for Architect Icons [https://steamcommunity.com/sharedfiles/filedetails/?id=1966995052]
Quality Of Building [https://steamcommunity.com/sharedfiles/filedetails/?id=2101676323]
QualityBuilder [https://steamcommunity.com/sharedfiles/filedetails/?id=754637870]
Replace Stuff [https://steamcommunity.com/sharedfiles/filedetails/?id=1372003680]
ResearchPal - Forked [https://steamcommunity.com/sharedfiles/filedetails/?id=2351393394]
Show Draftees Weapon [https://steamcommunity.com/sharedfiles/filedetails/?id=1690978457]
Simple sidearms [https://steamcommunity.com/sharedfiles/filedetails/?id=927155256]
Vanilla Textures Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2016436324]
World Map Beautification Project [https://steamcommunity.com/sharedfiles/filedetails/?id=2314407956]
[KV] Save Storage, Outfit, Crafting, Drug, & Operation Settings [https://steamcommunity.com/sharedfiles/filedetails/?id=1180718516]
[XND] Tiny Tweaks (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2270049772]
RimThreaded [https://steamcommunity.com/sharedfiles/filedetails/?id=2222907981]

**Comment by knox31085** [comment]
I've also seen this after a caravan came back. 2/5 animals had this issue.
