### ISSUE TITLE
Fleck Error on Trade Caravan Arrival

### ISSUE THREAD

**Issue by IK3Holy** [cseelhoff/RimThreaded#659]
## **IMPORTANT:**  
**Please first search existing bugs to ensure you are not creating a duplicate bug report!**   
**Make sure you have the latest version of Rimworld!**  

### **Describe the bug**
Occasionally when a trade caravan arrives the error log will start to be spammed and if the game is continued to be played either a hard crash to desktop will occur or the unity crash handler will be triggered before exiting to desktop.

### **Steps to reproduce the behavior (VERY IMPORTANT)**
1. Open up the attached save files (The Fleck Error save is about 12 hours before a trade caravan arrives, the In action save has the error in progress)
2. a. If you opened the fleck error save, fast forward to when a trade caravan arrives
b. If you opened the in action save, error should happen right away resulting on the game crashing when the save is loaded
3. If the error does not happen, try reloading the save

#### **Player.log**
Below are the full unity crash logs that are generated.
[Rimworld Unity Crash Logs.zip](https://github.com/cseelhoff/RimThreaded/files/7148602/Rimworld.Unity.Crash.Logs.zip)

### **Save file**
[Rimworld Fleck Error Saves.zip](https://github.com/cseelhoff/RimThreaded/files/7148604/Rimworld.Fleck.Error.Saves.zip)

### **Mod list (Preferably a RimPy compatible list.)**
[Rimworld Fleck Error Mod List.zip](https://github.com/cseelhoff/RimThreaded/files/7148606/Rimworld.Fleck.Error.Mod.List.zip)

[Mod list length: 162]
Harmony [https://steamcommunity.com/sharedfiles/filedetails/?id=2009463077]
Core [https:// no link (local mod)]
Royalty [Official DLC] [https:// no link (local mod)]
Ideology [Official DLC] [https:// no link (local mod)]
SRTS Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1845423808]
SRTS Expanded retexture [https://steamcommunity.com/sharedfiles/filedetails/?id=2345408737]
HugsLib [https://steamcommunity.com/sharedfiles/filedetails/?id=818773962]
Vanilla Expanded Framework [https://steamcommunity.com/sharedfiles/filedetails/?id=2023507013]
Vanilla Factions Expanded - Mechanoids [https://steamcommunity.com/sharedfiles/filedetails/?id=2329011599]
Vanilla Textures Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2016436324]
Vanilla Furniture Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1718190143]
Vanilla Furniture Expanded - Medical Module [https://steamcommunity.com/sharedfiles/filedetails/?id=1718191613]
Vanilla Furniture Expanded - Spacer Module [https://steamcommunity.com/sharedfiles/filedetails/?id=2028381079]
Vanilla Weapons Expanded - Coilguns [https://steamcommunity.com/sharedfiles/filedetails/?id=2375692535]
Vanilla Weapons Expanded - Grenades [https://steamcommunity.com/sharedfiles/filedetails/?id=2194472657]
Vanilla Weapons Expanded - Non-Lethal [https://steamcommunity.com/sharedfiles/filedetails/?id=2454918354]
Vanilla Traits Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2296404655]
Vanilla Furniture Expanded - Production [https://steamcommunity.com/sharedfiles/filedetails/?id=1880253632]
Vanilla Weapons Expanded - Heavy Weapons [https://steamcommunity.com/sharedfiles/filedetails/?id=2329126791]
RuntimeGC [1.3] [https://steamcommunity.com/sharedfiles/filedetails/?id=2559582557]
Compact Hediffs [https://steamcommunity.com/sharedfiles/filedetails/?id=2031734067]
ResearchPal - Forked [https://steamcommunity.com/sharedfiles/filedetails/?id=2351393394]
Alpha Animals [https://steamcommunity.com/sharedfiles/filedetails/?id=1541721856]
[NL] Facial Animation - WIP [https://steamcommunity.com/sharedfiles/filedetails/?id=1635901197]
Combat Extended [https://steamcommunity.com/sharedfiles/filedetails/?id=1631756268]
Combat Extended Melee [https://steamcommunity.com/sharedfiles/filedetails/?id=1924933379]
Combat Extended Guns [https://steamcommunity.com/sharedfiles/filedetails/?id=1582570547]
Better Pawn Control [https://steamcommunity.com/sharedfiles/filedetails/?id=1541460369]
Quarry [https://steamcommunity.com/sharedfiles/filedetails/?id=2007576583]
Rimsenal - Core [https://steamcommunity.com/sharedfiles/filedetails/?id=725947920]
Mod Manager [https://steamcommunity.com/sharedfiles/filedetails/?id=1507748539]
Graphics Settings+ [https://steamcommunity.com/sharedfiles/filedetails/?id=1678847247]
JecsTools (Unofficial) [https://steamcommunity.com/sharedfiles/filedetails/?id=2195729899]
Allow Tool [https://steamcommunity.com/sharedfiles/filedetails/?id=761421485]
Humanoid Alien Races [https://steamcommunity.com/sharedfiles/filedetails/?id=839005762]
Androids [https://steamcommunity.com/sharedfiles/filedetails/?id=1541064015]
Avoid Friendly Fire [https://steamcommunity.com/sharedfiles/filedetails/?id=1134165362]
Camping Tent [https://steamcommunity.com/sharedfiles/filedetails/?id=2407128339]
Blueprints [https://steamcommunity.com/sharedfiles/filedetails/?id=708455313]
Centralized Climate Control (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2007268173]
CM Color Coded Mood Bar [1.1+] [https://steamcommunity.com/sharedfiles/filedetails/?id=2006605356]
Common Sense [https://steamcommunity.com/sharedfiles/filedetails/?id=1561769193]
Rimsenal - Federation Faction Pack [https://steamcommunity.com/sharedfiles/filedetails/?id=736172213]
Rimsenal - Security pack [https://steamcommunity.com/sharedfiles/filedetails/?id=736139206]
Rimsenal - Storyteller pack [https://steamcommunity.com/sharedfiles/filedetails/?id=725952322]
Achtung! [https://steamcommunity.com/sharedfiles/filedetails/?id=730936602]
Beautiful Outdoors [https://steamcommunity.com/sharedfiles/filedetails/?id=2011794898]
Revia Race [https://steamcommunity.com/sharedfiles/filedetails/?id=2020041005]
Change map edge limit [https://steamcommunity.com/sharedfiles/filedetails/?id=1546494565]
Character Editor [https://steamcommunity.com/sharedfiles/filedetails/?id=1874644848]
Subsurface Conduit [https://steamcommunity.com/sharedfiles/filedetails/?id=1609226728]
Cybernetic Organism and Neural Network [https://steamcommunity.com/sharedfiles/filedetails/?id=2045064990]
Tilled Soil [https://steamcommunity.com/sharedfiles/filedetails/?id=725747149]
Damage Indicators [1.3] [https://steamcommunity.com/sharedfiles/filedetails/?id=2016331497]
Defensive Positions [https://steamcommunity.com/sharedfiles/filedetails/?id=761219125]
Designator Shapes [https://steamcommunity.com/sharedfiles/filedetails/?id=1235181370]
Dire Raids [https://steamcommunity.com/sharedfiles/filedetails/?id=1542379675]
DontBlockDoor [https://steamcommunity.com/sharedfiles/filedetails/?id=1691076769]
Dubs Mint Menus [https://steamcommunity.com/sharedfiles/filedetails/?id=1446523594]
Dubs Mint Minimap [https://steamcommunity.com/sharedfiles/filedetails/?id=1662119905]
Dubs Performance Analyzer [https://steamcommunity.com/sharedfiles/filedetails/?id=2038874626]
Expanded Prosthetics and Organ Engineering - Forked [https://steamcommunity.com/sharedfiles/filedetails/?id=1949064302]
GlitterNet [https://steamcommunity.com/sharedfiles/filedetails/?id=1725544583]
Harvest Organs Post Mortem [https://steamcommunity.com/sharedfiles/filedetails/?id=1204502413]
Haul to Stack [https://steamcommunity.com/sharedfiles/filedetails/?id=949498803]
Locks [https://steamcommunity.com/sharedfiles/filedetails/?id=1157085076]
Yayo's Bank [https://steamcommunity.com/sharedfiles/filedetails/?id=2368878128]
Tattoos Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2569243583]
Interaction Bubbles [https://steamcommunity.com/sharedfiles/filedetails/?id=1516158345]
Just Ignore Me Passing [https://steamcommunity.com/sharedfiles/filedetails/?id=1231617602]
KanbanStockpile [https://steamcommunity.com/sharedfiles/filedetails/?id=2287142613]
Mad Skills [https://steamcommunity.com/sharedfiles/filedetails/?id=731111514]
HD Pawn Rendering [https://steamcommunity.com/sharedfiles/filedetails/?id=2538746878]
Range Finder [https://steamcommunity.com/sharedfiles/filedetails/?id=1332119637]
More Sculpture [https://steamcommunity.com/sharedfiles/filedetails/?id=1612316880]
Remote Tech [https://steamcommunity.com/sharedfiles/filedetails/?id=761379469]
Nals Facial Animation for HAR [https://steamcommunity.com/sharedfiles/filedetails/?id=2280607572]
Nano Repair Tech [https://steamcommunity.com/sharedfiles/filedetails/?id=1447372624]
No Lazy Doctors [https://steamcommunity.com/sharedfiles/filedetails/?id=2476396157]
OgreStack [https://steamcommunity.com/sharedfiles/filedetails/?id=1447140290]
Questionable Ethics Enhanced [https://steamcommunity.com/sharedfiles/filedetails/?id=2566962342]
Map Designer [https://steamcommunity.com/sharedfiles/filedetails/?id=2111424996]
Packs Are Not Belts [https://steamcommunity.com/sharedfiles/filedetails/?id=2509511179]
Perfect Pathfinding [https://steamcommunity.com/sharedfiles/filedetails/?id=2341486509]
Eccentric Tech - Core [https://steamcommunity.com/sharedfiles/filedetails/?id=2552623545]
Eccentric Tech - Cosmetic Modifications 2.0 [https://steamcommunity.com/sharedfiles/filedetails/?id=2552628984]
Eccentric Tech - Flares 2.0 [https://steamcommunity.com/sharedfiles/filedetails/?id=2552628275]
Eccentric Tech - Advanced Shields [https:// no link (local mod)]
Polarisbloc - Core LAB [https://steamcommunity.com/sharedfiles/filedetails/?id=1500244593]
Polarisbloc - Mechenemy [https://steamcommunity.com/sharedfiles/filedetails/?id=1498573216]
Worthless Junk [https://steamcommunity.com/sharedfiles/filedetails/?id=2574022829]
EvolvedOrgansRedux [https://steamcommunity.com/sharedfiles/filedetails/?id=2424381146]
Power++ [https://steamcommunity.com/sharedfiles/filedetails/?id=1771402217]
[KV] RimFridge [https://steamcommunity.com/sharedfiles/filedetails/?id=1180721235]
Quality Colors [https://steamcommunity.com/sharedfiles/filedetails/?id=2420141361]
QualityBuilder [https://steamcommunity.com/sharedfiles/filedetails/?id=754637870]
Quest Reward Rebalance [https://steamcommunity.com/sharedfiles/filedetails/?id=2312419897]
RT Fuse [https://steamcommunity.com/sharedfiles/filedetails/?id=728314182]
RT Solar Flare Shield [https://steamcommunity.com/sharedfiles/filedetails/?id=728315620]
Raise The Roof 1.3 [https://steamcommunity.com/sharedfiles/filedetails/?id=1776143665]
Replace Stuff [https://steamcommunity.com/sharedfiles/filedetails/?id=1372003680]
World Map Beautification Project [https://steamcommunity.com/sharedfiles/filedetails/?id=2314407956]
RimPy Mod Manager Database [https://steamcommunity.com/sharedfiles/filedetails/?id=1847679158]
Dubs Rimatomics [https://steamcommunity.com/sharedfiles/filedetails/?id=1127530465]
RimThemes [https://steamcommunity.com/sharedfiles/filedetails/?id=1668983184]
RimSaves [https://steamcommunity.com/sharedfiles/filedetails/?id=1713367505]
Rimefeller [https://steamcommunity.com/sharedfiles/filedetails/?id=1321849735]
Selectable Sculpture Graphic [https://steamcommunity.com/sharedfiles/filedetails/?id=1537873717]
Show Draftees Weapon [https://steamcommunity.com/sharedfiles/filedetails/?id=1690978457]
Simple sidearms [https://steamcommunity.com/sharedfiles/filedetails/?id=927155256]
SimplyMoreFloors [https://steamcommunity.com/sharedfiles/filedetails/?id=1639883955]
CyberNet [https://steamcommunity.com/sharedfiles/filedetails/?id=1725545225]
Medical System Expansion 2 [https://steamcommunity.com/sharedfiles/filedetails/?id=2056706586]
Smarter Construction [https://steamcommunity.com/sharedfiles/filedetails/?id=2202185773]
Sparkling Worlds - Full Mod [https://steamcommunity.com/sharedfiles/filedetails/?id=1123043922]
Sparkling Worlds CE Patch [1.0, 1.1, 1.2, 1.3] [https://steamcommunity.com/sharedfiles/filedetails/?id=2047410899]
Statue of Colonist [https://steamcommunity.com/sharedfiles/filedetails/?id=1539031321]
Statue Of Colonist Alien Race Patch [https://steamcommunity.com/sharedfiles/filedetails/?id=1846741408]
VFE-M: Add-On [https://steamcommunity.com/sharedfiles/filedetails/?id=2329025520]
VFE Mechanoids - Craftable Mechanoid Components (Alternative) [https://steamcommunity.com/sharedfiles/filedetails/?id=2351501245]
Wall Light [https://steamcommunity.com/sharedfiles/filedetails/?id=1423699208]
Traders Have Money [https://steamcommunity.com/sharedfiles/filedetails/?id=2022959333]
Camera+ [https://steamcommunity.com/sharedfiles/filedetails/?id=867467808]
What's That Mod [https://steamcommunity.com/sharedfiles/filedetails/?id=2258431182]
Where is my weapon? [https://steamcommunity.com/sharedfiles/filedetails/?id=1539028008]
Work Tab [https://steamcommunity.com/sharedfiles/filedetails/?id=725219116]
[FSF] Filth Vanishes With Rain And Time [https://steamcommunity.com/sharedfiles/filedetails/?id=1508341791]
RimBank (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2071695947]
Ameiro anime hairs [https://steamcommunity.com/sharedfiles/filedetails/?id=1207934602]
[SR]Factional War [https://steamcommunity.com/sharedfiles/filedetails/?id=2534328163]
Show Me Your Hands [https://steamcommunity.com/sharedfiles/filedetails/?id=2475965842]
[RH2] BCD: CASEVAC [https://steamcommunity.com/sharedfiles/filedetails/?id=2563153311]
Project RimFactory Revived [https://steamcommunity.com/sharedfiles/filedetails/?id=2033979700]
Beautiful Bodies [https://steamcommunity.com/sharedfiles/filedetails/?id=2068281501]
Gloomy Hair mk2 [https://steamcommunity.com/sharedfiles/filedetails/?id=1870678335]
Polyamory Beds (Vanilla Edition) [https://steamcommunity.com/sharedfiles/filedetails/?id=2008138191]
Realistic Rooms Rewritten [https://steamcommunity.com/sharedfiles/filedetails/?id=2558042766]
Eccentric Tech - Foxy's Armory 2.0 [https://steamcommunity.com/sharedfiles/filedetails/?id=2552628608]
Pick Up And Haul [https://steamcommunity.com/sharedfiles/filedetails/?id=1279012058]
While You're Up / PUAH+ [https://steamcommunity.com/sharedfiles/filedetails/?id=2034960453]
Perspective: Doors [https://steamcommunity.com/sharedfiles/filedetails/?id=2567126933]
Perspective: Trees [https://steamcommunity.com/sharedfiles/filedetails/?id=2572022990]
RimHUD [https://steamcommunity.com/sharedfiles/filedetails/?id=1508850027]
Recipe icons [https://steamcommunity.com/sharedfiles/filedetails/?id=1616643195]
Eccentric Tech - Angel Apparel [https:// no link (local mod)]
Eyes back to 1.2! [https://steamcommunity.com/sharedfiles/filedetails/?id=2538702875]
Fortifications - Industrial [https://steamcommunity.com/sharedfiles/filedetails/?id=2561619583]
Share The Load [https://steamcommunity.com/sharedfiles/filedetails/?id=2576277142]
[WD] Fast Moisture Pumps [https://steamcommunity.com/sharedfiles/filedetails/?id=1164753788]
[WD] Realistic Darkness [https://steamcommunity.com/sharedfiles/filedetails/?id=1531882210]
Guards For Me [https://steamcommunity.com/sharedfiles/filedetails/?id=1855885448]
[FSF] Better Camp Loot [https://steamcommunity.com/sharedfiles/filedetails/?id=2584485274]
Auto-Cut Blight [https://steamcommunity.com/sharedfiles/filedetails/?id=1885186534]
RunAndGun [https://steamcommunity.com/sharedfiles/filedetails/?id=1204108550]
Comigo's Nutrition [https://steamcommunity.com/sharedfiles/filedetails/?id=2546863371]
Skilled Stonecutting [1.3] [https://steamcommunity.com/sharedfiles/filedetails/?id=2553698129]
Pawns Just Don't Die [https://steamcommunity.com/sharedfiles/filedetails/?id=2239397152]
Dubs Apparel Tweaks [https://steamcommunity.com/sharedfiles/filedetails/?id=2296697286]
Cash Register [https://steamcommunity.com/sharedfiles/filedetails/?id=2506046833]
Gastronomy [https://steamcommunity.com/sharedfiles/filedetails/?id=2279786905]
RimJobWorld [https:// no link (local mod)]
RimThreaded [https://steamcommunity.com/sharedfiles/filedetails/?id=2222907981]

**Comment by Sernior** [comment]
this one was fixed by my last pr
