### ISSUE TITLE
Ideology image alert error

### ISSUE THREAD

**Issue by sealvessel** [cseelhoff/RimThreaded#671]
- [ ] Reproduce the issue with RT
- [ ] Try to Reproduce the issue without RT
- [ ] Find out if its RT or an other issue. (probably load order or similar issue)
- [ ] Fix (if related to RT)

### **Describe the bug**
Having Ideology, Hugslib and this mod it creates a flurry of errors whenever hovering over the "ideology image" desired alert. 

### **Steps to reproduce the behavior (VERY IMPORTANT)**
1. Hover over the "Ideology image" when starting a new game. 
### **Error Logs**
Root level exception in OnGUI(): System.NullReferenceException: Object reference not set to an instance of an object
  at RimWorld.IdeoBuildingPresenceDemand.get_RoomRequirementsInfo () [0x00091] in <0449c5e9b8de427094b45999bcad39f5>:0 
  at RimWorld.Alert_IdeoBuildingMissing.GetExplanation () [0x0004e] in <0449c5e9b8de427094b45999bcad39f5>:0 
  at RimWorld.Alert.DrawInfoPane () [0x00023] in <0449c5e9b8de427094b45999bcad39f5>:0 
  at (wrapper dynamic-method) RimWorld.AlertsReadout.RimWorld.AlertsReadout.AlertsReadoutOnGUI_Patch1(RimWorld.AlertsReadout)
  at (wrapper dynamic-method) RimWorld.UIRoot_Play.RimWorld.UIRoot_Play.UIRootOnGUI_Patch1(RimWorld.UIRoot_Play)
  at (wrapper dynamic-method) Verse.Root.Verse.Root.OnGUI_Patch1(Verse.Root)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch2 (string)
(wrapper dynamic-method) Verse.Root:Verse.Root.OnGUI_Patch1 (Verse.Root)(edited)
#### **Player.log**
https://ghostbin.com/sseVQ

#### **HugsLib log**
https://gist.github.com/33fdd01695b2f1a526f7a55bcb303c0c

### **Save file**
Just make a new save with alerts and an ideology which requires an image. 

### **Screenshots**
![image](https://user-images.githubusercontent.com/66351949/133878448-37474e0c-ddb0-4ae0-b26c-38938715e423.png)

### **Mod list (For vanilla report, it has to be same as below list.)**
* Harmony
* Core
* Royalty (Optional)
* Ideology (Optional)
* HugsLib
* RimThreaded

**Comment by sealvessel** [comment]
Note that this only works on the default archotech ideology grand sculpture image, that is the wooden grand sculpture named "Archotech Image." This error also spams upon hovering the item in the ideology customize ideologion menu before starting the game. I can give an example partial screen recording tomorrow.

**Comment by Niilo007** [comment]
I was unable to get any errors with the info provided, possible because this is fixed in 2.5.16
![image](https://user-images.githubusercontent.com/75486261/135123649-132e520d-8a41-4da8-817a-e92fd09d59ff.png)

**Comment by sealvessel** [comment]
Its fixed, I hover over it and on the latest version from the discord server, nothing happens. I have made alot of new colonies for testing and have an image, and none had errors from hovering over a persistent letter.
