### ISSUE TITLE
[UI Not Included: Customizable UI Overhaul] Possible rimthreaded conflict with ui not included

### ISSUE THREAD

**Issue by Hellcommander** [cseelhoff/RimThreaded#714]
## **IMPORTANT:**  
**Please first search existing bugs to ensure you are not creating a duplicate bug report!**   
**Make sure you have the latest version of Rimworld!**  

### **Describe the bug**
!!! bug description here !!!
https://steamcommunity.com/sharedfiles/filedetails/?id=2588873455
### **Steps to reproduce the behavior (VERY IMPORTANT)**
1. Add ui not included to modlist
2. sort with rimPy and save
3. start game
4. check player.log for potential Rimthreaded conflicts
5. find   ---Patch method: RimThreaded.Messages_Patch Boolean MessagesDoGUI()---
  RimThreaded priority: 0
  owner: GonDragon.UINotIncluded -   priority: 400**

#### **Player.log**
https://www.dropbox.com/s/zrfwrgp5ugfwvmi/Player.log?dl=0
#### **HugsLib log**
https://gist.github.com/752608dffb4ff92b0868d55f41b11eed

### **Save file**
No need

### **Screenshots**
in the log so screenshots would be useless (not even as error as far as error log showing or not just a warning)

### **Mod list (Preferably a RimPy compatible list.)**
<?xml version="1.0" encoding="utf-8"?>
<ModsConfigData>
    <version>1.3.3159 rev754</version>
    <activeMods>
        <li>brrainz.harmony</li>
        <li>me.samboycoding.betterloading</li>
        <li>ludeon.rimworld</li>
        <li>ludeon.rimworld.royalty</li>
        <li>ludeon.rimworld.ideology</li>
        <li>unlimitedhugs.hugslib</li>
        <li>saucypigeon.pawnbadge</li>
        <li>pawnbadges.byt</li>
        <li>mlie.apetitionforprovisions</li>
        <li>telefonmast.graphicssettings</li>
        <li>jecrell.jecstools</li>
        <li>torann.arimworldofmagic</li>
        <li>netzachsloth.arimworldofmagic.blackguardclass</li>
        <li>netzachsloth.arom.dreadlich</li>
        <li>netzachsloth.arimworldofmagic.dreadnecromancerclass_copy_copy</li>
        <li>netzachsloth.arimworldofmagic.elementalshamanclass_copy</li>
        <li>netzachsloth.arimworldofmagic.jackofshadowsclass</li>
        <li>netzachsloth.arimworldofmagic.magitekcommanderclass_copy</li>
        <li>netzachsloth.arom.psioniclich</li>
        <li>netzachsloth.arimworldofmagic.adventurerclass_copy</li>
        <li>georodin.cooldownindicator</li>
        <li>airetexture.core</li>
        <li>mlie.advancedbiomes</li>
        <li>nals.facialanimation</li>
        <li>erdelf.humanoidalienraces</li>
        <li>chjees.androids</li>
        <li>sdknm2.beautyandugly</li>
        <li>automatic.bionicicons</li>
        <li>atomicravioli.crystalloid</li>
        <li>dubwise.dubsbadhygiene</li>
        <li>dianawinters.orassans</li>
        <li>mlie.rimwriter</li>
        <li>rimsenal.hair</li>
        <li>orion.xevarimhair</li>
        <li>airetexture.mods</li>
        <li>activated.carbon</li>
        <li>mlie.activeresponsetraining</li>
        <li>solaris.additionalverbmod</li>
        <li>ogliss.admech.armoury</li>
        <li>jp.adjacentlight</li>
        <li>praedon.adjustarchonexus</li>
        <li>pointfeev.storagefilters</li>
        <li>saloid.advancedraiders</li>
        <li>ali.biggeranimalboxes</li>
        <li>baalevan.allturretscansetforcedtarget</li>
        <li>mehni.allyourbase</li>
        <li>whatamidoing.adjacentsettlements</li>
        <li>z4k97b.altarsinthroneroom</li>
        <li>roolo.almostthere</li>
        <li>oskarpotocki.vanillafactionsexpanded.core</li>
        <li>sarg.alphabiomes</li>
        <li>zylle.alphabiomesmatscompat</li>
        <li>robogerbil.mycoticjunglevegetationpatch</li>
        <li>vanillaexpanded.vee</li>
        <li>kentington.saveourship2</li>
        <li>sarg.alphaships</li>
        <li>thegoofyone.amazonianriver</li>
        <li>dekeche.androidconversion</li>
        <li>android.bodies2</li>
        <li>peptide.androidsexpanded</li>
        <li>jelly.aeff</li>
        <li>jelly.aerancher</li>
        <li>animafruit.velcroboy333</li>
        <li>xrushha.animagear</li>
        <li>avilmask.animalcontrols</li>
        <li>dylan.animalgear</li>
        <li>owlchemist.animalgear.equipment</li>
        <li>mlie.animalfeedtrough</li>
        <li>cucumpear.flap</li>
        <li>mlie.animalhusbandryraids</li>
        <li>neceros.animalmedicalbed</li>
        <li>onceupon2635.animalnamer</li>
        <li>fluffy.animaltab</li>
        <li>vanillaexpanded.vtexe</li>
        <li>cucumpear.azrael.varietycoats</li>
        <li>dorsai.animalsaresmart</li>
        <li>simmin.animalsforage</li>
        <li>mlie.animalsforagepatches</li>
        <li>vanillaexpanded.vfeproduction</li>
        <li>arcjc007.wallstuff</li>
        <li>arcjc007.walldefenses</li>
        <li>scorpio.core</li>
        <li>gguake.apparelbodyresolver</li>
        <li>mlie.apparelorganizer</li>
        <li>dimonsever000.appareltab.specific</li>
        <li>mlie.arrowplease</li>
        <li>4ydra.arsenalofideology</li>
        <li>pipai.artreroll</li>
        <li>dizzy.neolithicweaponart</li>
        <li>carnagion.artifactsexpanded</li>
        <li>nercury.assignanimalfood</li>
        <li>slimesenpai.autovents</li>
        <li>ben.automaticnightowl</li>
        <li>yoann.babiesanimals</li>
        <li>mlie.backupgenerators</li>
        <li>fluffy.backuppower</li>
        <li>mlie.badleathercategory</li>
        <li>mlie.badmeatcategory</li>
        <li>neceros.balancedeclipseandsolarflare</li>
        <li>vanillaexpanded.vfearchitect</li>
        <li>yoann.balancedfloorsmarketvalue</li>
        <li>sk.bandagewrap</li>
        <li>vanillaexpanded.achievements</li>
        <li>scurvyez.bastyon</li>
        <li>hmd.battledroidarmors</li>
        <li>meltup.beautifuloutdoors</li>
        <li>mlie.beautyfloors</li>
        <li>bedrestforfoodpoisoning.1trickponyta</li>
        <li>lbmaian.begonemessage</li>
        <li>vanillaexpanded.vfepropsanddecor</li>
        <li>sarg.alphaanimals</li>
        <li>vanillaexpanded.vbookse</li>
        <li>vanillaexpanded.vcooke</li>
        <li>vanillaexpanded.vcef</li>
        <li>vanillaexpanded.vmemese</li>
        <li>me.lubar.vanillabooksexpandedexpanded</li>
        <li>mlie.bestmix</li>
        <li>captainmuscles.coolandgoodambush</li>
        <li>ender.bettertableeat</li>
        <li>legodude17.bba</li>
        <li>nesi.scaledagereversal</li>
        <li>nephlite.advexplosions</li>
        <li>betterhearingmatters.choosechee</li>
        <li>machine.betterinfestations</li>
        <li>madeline.modmismatchformatter</li>
        <li>aelanna.betterpyromania</li>
        <li>lperkins2.bri</li>
        <li>mlie.betterrecordstab</li>
        <li>wphant0m.patch.bettersos2holograms</li>
        <li>bettertalkingmatters.choosechee</li>
        <li>netrve.bettertime</li>
        <li>jm.bettertraders</li>
        <li>owlchemist.bettervanillamasking</li>
        <li>innias.betterwallsandfloors</li>
        <li>falconne.bwm</li>
        <li>sirrandoo.bettersliders</li>
        <li>antaioz.bettervents</li>
        <li>archiev.betterweight</li>
        <li>vanillaexpanded.vbrewe</li>
        <li>fluffysminion.itw.caveworldfloraunleashed</li>
        <li>odeum.wmbp</li>
        <li>biomesteam.biomescore</li>
        <li>biomesteam.oasis</li>
        <li>mic.oasisaapatch</li>
        <li>jexa.blindsightworks</li>
        <li>izzimon.blooddries</li>
        <li>ogliss.dalrae.bloodpack</li>
        <li>mlie.blowguns</li>
        <li>chippedchap.blueprinttotalstooltip</li>
        <li>fluffy.blueprints</li>
        <li>murmur.bodypartsrot</li>
        <li>procrastinus.boiledeggs</li>
        <li>mlie.boommodexpanded</li>
        <li>techmago.bootsnstuff</li>
        <li>deon.borderlandsstorytellers</li>
        <li>bs.mbifvte</li>
        <li>vanillaexpanded.vfecore</li>
        <li>vanillaexpanded.vfespacer</li>
        <li>anon.vanillaembrasures</li>
        <li>calamabanana.breachableembrasures</li>
        <li>mosi.bridgecolor</li>
        <li>shinzy.bridgello</li>
        <li>mlie.brrandphew</li>
        <li>nercury.bugcracks</li>
        <li>vanya.tools.bulkcarrier</li>
        <li>butihave.rw</li>
        <li>mrhacky.butcherycountsmeattypes</li>
        <li>mlie.camouflageandstealth</li>
        <li>mlie.cascataphractarmour</li>
        <li>mlie.casflakarmour</li>
        <li>mlie.caspowerarmour</li>
        <li>cucumpear.mentalbreaks</li>
        <li>8z.callforintel</li>
        <li>brrainz.cameraplus</li>
        <li>aoba.tent</li>
        <li>cannibalideologieswillwearhumanleather.1trickponyta</li>
        <li>mlie.cannibalmeals</li>
        <li>iforgotmysocks.caravanadventures</li>
        <li>caravanjourneyspot.leeh</li>
        <li>nowano.caravanentrypoint</li>
        <li>reiquard.caravancolonistinfo</li>
        <li>proxyer.caravanpackingspotfix</li>
        <li>caravansrestbeforearrival.1trickponyta</li>
        <li>brrainz.carefulraids</li>
        <li>stallion.cartographersicons</li>
        <li>fluffykittens.billcategories</li>
        <li>captainmuscles.categorizedbills</li>
        <li>mrchimick.cattlegate</li>
        <li>mlie.caveworldflora</li>
        <li>mlie.cavebiome</li>
        <li>dhultgren.changecaravanloadout</li>
        <li>5katz.commschat</li>
        <li>owlchemist.cherrypicker</li>
        <li>captainmuscles.chillout</li>
        <li>oskarpotocki.vfe.insectoid</li>
        <li>stevezero.chitinmatters</li>
        <li>mlie.choosebiomecommonality</li>
        <li>owlchemist.cleanpathfinding</li>
        <li>mlie.cleaningpriority</li>
        <li>mlie.colddesertnights</li>
        <li>derekbickley.ltocolonygroupsfinal</li>
        <li>derekbickley.ltocguirimworld</li>
        <li>martinbaste.rimworld.combinefaceitems</li>
        <li>comigogames.water.bridges</li>
        <li>mlie.commonailments</li>
        <li>onegative.communicablediseases</li>
        <li>qux.onegative.communicablediseases</li>
        <li>petetimessix.compacthediffs</li>
        <li>vanillaexpanded.vbrewecandt</li>
        <li>oskarpotocki.vfe.mechanoid</li>
        <li>vanillaexpanded.vfepower</li>
        <li>vanillaexpanded.vfesecurity</li>
        <li>roolo.whatthehack</li>
        <li>frozensnowfox.complexjobs</li>
        <li>syrchalis.prosthetictable</li>
        <li>ljsmith.complexjobs_prosthetictable_patch</li>
        <li>dimonsever000.connortp.specific</li>
        <li>tikubonn.corpsetab</li>
        <li>katavrik.crashlanding</li>
        <li>uuugggg.crazycatlady</li>
        <li>sk.crudebionics</li>
        <li>georodin.deepdrillindicator</li>
        <li>proxyer.desurgeries.hardcolor</li>
        <li>proxyer.desurgeries.alphaanimalpatch</li>
        <li>proxyer.desurgeries.dbhpatch</li>
        <li>dubwise.dubscentralheating</li>
        <li>zylle.ducks</li>
        <li>heis.edo.themed.expansion</li>
        <li>trickity.samurai.faction</li>
        <li>heis.edo.themed.expansion.redundancy.patch</li>
        <li>erin.hairredux</li>
        <li>statistno1.evolvedorgansredux</li>
        <li>unlimitedhugs.allowtool</li>
        <li>merthsoft.expandedcontextmenus</li>
        <li>oskarpotocki.vanillafactionsexpanded.settlersmodule</li>
        <li>vanillaexpanded.vwec</li>
        <li>vanillaexpanded.vwe</li>
        <li>vanillaexpanded.vwehw</li>
        <li>vanillaexpanded.vweq</li>
        <li>vanillaexpanded.vweft</li>
        <li>argon.vmeu</li>
        <li>gamingtesh.emp</li>
        <li>vanillasky.crystalloidfa</li>
        <li>vanillasky.humanfa</li>
        <li>vanillasky.orassansfa</li>
        <li>sineswiper.factionblender</li>
        <li>murmur.factionraidcooldown</li>
        <li>karmgahl.factioncustomizer</li>
        <li>denneisk.factorialrange</li>
        <li>georodin.finecuisine</li>
        <li>warlocksforge.fishtraps</li>
        <li>me.lubar.fixedideostyle</li>
        <li>mayo.noideologybs</li>
        <li>nals.facialanimationexperimentals</li>
        <li>laast.girlyfacialanim.fr</li>
        <li>ancientgammoner.groundtargeter</li>
        <li>arandomkiwi.guardsforme</li>
        <li>thanderhall.gfmwthcompat</li>
        <li>automatic.hairdye</li>
        <li>arquebus.hotseat</li>
        <li>flashpoint55.humanpowergeneratormod</li>
        <li>jgh.humangenerator</li>
        <li>com.yayo.propaganda</li>
        <li>mlie.jecshuntingwithtraps</li>
        <li>dark.jobinbar</li>
        <li>kit.powerprotein</li>
        <li>kure.arom</li>
        <li>limetreesnake.ammunition</li>
        <li>bblkepling.ltsammoroyalkits</li>
        <li>bblkepling.ltsammoturretsuseammo</li>
        <li>imranfish.xmlextensions</li>
        <li>bblkepling.ltsharautopatcher</li>
        <li>sztorno.liquidtanks</li>
        <li>smashphil.loadinginprogress</li>
        <li>sarg.magicalmenagerie</li>
        <li>laast.manlyfacialanim.fr</li>
        <li>flashpoint55.mentalshieldcrystal</li>
        <li>compilatron.minecarts</li>
        <li>erdelf.minifyeverything</li>
        <li>moonjelly.race.mod</li>
        <li>daemon976.moreandroidstories</li>
        <li>mlie.morefactioninteraction</li>
        <li>purpleyam.moreideologicalwords</li>
        <li>llunak.moreprecepts</li>
        <li>kirby.morereligiousorigins</li>
        <li>mlie.mountainminer</li>
        <li>thevillageguy.mousetraps.1</li>
        <li>nackbladinc.rimhair</li>
        <li>daemon976.facialanimationplus</li>
        <li>amch.needbaroverflow</li>
        <li>slashandz.noincreasedexpectationsforideologyroles</li>
        <li>ed86.nocaravanabandon</li>
        <li>simmin.omnivorousducks</li>
        <li>com.bymarcin.architecticons</li>
        <li>proxyer.optionalicons4ai</li>
        <li>apatheticslug.orbitalbionicstrader</li>
        <li>outfit.builder.redux</li>
        <li>supes.parallelpowergrid</li>
        <li>ttr.parallelpowergridaddon</li>
        <li>psyra.miscpawnbadgerevitalized</li>
        <li>fed1splay.pawntargetfix</li>
        <li>solidwires.pawnkindracediversification</li>
        <li>owlchemist.permeableterrain</li>
        <li>hahkethomemah.simplepersonalities</li>
        <li>hahkethomemah.simplepersonalities.serious</li>
        <li>owlchemist.perspectivebuildings</li>
        <li>thomotron.phinix</li>
        <li>gargamiel.pokeworld</li>
        <li>meltup.polyamorybeds.vanilla</li>
        <li>thesepeople.ritualattachableoutcomes</li>
        <li>zezz.pandm</li>
        <li>zezz.pandm.rituals</li>
        <li>laast.pupilfacialanim.fr</li>
        <li>rebelrabbit.qualitybionics</li>
        <li>sdknm2.qualityofbuilding</li>
        <li>hatti.qualitybuilder</li>
        <li>jgh.qualitybuilder</li>
        <li>22.mf</li>
        <li>goudaquiche.moharframework</li>
        <li>metalocif.bluemage</li>
        <li>ahndemi.racesleepfaceaddon2</li>
        <li>rah.rbse</li>
        <li>rah.rvte</li>
        <li>automatic.recipeicons</li>
        <li>mlie.refactoredworkpriorities</li>
        <li>legodude17.heavyweaponsreloading</li>
        <li>legodude17.rocketreloading</li>
        <li>vinalx.researchpalforked</li>
        <li>lordfanger.rimlanguagehotreload</li>
        <li>sera.apinialienrace</li>
        <li>sarg.rimbees</li>
        <li>seblivion.rimbeesbiomepatches</li>
        <li>miki4920.rimdungeontraps</li>
        <li>sargoskar.witcherhunt</li>
        <li>k.psitech</li>
        <li>ironxides.royaltypsitechmerger</li>
        <li>seohyeon.bestdrugpolicy</li>
        <li>kentington.saveloadideo</li>
        <li>imranfish.shortbowsrequireresearch</li>
        <li>blues.shortcircuit</li>
        <li>razar1.skrixrace</li>
        <li>taoschagic.sliperyicetrap</li>
        <li>marvinkosh.sometimesraidsgowrong</li>
        <li>tammybee.statueofcolonist</li>
        <li>tammybee.statueofcolonist.alienracepatch</li>
        <li>crazedmonkey23.armormaterials</li>
        <li>tikubonn.surveillancecamera</li>
        <li>eastern.armory.geminingen</li>
        <li>trickity.samurai.faction.easternarmorypatch</li>
        <li>trickity.samurai.faction.morereligiousoriginspatch</li>
        <li>mlie.tacticalablativearmor</li>
        <li>qux.tattoos</li>
        <li>laast.threatfacialanim.fr</li>
        <li>error277.tunneler.expanded</li>
        <li>beast.ultimatestoryteller</li>
        <li>cnnuclear.betterassetbundlesloader</li>
        <li>vanillaexpanded.vaeas</li>
        <li>vanillaexpanded.vaeau</li>
        <li>vanillaexpanded.vaebf</li>
        <li>vanillaexpanded.vaecaves</li>
        <li>vanillaexpanded.vaed</li>
        <li>vanillaexpanded.vaeendandext</li>
        <li>vanillaexpanded.vaeed</li>
        <li>vanillaexpanded.vaeis</li>
        <li>vanillaexpanded.vaetf</li>
        <li>vanillaexpanded.vaetr</li>
        <li>vanillaexpanded.vaets</li>
        <li>vanillaexpanded.vaet</li>
        <li>vanillaexpanded.vappe</li>
        <li>vanillaexpanded.varme</li>
        <li>thegoofyone.vanillabrewingexpandednerfed</li>
        <li>vanillaexpanded.vcookestews</li>
        <li>vanillaexpanded.vcookesushi</li>
        <li>oskarpotocki.vanillaexpanded.ideologypatches</li>
        <li>legodude17.vfemechscp</li>
        <li>oskarpotocki.vfe.vikings</li>
        <li>cobalt.vfevikings.balancepatch</li>
        <li>vanillaexpanded.vfeart</li>
        <li>mrkociak.rainbowholonew</li>
        <li>vanillaexpanded.vfefarming</li>
        <li>vanillaexpanded.vfemedical</li>
        <li>vanillaexpanded.vhe</li>
        <li>vanillaexpanded.viehar</li>
        <li>vanillaexpanded.ideo.iconsandsymbols</li>
        <li>vanillaexpanded.ideo.relicsandartifacts</li>
        <li>vanillaexpanded.viesas</li>
        <li>vanillaexpanded.vplantse</li>
        <li>vanillaexpanded.vplantsesucculents</li>
        <li>vse.diegoindustrial</li>
        <li>vse.perrypersistent</li>
        <li>vanillaexpanded.vanillatraitsexpanded</li>
        <li>vanillaexpanded.vweg</li>
        <li>vanillaexpanded.vwenl</li>
        <li>vv.vituvisek</li>
        <li>relaxedotter.wearwhatyouwant</li>
        <li>uuugggg.whatismypurpose</li>
        <li>mrkociak.morewthmechimplants</li>
        <li>fluffykittens.whatthepatch</li>
        <li>kikohi.whatsforsale</li>
        <li>eagle0600.dresspatients</li>
        <li>lilscoot.wheelchairs</li>
        <li>the1nk.workgroups</li>
        <li>carolusclen.dlc.wmbp.abc</li>
        <li>carolusclen.dlc.wmbp</li>
        <li>zylle.morevanillabiomes</li>
        <li>carolusclen.dlc.wmbp.mvb</li>
        <li>sjaak31367.zoologicaltradercaravans</li>
        <li>vanillaexpanded.vaeaccessories</li>
        <li>vanillaexpanded.vwetb</li>
        <li>fuu.uncompromisingtribalfaction</li>
        <li>jpt.trapsgowet</li>
        <li>kirby.droppodsarespacertech</li>
        <li>calltradeships.kv.rw</li>
        <li>showhair.kv.rw</li>
        <li>kyd.coveryournose</li>
        <li>kittahkhan.grazeup</li>
        <li>kittahkhan.justafleshwound</li>
        <li>ladycookie.vteexpansion</li>
        <li>derekbickley.cgsmallui</li>
        <li>neronix17.ancient.decon</li>
        <li>mlie.rfrumorhasit</li>
        <li>rh2.bcd.casevac</li>
        <li>rh2.bcd.first.aid</li>
        <li>rh2.cpers.arrest.here</li>
        <li>rh2.handtohand</li>
        <li>sr.modrimworld.factionalwar</li>
        <li>rabisquare.realisticoregeneration</li>
        <li>mlie.ssraiderscanswim</li>
        <li>bjis.lovelyhairstyle</li>
        <li>syrchalis.harvestyieldpatch</li>
        <li>syrchalis.naga</li>
        <li>syrchalis.processor.framework</li>
        <li>wemd.fueledheaters</li>
        <li>wemd.handsarenotoutside</li>
        <li>wemd.materialsforcoolers</li>
        <li>wemd.materialsforvents</li>
        <li>wemd.realisticdarknesslight</li>
        <li>mlie.xndadrenaline</li>
        <li>mlie.xndwatermilltweaks</li>
        <li>poet.ddexpandedcollection</li>
        <li>mlie.sdbridges</li>
        <li>rim.job.world</li>
        <li>majorhoff.rimthreaded.experimental</li>
    </activeMods>
    <knownExpansions>
        <li>ludeon.rimworld</li>
        <li>ludeon.rimworld.royalty</li>
        <li>ludeon.rimworld.ideology</li>
    </knownExpansions>
</ModsConfigData>

**Comment by Niilo007** [comment]
You can ignore that warning if there is no gameplay impact, and if everything works correctly

**Comment by Niilo007** [comment]
Re open this issue if you notice some sort of gameplay impact
