### ISSUE TITLE
[Dub's bad hygiene] More than 1 pipe comp in the same cell at (x, y)

### ISSUE THREAD

**Issue by sealvessel** [cseelhoff/RimThreaded#718]
### **Describe the bug**
More than 1 pipe comp when ship hull is destroyed

### **Error Logs**
```c
More than 1 pipe comp in the same cell at (143, 0, 105), things with pipes cannot overlap!
System.ArgumentException: An item with the same key has already been added. Key: (143, 0, 105)
  at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x000c1] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at DubsBadHygiene.HygienePipeMapComp.RebuildPipeGrid (System.Int32 P) [0x00122] in <b304e300710b43ab89482da7df6e86f3>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch2 (string)
DubsBadHygiene.HygienePipeMapComp:RebuildPipeGrid (int)
DubsBadHygiene.HygienePipeMapComp:RegenGrids ()
DubsBadHygiene.Patches.HarmonyPatches_Plumbing:GridRegen_Prefix (Verse.Map)
(wrapper dynamic-method) Verse.Map:Verse.Map.MapUpdate_Patch3 (Verse.Map)
(wrapper dynamic-method) Verse.Game:Verse.Game.UpdatePlay_Patch3 (Verse.Game)
(wrapper dynamic-method) Verse.Root_Play:Verse.Root_Play.Update_Patch0 (Verse.Root_Play)
```
#### **Player.log**
!!! Link to contents of Player.log or Error.log (MUST BE LINK) !!!  
#### **HugsLib log**
https://gist.github.com/307c67cd58fc07be120462871ecc5f51

### **Save file**
!!! Please add a save file where the issue occurs to speed up testing and fixing of the issue !!!

### **Screenshots**

https://user-images.githubusercontent.com/66351949/141716319-bfc9d3b6-8286-4652-8d5f-0990fe8d7786.mov

### **Mod list (Preferably a RimPy compatible list.)**
* Harmony
* Core
* Royalty (Optional)
* Ideology (Optional)
* HugsLib
li>automatic.startupimpact</li>
    <li>telefonmast.graphicssettings</li>
    <li>edb.preparecarefully</li>
    <li>void.charactereditor</li>
    <li>oskarpotocki.vanillafactionsexpanded.core</li>
    <li>haplo.miscellaneous.core</li>
    <li>haplo.miscellaneous.robots</li>
    <li>alaestor.miscrobots.plusplus</li>
    <li>oskarpotocki.vfe.mechanoid</li>
    <li>uuugggg.tdpack</li>
    <li>roolo.runandgun</li>
    <li>roolo.searchanddestroy</li>
    <li>roolo.dualwield</li>
    <li>zylle.mapdesigner</li>
    <li>ykara.epoe</li>
    <li>taranchuk.archotechplus</li>
    <li>gondragon.uinotincluded</li>
    <li>owlchemist.toggleableoverlays</li>
    <li>lwm.deepstorage</li>
    <li>legodude17.smartdecon</li>
    <li>vanillaexpanded.vcooke</li>
    <li>seohyeon.optimizationmeats</li>
    <li>owlchemist.barelyvisiblespots</li>
    <li>owlchemist.bettervanillamasking</li>
    <li>owlchemist.moonlight</li>
    <li>owlchemist.wallutilities</li>
    <li>owlchemist.perspectivebuildings</li>
    <li>owlchemist.perspectivetrees</li>
    <li>vanillaexpanded.vbrewecandt</li>
    <li>vanillaexpanded.vfeproduction</li>
    <li>oskarpotocki.vanillaexpanded.royaltypatches</li>
    <li>vanillaexpanded.vfecore</li>
    <li>vanillaexpanded.vfepower</li>
    <li>kentington.saveourship2</li>
    <li>uuugggg.replacestuff</li>
    <li>garethp.replacestuffcompatibility</li>
    <li>owlchemist.simplefx.smoke2</li>
    <li>owlchemist.ceilingutilities</li>
    <li>owlchemist.smartfarming</li>
    <li>owlchemist.windows</li>
    <li>fluffy.animaltab</li>
    <li>fluffy.areaunlocker</li>
    <li>fluffy.backuppower</li>
    <li>fluffy.blueprints</li>
    <li>fluffy.medicaltab</li>
    <li>fluffy.musicmanager</li>
    <li>fluffy.pharmacist</li>
    <li>fluffy.worktab</li>
    <li>dubwise.dubsappareltweaks</li>
    <li>dubwise.dubsmintmenus</li>
    <li>dubwise.dubsmintminimap</li>
    <li>dubwise.dubspaintshop</li>
    <li>arandomkiwi.rimsaves</li>
    <li>telardo.dragselect</li>
    <li>unlimitedhugs.allowtool</li>
    <li>madarauchiha.custommapsizes</li>
    <li>voult.betterpawncontrol</li>
    <li>automatic.bionicicons</li>
    <li>chippedchap.blueprinttotalstooltip</li>
    <li>brrainz.cameraplus</li>
    <li>dubwise.dubsbadhygiene</li>
    <li>sumghai.replimat</li>
    <li>sumghai.medpod</li>
    <li>steaplay.constructvanillarockwalls</li>
    <li>unlimitedhugs.defensivepositions</li>
    <li>merthsoft.designatorshapes</li>
    <li>vanillaexpanded.vfefarming</li>
    <li>vanillaexpanded.vfesecurity</li>
    <li>vanillaexpanded.vfespacer</li>
    <li>owlchemist.cleanpathfinding</li>
    <li>owlchemist.permeableterrain</li>
    <li>frozensnowfox.improvedvanometricpowercells</li>
    <li>frozensnowfox.nodefaultshelfstorage</li>
    <li>frozensnowfox.growableambrosia</li>
    <li>frozensnowfox.filthvanisheswithrainandtime</li>
    <li>frozensnowfox.betterancientcomplexloot</li>
    <li>frozensnowfox.bettercamploot</li>
    <li>frozensnowfox.growablegrass</li>
    <li>frozensnowfox.efficientutilities</li>
    <li>sgc.quests</li>
    <li>mlie.giveupyourbuilding</li>
    <li>mlie.nomoreautoroof</li>
    <li>mlie.weaponssorter</li>
    <li>mlie.scenarioamender</li>
    <li>sarg.smartspeed</li>
    <li>neptimus7.homearearadius</li>
    <li>falconne.heatmap</li>
    <li>notfood.mendandrecycle</li>
    <li>modsyncrw.kv.rw</li>
    <li>com.github.alandariva.moreplanning</li>
    <li>ogre.ogrestack</li>
    <li>jaxe.reorderer</li>
    <li>cp.rimdeed</li>
    <li>cabbage.rimcities</li>
    <li>jaxe.rimhud</li>
    <li>denev.smartturretcovering</li>
    <li>ratys.rtfuse</li>
    <li>ratys.rtpowerswitch</li>
    <li>ratys.rtsolarflareshield</li>
    <li>neceros.fuseplus</li>
    <li>dubwise.dubsrimkit</li>
    <li>neitsa.preparelanding</li>
    <li>neptimus7.progressrenderer</li>
    <li>mastertea.randomplus</li>
    <li>owlchemist.packedsand</li>
    <li>herigony.mapedittools</li>
    <li>uuugggg.sharetheload</li>
    <li>dubwise.rimatomics</li>
    <li>dubwise.rimefeller</li>
    <li>dubwise.dubsskylights</li>
    <li>vanillaexpanded.vbookse</li>
    <li>vanillaexpanded.vwe</li>
    <li>vanillaexpanded.vweg</li>
    <li>vanillaexpanded.vwehw</li>
    <li>vanillaexpanded.vwel</li>
    <li>vanillaexpanded.vwec</li>
    <li>vanillaexpanded.vwenl</li>
    <li>legodude17.heavyweaponsreloading</li>
    <li>vanillaexpanded.vfemedical</li>
    <li>vanillaexpanded.vfeart</li>
    <li>vanillaexpanded.vfepropsanddecor</li>
    <li>vanillaexpanded.vfearchitect</li>
    <li>vanillaexpanded.vaeaccessories</li>
    <li>turnovus.submod.backpacksarenotbelts</li>
    <li>owlchemist.fridgeutilities</li>
    <li>vanillaexpanded.vbrewe</li>
    <li>vanillaexpanded.varme</li>
    <li>vanillaexpanded.vcef</li>
    <li>vanillaexpanded.vplantse</li>
    <li>spacemoth.vfavccrsze</li>
    <li>zzz.wallvitalsmonitor</li>
    <li>oskarpotocki.vanillaexpanded.ideologypatches</li>
    <li>anon.vanillaembrasures</li>
    <li>mlie.mechanicaldefense2walls</li>
    <li>chv.diagonalwalls</li>
    <li>jelly.rimflix</li>
    <li>murmur.walllight</li>
    <li>owlchemist.undergroundpowerconduits</li>
    <li>kentington.saveourshipck</li>
    <li>dubwise.dubsperformanceanalyzer</li>
    <li>automatic.autocleaner</li>
    <li>oskarpotocki.vfe.insectoid</li>
    <li>bs.mbifvte</li>
    <li>imranfish.xmlextensions</li>
    <li>imranfishnikos.tallertabmenus</li>
    <li>orion.hospitality</li>
    <li>mehni.pickupandhaul</li>
    <li>niilo007.niilosqol</li>
    <li>adambucior.betterelectronics</li>
    <li>supes.selectedreconnector</li>
    <li>kyd.rapidfireturrets</li>
    <li>trinity.runtimegcupdated</li>
* RimThreaded

**Comment by Niilo007** [comment]
This one seems like it might be a dubs had hygiene issu, rather than a rimthreaded issue, Please test without rimthreaded, and if it only happens with RimThreaded, re open this issue
