### ISSUE TITLE
Rimworld.WorkGiver

### ISSUE THREAD

**Issue by OcrecOrg** [cseelhoff/RimThreaded#725]
### **Describe the bug**
Whenever Pawns try to do a job like Production, Cooking or the like it throws the same error message constantly and nothing gets done, making pawns do a job manually works though

### **Steps to reproduce the behavior (VERY IMPORTANT)**
1. Build Stove
2. create task
3. Errors

### **Error Logs**
Exception in BreadthFirstTraverse: System.MissingMethodException: void RimWorld.WorkGiver_DoBill.MakeIngredientsListInProcessingOrder(System.Collections.Generic.List`1<Verse.IngredientCount>,RimWorld.Bill)
  at RimThreaded.WorkGiver_Scanner_Patch.CanStartOrResumeBillJob (RimWorld.WorkGiver_DoBill __instance, Verse.Pawn pawn, RimWorld.IBillGiver giver) [0x00147] in <e7b2aee242114846931720924bd1ca59>:0 
  at RimThreaded.WorkGiver_Scanner_Patch.HasJobOnThing (RimWorld.WorkGiver_DoBill __instance, Verse.Pawn pawn, Verse.Thing thing, System.Boolean forced) [0x00084] in <e7b2aee242114846931720924bd1ca59>:0 
  at RimThreaded.JobGiver_Work_Patch+<>c__DisplayClass1_1.<TryIssueJobPackage>b__1 (Verse.Thing t) [0x00013] in <e7b2aee242114846931720924bd1ca59>:0 
  at Verse.GenClosest+<>c__DisplayClass4_0.<RegionwiseBFSWorker>b__1 (Verse.Region r) [0x000f7] in <e13bd2f1929544099ed2b58e66ece833>:0 
  at (wrapper dynamic-method) Verse.RegionTraverser+BFSWorker.Verse.RegionTraverser+BFSWorker.BreadthFirstTraverseWork_Patch0(Verse.RegionTraverser/BFSWorker,Verse.Region,Verse.RegionEntryPredicate,Verse.RegionProcessor,int,Verse.RegionType)
  at (wrapper dynamic-method) Verse.RegionTraverser.Verse.RegionTraverser.BreadthFirstTraverse_Patch0(Verse.Region,Verse.RegionEntryPredicate,Verse.RegionProcessor,int,Verse.RegionType)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
(wrapper dynamic-method) Verse.RegionTraverser:Verse.RegionTraverser.BreadthFirstTraverse_Patch0 (Verse.Region,Verse.RegionEntryPredicate,Verse.RegionProcessor,int,Verse.RegionType)
Verse.GenClosest:RegionwiseBFSWorker (Verse.IntVec3,Verse.Map,Verse.ThingRequest,Verse.AI.PathEndMode,Verse.TraverseParms,System.Predicate`1<Verse.Thing>,System.Func`2<Verse.Thing, single>,int,int,single,int&,Verse.RegionType,bool)
RimThreaded.GenClosest_Patch:ClosestThingReachable2 (Verse.IntVec3,Verse.Map,Verse.ThingRequest,Verse.AI.PathEndMode,Verse.TraverseParms,single,System.Predicate`1<Verse.Thing>,System.Collections.Generic.IEnumerable`1<Verse.Thing>,int,int,bool,Verse.RegionType,bool)
RimThreaded.JobGiver_Work_Patch:TryIssueJobPackage (RimWorld.JobGiver_Work,Verse.AI.ThinkResult&,Verse.Pawn,Verse.AI.JobIssueParams)
(wrapper dynamic-method) RimWorld.JobGiver_Work:RimWorld.JobGiver_Work.TryIssueJobPackage_Patch1 (RimWorld.JobGiver_Work,Verse.Pawn,Verse.AI.JobIssueParams)
(wrapper dynamic-method) Verse.AI.ThinkNode_PrioritySorter:Verse.AI.ThinkNode_PrioritySorter.TryIssueJobPackage_Patch0 (Verse.AI.ThinkNode_PrioritySorter,Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Tagger:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Subtree:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Conditional:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
RimThreaded.Pawn_JobTracker_Patch:DetermineNextJob2 (Verse.AI.Pawn_JobTracker,Verse.ThinkTreeDef&)
RimThreaded.Pawn_JobTracker_Patch:TryFindAndStartJob (Verse.AI.Pawn_JobTracker)
(wrapper dynamic-method) Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.TryFindAndStartJob_Patch1 (Verse.AI.Pawn_JobTracker)
Verse.AI.Pawn_JobTracker:EndCurrentJob (Verse.AI.JobCondition,bool,bool)
Verse.AI.Pawn_JobTracker:JobTrackerTick ()
Verse.Pawn:Tick ()
RimThreaded.TickList_Patch:NormalThingTick ()
RimThreaded.RimThreaded:ExecuteTicks ()
RimThreaded.RimThreaded:ProcessTicks (RimThreaded.RimThreaded/ThreadInfo)
RimThreaded.RimThreaded:InitializeThread (object)
System.Threading.ThreadHelper:ThreadStart_Context (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object)
System.Threading.ThreadHelper:ThreadStart (object)

#### **Player.log**
https://gist.github.com/OcrecOrg/613f3d94a4f1374a59e1925169c49f05
#### **HugsLib log**
https://gist.github.com/OcrecOrg/c528641d49827dfbeae6a057d9b89e27

### **Save file**
[test.zip](https://github.com/cseelhoff/RimThreaded/files/7579606/test.zip)

### **Screenshots**
![image](https://user-images.githubusercontent.com/87601536/142833853-9499d087-0a94-4f58-841e-8334b15ccbcf.png)

### **Mod list (For vanilla report, it has to be same as below list.)**
Harmony
Core
Royalty (Optional)
Ideology (Optional)
HugsLib
RimThreaded
![image](https://user-images.githubusercontent.com/87601536/142833991-878d8f4b-aec9-4e7c-8a35-06b8b0a60fd1.png)

**Comment by MiningInMySleep** [comment]
I also had this issue. There's a build available on the discord that hasn't been made available here yet that seemingly fixes it. Still have a bunch of errors popping up in the latest version but jobs are getting done at least.

**Comment by Niilo007** [comment]
use this version instead:
https://steamcommunity.com/sharedfiles/filedetails/?id=2652641362&searchtext=threaded
