### ISSUE TITLE
A huge amount of repeating red errors right after loading a save

### ISSUE THREAD

**Issue by Zemogiter** [cseelhoff/RimThreaded#81]
A sort of continuation to #6 but now the issue remains even if Time Control and LinkedDoors are out of the question, 
https://gist.github.com/HugsLibRecordKeeper/2799b003714e2322d34f859d5f8247d7
Edit: Tried again with RimThreaded right after core and harmony and all mods that have anything to do with vanilla doors removed. Still the same problem but now the game crashed. Previously I was able to press ESC and shutdown rimworld.
[Player.log](https://github.com/cseelhoff/RimThreaded/files/5213044/Player.log)
UPDATE: Tried a new save and some time after I've designated some doors and walls I got this:
[Player.log](https://github.com/cseelhoff/RimThreaded/files/5213067/Player.log)

**Comment by cseelhoff** [comment]
Please reopen, if this issue still is occuring
