### ISSUE TITLE
Rivers?

### ISSUE THREAD

**Issue by ShamusOReilly** [cseelhoff/RimThreaded#87]
Failed to find all necessary river flow data
Verse.Log:Error(String, Boolean)
Verse.Log:ErrorOnce(String, Int32, Boolean)
RimWorld.GenStep_Terrain:GenerateRiverLookupTexture(Map, RiverMaker)
RimWorld.GenStep_Terrain:GenerateRiver(Map)
RimWorld.GenStep_Terrain:RimWorld.GenStep_Terrain.Generate_Patch0(GenStep_Terrain, Map, GenStepParams)
Verse.MapGenerator:GenerateContentsIntoMap(IEnumerable`1, Map, Int32)
Verse.MapGenerator:GenerateMap(IntVec3, MapParent, MapGeneratorDef, IEnumerable`1, Action`1)
Verse.Game:Verse.Game.InitNewGame_Patch0(Game)
Verse.<>c:<Start>b__1_2()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

**Comment by cseelhoff** [comment]
I have not seen this error in a while. I am going to close this bug.
