### ISSUE TITLE
Logo if you want it

### ISSUE THREAD

**Issue by ArchieV1** [cseelhoff/RimThreaded#9]
Logo if you want it: https://imgur.com/a/p5Lqrbt
The background is copyright free from [here](https://pixabay.com/photos/fibre-optics-christmas-holiday-1562702/)
and text also free from[Marnador](https://ludeon.com/forums/index.php?action=profile;u=36313)
If you use it please credit these two and me but its not great so eh

**Comment by cseelhoff** [comment]
This is fantastic! Thank you! I will put credits in my workshop mod description. If there are other places I should credit, please let me know!
