### ISSUE TITLE
Vanilla Animals Expanded issue or vanilla?

### ISSUE THREAD

**Issue by ShamusOReilly** [cseelhoff/RimThreaded#90]
AEXP_Otter24155 tried to reserve job PredatorHunt (Job_8193) A=Thing_Corpse_Rat24606 on target Thing_Corpse_Rat24606, but it's already reserved by him.
Verse.Log:Warning(String, Boolean)
RimThreaded.PhysicalInteractionReservationManager_Patch:Reserve(PhysicalInteractionReservationManager, Pawn, Job, LocalTargetInfo)
Verse.PhysicalInteractionReservationManager:Verse.PhysicalInteractionReservationManager.Reserve_Patch1(PhysicalInteractionReservationManager, Pawn, Job, LocalTargetInfo)
RimWorld.<>cDisplayClass10_0:<ChewIngestible>b0()
Verse.AI.JobDriver:TryActuallyStartNextToil()
Verse.AI.JobDriver:ReadyForNextToil()
Verse.AI.JobDriver:Notify_PatherArrived()
Verse.AI.Pawn_PathFollower:PatherArrived()
Verse.AI.Pawn_PathFollower:Verse.AI.Pawn_PathFollower.StartPath_Patch1(Pawn_PathFollower, LocalTargetInfo, PathEndMode)
Verse.AI.<>cDisplayClass1_0:<GotoThing>b0()
Verse.AI.JobDriver:TryActuallyStartNextToil()
Verse.AI.JobDriver:ReadyForNextToil()
Verse.AI.JobDriver:JumpToToil(Toil)
Verse.AI.<>cDisplayClass1_0:<JumpIf>b0()
Verse.AI.JobDriver:TryActuallyStartNextToil()
Verse.AI.JobDriver:ReadyForNextToil()
Verse.AI.JobDriver:TryActuallyStartNextToil()
Verse.AI.JobDriver:ReadyForNextToil()
Verse.AI.JobDriver:Verse.AI.JobDriver.DriverTick_Patch1(JobDriver)
Verse.AI.Pawn_JobTracker:JobTrackerTick()
Verse.Pawn:Tick()
RimThreaded.Ticklist_Patch:ProcessTicks()
RimThreaded.<>c:<CreateTickThreads>b__28_2()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

**Comment by Natrukei** [comment]
@ShamusOReilly Was there any melee fighting involved?
For me it reads like it does.
@cseelhoff If he confirms this can be closed aswell

**Comment by cseelhoff** [comment]
Closing bug. Many bugs have been fixed since this was reported. Please reopen in new bug report using the new templates if this issue persists.
