### ISSUE TITLE
Game crashes upon finalizing save load

### ISSUE THREAD

**Issue by Zemogiter** [cseelhoff/RimThreaded#92]
Pretty self-explainatory. 
[ModsConfig.zip](https://github.com/cseelhoff/RimThreaded/files/5213821/ModsConfig.zip)
[Player.log](https://github.com/cseelhoff/RimThreaded/files/5213823/Player.log)

**Comment by Natrukei** [comment]
Well not really. Could you provide a szenario around this log?

That would help us alot :)

**Comment by cseelhoff** [comment]
Closing bug. Many bugs have been fixed since this was reported. Please reopen in new bug report using the new templates if this issue persists.
