### ISSUE TITLE
Minor incompatibility with mod: Humanoid Alien Races 2.0

### ISSUE THREAD

**Issue by drunken-dwarf** [cseelhoff/RimThreaded#94]
When I load both RimThreaded and Humanoid Alien Races 2.0 and start a new game (eg. crashlanded), it doesn't take long for the log to get spammed with the following error:

```
Could not load UnityEngine.Texture2D at Things/Pawn/Humanlike/Heads/Male/Male_Narrow_Wide_northm in any active mod or in base resources.
Verse.Log:Error(String, Boolean)
Verse.ContentFinder`1:Verse.ContentFinder`1[[UnityEngine.Texture2D, UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]].Get_Patch1(String, Boolean)
RimThreaded.Ticklist_Patch:MainThreadWaitLoop()
RimThreaded.Ticklist_Patch:Tick(TickList)
Verse.TickList:Verse.TickList.Tick_Patch1(TickList)
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()
```
There are no visual glitches or symptoms other than the log messages.

Loadorder (suggested by RimPy Mod Manager):
- Harmony
- Core
- Hugslib
- [Humanoid Alien Races 2.0](https://steamcommunity.com/sharedfiles/filedetails/?id=839005762)
- RimThreaded [1.2]

**Comment by Natrukei** [comment]
As far as I can tell this is just texture related and not mod specific

**Comment by drunken-dwarf** [comment]
Just to be clear: I only get these erros when I load RimThreaded as well

**Comment by Natrukei** [comment]
Don't get me wrong: The error is created by RimThreads. But it's not because of Humanoid Alien Races.

**Comment by drunken-dwarf** [comment]
Hmm, that's strange. It only occurs when I load Humanoid Alien Races.
But I guess you know more about this than me.

**Comment by cseelhoff** [comment]
Closing bug. Many bugs have been fixed since this was reported. Please reopen in new bug report using the new templates if this issue persists.
