### ISSUE TITLE
Pre-Release ‎1.0.12.0 - Sunday, ‎13 ‎September ‎2020, ‏‎23:09:05

### ISSUE THREAD

**Issue by Tschuangtse** [cseelhoff/RimThreaded#96]
Testing new pre-release
--> Loading game with Harmony, Core, HugsLib, Rimthreaded
--> Running Rimworld 1.2.2753
--> New Colony, Tribe
--> Random pawns
--> Random starting location

Game throws massive error logs the moment pawns start interacting with items; e.g. eating food.
The following log was thrown within 4 seconds of gameplay.
Test aborted, unstable.

System information and error log attached.

[System-Info.zip](https://github.com/cseelhoff/RimThreaded/files/5215118/System-Info.zip)
[Player.log](https://github.com/cseelhoff/RimThreaded/files/5215119/Player.log)
[Player-prev.log](https://github.com/cseelhoff/RimThreaded/files/5215120/Player-prev.log)

Edit: verified findings, added addition log.

[Player - verified.log](https://github.com/cseelhoff/RimThreaded/files/5215132/Player.-.verified.log)

**Comment by cseelhoff** [comment]
bad preview version was released
