### ISSUE TITLE
Using Project Itzal weapon mods

### ISSUE THREAD

**Issue by Starteskash** [cseelhoff/RimThreaded#99]
I spawned a lot of mercenaries and put them against a lot of empire cataphracts and this was the result. (I was usnig Camera+ too)

https://gist.github.com/4179933851ac5b8b64016b0945e08938

**Comment by Natrukei** [comment]
@cseelhoff The scenario matches but he doesn't describe if there is a slowdown.
@Starteskash Can you confirm if there was a large slowdown (1TPS)?

**Comment by Starteskash** [comment]
It wasn't a large slowdown, it was a faster than 1 TPS

**Comment by cseelhoff** [comment]
Closing bug. Many bugs have been fixed since this was reported. Please reopen in new bug report using the new templates if this issue persists.
